### ISSUE TITLE
Ruby 2.3.1 openssl build issues on OSX

### ISSUE THREAD

**Issue by elliotcm** [rbenv/ruby-build#1008]
Hi!

I'm having significant issues building 2.3.1 on OSX El Capitan 10.11.6 (15G31), due to openssl.

I've tried every combination of build flag, homebrew, and openssl version I have available to no avail.

Here's an attempt to install it using rbenv without openssl via homebrew:

```
[~ (2.3.0)]$ rbenv install 2.3.1
Downloading openssl-1.0.2h.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/1d4007e53aad94a5b2002fe045ee7bb0b3d98f1a47f8b2bc851dcd1c74332919
Installing openssl-1.0.2h...
Installed openssl-1.0.2h to /Users/elliot/.rbenv/versions/2.3.1

Downloading ruby-2.3.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
Installing ruby-2.3.1...

BUILD FAILED (OS X 10.11.6 using ruby-build 20160602)

Inspect or clean up the working tree at /var/folders/kz/2x9vsz6x473_7b21yjcxxpmw0000gn/T/ruby-build.20161011114846.80965
Results logged to /var/folders/kz/2x9vsz6x473_7b21yjcxxpmw0000gn/T/ruby-build.20161011114846.80965.log

Last 10 log lines:
installing tcltklib libraries
compiling ifaddr.c
installing default socket libraries
compiling init.c
compiling constants.c
linking shared-object socket.bundle
linking shared-object tcltklib.bundle
installing default tcltklib libraries
linking shared-object ripper.bundle
make: *** [build-ext] Error 2
```

The log file mentioned ends like this:

```
ossl_ssl.c:107:5: error: use of undeclared identifier 'SSLv2_method'
    OSSL_SSL_METHOD_ENTRY(SSLv2),
    ^
ossl_ssl.c:89:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
<scratch space>:171:1: note: expanded from here
SSLv2_method
^
ossl_ssl.c:108:5: error: use of undeclared identifier 'SSLv2_server_method'
    OSSL_SSL_METHOD_ENTRY(SSLv2_server),
    ^
ossl_ssl.c:89:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
<scratch space>:171:1: note: expanded from here
SSLv2_server_method
^
ossl_ssl.c:109:5: error: use of undeclared identifier 'SSLv2_client_method'
    OSSL_SSL_METHOD_ENTRY(SSLv2_client),
    ^
ossl_ssl.c:89:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
<scratch space>:171:1: note: expanded from here
SSLv2_client_method
^
ossl_ssl.c:186:21: error: invalid application of 'sizeof' to an incomplete type 'const struct (anonymous struct at ossl_ssl.c:85:14) []'
    for (i = 0; i < numberof(ossl_ssl_method_tab); i++) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:18:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
ossl_ssl.c:2266:23: error: invalid application of 'sizeof' to an incomplete type 'const struct (anonymous struct at ossl_ssl.c:85:14) []'
    ary = rb_ary_new2(numberof(ossl_ssl_method_tab));
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:18:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
ossl_ssl.c:2267:21: error: invalid application of 'sizeof' to an incomplete type 'const struct (anonymous struct at ossl_ssl.c:85:14) []'
    for (i = 0; i < numberof(ossl_ssl_method_tab); i++) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:18:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
6 errors generated.
make[2]: *** [ossl_ssl.o] Error 1
make[1]: *** [ext/openssl/all] Error 2
```

I'm now at something of a loss.

**Comment by elliotcm** [comment]
I noticed that the version of ruby-build being used was older than the one I had installed via homebrew.

After much hitting it with a hammer and eventually installing from git, still fails, sadly:
```
[~ (2.3.0)]$ rbenv install 2.3.1
Downloading openssl-1.0.2j.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/e7aff292be21c259c6af26469c7a9b3ba26e9abaaffd325e3dccc9785256c431
Installing openssl-1.0.2j...
Installed openssl-1.0.2j to /Users/elliot/.rbenv/versions/2.3.1

Downloading ruby-2.3.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
Installing ruby-2.3.1...

BUILD FAILED (OS X 10.11.6 using ruby-build 20160913-13-g8ef0c34)

Inspect or clean up the working tree at /var/folders/kz/2x9vsz6x473_7b21yjcxxpmw0000gn/T/ruby-build.20161011122506.11017
Results logged to /var/folders/kz/2x9vsz6x473_7b21yjcxxpmw0000gn/T/ruby-build.20161011122506.11017.log

Last 10 log lines:
6 errors generated.
make[2]: *** [ossl_ssl.o] Error 1
make[1]: *** [ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
installing default socket libraries
compiling init.c
compiling constants.c
linking shared-object socket.bundle
linking shared-object ripper.bundle
make: *** [build-ext] Error 2
```

**Comment by elliotcm** [comment]
Right I've solved this for my specific case but it looks like there's some weirdness still worth looking at.

I wiped my entire rbenv installation and started afresh from git checkouts, to no avail.

I finally noticed that I also had openssl installed via macports and updated that to the most recent version.  The installation then worked.

This suggests that ruby-build is using the macports version of openssl while implying that it isn't, as it still downloads and installs its own copy of openssl.

Here's the output:
```
[~ ((set)]$ rbenv install 2.3.1
Downloading openssl-1.0.2j.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/e7aff292be21c259c6af26469c7a9b3ba26e9abaaffd325e3dccc9785256c431
Installing openssl-1.0.2j...
Installed openssl-1.0.2j to /Users/elliot/.rbenv/versions/2.3.1

Downloading ruby-2.3.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
Installing ruby-2.3.1...
Installed ruby-2.3.1 to /Users/elliot/.rbenv/versions/2.3.1
```

If ruby-build is using the macports openssl it should probably not download its own (or should download it and use it), just to avoid confusion in these situations.

Cheers,
Elliot

**Comment by ClementTANGUY** [comment]
Hi Elliot,
I'm newbie on coding and ruby.
Closed issues building 2.3.1 on OSX Sierra 10.12, same logs:

> ossl_ssl.c:107:5: error: use of undeclared identifier 'SSLv2_method'
    OSSL_SSL_METHOD_ENTRY(SSLv2),
    ^
ossl_ssl.c:89:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
<scratch space>:174:1: note: expanded from here
SSLv2_method
^
ossl_ssl.c:108:5: error: use of undeclared identifier 'SSLv2_server_method'
    OSSL_SSL_METHOD_ENTRY(SSLv2_server),
    ^
ossl_ssl.c:89:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
<scratch space>:174:1: note: expanded from here
SSLv2_server_method
^
ossl_ssl.c:109:5: error: use of undeclared identifier 'SSLv2_client_method'
    OSSL_SSL_METHOD_ENTRY(SSLv2_client),
    ^
ossl_ssl.c:89:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
<scratch space>:174:1: note: expanded from here
SSLv2_client_method
^
ossl_ssl.c:186:21: error: invalid application of 'sizeof' to an incomplete type 'const struct (anonymous struct at ossl_ssl.c:85:14) []'
    for (i = 0; i < numberof(ossl_ssl_method_tab); i++) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:18:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
ossl_ssl.c:2266:23: error: invalid application of 'sizeof' to an incomplete type 'const struct (anonymous struct at ossl_ssl.c:85:14) []'
    ary = rb_ary_new2(numberof(ossl_ssl_method_tab));
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:18:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
ossl_ssl.c:2267:21: error: invalid application of 'sizeof' to an incomplete type 'const struct (anonymous struct at ossl_ssl.c:85:14) []'
    for (i = 0; i < numberof(ossl_ssl_method_tab); i++) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:18:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
6 errors generated.
make[2]: *** [ossl_ssl.o] Error 1
make[1]: *** [ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
checking ../.././parse.y and ../.././ext/ripper/eventids2.c
compiling ifaddr.c
linking shared-object stringio.bundle
installing default ripper libraries
installing default socket libraries
compiling init.c
compiling constants.c
linking shared-object socket.bundle
linking shared-object ripper.bundle
make: *** [build-ext] Error 2

Going crazy. Please could u help describing how to proceed?
Thanks a lot.

**Comment by elliotcm** [comment]
@ClementTANGUY Make sure your versions of openssl are up to date in every package manager you have installed.  That's the best I can suggest.

**Comment by hsbt** [comment]
@ClementTANGUY or invoke `xcode-select --intall`

**Comment by ClementTANGUY** [comment]
@hsbt @elliotcm Thanks guys, I'll try this

**Comment by ClementTANGUY** [comment]
This works finally for me:

brew uninstall --force openssl
brew install openssl
rbenv install 2.3.1

**Comment by hkorhola** [comment]
I faced the same problem. The only thing that helped was to remove Port Openssl with force and then update symlinks for Brew's Openssl. After that I was able to install Ruby with Rbenv.

sudo port -f uninstall openssl 1.0.2g
sudo ln -s /usr/local/Cellar/openssl/1.0.2j/bin/openssl /opt/local/bin/openssl
rbenv install 2.3.1
rbenv rehash

**Comment by bormat** [comment]
For me, it was because of the Xcode version 

`xcode-select --print-path` must print the path of the version Xcode_10.2.1.app and not the 9.4

`sudo xcode-select --switch /Applications/Xcode_10.2.1.app`

`brew reinstall openssl # I suppose it use xcode 9.4 and it was the problem`

`rvm install 2.3.1 --with-openssl-dir=/usr/local/opt/openssl --with-openssl-lib=/usr/local/opt/openssl/lib --with-openssl-include=/usr/local/opt/openssl/include`

where `/usr/local` is what is returned by brew --prefix
