### ISSUE TITLE
Got ruby-build usage example when trying to run "rbenv install 2.3.1"

### ISSUE THREAD

**Issue by yidingalan** [rbenv/ruby-build#1010]
Hi,

I am trying to run the command "rbenv install 2.3.1", but then it returned the ruby build examples and failed: 

Usage: ruby-build [-kpv] <definition> <prefix>
       ruby-build --definitions
       ruby-build --version

  -k/--keep        Do not remove source tree after installation
  -p/--patch       Apply a patch from stdin before building
  -v/--verbose     Verbose mode: print compilation status to stdout
  -4/--ipv4        Resolve names to IPv4 addresses only
  -6/--ipv6        Resolve names to IPv6 addresses only
  --definitions    List all built-in definitions
  --version        Show version of ruby-build

My OS is Ubuntu 14.04 LTS. I am just wondering how to fix this. Any helps will be appreciated!

Alan

**Comment by mislav** [comment]
@yidingalan That's a very weird error! Can you tell use what version of rbenv and ruby-build you have on your system, where and how you installed rbenv, and where and how you installed ruby-build? Also please tell us the result of:

```sh
ls "$(rbenv root)"/plugins
which -a ruby-build
```

**Comment by yidingalan** [comment]
@mislav Hey I already fixed the error myself. Thanks for following up :+1:
