### ISSUE TITLE
Error on upgrading to 2.3.1 on Linux AWS

### ISSUE THREAD

**Issue by asakk046** [rbenv/ruby-build#1012]
I keep getting the same time out error even when I tried different versions of ruby. The time out itself is not the issue since I installed ruby 2.3.1 using RVM before I removed it. This is what I get:

$ rbenv install 2.3.1
Downloading ruby-2.3.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
Installing ruby-2.3.1...
BUILD FAILED (Amazon Linux AMI 2016.09 using ruby-build 20160602)

Inspect or clean up the working tree at /tmp/ruby-build.20161024024027.9081
Results logged to /tmp/ruby-build.20161024024027.9081.log

Last 10 log lines:
 # define rl_username_completion_function username_completion_function
                                          ^
readline.c:1780:37: note: in expansion of macro 'rl_username_completion_function'
                                     rl_username_completion_function);
                                     ^
make[2]: *** [readline.o] Error 1
make[2]: Leaving directory `/tmp/ruby-build.20161024024027.9081/ruby-2.3.1/ext/readline'
make[1]: *** [ext/readline/all] Error 2
make[1]: Leaving directory `/tmp/ruby-build.20161024024027.9081/ruby-2.3.1'
make: *** [build-ext] Error 2

**Comment by hsbt** [comment]
It caused by newer readline. I'm going to investigate it.

**Comment by hsbt** [comment]
and Can you check to install `lreadline-devel`?

**Comment by asakk046** [comment]
-bash: lreadline-devel: command not found

**Comment by asakk046** [comment]
ERROR:  Could not find a valid gem 'lreadline-devel' (>= 0) in any repository

**Comment by asakk046** [comment]
BUILD FAILED (Amazon Linux AMI 2016.09 using ruby-build 20160602)

Inspect or clean up the working tree at /tmp/ruby-build.20161024151611.24040
Results logged to /tmp/ruby-build.20161024151611.24040.log

Last 10 log lines:
 # define rl_username_completion_function username_completion_function
                                          ^
readline.c:1780:37: note: in expansion of macro 'rl_username_completion_function'
                                     rl_username_completion_function);
                                     ^
make[2]: *** [readline.o] Error 1
make[2]: Leaving directory `/tmp/ruby-build.20161024151611.24040/ruby-2.3.1/ext/readline'
make[1]: *** [ext/readline/all] Error 2
make[1]: Leaving directory `/tmp/ruby-build.20161024151611.24040/ruby-2.3.1'

**Comment by asakk046** [comment]
This what I get:
Loaded plugins: priorities, update-motd, upgrade-helper
amzn-main/latest                                                                                                     | 2.1 kB     00:00     
amzn-updates/latest                                                                                                  | 2.3 kB     00:00     
Package readline-devel-6.2-9.14.amzn1.x86_64 already installed and latest version
Nothing to do

**Comment by mislav** [comment]
@asakk046 What was the conclusion of your problem?

**Comment by asakk046** [comment]
It was fixed by brew install readline
