### ISSUE TITLE
Unable to install ruby on Ubuntu 16.04 - CAfile error

### ISSUE THREAD

**Issue by AnimeshShaw** [rbenv/ruby-build#1013]
I followed [this](https://gorails.com/setup/ubuntu/16.04) tutorial to install rbenv and ruby-build but when I execute `rbenv install 2.3.1 -v` I get the following error. I searched for different solutions on google but they aren't working. 

    coder@no-one:~$ rbenv install 2.3.1 -v
    /tmp/ruby-build.20161028202105.12567 ~
    Downloading ruby-2.3.1.tar.bz2...
    -> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
    curl: (77) error setting certificate verify locations:
      CAfile: /etc/pki/tls/certs/ca-bundle.crt
      CApath: none
    error: failed to download ruby-2.3.1.tar.bz2

    BUILD FAILED (Ubuntu 16.04 using ruby-build 20160913-13-g8ef0c34)

I made sure that I had install the dependencies from beforehand including OpenSSL and ca-certificates. 

Any insights?

**Comment by AnimeshShaw** [comment]
I tried several things that were said in other places but most didn't work. Next I tried to manipulate the script to use the ~/.curlrc but changing the -qsSfL instruction to -sSfL in the shell script `~/.rbenv/plugins/ruby-build/script/mirror` but this didn't work. I reverted the changes.

I fixed the problem though by creating a symlink, `sudo ln -s /etc/pki/tls/certs/ /etc/ssl/certs/`

Finally it worked. Closing..

**Comment by bladedge666** [comment]
I am having the same problem. I created the symlink but no help.

**Comment by chrisamow** [comment]
On a 14.04 based system I had to symlink fix it differently (opposite direction, new name,) complete fix:
```
sudo apt-get install ca-certificates
sudo mkdir -p /etc/pki/tls/certs
sudo ln -s /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt
```
