### ISSUE TITLE
Why we are still keeping older ruby definitions?

### ISSUE THREAD

**Issue by r3bo0t** [rbenv/ruby-build#1020]
Well, its not an issue, just a concern. why we are keeping `older ruby definitions` (1.7.x, 1.8.x)? Is there any specific reason. Personally speaking, if people are still using them they are missing on lots of good things and they should move to latest ones. Soon ruby will deprecate even 1.9.x and its time to move forward 😈

**Comment by jeremy** [comment]
We indicate end-of-life and unsupported Ruby versions: #942 

We'd still like to build and run old Ruby versions even though they reached their end of life 😊

**Comment by jeremy** [comment]
(You may be interested in https://bugs.ruby-lang.org/issues/12328, too.)
