### ISSUE TITLE
BUILD FAILED (OS X 10.11.5 using ruby-build 20160913)

### ISSUE THREAD

**Issue by recyclablestudios** [rbenv/ruby-build#1021]
Inspect or clean up the working tree at /var/folders/tp/c_qlq64j3xg9fg2l7dw0q0400000gn/T/ruby-build.20161117072715.65539
Results logged to /var/folders/tp/c_qlq64j3xg9fg2l7dw0q0400000gn/T/ruby-build.20161117072715.65539.log

Last 10 log lines:
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/juliomiranda/.rvm/gems/ruby-2.3.1/gems/psych-2.1.1/lib/psych.rb:7:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/yaml.rb:6:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:15:in `block in <main>'
	from -e:13:in `reject'
	from -e:13:in `<main>'

**Comment by hsbt** [comment]
Can you remove/uninstall rvm? rbenv and ruby-build does not work with another version manager.

**Comment by recyclablestudios** [comment]
Works like a charm! Thank you hsbt
