### ISSUE TITLE
Fresh Install Mac OSX10.11.6 El Capitan Brew Install rbenv. Dowload Error All Ruby Versions

### ISSUE THREAD

**Issue by lacostenycoder** [rbenv/ruby-build#1023]
Fresh install of my OS, installed xcode with `xcode-select --install`
Installed rbenv and ruby 2.3 with no problem.
Try to install ruby 2.1.10 and get error:
```
Downloading ruby-2.1.10.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.10.tar.bz2
error: failed to download ruby-2.1.10.tar.bz2

BUILD FAILED (OS X 10.11.6 using ruby-build 20161115)
Failed to download ruby-2.1.10.tar.bz2
```
I'm running ZSH.  Here's my PATH:
```
echo $PATH
/Users/lacoste/.nvm/versions/node/v7.1.0/bin:/Users/lacoste/.rbenv/shims:/usr/local/heroku/bin:/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:/Users/lacoste/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```

Still upsetting why I always have problems with this...

**Comment by hsbt** [comment]
Can you download "https://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.10.tar.bz2" using web browser like Safari?

**Comment by lacostenycoder** [comment]
@hsbt Yes, that works fine. But when I try any version with rbenv, same error.

**Comment by jeremy** [comment]
Perhaps you have a `curl` install that's missing OpenSSL support?

```bash
$ which curl
/usr/bin/curl

$ curl --version
curl 7.51.0 (x86_64-apple-darwin16.0) libcurl/7.51.0 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets 
```

What do you see?

**Comment by lacostenycoder** [comment]
@jeremy 
```
~ % which curl
/usr/bin/curl
~ % curl --version
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets 
```

**Comment by jeremy** [comment]
We get this error if an HTTP fetch fails. The full details of the fetch command (usually `curl`) and the results + error will be in the log. Do you see an error in there?

(You can run with the verbose `-v` flag to output the full logs as it runs, too, btw)

**Comment by lacostenycoder** [comment]
@jeremy It's definitely an SSH Cert issue.  Found similar issue here but can't seem to find work around / solution.

**Comment by lacostenycoder** [comment]
OK I figured out solution.  Use browser to download file from https://curl.haxx.se/ca/cacert.pem
Then move file to correct directory where curl will expect it:
```
`mv /Users/lacoste/Downloads/cacert.pem /usr/local/etc/openssl/certs/`
```
Then use home brew to install curl with open ssl :
```
brew install --with-openssl curl
```
Then I was able to successfully install Ruby with
```
rbenv install 2.1.10
```
