### ISSUE TITLE
2.3.3 not listed in ruby-build --definitions

### ISSUE THREAD

**Issue by railstation** [rbenv/ruby-build#1025]
Git pull gave me the info that 2.3.3 is available
> ruby-build 2.3.3
ruby-build: definition not found: 2.3.3

**Comment by mislav** [comment]
Often people end up with duplicate installs of ruby-build. They might update one to the latest version (potentially even from git master), but the other still stays at old version.

Therefore, check your `where -a ruby-build` and ``ls `rbenv root`/plugins``, see if you have duplicate installs, and delete the stale install. Then try installing 2.3.3 again.

**Comment by railstation** [comment]
Hi Mislav,
I did the git pull but forgot to run ./install.sh
It's listed now. Thx !
