### ISSUE TITLE
rbenv  build  2.1.6 fail   on macOS Sierra 

### ISSUE THREAD

**Issue by guandai** [rbenv/ruby-build#1037]
I have tried install with sudo . but still get same error

`BUILD FAILED (OS X 10.12.1 using ruby-build 20160913)`

Here is log file
https://gist.github.com/guandai/d716293bf21bead7aea0569a1c90d5f6

**Comment by guandai** [comment]
I also tried goto temp folder and run  `make install`
And break  at following

```
Generating RDoc documentation
/private/var/folders/yw/4hjqg8nd1wv76t8zvzls6b2w0000gn/T/ruby-build.20161217163844.39627/ruby-2.1.6/lib/rubygems/ext/builder.rb:89:in `run': ERROR: Failed to build gem native extension. (Gem::Ext::BuildError)

    /Users/zhengdai/.rbenv/versions/2.1.6/bin/ruby extconf.rb
sh: /Users/zhengdai/.rbenv/versions/2.1.6/bin/ruby: No such file or directory

extconf failed, exit code 127

Gem files will remain installed in /Users/zhengdai/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/json-1.8.3 for inspection.
```

**Comment by chrislavender** [comment]
I'm having this same issue. Did you ever find a solution?

**Comment by chrislavender** [comment]
Actually I solved this via http://stackoverflow.com/a/19706191/558776

My issue was related to an SSL cert for https://cache.ruby-lang.org/.  Not stoked about this workaround but it got me unstuck.

**Comment by mislav** [comment]
@guandai Is it an option for you to upgrade to the latest `2.1.x` version and see if that fixes the build problem on Sierra?

Often newer releases of Ruby fix build problems across platforms.

**Comment by guandai** [comment]
@mislav   I have no problem in 2.1.7   and no problem to compile in `rvm`

**Comment by mislav** [comment]
Then I would suggest to migrate your project to 2.1.7. There are no feature changes in patch releases of Ruby, so that should be perfectly safe.

**Comment by guandai** [comment]
@mislav Thanks,   2.1.6 was for old project version.   now I change to 2.3.1    it can compile.
But what surprised me is the ruby 2.3.1 from rvm and rbenv  could give different calculation result...
By using a ssh gem to get response from remote server,   rbenv ruby get 'nil'   rvm ruby get ''  , empty string.     I will create another issue about that. Even not sure which response is suppose to be..  

Back to this issue,  I just try once more.   my rbenv can compile 2.1.6 again , no clue why.    not sure what my env changed...    I switch to rvm , and now I switch back , and deleted all rvm related files.    I am sure there is no `rvm`  load lines from my profiles.....  

I close this issue, if I meet it again, will reopen it.   Thanks

**Comment by wantsdev** [comment]
By refering to https://github.com/rbenv/ruby-build/issues/1700,
export  CFLAGS="-Wno-error=implicit-function-declaration".

It works.
