### ISSUE TITLE
ruby-build --version reports incorrect version

### ISSUE THREAD

**Issue by nertzy** [rbenv/ruby-build#1041]
I installed ruby-build 20161225 via homebrew. 🎄 🎅 🎁 

It gives the wrong version:

```
$ ruby-build --version
ruby-build 20160913
```

See https://github.com/rbenv/ruby-build/blob/3956c5776136177d5c200aa085fa67f70a45f090/bin/ruby-build#L16

**Comment by mislav** [comment]
Thank you for reporting! I have bumped up the version string. It should be reflected in the next release.

@hsbt: please use `script/release` for future releases. 🙇

**Comment by hsbt** [comment]
🙇
