### ISSUE TITLE
Strange things with RUBY_BUILD_VERSION

### ISSUE THREAD

**Issue by ivanovaleksey** [rbenv/ruby-build#1044]
Hi guys!

I tried to install `rbx-3.69` but I didn't have it in my `rbenv install --list`.
I have `ruby-build 20161225` installed.

When I run `ruby-build --version` I have `ruby-build 20160913`.
`which ruby-build` gives me `/usr/local/bin/ruby-build` and it is symlinked to `/usr/local/Cellar/ruby-build/20161225/bin/ruby-build`.

It is written in this file `RUBY_BUILD_VERSION="20160913"` which is very strange for me.

I tried to remove `ruby-build` and clear homebrew cache.

```
$ rm -rf /Users/aleksey/Library/Caches/Homebrew
$ brew install ruby-build
==> Using the sandbox
==> Downloading https://github.com/rbenv/ruby-build/archive/v20161225.tar.gz
==> Downloading from https://codeload.github.com/rbenv/ruby-build/tar.gz/v20161225
######################################################################## 100.0%
==> ./install.sh
🍺  /usr/local/Cellar/ruby-build/20161225: 323 files, 173.7K, built in 3 seconds
```

I downloaded this `https://codeload.github.com/rbenv/ruby-build/tar.gz/v20161225` manually, extracted it and opened `bin/ruby-build`. And **there it is** -  `RUBY_BUILD_VERSION="20160913"`.

What is wrong with my ruby-build? Am I doing something wrong?

Thank you.

**Comment by ivanovaleksey** [comment]
By the way `ruby 2.4.0` is available in `rbenv --list`.

**Comment by hsbt** [comment]
We didn't add rbx-3.69 definition yet. see https://github.com/rbenv/ruby-build/pull/1035

**Comment by ivanovaleksey** [comment]
Thank you @hsbt
