### ISSUE TITLE
wrong version 2.5.0 instead of 2.4.0

### ISSUE THREAD

**Issue by exocode** [rbenv/ruby-build#1045]
saying that my ruby version is 2.5.0
But 2.5.0 is not installed on my machine

```
➜  gn2016 git:(master) ✗ rbenv local 2.4.0-dev
➜  gn2016 git:(master) ✗ ruby -v
ruby 2.5.0dev (2017-01-15 trunk 57334) [x86_64-darwin16]
➜  gn2016 git:(master) ✗ rbenv versions
  system
  2.2.2
  2.2.3
  2.2.5
  2.3.1
* 2.4.0-dev (set by /Users/jan/RubymineProjects/gn2016/.ruby-version)
```

**Comment by hsbt** [comment]
What's version of ruby-build?

**Comment by mislav** [comment]
Before 6e96a35d1c609243b7dbff400a191d27ecbb8a07, the `2.4.0-dev` definition simply installed Ruby from trunk, meaning the bleeding edge version of the repository. If your ruby-build version is from before Dec 26, which is quite likely, then installing `2.4.0-dev` today will actually build the latest state of 2.5.0 instead.

To fix this, upgrade ruby-build to latest version and re-install `2.4.0-dev`.
