### ISSUE TITLE
Wrong llvm installation instructions when installing Rubinius (osx)

### ISSUE THREAD

**Issue by stephanvane** [rbenv/ruby-build#1047]
When I try to install Rubinius (3.60) the following instructions appear:

```
TO FIX THE PROBLEM: Install Homebrew's llvm package with this
command: brew tap homebrew/versions ; brew install llvm36
```

However, the homebrew/versions tab is [deprecated](https://github.com/Homebrew/homebrew-versions) and doesn't work anymore:

```
➜  ~ brew tap homebrew/versions ; brew install llvm36
Error: No available formula with the name "llvm36" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

The [new way of doing this](http://docs.brew.sh/Versions.html) would look like this: `brew install llvm@3.6`
Unfortunately 3.6 doesn't seem to be available anymore:

```
➜  ~ brew search llvm
llvm                     llvm@3.7                 llvm@3.8
```

Is there a reason for using version 3.6 ([from 2015](http://releases.llvm.org/))?

I was able to install rbx-3.60 with llvm 3.7 (although I didn't test it thoroughly afterwards) by using `brew install llvm@3.7` and changing `require_llvm 3.6` to `require_llvm 3.7` in `share/ruby-build/rbx-3.60`

**Comment by mach-kernel** [comment]
I was able to reproduce @stephanvane's instructions locally as I was stuck with the same issue. Is there some special process to PR this?

**Comment by hsbt** [comment]
I could reproduce it. but I can build and install only rbx-3.66 to 3.69.

**Comment by hsbt** [comment]
@stephanvane @mach-kernel Can you try with master of ruby-build for installing to `rbx-3.69`?
