### ISSUE TITLE
Ruby 2.2.6, Rails 4.0.4 in Mac 10.12.3. `mkdir': No such file or directory @ dir_s_mkdir

### ISSUE THREAD

**Issue by Diiru** [rbenv/ruby-build#1052]
Hi !
I am getting this error when trying to initialize a rails server.

    wireless-10-147-105-213:used_products
    diiru$ gem env
    RubyGems Environment:
       - RUBYGEMS VERSION: 2.4.5.2
       - RUBY VERSION: 2.2.6 (2016-11-15 patchlevel 396) [x86_64-darwin16]
       - INSTALLATION DIRECTORY: /Users/diiru/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0
       - RUBY EXECUTABLE: /Users/diiru/.rbenv/versions/2.2.6/bin/ruby
       - EXECUTABLE DIRECTORY: /Users/diiru/.rbenv/versions/2.2.6/bin
       - SPEC CACHE DIRECTORY: /Users/diiru/.gem/specs
       - SYSTEM CONFIGURATION DIRECTORY: /Users/diiru/.rbenv/versions/2.2.6/etc
       - RUBYGEMS PLATFORMS:
         - ruby
         - x86_64-darwin-16
       - GEM PATHS:
          - /Users/diiru/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0
          - /Users/diiru/.gem/ruby/2.2.0
       - GEM CONFIGURATION:
          - :update_sources => true
          - :verbose => true
          - :backtrace => false
          - :bulk_threshold => 1000
       - REMOTE SOURCES:
          - https://rubygems.org/
       - SHELL PATH:
          - /Users/diiru/.rbenv/versions/2.2.6/bin
          - /usr/local/Cellar/rbenv/1.1.0/libexec
          - /Users/diiru/.rbenv/shims
          - /usr/local/bin
          - /usr/bin
          - /bin
          - /usr/sbin
          - /sbin
          - /Applications/Postgres.app/Contents/Versions/latest/bin
     wireless-10-147-105-213:used_products diiru$ which rails
     /Users/diiru/.rbenv/shims/rails
     wireless-10-147-105-213:used_products diiru$ which ruby
     /Users/diiru/.rbenv/shims/ruby
     wireless-10-147-105-213:used_products diiru$ rails s
     /Users/diiru/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/activesupport-4.0.4/lib/active_support/values/time_zone.rb:283: warning: circular argument reference - now
     /Users/diiru/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/tbk-1.0.3/lib/tbk/webpay/logger/official_logger.rb:13:in `mkdir': No such file or directory @ dir_s_mkdir - /Users/diiru/Desktop/Try/used_products/log/webpay (Errno::ENOENT)
     	from /Users/diiru/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/tbk-1.0.3/lib/tbk/webpay/logger/official_logger.rb:13:in `directory'
     	from /Users/diiru/Desktop/Try/used_products/config/application.rb:37:in `block (2 levels) in <class:Application>'
     	from /Users/diiru/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/tbk-1.0.3/lib/tbk/webpay/logger/base_logger.rb:9:in `call'
     	from /Users/diiru/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/tbk-1.0.3/lib/tbk/webpay/logger/base_logger.rb:9:in `initialize'
     	from /Users/diiru/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/tbk-1.0.3/lib/tbk/webpay/logger.rb:26:in `new'
     	from /Users/diiru/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/tbk-1.0.3/lib/tbk/webpay/logger.rb:26:in `logger'
     	from /Users/diiru/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/tbk-1.0.3/lib/tbk/webpay/logger.rb:35:in `webpay_logger'
     	from /Users/diiru/Desktop/Try/used_products/config/application.rb:35:in `block in <class:Application>'
     	from /Users/diiru/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/tbk-1.0.3/lib/tbk/config.rb:44:in `configure'
     	from /Users/diiru/Desktop/Try/used_products/config/application.rb:30:in `<class:Application>'
     	from /Users/diiru/Desktop/Try/used_products/config/application.rb:10:in `<module:UsedProducts>'
     	from /Users/diiru/Desktop/Try/used_products/config/application.rb:9:in `<top (required)>'
     	from /Users/diiru/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/railties-4.0.4/lib/rails/commands.rb:74:in `require'
     	from /Users/diiru/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/railties-4.0.4/lib/rails/commands.rb:74:in `block in <top (required)>'
     	from /Users/diiru/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/railties-4.0.4/lib/rails/commands.rb:71:in `tap'
     	from /Users/diiru/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/railties-4.0.4/lib/rails/commands.rb:71:in `<top (required)>'
     	from bin/rails:4:in `require'
     	from bin/rails:4:in `<main>'
     wireless-10-147-105-213:used_products diiru$ `

Any ideas ?

**Comment by mislav** [comment]
Hello, this is a problem with your application setup, not with ruby-build itself. This issue tracker is only for problems with ruby-build; i.e. problems with installation of Ruby itself. You seem to already have a functioning Ruby v2.2.6.

Please search for the `directory` directive to configure the logger path for the "tbk" library. It's probably set to a wrong (non-existent) location.

```
grep -R directory config
```
