### ISSUE TITLE
Can rbenv be used to install ruby binaries instead of building from source?

### ISSUE THREAD

**Issue by oddhack** [rbenv/ruby-build#1054]
I apologize if this is covered somewhere I haven't found yet - as a complete newbie to Ruby, much of this environment manager stuff is puzzling. Is it necessary to build ruby from source? After installing ruby_build I 'ruby install 2.3.3' and it takes 25-30 minutes on a not terribly slow FX-6300 CPU, which is frustrating (especially if the build aborts only at the very end due to lack of a required package). Are there prebuilt binaries that could be installed through rbenv on Debian 8 and the Windows Ubuntu subsystem, for example?

**Comment by hsbt** [comment]
Duplicates with https://github.com/rbenv/ruby-build/issues/42

It have many of concerns. example for

 * Who will pay infrastructure resource like CDN and s3?
 * Who will maintain binary package when latest version releasing?
 * Who is responsible for the vulnerability about binary package?

It's too hard to handle volunteer work.

**Comment by mislav** [comment]
@oddhack It would be great it we had prebuilt binaries to speed up installs, but this is easier said than done. The infrastructure to make/maintain prebuilt binaries is out of the scope of what we can achieve right now.

You can speed up Ruby installs by avoiding generating ri/RDoc documentation for them:

```
RUBY_CONFIGURE_OPTS=--disable-install-doc rbenv install 2.4.0
```

**Comment by oddhack** [comment]
@mislav thanks, will recommend that to our users.

**Comment by aurimus** [comment]
Is there however someplace on the internet where I could just download the binaries for rbenv, at my own risk? I can't seem to compile it on windows bash, it takes forever and throws some error, and then repeat..

**Comment by tlopo** [comment]
@hsbt  WRT to  Storage + CDN, have you considered  bintray?  They have a free plan for OSS which provides 10GB of  Storage and 1TB download monthly. 

https://bintray.com/signup/oss

If you think it's worth, I would like to volunteer to get it setup, and help in the maintenance tasks.

**Comment by cupnoodle** [comment]
RVM.io provides public link for ruby binaries : https://rvm.io/binaries/

I have tested downloading the ubuntu 20.04 ruby 2.7.1 binary, and placed the binary into **~/username/.rbenv/version/2.7.1** , then run `rbenv rehash` , and it worked.

Hope this helps! I have switched to downloading binaries from RVM instead of rbenv install for my ansible server scripts and it has shorten the execution time by ~15 minutes.

**Comment by technicalpickles** [comment]
GitHub packages is an option now too. Homebrew recently moved to it from bintray recently.

**Comment by technicalpickles** [comment]
I think this can be closed as a duplicate of https://github.com/rbenv/ruby-build/issues/1054

**Comment by ronkorving** [comment]
@technicalpickles This *is* #1054 :)
