### ISSUE TITLE
rbenv install fails silently when curl/wget are absent

### ISSUE THREAD

**Issue by sandys** [rbenv/ruby-build#1058]
I was trying to setup ruby using rbenv on a google cloud docker instance (ubuntu 16.04). this VM does not come with curl or wget installed. "rbenv install 2.3.0" etc kept returning with a non-zero status without any errors. 
I wasted a day trying to figure out what was happening. The only way I figured out was when I tried "rbenv install 2.1.0" - at that time, rbenv actually spit out meaningful errors.

Please show errors when curl/wget are absent

**Comment by olleolleolle** [comment]
Does this code express what you describe?

https://github.com/rbenv/ruby-build/blob/master/bin/ruby-build#L297-L313

**Comment by andor-pierdelacabeza** [comment]
@olleolleolle That should be the output, but when trying to install 1.8.7 it just spits the url where it's going to download ruby and silently fails.

**Comment by emiltin** [comment]
i had the same problem when trying to install ruby 2.4.2 via docker. the download step fails without any errors:

```
root@beda4cb18a1b:~# rbenv install 2.4.2          
Downloading ruby-2.4.2.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.2.tar.bz2
```

after `apt-get install curl` it works as expected.

**Comment by mislav** [comment]
We now have a test that verifies that an appropriate error message is printed e2b1da83bb9d2bc23c6e8665965492c2d10d1536
