### ISSUE TITLE
Consistent 'checksum mismatch' errors when trying to install certain MRI versions

### ISSUE THREAD

**Issue by omehegan** [rbenv/ruby-build#1065]
I'm using ruby-build v20170201, I've used rbenv and ruby-build in production for several years now. Recently, attempts to install new-to-us versions of Ruby (2.0.0-p353, 2.4.0) have consistently failed with checksum mismatch errors:

```
owen@mybox:~$ rbenv install 2.4.0
Downloading ruby-2.4.0.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/440bbbdc49d08d3650f340dccb35986d9399177ad69a204def56e5d3954600cf
-> https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.0.tar.bz2

BUILD FAILED

Inspect or clean up the working tree at /tmp/ruby-build.20170317212156.18771
Results logged to /tmp/ruby-build.20170317212156.18771.log

Last 10 log lines:


checksum mismatch: ruby-2.4.0.tar.gz (file is corrupt)
expected 440bbbdc49d08d3650f340dccb35986d9399177ad69a204def56e5d3954600cf, got 98f29161860fe1b6c65396717847a358

curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.

checksum mismatch: ruby-2.4.0.tar.gz (file is corrupt)
expected 440bbbdc49d08d3650f340dccb35986d9399177ad69a204def56e5d3954600cf, got 98f29161860fe1b6c65396717847a358
```

First, I notice that Cloudfront is redirecting us to a tar.bz2 file, but it seems that ruby-build is saving it as a tar.gz. So:

```
owen@mybox:~$ file /tmp/ruby-build.20170317212410.18947/ruby-2.4.0.tar.gz
/tmp/ruby-build.20170317212410.18947/ruby-2.4.0.tar.gz: bzip2 compressed data, block size = 900k
```

So if I just short-circuit the ruby-build checksum code, it still fails to install because of that assumption. But as for the checksumming, I looked through the ruby-build code and I see that it may use a couple of different methods to do that. This is an Ubuntu Trusty system, I'm having the same problem on Precise hosts as well. So ruby-build thinks the checksum for this file should be 440bbbdc49d08d3650f340dccb35986d9399177ad69a204def56e5d3954600cf. But:

```
owen@mybox:~$ md5sum /tmp/ruby-build.20170317212410.18947/ruby-2.4.0.tar.gz
98f29161860fe1b6c65396717847a358  /tmp/ruby-build.20170317212410.18947/ruby-2.4.0.tar.gz
owen@mybox:~$ openssl md5 /tmp/ruby-build.20170317212410.18947/ruby-2.4.0.tar.gz
MD5(/tmp/ruby-build.20170317212410.18947/ruby-2.4.0.tar.gz)= 98f29161860fe1b6c65396717847a358
```

Both md5sum and openssl agree about the checksum of what we downloaded, so my sense is that this is not a problem with my local tools.

**Comment by omehegan** [comment]
Oh, interesting... the systems I'm using are Amazon EC2 instances... I just realized that the ruby-build definitions don't specify a Cloudfront URL, so perhaps Amazon is redirecting my request for me, and this is causing breakage.

**Comment by mislav** [comment]
Closing as stale
