### ISSUE TITLE
ruby 2.3.4 support

### ISSUE THREAD

**Issue by HLFH** [rbenv/ruby-build#1070]
Hi,

We need ruby 2.3.4 support.

https://github.com/ruby/ruby/releases/tag/v2_3_4

Thanks,

**Comment by mislav** [comment]
@hsbt Is 2.3.4 release public by now? I don't see it on the official downloads site.

**Comment by hsbt** [comment]
@mislav It's not public release yet.

@HLFH After that, We will add it definition and bump new version of ruby-build.

**Comment by maikrhg** [comment]
ruby 2.3.4 is released since 5 days. I think it's time for a new release.

**Comment by HLFH** [comment]
@maikrhg https://github.com/rbenv/ruby-build/blob/master/share/ruby-build/2.3.4

**Comment by maikrhg** [comment]
@HLFH If I am not mistaken, it's in master but not in the current release.

**Comment by HLFH** [comment]
@maikrhg https://github.com/rbenv/ruby-build/releases/tag/v20170405
https://github.com/rbenv/ruby-build/pull/1072

It is now.

**Comment by maikrhg** [comment]
@HLFH 👍
