### ISSUE TITLE
rbenv install fails C compiler MacOS Sierra

### ISSUE THREAD

**Issue by fernandoaleman** [rbenv/ruby-build#1071]
I have rbenv `1.1.0` and ruby-build `20170201` installed and no matter what version of ruby I try to install, it fails with the following error:

![screen shot 2017-03-28 at 1 57 00 pm](https://cloud.githubusercontent.com/assets/523634/24422257/7e42df9a-13be-11e7-925e-80bab557ce70.png)

It is currently using the default gcc, but I have also tried installing `brew apple-gcc42` and `brew gcc` without any luck.

I have also tried uninstalling and re-installing both `rbenv` and `ruby-build` as well as the Xcode `command line tools`.

The ONLY way I can get a ruby to install is by using `sudo`. Any way to get around this? I've never had to use `sudo` before.

**Comment by mislav** [comment]
You shouldn't need either `sudo` nor an extra compiler to install Ruby 2.3.3.

Did you install xcode command lines tools properly?

**Comment by fernandoaleman** [comment]
@mislav Thank you for your quick response. Turns out I had previously added these lines of code at some point and they were causing the issue. Removing them fixed this up for me. Sorry for the false alarm. 😃

```
export LDFLAGS=L/usr/local/opt/openssl/lib
export CPPFLAGS=-I/usr/local/opt/openssl/include
export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
```
