### ISSUE TITLE
ruby-build release v20170405 identifies as v20170322

### ISSUE THREAD

**Issue by moritzheiber** [rbenv/ruby-build#1078]
Running `ruby-build --version` returns `ruby-build 20170322` while it should return `ruby-build 20170405`.

See also https://github.com/rbenv/ruby-build/blob/v20170405/bin/ruby-build#L16

Since this has been "mitigated" by a commit after the tag I'd propose a new release (and tagging after the version has been incremented) to fix this :smiley:

**Comment by hsbt** [comment]
I submit a new version of ruby-build.

https://github.com/Homebrew/homebrew-core/pull/13853

It was updated ruby-build release version and tag too 😇
