### ISSUE TITLE
bundled gems are not installed for 2.5.0-dev

### ISSUE THREAD

**Issue by k0kubun** [rbenv/ruby-build#1093]
```bash
$ rbenv install 2.4.1
(snip)
$ rbenv shell 2.4.1
$ irb
irb(main):001:0> require 'minitest'
=> true
```

```bash
$ rbenv install 2.5.0-dev
(snip)
$ rbenv shell 2.5.0-dev
$ irb
irb(main):001:0> require 'minitest'
LoadError: cannot load such file -- minitest
```

Is this intentional?

**Comment by hsbt** [comment]
Yes, It is. You got the same result with `make install` on ruby/ruby repository without `make update-gems`.

But I'm ok to invoke `make update-gems` before `make install` on ruby-build. How do you think this?

**Comment by k0kubun** [comment]
> But I'm ok to invoke make update-gems before make install on ruby-build. How do you think this?

I feel it's convenient and I want ruby-build to behave like it if there's no demerits.

**Comment by hsbt** [comment]
Created pull request https://github.com/rbenv/ruby-build/pull/1098

If you have any request, Please comment to this pr.
