### ISSUE TITLE
Ruby 2.2.4 build fails on arch linux with openssl 1.0.2

### ISSUE THREAD

**Issue by tom-mayer** [rbenv/ruby-build#1094]
[ruby-build.log.zip](https://github.com/rbenv/ruby-build/files/1061221/ruby-build.log.zip)

Hey,

I'm trying to build ruby 2.2.4 on arch linux. I have openssl-1.1 and openssl-1.0 packages installed on my system. 
Openssl 1.0 is located in `/usr/lib/openssl-1.0`.

Since 2.2.x requires openssl-1.0 I tried installing it like this:
>  PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig \
  rbenv install 2.2.4

When I look through the attached logfile, there are a lot of warnings around openssl_pkey.h. Am I doing something wrong to build Ruby agains the openssl-1.0 lib?

Cheers

**Comment by tom-mayer** [comment]
For completeness: 

> PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig \
CFLAGS+=" -I/usr/include/openssl-1.0" \
LDFLAGS+=" -L/usr/lib/openssl-1.0 -lssl" \
rbenv install 2.2.4

setting the compiler flags explicitely solved the issue for me (for the record: I don't know what PKG_CONFIG_PATH is or what it does, or if it is even needed, might also be some rvm specific thing)

**Comment by holguinj** [comment]
The above didn't quite work for me, but this did:

```
export PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig;
export CFLAGS="$CFLAGS -I/usr/include/openssl-1.0";
export LDFLAGS="$LDFLAGS -L/usr/lib/openssl-1.0 -lssl";
rbenv install 2.2.4
```

**Comment by diegomorg** [comment]
@juxtin It worked for me. Tks!! :clap:
