### ISSUE TITLE
Release jruby-9.1.12.0

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [rbenv/ruby-build#1109]
Please release a version (current master) with jruby-9.1.12.0 in it for homebrew.

**Comment by LeeXGreen** [comment]
I'd like to chime in and say that this would be useful to my organization as well -- our servers run ruby-build via git, so we can pull latest master at any time, but we can't use a given version of Ruby (JRuby 1.7.27, if it matters) until our developers can install it via homebrew.

Thanks!

**Comment by hsbt** [comment]
submitted https://github.com/Homebrew/homebrew-core/pull/16052
