### ISSUE TITLE
Strange build fail (Ruby 2.4, 2.3, 2.2) "recipe for target '.rbconfig.time' failed"

### ISSUE THREAD

**Issue by vanburg** [rbenv/ruby-build#1110]
For past years I saw a lot of issues while compiling ruby, but this one is something new for me.
All prereqs updated and installed. Googling didn't help here. 
Actually, I don't know where to dig, no clues here.
Also, I believe it's not rbenv-build issue, but if this error looks familiar for someone, please help :)
```
rbenv  install 2.4.1 --keep
Installing ruby-2.4.1...

BUILD FAILED (LinuxMint 18.1 using ruby-build 20170523-25-g476d09b)

Inspect or clean up the working tree at /home/vanburg/.rbenv/sources/2.4.1
Results logged to /tmp/ruby-build.20170622170132.19970.log

Last 10 log lines:
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

linking miniruby
uncommon.mk:643: recipe for target '.rbconfig.time' failed
make: *** [.rbconfig.time] Illegal instruction
make: *** Waiting for unfinished jobs....
generating encdb.h
uncommon.mk:853: recipe for target 'encdb.h' failed
make: *** [encdb.h] Illegal instruction
```

**Comment by vanburg** [comment]
The problem was with wrong ``CXXFLAGS`` flags.

**Comment by d-damien** [comment]
How did you solve it exactly ?

**Comment by vanburg** [comment]
@d-damien I mistakenly taken flags values for another arch. Just unset it or set to something like ``CXXFLAGS -march=native -O2 -pipe``
