### ISSUE TITLE
Recommend libssl1.0-dev for ruby 2.3 and openssl 1.1

### ISSUE THREAD

**Issue by p-salido** [rbenv/ruby-build#1111]
As already known (#1006) ruby 2.3 does not build with openssl 1.1. This is a pretty bad user experience as ruby 2.3 is not exactly old. By pure chance I came across the fix in https://github.com/dochang/dotfiles/commit/09cd0f1558cb0d8f19d02dd53f2bae96193bfa09 - simply install libssl1.0-dev instead of libssl-dev, and ruby-build is then able to build ruby 2.3.4.

ruby-build knows that openssl extension fails (it prompts to install libssl-dev which does nothing for ruby 2.3 - build still fails and the suggestion is repeated), therefore it would be good if ruby-build checked if the ruby being attempted to build is 2.3 and if openssl version is 1.1 and if libssl1.0-dev is an available package and if so recommend the latter.

**Comment by jarongao** [comment]
Also, for Fedora, the package to be checked for Ruby 2.3 should be `compat-openssl10-devel`. However, it conflicts with `openssl-devel`. I managed to install `2.3.5` and `2.3.1` under #1115.

**Comment by hsbt** [comment]
@jarongao Thanks for your information.

I update faq on wiki page: https://github.com/rbenv/ruby-build/wiki#openssl-usrincludeopensslasn1_mach102-error-error-this-file-is-obsolete-please-update-your-software
