### ISSUE TITLE
TMPDIR=/tmp cannot hold executables (partition possibly mounted with `noexec`)

### ISSUE THREAD

**Issue by joeywheels** [rbenv/ruby-build#1129]
I continue to run into a temporary directory issue. README.md does not explain how to fix this for configure TMPDIR to another folder that is not within the `noexec` parameters.

$ rbenv -v
rbenv 1.1.1-6-g2d7cefe
$ rbenv install 2.0.0-p247
ruby-build: TMPDIR=/tmp cannot hold executables (partition possibly mounted with `noexec`)

Any advice and/or solutions would be greatly appreciated.

**Comment by fauno** [comment]
maybe a little late, but according to bin/ruby-build#1287 you can just `export TMPDIR=/whatever/you/like` before installing.  It seems the directory needs to exist before hand

**Comment by mislav** [comment]
Closing in favor of @fauno's workaround. If your TMPDIR cannot hold executables, just assign a new one temporarily. We can't do it for you because we don't know where you want to store your temporary files.
