### ISSUE TITLE
Incompatible with Java 9

### ISSUE THREAD

**Issue by chrisseaton** [rbenv/ruby-build#1135]
Java 9's version is `9` - just `9`, not `1.9` - but `ruby-build` checks for `1.[789]`, so it thinks Java 9 is incompatible.

https://github.com/rbenv/ruby-build/blob/73988db2ae1cb0339f7e8fde959baf243f19f05e/bin/ruby-build#L691

**Comment by Centaur** [comment]
And this caused the "ERROR: Java 7 required. Please install a 1.7-compatible JRE." error.

**Comment by ratneshnavlakhe** [comment]
how do we resolve this issue!!

**Comment by hsbt** [comment]
Patches welcome.
