### ISSUE TITLE
Problem with space character in the name of home directory

### ISSUE THREAD

**Issue by adamvandenhovenfm** [rbenv/ruby-build#1140]
Hey, I was having trouble with rbenv on my mac becuase the IT folks put a _space_ in my home directory. certainly not a _normal_ thing to do, all things considered, and I've fixed it, but you might want to look into quoting anything that uses the home directory.

**Comment by mislav** [comment]
Thank you for reporting!

**Comment by mislav** [comment]
We haven't had other reports about this, so I'm going to close this as something that generally isn't affecting too many people. Also some parts of Ruby (like compiling native extensions with Rubygems) doesn't really like when it's installed into a path that contains spaces, so you might want to avoid that for now.
