### ISSUE TITLE
tests fail on OSX

### ISSUE THREAD

**Issue by jasonkarns** [rbenv/ruby-build#1141]
duplicate of #1056 (reopening)

latest master running on OSX on travis: https://travis-ci.org/jasonkarns/ruby-build/builds/292948933 (the compare for this branch: https://github.com/rbenv/ruby-build/compare/master...jasonkarns:osx-tests)

<details>
<summary>failures</summary>
<pre>
not ok 9 number of CPU cores defaults to 2
# (from function `unstub' in file test/test_helper.bash, line 73,
#  in test file test/build.bats, line 225)
#   `unstub uname' failed
not ok 10 number of CPU cores is detected on Mac
# (from function `unstub' in file test/test_helper.bash, line 73,
#  in test file test/build.bats, line 248)
#   `unstub uname' failed
not ok 11 number of CPU cores is detected on FreeBSD
# (from function `unstub' in file test/test_helper.bash, line 73,
#  in test file test/build.bats, line 272)
#   `unstub uname' failed
not ok 12 setting RUBY_MAKE_INSTALL_OPTS to a multi-word string
# (from function `unstub' in file test/test_helper.bash, line 73,
#  in test file test/build.bats, line 295)
#   `unstub uname' failed
not ok 13 setting MAKE_INSTALL_OPTS to a multi-word string
# (from function `unstub' in file test/test_helper.bash, line 73,
#  in test file test/build.bats, line 317)
#   `unstub uname' failed
ok 14 custom relative install destination
not ok 15 make on FreeBSD 9 defaults to gmake
# (from function `unstub' in file test/test_helper.bash, line 73,
#  in test file test/build.bats, line 346)
#   `unstub uname' failed
not ok 16 make on FreeBSD 10
# (from function `unstub' in file test/test_helper.bash, line 73,
#  in test file test/build.bats, line 358)
#   `unstub uname' failed
not ok 17 make on FreeBSD 11
# (from function `unstub' in file test/test_helper.bash, line 73,
#  in test file test/build.bats, line 370)
#   `unstub uname' failed
not ok 18 can use RUBY_CONFIGURE to apply a patch
# (from function `unstub' in file test/test_helper.bash, line 73,
#  in test file test/build.bats, line 392)
#   `unstub uname' failed
</pre>
</details>

**Comment by hsbt** [comment]
Do you still have this issue? I couldn't reproduce them.

**Comment by jasonkarns** [comment]
Yep, still have the. Reproduced on travis: https://travis-ci.org/jasonkarns/ruby-build/builds/292948933

**Comment by mislav** [comment]
Will reopen original issue
