### ISSUE TITLE
Ruby 2.4.2 fails to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by kuroda** [rbenv/ruby-build#1146]
I have installed Ruby 2.4.1 successfully on my Ubuntu 16.04 Desktop, but failed to build Ruby 2.4.2.

Here are the last lines of error log:

```
make[2]: Entering directory '/tmp/ruby-build.20171106150424.32381/ruby-2.4.2/ext/digest/md5'
compiling md5init.c
linking shared-object digest/md5.so
/usr/bin/ld: /usr/local/lib/libcrypto.a(md5_dgst.o): relocation R_X86_64_PC32 against symbol `md5_block_asm_data_order' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:262: recipe for target '../../../.ext/x86_64-linux/digest/md5.so' failed
make[2]: *** [../../../.ext/x86_64-linux/digest/md5.so] Error 1
make[2]: Leaving directory '/tmp/ruby-build.20171106150424.32381/ruby-2.4.2/ext/digest/md5'
exts.mk:198: recipe for target 'ext/digest/md5/all' failed
make[1]: *** [ext/digest/md5/all] Error 2
make[1]: Leaving directory '/tmp/ruby-build.20171106150424.32381/ruby-2.4.2'
uncommon.mk:220: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2
```

**Comment by Lewington-pitsos** [comment]
I have the same problem on ubuntu 17.10 for all ruby versions I have tried to install

Re-installing rbenv did not seem to help.

**Comment by kuroda** [comment]
[UPDATE]

I succeeded to install Ruby 2.4.2 on the *clean installed* Ubuntu 16.04 Desktop.

It seems that something goes wrong on my *working* Ubuntu 16.04.

I will close this issue after researching just a little bit more.

**Comment by kuroda** [comment]
I have not detected the root cause of the problem, I found a workaround:

1. Build `openssl` from the source:

```
$ cd /tmp
$ curl -LO https://www.openssl.org/source/openssl-1.1.0f.tar.gz
$ tar xvfz openssl-1.1.0f.tar.gz
$ cd openssl-1.1.0f
$ ./config --prefix=/opt/openssl/1.1.0f
$ make
$ sudo make install
```

2. Build ruby with `CONFIGURE_OPTS` environment variable:

```
$ CONFIGURE_OPTS="--with-openssl-dir=/opt/openssl/1.1.0f" rbenv install 2.4.2
```

**Comment by casperl** [comment]
I have the same problem.  Apt-Get installed versiion on Ubuntu 17.10 is Ruby Build version: 20161225-1
No version of Ruby installs now through rbenv.  Error reportd:
BUILD FAILED (Ubuntu 17.10 using ruby-build 20170914-5-gf41e847) .... ends in "segmentation fault, core dumped."
Since rbenv appears to have a gem version of ruby-build (did "gem update" under rbenv do this, because I did not?) I issued "gem uninstall ruby-build) and ran "rbenv install 2.3.1" using the Ubuntu installed version of Ruby-Build, but the same error and version number of Ruby-build appears.

Next step to is to uninstall + purge rbenv and to sea if Ubuntu supplied Ruby will be sufficient for my needs.

**Comment by casperl** [comment]
Purging rbenv and the ~/.rbenv directory and a clean install of rbenv performed.
Running "rbenv install 2.3.1" produced a similar error: 
![image](https://user-images.githubusercontent.com/1303185/32947783-6f296976-cba5-11e7-9632-8d6491435c30.png)

**Comment by kuroda** [comment]
@casperl I think your problem is different from mine.

I don't encounter with any segmentation faults. My problem is related to linker.

**Comment by kuroda** [comment]
@casperl

According to [a bug report](https://bugs.ruby-lang.org/issues/14076), you shoud type:

```
CC=/usr/bin/gcc-6 rbenv install 2.3.1
```

**Comment by m-rwash** [comment]
@kuroda that worked for me. Thanks!

**Comment by kuroda** [comment]
Upon the release of Ruby 2.5.0, I tried to build on my Ubuntu 16.04. I got following error messages:

```
BUILD FAILED (Ubuntu 16.04 using ruby-build 20171215-3-ga97a138)

Inspect or clean up the working tree at /tmp/ruby-build.20171226020853.23177
Results logged to /tmp/ruby-build.20171226020853.23177.log

Last 10 log lines:
make[2]: Leaving directory '/tmp/ruby-build.20171226020853.23177/ruby-2.5.0/ext/digest/sha1'
exts.mk:259: recipe for target 'ext/digest/sha1/all' failed
make[1]: *** [ext/digest/sha1/all] Error 2
linking shared-object digest.so
make[2]: Leaving directory '/tmp/ruby-build.20171226020853.23177/ruby-2.5.0/ext/continuation'
make[2]: Leaving directory '/tmp/ruby-build.20171226020853.23177/ruby-2.5.0/ext/-test-/string'
make[2]: Leaving directory '/tmp/ruby-build.20171226020853.23177/ruby-2.5.0/ext/digest'
make[1]: Leaving directory '/tmp/ruby-build.20171226020853.23177/ruby-2.5.0'
uncommon.mk:240: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2
```

As I did for Ruby 2.4.2, after building the `openssl` from the source, I succeeded to compile ruby with this command:

```
CONFIGURE_OPTS="--with-openssl-dir=/opt/openssl/1.1.0f" rbenv install 2.5.0
```

**Comment by vijaymca** [comment]
I am also getting the similar error, please could you help me.

![ruby error](https://user-images.githubusercontent.com/1425672/39635819-31584ca0-4fdc-11e8-919b-080543acadca.png)

**Comment by goermine** [comment]
Did you try to install this list of dependency in your Ubuntu system ?:
```sudo apt-get install autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-de```

**Comment by kubakrzempek** [comment]
As far as I know, (and tested) Ruby versions < 2.4 requires libssl1.0, while >2.4 libssl1.1+. The two libssl packages conflict with each other, so you can't have both of them, so I had to juggle the libs in order to install the required ruby version. To make things even funnier (or more complicated), Ruby <2.4 tends to require `gcc-6` instead of the current upstream version (which is 7).
So, usually it looks like that:
```
# for ruby <2.4
apt install libssl1.0-dev
CC=$(which gcc-6) rbenv install `version`

# for ruby >2.4
apt install libssl-dev
rbenv install `version`
```

**Comment by RaminMammadzada** [comment]
I also faced this problem. This resource helped me to solve the problem.
https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rvm-on-ubuntu-18-04

**Comment by MatzFan** [comment]
Can this issue not be closed, as both the `gcc-6` and `libssl` dependencies for earlier Rubies are documented in the wiki ([here](https://github.com/rbenv/ruby-build/wiki#gcc-compatibility) and [here](https://github.com/rbenv/ruby-build/wiki#openssl-usrincludeopensslasn1_mach102-error-error-this-file-is-obsolete-please-update-your-software))?

After installing `gcc-6` and `libssl1.0-dev` I was able to install both pre and post 2.4 Rubies on Ubuntu 18.04 as per the solution offered by @kubakrzempek without a problem. BTW it appears I do have both `libssl` libraries installed:
```
$ /sbin/ldconfig -pv|grep libssl
   libssl3.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl3.so
   libssl.so.1.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so.1.1
   libssl.so.1.0.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
   libssl.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so
```

**Comment by robclancy** [comment]
Why should it be closed? What's the point of using a tool that works with all ruby envs if you have to dive into the docs for a compile error? At the very least it should check for these dependencies before building and get them or tell you they are missing so you can install them.

**Comment by jmig5776** [comment]
@kubakrzempek 
> # for ruby <2.4
apt install libssl1.0-dev
CC=$(which gcc-6) rbenv install `version`

# for ruby >2.4
apt install libssl-dev
rbenv install `version`

this worked very well.

**Comment by bcawrse** [comment]
> ```
> # for ruby <2.4
> apt install libssl1.0-dev
> CC=$(which gcc-6) rbenv install `version`
> 
> # for ruby >2.4
> apt install libssl-dev
> rbenv install `version`
> ```

saved me installing an older Ruby version for a project I inherited.

**Comment by patrickemuller** [comment]
> As far as I know, (and tested) Ruby versions < 2.4 requires libssl1.0, while >2.4 libssl1.1+. The two libssl packages conflict with each other, so you can't have both of them, so I had to juggle the libs in order to install the required ruby version. To make things even funnier (or more complicated), Ruby <2.4 tends to require `gcc-6` instead of the current upstream version (which is 7).
> So, usually it looks like that:
> 
> ```
> # for ruby <2.4
> apt install libssl1.0-dev
> CC=$(which gcc-6) rbenv install `version`
> 
> # for ruby >2.4
> apt install libssl-dev
> rbenv install `version`
> ```

You're an angel!

**Comment by hsbt** [comment]
This issue was fixed at the first reporter.
