### ISSUE TITLE
Add support for jenv

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [rbenv/ruby-build#1151]
I tried to install `JRuby-9.1.13.0` on MacOS with Java 9 but this is currently not possible (https://github.com/rbenv/ruby-build/issues/1135). So i tried to switch the local Java version with `jenv` to `1.8`. This solves the above issue but later the "wrong" path is assumed.
The log below shows, that for the `system` instead of the `1.8` version is searched:

```
/Users/<user>/.rbenv/versions/jruby-9.1.13.0/bin/jruby: line 401: /Users/<user>/.jenv/versions/system/bin/java: No such file or directory
```
Log output:

```
rbenv install jruby-9.1.13.0
Downloading jruby-bin-9.1.13.0.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/9d156646623ac2f27174721035b52572a4b05690db7c1293295aa2c04aad3908
Installing jruby-9.1.13.0...

BUILD FAILED (OS X 10.13.1 using ruby-build 20170914)

Inspect or clean up the working tree at /var/folders/py/nf21vy_s2rqg2q95353lhk1m0000gp/T/ruby-build.20171111190733.17859
Results logged to /var/folders/py/nf21vy_s2rqg2q95353lhk1m0000gp/T/ruby-build.20171111190733.17859.log

Last 10 log lines:

    current directory: /Users/<user>/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/jruby-launcher-1.1.2-java
/Users/<user>/.rbenv/versions/jruby-9.1.13.0/bin/jruby -r ./siteconf20171111-17953-11yzvn6.rb extconf.rb
/Users/<user>/.rbenv/versions/jruby-9.1.13.0/bin/jruby: line 401: /Users/<user>/.jenv/versions/system/bin/java: No such file or directory
/Users/<user>/.rbenv/versions/jruby-9.1.13.0/bin/jruby: line 401: exec: /Users/<user>/.jenv/versions/system/bin/java: cannot execute: No such file or directory

extconf failed, exit code 126

Gem files will remain installed in /Users/<user>/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/jruby-launcher-1.1.2-java for inspection.
Results logged to /Users/<user>/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/extensions/universal-java-9/2.3.0/jruby-launcher-1.1.2-java/gem_make.out
```

Can you please add the support for [jenv](http://www.jenv.be/).

**Comment by mislav** [comment]
I don't know what jenv is, but I suspect it's something like rbenv but for Java. We won't add support for jenv because we wouldn't add explicit support for a tool like rbenv either. Rbenv and related tools works by switching PATH so that the current Ruby version is the one currently present in PATH. That means that processes don't need to be aware that there is a version switcher— they just call `ruby`, `gem` etc.

Integrating directly with a version switcher defeats the point of transparent version switcher.

**Comment by mislav** [comment]
Also see https://github.com/rbenv/ruby-build/commit/331a408adc91f786ed2707a7003422fc6a7a35cd which landed in ruby-build master
