### ISSUE TITLE
Ruby install aborted due to missing extensions on OS X Sierra and installing ruby 2.4.2

### ISSUE THREAD

**Issue by darshakthakore** [rbenv/ruby-build#1154]
I went thru the process of configuring rbenv and installed rbenv and ruby-build. Then tried to install ruby 2.4.2 and am getting the following error

```
rbenv install 2.4.2
Downloading openssl-1.1.0f.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/12f746f3f2493b2f39da7ecf63d7ee19c6ac9ec6a4fcd8c229da8a522cb12765
Installing openssl-1.1.0f...
Installed openssl-1.1.0f to /Users/dthakore/.rbenv/versions/2.4.2

Downloading ruby-2.4.2.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.2.tar.bz2
Installing ruby-2.4.2...

BUILD FAILED (OS X 10.12.6 using ruby-build 20170914)

Inspect or clean up the working tree at /var/folders/t0/rnsgj2k169n3pkzr5l2n8h7w0000gn/T/ruby-build.20171115190820.60130
Results logged to /var/folders/t0/rnsgj2k169n3pkzr5l2n8h7w0000gn/T/ruby-build.20171115190820.60130.log

Last 10 log lines:
installing rdoc:              /Users/dthakore/.rbenv/versions/2.4.2/share/ri/2.4.0/system
installing capi-docs:         /Users/dthakore/.rbenv/versions/2.4.2/share/doc/ruby
The Ruby openssl extension was not compiled.
ERROR: Ruby install aborted due to missing extensions
Configure options used:
  --prefix=/Users/dthakore/.rbenv/versions/2.4.2
  --with-openssl-dir=/Users/dthakore/.rbenv/versions/2.4.2/openssl
  CC=clang
  LDFLAGS=-L/Users/dthakore/.rbenv/versions/2.4.2/lib 
  CPPFLAGS=-I/Users/dthakore/.rbenv/versions/2.4.2/include 
```

**Comment by darshakthakore** [comment]
as an FYI, i was able to install ruby 2.3.5 without any problem. it seems like this is specific to 2.4.X versions only

**Comment by tomandersen** [comment]
I just tried rbenv install 2.3.5 and got the same missing yaml extensions error. This is on 10.13.1 high sierra, after brew upgrade and brew doctor, etc

**Comment by darshakthakore** [comment]
@tomandersen how did you determine that it was a missing yaml extensions error ? 
In my case (as per the log), it just says missing extensions, no mention of yaml. Can you post your log ?

I seem to be able to install version 2.3.5 but not any of 2.4.X

**Comment by mfdavid** [comment]
2.4.1 works fine, but 2.4.2 I get the same error (latest macOS version, rbenv and ruby-build).

**Comment by nynhex** [comment]
I'm on MacOS sierra and did not have this problem.  I will try a machine with High Sierra to see if I can replicate.  I'm on 2.4.2

**Comment by mislav** [comment]
Closing as stale
