### ISSUE TITLE
Patch striplevel detection needlessly restricted

### ISSUE THREAD

**Issue by lloeki** [rbenv/ruby-build#1159]
Detecting `$striplevel` depends on a match on `^diff --git a/` while it could readily match on `^--- a/`. This makes applying [those patches]( https://bugs.ruby-lang.org/issues/13899) a chore since they start this way:

```
diff -pU3 a/configure b/configure
--- a/configure	2017-09-14 21:09:29.000000000 +0900
+++ b/configure	2017-09-15 05:56:46.000000000 +0900
```

**Comment by mislav** [comment]
Good catch! PR welcome :)
