### ISSUE TITLE
rbenv failed to install ruby 2.4.3

### ISSUE THREAD

**Issue by dragonabv** [rbenv/ruby-build#1164]
rbenv install 2.4.3
Downloading ruby-2.4.3.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.3.tar.bz2
error: failed to download ruby-2.4.3.tar.bz2

BUILD FAILED (Ubuntu 16.04 using ruby-build 20171215-2-g5481719)

**Comment by rodloboz** [comment]
I had the same issue... Try `rbenv install 2.4.3 -v` That did the trick for me

**Comment by mislav** [comment]
The download failure is indicative of a network problem and not something we can help with. The download target itself exists:

```
$ curl -I https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.3.tar.bz2
HTTP/2 200
```
