### ISSUE TITLE
List definitions also from plugins for tools

### ISSUE THREAD

**Issue by toy** [rbenv/ruby-build#1170]
Currently there are two ways for rbenv plugins to get the list of definitions:
- `ruby-build --definitions` which lists only definitions provided by ruby-build itself
- `rbenv-install --list` which lists all definitions, but adds a line 'Available versions:' and adds indent
While output of `rbenv-install --list` can be easily cleaned, maybe it is better to provide a way to get output for tools but with definitions from other plugins? Either using second switch (like `--bare`) for `--list` or using a separate switch like `--list-bare`, `--bare-list` or `--definitions`.

**Comment by jsoref** [comment]
This made things much less discoverable. It also makes it harder to add useful help like "how do i get something which is missing from the list?"
