### ISSUE TITLE
Ruby 2.3.6 build failed

### ISSUE THREAD

**Issue by AlexWayfer** [rbenv/ruby-build#1173]
```
make[2]: *** [Makefile:301: ossl_x509crl.o] Error 1
make[2]: Leaving directory '/tmp/ruby-build.20180115182544.10577/ruby-2.3.6/ext/openssl'
make[1]: *** [exts.mk:212: ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/tmp/ruby-build.20180115182544.10577/ruby-2.3.6/ext/json/parser'
linking shared-object objspace.so
make[2]: Leaving directory '/tmp/ruby-build.20180115182544.10577/ruby-2.3.6/ext/objspace'
linking shared-object json/ext/generator.so
make[2]: Leaving directory '/tmp/ruby-build.20180115182544.10577/ruby-2.3.6/ext/json/generator'
linking shared-object pathname.so
make[2]: Leaving directory '/tmp/ruby-build.20180115182544.10577/ruby-2.3.6/ext/pathname'
linking shared-object bigdecimal.so
make[2]: Leaving directory '/tmp/ruby-build.20180115182544.10577/ruby-2.3.6/ext/bigdecimal'
linking shared-object date_core.so
make[2]: Leaving directory '/tmp/ruby-build.20180115182544.10577/ruby-2.3.6/ext/date'
linking shared-object nkf.so
make[2]: Leaving directory '/tmp/ruby-build.20180115182544.10577/ruby-2.3.6/ext/nkf'
make[1]: Leaving directory '/tmp/ruby-build.20180115182544.10577/ruby-2.3.6'
make: *** [uncommon.mk:203: build-ext] Error 2
```

[ruby-build.20180115182544.10577.log](https://github.com/rbenv/ruby-build/files/1632147/ruby-build.20180115182544.10577.log)

```
$ pacman -Qs openssl
local/openssl 1.1.0.g-1
    The Open Source toolkit for Secure Sockets Layer and Transport Layer Security
local/openssl-1.0 1.0.2.n-1
    The Open Source toolkit for Secure Sockets Layer and Transport Layer Security

$ uname -a
Linux alex-workpc-arch 4.14.13-1-ARCH #1 SMP PREEMPT Wed Jan 10 11:14:50 UTC 2018 x86_64 GNU/Linux
```

**Comment by ceclinux** [comment]
same problem here
My pc
```
Linux ceclinux-pc 4.9.76-1-MANJARO #1 SMP PREEMPT Wed Jan 10 20:17:16 UTC 2018 x86_64 GNU/Linux

```

**Comment by AlexWayfer** [comment]
Maybe related, 2.3.7 also failed.

[ruby-build.20180329105340.19745.log](https://github.com/rbenv/ruby-build/files/1859104/ruby-build.20180329105340.19745.log)

**Comment by hsbt** [comment]
@AlexWayfer Ruby 2.3 is only security maintenance status after April 2018. Therefore, It has no chance to fix build error. I suggest using Ruby 2.4 or 2.5 instead of 2.3.

**Comment by AlexWayfer** [comment]
> @AlexWayfer Ruby 2.3 is only security maintenance status after April 2018. Therefore, It has no chance to fix build error. I suggest using Ruby 2.4 or 2.5 instead of 2.3.

Thank you for your response.

Can Ruby 2.3 be shipped with necessary versions of libraries in `ruby-build`?

Ruby 2.3 is still supported, so I want to test some gems for this version.

**Comment by AlexWayfer** [comment]
It's just strange situation: `ruby-build` has Ruby 2.3 versions, and 2.3.7 has been added recently, but they can't be installed.

**Comment by hsbt** [comment]
https://github.com/rbenv/ruby-build/wiki#openssl-usrincludeopensslasn1_mach102-error-error-this-file-is-obsolete-please-update-your-software

Can you try this instruction? Ruby 2.3 didn't support OpenSSL 1.1.x.

**Comment by AlexWayfer** [comment]
> https://github.com/rbenv/ruby-build/wiki#openssl-usrincludeopensslasn1_mach102-error-error-this-file-is-obsolete-please-update-your-software
>
> Can you try this instruction? Ruby 2.3 didn't support OpenSSL 1.1.x.

Thanks, it helps! Sorry to bother you.
