### ISSUE TITLE
Release latest build to allow ruby 2.5.0 on Ubuntu

### ISSUE THREAD

**Issue by safetypins** [rbenv/ruby-build#1175]
I saw https://github.com/rbenv/ruby-build/issues/1166 and it looks like this is available in homebrew, but I use rbenv in Ubuntu for my production web server, and I'd really like to continue using rbenv. Could someone please update the ruby-build that's available for rbenv on Ubuntu to include the latest versions of Ruby? Thanks!

**Comment by hsbt** [comment]
It's out of the scope of ruby-build. Please do contact Ubuntu distributor or ruby-build maintainer of ubuntu package.
