### ISSUE TITLE
Include information about prerequisites

### ISSUE THREAD

**Issue by psukys** [rbenv/ruby-build#1177]
I found out that apparently `curl`, `gcc`, `make`, `libssl-dev`, `libreadline-dev`, `zlib1g-dev` and `bzip2` is needed for Ubuntu (guess equivalent packages for other OSs). Are there any other prereqs?

**Comment by hsbt** [comment]
We listed requirements on the wiki page of this repository.

https://github.com/rbenv/ruby-build/wiki#suggested-build-environment

Please refer it.
