### ISSUE TITLE
rbenv install (with no specified version) parses .ruby-version differently than other rbenv commands

### ISSUE THREAD

**Issue by cjlarose** [rbenv/ruby-build#1179]
### Steps to reproduce

```
mkdir ruby-build-install-test
cd !$
echo "ruby-2.3.6" > .ruby-version
rbenv install
```

### Actual

```
ruby-build: definition not found: ruby-2.3.6

See all available versions with `rbenv install --list'.

If the version you need is missing, try upgrading ruby-build:

  cd /Users/cjlarose/.rbenv/plugins/ruby-build && git pull && cd -
```

### Expected

`ruby-build` installs MRI version 2.3.6

Having a leading `ruby-` in the `.ruby-version` file is supported by most other `rbenv` functionality.

```
$ rbenv version
2.3.6 (set by /Users/cjlarose/dev/ruby-build-install-test/.ruby-version)
$ rbenv versions
  system
  2.2.4
  2.3.1
  2.3.5
* 2.3.6 (set by /Users/cjlarose/dev/ruby-build-install-test/.ruby-version)
  2.4.3
```

In fact, after installation of the Ruby, using `rbenv` with a `.ruby-version` with a `ruby-` prefix is pretty pleasant, though this functionality does not appear to be explicitly documented.

This format also appears to be supported by RVM. This is actually how I found this issue. On one project at my company, we have a `.ruby-version` file with `ruby-2.3.6`. It works fine for everyone using RVM, but for people using rbenv, they have to manually `rbenv install 2.3.6`. This isn't much of a pain when installing new apps by hand, but our automated setup tasks have to basically parse and reformat the `.ruby-version` file before installing.

**Comment by cjlarose** [comment]
It looks like rbenv-install just invokes `rbenv-local` if no version is specified as a command line argument.

https://github.com/rbenv/ruby-build/blob/01e7b7bc69b3f687056cb9e2bb0217c694fe369f/bin/rbenv-install#L116-L117

In this case, `rbenv-local` returns `ruby-2.3.6`. It's not clear whether `rbenv-local` should be modified so that it returns `2.3.6` in this case, or if it should be the responsibility of `rbenv-install` to parse.

**Comment by hsbt** [comment]
In my company, no-one uses RVM. So, I have no motivation to code this.
But I welcome to patch for this.

**Comment by cjlarose** [comment]
@hsbt I'm happy to open a patch for this, but it wasn't clear to me where the fix should be made. I think it might be reasonable to modify `rbenv-local` to return `2.3.6` if `.ruby-version` contains `ruby-2.3.6`. What do you think?

**Comment by mislav** [comment]
@cjlarose This is a good find; thank you for writing it up. Please open an issue in the rbenv repository, which is where I feel this belongs. I think the problem is that `rbenv version-name` and `rbenv local` have different outputs: the former strips the `ruby-` prefix while the latter doesn't. We can decide what to do about this then. Thank you!
