### ISSUE TITLE
Feature request: install from specific Ruby fork

### ISSUE THREAD

**Issue by boazsegev** [rbenv/ruby-build#1184]
The Ruby source is now hosted on Github and it would be great if I could use `rbenv` to install a specific Ruby fork/branch in order to simplify the Ruby development.

For example, I'm working on a fix for the ASYNC BUG error messages in Ruby and I would like to test it on my local machine. But I don't want to run the whole process of creating a VM with a modified Ruby version (for system installation) and I don't want to clutter my own system.

Having something like `rbenv install -mri git://...` would be great.

Maybe the feature exists and I couldn't find the documentation for it?

**Comment by jeremy** [comment]
You can set this up with a [custom build definition](https://github.com/rbenv/ruby-build#custom-build-definitions) that behaves like [2.6.0-dev](https://github.com/rbenv/ruby-build/blob/master/share/ruby-build/2.6.0-dev).
