### ISSUE TITLE
2.4.3, 2.4.4 failures on Arch Linux

### ISSUE THREAD

**Issue by mrzor** [rbenv/ruby-build#1190]
Greetings,

### The setup
I'm using the following to build `2.4.3` or `2.4.4` on Arch, but unfortunately it mysteriously fails.

~~~~sh
CC=/usr/bin/gcc-6 \
PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig \
rbenv install 2.4.3 -v`
~~~~

Please note that this setup works like a charm for `2.3.x` and `2.5.x`. 

### The error
Here is the end of the log, beyond the last 10 log lines:
~~~~
installing rdoc:              /home/zor/.rbenv/versions/2.4.3/share/ri/2.4.0/system
installing capi-docs:         /home/zor/.rbenv/versions/2.4.3/share/doc/ruby
Ignoring bigdecimal-1.3.4 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.4
Ignoring eventmachine-1.2.5 because its extensions are not built.  Try: gem pristine eventmachine --version 1.2.5
Ignoring ffi-1.9.18 because its extensions are not built.  Try: gem pristine ffi --version 1.9.18
Ignoring http_parser.rb-0.6.0 because its extensions are not built.  Try: gem pristine http_parser.rb --version 0.6.0
Ignoring json-2.1.0 because its extensions are not built.  Try: gem pristine json --version 2.1.0
Ignoring openssl-2.1.0 because its extensions are not built.  Try: gem pristine openssl --version 2.1.0
Ignoring psych-3.0.2 because its extensions are not built.  Try: gem pristine psych --version 3.0.2
The Ruby openssl extension was not compiled.
/home/zor/.rbenv/versions/2.4.3/lib/ruby/2.4.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
The Ruby yaml extension was not compiled.
ERROR: Ruby install aborted due to missing extensions
Configure options used:
  --prefix=/home/zor/.rbenv/versions/2.4.3
  CC=/usr/bin/gcc-6
  LDFLAGS=-L/home/zor/.rbenv/versions/2.4.3/lib 
  CPPFLAGS=-I/home/zor/.rbenv/versions/2.4.3/include 

BUILD FAILED (Arch rolling using ruby-build 20180329)

Inspect or clean up the working tree at /tmp/ruby-build.20180403155308.12342
Results logged to /tmp/ruby-build.20180403155308.12342.log
~~~~

### Investigating OpenSSL error message

When it says `The Ruby openssl extension was not compiled.` ... well I don't think so. `/tmp/ruby-build.20180403155308.12342/ruby-2.4.3/ext/openssl` is filled with `.o` files, and running `make clean; make` in that directory clearly builds (without errors), and `/tmp/ruby-build.20180403155308.12342/ruby-2.4.3/.ext/x86_64-linux` has an `openssl.so` file that looks okay to me (`ldd` shows that its correctly linked with `openssl-1.0`, notably)

### Investigating Psych error message

When the log says:

~~~~
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
The Ruby yaml extension was not compiled.
~~~~

I think it's missing the actual error ... `/tmp/ruby-build.20180403155308.12342/ruby-2.4.3/ext/psych` has the `.o` files, running `make` in that directory works, and `/tmp/ruby-build.20180403155308.12342/ruby-2.4.3/.ext/x86_64-linux` has a `psych.so`.

~~~~
 zor@windshield  /tmp/ruby-build.20180403155308.12342/ruby-2.4.3/.ext/x86_64-linux  ldd psych.so
	linux-vdso.so.1 (0x00007fff22071000)
	libyaml-0.so.2 => /usr/lib/libyaml-0.so.2 (0x00007fcfc973d000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fcfc951f000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007fcfc928c000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fcfc9088000)
	libcrypt.so.1 => /usr/lib/libcrypt.so.1 (0x00007fcfc8e50000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fcfc8b04000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fcfc874d000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007fcfc9b63000)
~~~~

~~~~
 zor@windshield  /tmp/ruby-build.20180403155308.12342/ruby-2.4.3/.ext/x86_64-linux  pacman -Qo /usr/lib/libyaml-0.so.2
/usr/lib/libyaml-0.so.2 is owned by libyaml 0.1.7-1
~~~~

from that I conclude psych extension was built, and was linked against Arch's `libyaml 0.1.7-1`

### Installing manually to get more errors ...

So something neat is that running `make install` from the `/tmp/ruby-build.20180403155308.12342/ruby-2.4.3` folder ... works ?!?

**What is ruby-build doing if not _make install_ there ? Knowing that would help me reproduce the error I got without re-running the full build**

So running `make install` worked, and indeed `rbenv versions` shows a neat `2.4.3` version.
After setting up my shell with `rbenv shell 2.4.3`, trying a few things:

~~~~
 zor@windshield  ~  ruby -v                   
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
 zor@windshield  ~  echo "puts 'YESSS?'" | ruby
YESSS?
~~~~

So the interpreter appears to be working okay.

~~~~
zor@windshield  ~  ruby -ryaml -e 'puts YAML'
Ignoring bigdecimal-1.3.4 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.4
Ignoring eventmachine-1.2.5 because its extensions are not built.  Try: gem pristine eventmachine --version 1.2.5
Ignoring ffi-1.9.18 because its extensions are not built.  Try: gem pristine ffi --version 1.9.18
Ignoring http_parser.rb-0.6.0 because its extensions are not built.  Try: gem pristine http_parser.rb --version 0.6.0
Ignoring json-2.1.0 because its extensions are not built.  Try: gem pristine json --version 2.1.0
Ignoring openssl-2.1.0 because its extensions are not built.  Try: gem pristine openssl --version 2.1.0
Ignoring psych-3.0.2 because its extensions are not built.  Try: gem pristine psych --version 3.0.2
/home/zor/.rbenv/versions/2.4.3/lib/ruby/2.4.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/home/zor/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': incompatible library version - /home/zor/.gem/ruby/2.4.0/gems/psych-3.0.2/lib/psych.so (LoadError)
	from /home/zor/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/zor/.gem/ruby/2.4.0/gems/psych-3.0.2/lib/psych.rb:11:in `rescue in <top (required)>'
	from /home/zor/.gem/ruby/2.4.0/gems/psych-3.0.2/lib/psych.rb:8:in `<top (required)>'
	from /home/zor/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/zor/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/zor/.rbenv/versions/2.4.3/lib/ruby/2.4.0/yaml.rb:6:in `<top (required)>'
	from /home/zor/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/zor/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/zor/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems.rb:701:in `load_yaml'
	from /home/zor/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems/config_file.rb:340:in `load_file'
	from /home/zor/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems/config_file.rb:202:in `initialize'
	from /home/zor/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `new'
	from /home/zor/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `do_configuration'
	from /home/zor/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems/gem_runner.rb:40:in `run'
	from /home/zor/.rbenv/versions/2.4.3/bin/gem:21:in `<main>'
~~~~

But requiring yaml ... not okay.
Got a (never seen before?) error trying in the preceding error : **`/home/zor/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in 'require': incompatible library version - /home/zor/.gem/ruby/2.4.0/gems/psych-3.0.2/lib/psych.so (LoadError)`**

### Conclusion

Something is wrong with the `2.4.x` extensions on Arch, and I am not sure what.

Any help appreciated!

Troubleshooting help welcome too : pointers to ruby extension building docs/readmes/KBs, other troubleshooting commands I could run, ideas, all welcome.

**Comment by mislav** [comment]
@mrzor Thank you for all the info, and sorry that this hasn't got more attention in the meantime.

Is this still an issue?

**Comment by mrzor** [comment]
Hello there! 

Thanks for taking the time to comb through all the old issue reports. Looks like a huge effort, and you're down to 26 opened including this one. :clap: :clap: :clap: 

I'm on another machine, so here's what I did:
~~~~
you@yours$ docker pull archlinux/base
you@yours$ docker run -it archlinux/base /bin/bash
root@container# pacman -Sy
root@container# pacman -S --needed --noconfirm base-devel git awk tar libffi libyaml openssl zlib
root@container# git clone https://github.com/rbenv/ruby-build.git
root@container# ./ruby-build/install.sh
root@container# ruby-build --version
ruby-build 20191105
~~~~
So that's for the prelude. It's not `windshield` but it'll have to do.

~~~~
root@container# ruby-build 2.4.3 /ruby-2.4.3
... (succeeds) 
root@container# /ruby-2.4.3/bin/ruby --version
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
~~~~

Color me surprised. So ruby 2.4.3 builds with ... GCC 9 and openssl 1.1 ? I'm super suprised - it used not to be the case. It is the same ruby as my 18 month old bug report, but the underlying Arch certainly changed a lot in between.

~~~~
root@container# /ruby-2.4.3/bin/ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
OpenSSL 1.1.1d  10 Sep 2019
~~~~

Doesn't get fresher than that. (Thanks Arch) So what about building against openssl-1.0 ? I don't remember the specifics, but it seems plausible that there was a gem from that 18 months old bundle that required openssl-1.0.

**Since I don't remember the original underlying issue, one could consider this a win and close this.**

---
---
---

However I'd like to dig a bit more, see if I can still reproduce after all this time with the info in the original report.

GCC6 needs to be installed from AUR - which is going to add a whole new layer of complexity/uncertainty to this endeavor. So first, let's try to build build ruby 2.4.3 + openssl 1.0 with GCC 9.

~~~~
root@container# pacman -S openssl-1.0
root@container# PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig ruby-build 2.4.3 /ruby-2.4.3+openssl-1.0
root@container# /ruby-2.4.3+openssl-1.0/bin/ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
OpenSSL 1.1.1d  10 Sep 2019
~~~~

Something masks my supplied PKG_CONFIG_PATH :thinking: 
Maybe something changed in ruby-build in the meantime, let's try exporting it ...

~~~~
root@container# export PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig
root@container# ruby-build 2.4.3 /ruby-2.4.3+openssl-1.0
root@container# /ruby-2.4.3+openssl-1.0/bin/ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
OpenSSL 1.1.1d  10 Sep 2019
~~~~

Would have been too easy. :thinking: :thinking: :thinking: 
So I rebuild with `-k` and go find `openssl/mkmf.log` and this is what I find in it:

~~~~
== Checking for required stuff... ===
"pkg-config --exists openssl"
| pkg-config --libs openssl
=> "-L/usr/lib/openssl-1.0 -lssl -lcrypto \n"
"gcc -o conftest -I../../.ext/include/x86_64-linux -I../.././include -I../.././ext/openssl -I/ruby-2.4.3+openssl-1.0/include    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -Wimplicit-fallthrough=0  -fPIC conftest.c  -L. -L../.. -L. -L/ruby-2.4.3+openssl-1.0/lib  -fstack-protector -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/ruby-2.4.3+openssl-1.0/lib -L/ruby-2.4.3+openssl-1.0/lib -lruby-static -L/usr/lib/openssl-1.0 -lssl -lcrypto -lpthread -lgmp -ldl -lcrypt -lm   -lc"
~~~~

So the variable was **not** ignored and yet the resulting ruby is linking against the wrong OpenSSL version. (Or is it ?)

~~~~
root@container ruby-2.4.3-builddir]# ldd .ext/x86_64-linux/openssl.so  | grep ssl.so
	libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007f36771c9000)
~~~~

It is linking against the wrong OpenSSL version :man_facepalming: 

I see the `-L ../..` but if the pwd is the openssl directory, that would be the ruby tarball directory. If it were the ruby extracted tarball directory (build basedir as well), well that would resolve to /tmp. Now if the pwd was `/tmp/ruby-build.20191105161728.11327.HO7rQY` then `../..` would be .. `/` and ... :thinking: still no openssl 1.1.

I don't see the right `-L/usr/lib/openssl-1.0`. Another way would be to use --with-openssl-dir configure option, but that would be a stretch.

*Can't reproduce the issue in ~2hours worth of effort*

Thanks for all the fish!

**Comment by mislav** [comment]
@mrzor Thank you for investing so much time digging into this! 💖 

It's not clear to me whether there is anything that we could solve here from within ruby-build, so due to the lack of actionable items from our end, I'm going to close this to keep the bug backlog down.
