### ISSUE TITLE
Missing ruby 2.5.0p0 on rbenv install --list / ubuntu

### ISSUE THREAD

**Issue by marvindanig** [rbenv/ruby-build#1192]
I was able to install `ruby 2.5.0p0` on my development machine (MacOS) but on the server (Ubuntu) `rbenv install --list` doesn't show the option `2.5.0p0`. It shows `2.5.0-dev` instead. Now I normally try to keep my dev/test and prod environments exactly the same so I was wondering if reporting an issue here will help?

Feel free to close this if it has been reported earlier.

**Comment by jeremy** [comment]
If you don't see a new version of Ruby that you expect, it's because your ruby-build install is too old. Check `ruby-build --version`. Upgrade ruby-build and you'll get the new Ruby versions!
