### ISSUE TITLE
Pull versions from postmodern/ruby-versions

### ISSUE THREAD

**Issue by 0xdevalias** [rbenv/ruby-build#1194]
It would be cool if the versions could be automagically updated without having to update the plugin itself.

Looking at https://github.com/postmodern/ruby-install , it pulls the versions from https://github.com/postmodern/ruby-versions

This would be a cool feature.

**Comment by hsbt** [comment]
We have the script for updating all of definitions like `script/update-cruby` from the upstream. I think we leave to this feature request.
