### ISSUE TITLE
After installing ruby 2.4.4, rubygems version is reported to be 2.6.14.1

### ISSUE THREAD

**Issue by bunufi** [rbenv/ruby-build#1197]
I am getting a following result when installing a new version of ruby using rbenv:

```
rbenv install 2.4.4
rbenv global 2.4.4
```
```
➜  gem -v
2.6.14.1
```
According to https://www.ruby-lang.org/en/news/2018/02/17/multiple-vulnerabilities-in-rubygems/, I should be able to have the new version of rubygems, which is 2.7.6.

> In principle, you should upgrade your Ruby installation to the latest version. RubyGems 2.7.6 or later includes the fix for the vulnerabilities, so upgrade RubyGems to the latest version if you can’t upgrade Ruby itself.

Is this expected behavior? I was led to believe that updating ruby to 2.4.4, will let me use rubygems of version 2.7.6

**Comment by hsbt** [comment]
It's expected behavior. 2.6.14.1 of Ruby 2.4.4 is not vulnerable. Because it contains 2.7.6 fixes for vulnerability issues.
