### ISSUE TITLE
Getting error while installing Ruby on Ubuntu 18.4

### ISSUE THREAD

**Issue by vijaymca** [rbenv/ruby-build#1200]
I am getting the below issue when im installing the ruby. I am following the below article

https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rbenv-on-ubuntu-16-04
This article for 16.4 but mine is Ubuntu 18.4

![ruby_error](https://user-images.githubusercontent.com/1425672/39636008-a2db17a4-4fdc-11e8-9206-4f973810d5b9.png)

Please, could you help me?

**Comment by hsbt** [comment]
Ruby 2.2 is not supported openssl-1.1.x. 

see its detail. https://github.com/rbenv/ruby-build/wiki#openssl-usrincludeopensslasn1_mach102-error-error-this-file-is-obsolete-please-update-your-software

**Comment by vijaymca** [comment]
@hsbt I have tried below

$ sudo apt-get install libffi-dev
$ RUBY_CONFIGURE_OPTS=--enable-shared rbenv install 2.2.1

though I am getting the same issue. Any help
