### ISSUE TITLE
rbenv failed to install 1.8.7-p375 on ubuntu16.04 LTS

### ISSUE THREAD

**Issue by mak003** [rbenv/ruby-build#1202]
Hello everyone,

I have to use ruby1.8.7-p375 on ubuntu16.04, when I run it, I got build failed error.

root@ad3426142aa2:/# rbenv install 1.8.7-p375
Checking out http://svn.ruby-lang.org/repos/ruby/branches/ruby_1_8_7...
Installing ruby-1.8.7-p375...

BUILD FAILED (Ubuntu 16.04 using ruby-build 20151028)

Inspect or clean up the working tree at /tmp/ruby-build.20180514091016.378
Results logged to /tmp/ruby-build.20180514091016.378.log

Last 10 log lines:
A    ruby-1.8.7-p375/ChangeLog
A    ruby-1.8.7-p375/mkconfig.rb
A    ruby-1.8.7-p375/ia64.s
A    ruby-1.8.7-p375/inits.c
A    ruby-1.8.7-p375/version.h
A    ruby-1.8.7-p375/eval.c
 U   ruby-1.8.7-p375
 44351
/tmp/ruby-build.20180514091016.378/ruby-1.8.7-p375 /tmp/ruby-build.20180514091016.378 /
/usr/bin/ruby-build:  521: autoconf:

I tried to install some packages, but it seems like not works. Wish anyone can help me!

Thank u all.

**Comment by p-mongo** [comment]
That is a very old ruby and is unlikely to build without patches. See https://github.com/rbenv/ruby-build/wiki#troubleshooting for known tips/workarounds for old ruby versions.

1.8.7 is almost entirely unsupported these days, you may need to adjust 1.9.3 SSL patches yourself to apply to 1.8.7 if you want/need SSL functionality.

It will also be easier building ruby from its official tarball without rbenv/ruby-build in the way. If and when that works the next step would be getting 1.8.7 built with rbenv.

**Comment by mak003** [comment]
@p-mongo Thank you for your advise! I'm doing some thing about natural language processing, need use old tool, that tool require ruby-1.8.7 . As your said, openssl is the reason. So I chose to install the ruby-1.8.7 directly and solve the problem.
Thank your very much!
