### ISSUE TITLE
C compiler cannot create executables

### ISSUE THREAD

**Issue by jenkennedy** [rbenv/ruby-build#1203]
Can someone help me with this problem? I've been searching like crazy and tried all the tricks people suggest but to no avail.  Give me the same error no matter what version of Ruby I am trying to install.  Currently running iOS 10.13.4 on my Macbook pro. Using xcode. 

rbenv install 2.3.1
ruby-build: use openssl from homebrew
Downloading ruby-2.3.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
Installing ruby-2.3.1...

BUILD FAILED (OS X 10.13.4 using ruby-build 20180424)

Inspect or clean up the working tree at /var/folders/vl/2dy_p0lj2w97zx8zz7xxbx580000gn/T/ruby-build.20180514183710.603
Results logged to /var/folders/vl/2dy_p0lj2w97zx8zz7xxbx580000gn/T/ruby-build.20180514183710.603.log

Last 10 log lines:
config.guess already exists
config.sub already exists
checking build system type... x86_64-apple-darwin17.5.0
checking host system type... x86_64-apple-darwin17.5.0
checking target system type... x86_64-apple-darwin17.5.0
checking whether the C compiler works... no
configure: error: in `/var/folders/vl/2dy_p0lj2w97zx8zz7xxbx580000gn/T/ruby-build.20180514183710.603/ruby-2.3.1':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.

**Comment by jenkennedy** [comment]
SOLVED.

My home folder had a space in the name and the compiler didn't like that apparently...

**Comment by charlotteprevost** [comment]
@jenkennedy You're a lifesaver, tysm!
