### ISSUE TITLE
getting an error from ssl?

### ISSUE THREAD

**Issue by briandsquinn** [rbenv/ruby-build#1207]
been getting this error with any version of Ruby I try to install. I've tried reinstalling openssl and still getting the same thing.

here's the last few lines of the log file it created:

> linking shared-object objspace.so
> make[2]: Leaving directory '/tmp/ruby-build.20180605123236.4773/ruby-2.2.7/ext/objspace'
> make[2]: Entering directory '/tmp/ruby-build.20180605123236.4773/ruby-2.2.7/ext/openssl'
> compiling ossl_ssl_session.c
> In file included from ossl.h:58:0,
>                  from ossl_ssl_session.c:5:
> /usr/include/openssl/asn1_mac.h:10:2: error: #error "This file is obsolete; please update your software."
>  #error "This file is obsolete; please update your software."
>   ^~~~~
> In file included from ossl.h:220:0,
>                  from ossl_ssl_session.c:5:
> openssl_missing.h:79:35: error: macro "EVP_MD_CTX_create" passed 1 arguments, but takes just 0
>  EVP_MD_CTX *EVP_MD_CTX_create(void);
>                                    ^
> In file included from /usr/include/openssl/x509.h:23:0,
>                  from /usr/include/openssl/x509v3.h:14,
>                  from ossl.h:59,
>                  from ossl_ssl_session.c:5:
> openssl_missing.h:83:6: error: expected declaration specifiers or ‘...’ before ‘(’ token
>  void EVP_MD_CTX_init(EVP_MD_CTX *ctx);
>       ^
> openssl_missing.h:91:6: error: expected declaration specifiers or ‘...’ before ‘(’ token
>  void EVP_MD_CTX_destroy(EVP_MD_CTX *ctx);
>       ^
> In file included from ossl.h:234:0,
>                  from ossl_ssl_session.c:5:
> ossl_pkey.h:44:5: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
>  #if HAVE_BN_GENCB
>      ^~~~~~~~~~~~~
> ossl_pkey.h:44:5: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
> ossl_pkey.h:44:5: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
> ossl_ssl_session.c: In function ‘SSL_SESSION_cmp’:
> ossl_ssl_session.c:79:10: error: dereferencing pointer to incomplete type ‘SSL_SESSION {aka const struct ssl_session_st}’
>      if (a->ssl_version != b->ssl_version ||
>           ^~
> ossl_ssl_session.c:83:1: warning: control reaches end of non-void function [-Wreturn-type]
>  }
>  ^
> Makefile:293: recipe for target 'ossl_ssl_session.o' failed
> make[2]: *** [ossl_ssl_session.o] Error 1
> make[2]: Leaving directory '/tmp/ruby-build.20180605123236.4773/ruby-2.2.7/ext/openssl'
> exts.mk:205: recipe for target 'ext/openssl/all' failed
> make[1]: *** [ext/openssl/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> installing default nkf libraries
> linking shared-object nkf.so
> make[2]: Leaving directory '/tmp/ruby-build.20180605123236.4773/ruby-2.2.7/ext/nkf'
> make[1]: Leaving directory '/tmp/ruby-build.20180605123236.4773/ruby-2.2.7'
> uncommon.mk:189: recipe for target 'build-ext' failed
> make: *** [build-ext] Error 2

**Comment by briandsquinn** [comment]
edits were me being a noob at github. trying to figure out that quote thing. ¯\_(ツ)_/¯

**Comment by mislav** [comment]
It would really help if you provided: 
* ruby-build version
* your OS information
* `which -a openssl` and `openssl version`

**Comment by briandsquinn** [comment]
AH! i guess it would, wouldn't it?

Ruby_Build version 20170726
Ubuntu 18.04 LTS
OpenSSL 1.1.0g 2 Nov 2017

**Comment by mislav** [comment]
@briandsquinn Thank you! Could you try a newer version of ruby-build to see if there are any differences? https://github.com/rbenv/ruby-build/releases

**Comment by tpope** [comment]
Same setup with 20180601 and can confirm the same failure. I was able to sidestep the issue by installing `libssl1.0-dev`.

**Comment by hsbt** [comment]
The old Ruby (< Ruby 2.4) didn't support openssl 1.1. Please do install libssl1.0 and libssl1.0-dev or upgrade your ruby version that was the latest version like 2.5.

See https://github.com/rbenv/ruby-build/wiki#openssl-usrincludeopensslasn1_mach102-error-error-this-file-is-obsolete-please-update-your-software
