### ISSUE TITLE
Installing Ruby 2.3.6 fails (related to OpenSSL 1.0.2o)

### ISSUE THREAD

**Issue by europ** [rbenv/ruby-build#1212]
### Installing Ruby 2.3.6 always results in a fail.

**Environment**:
OS = `Ubuntu 16.04.4 x86_64 Linux`
rbenv = `2.5.1`
ruby-build = `20180601-6-ge73041e`

<br>

The previous installations failed on an invalid OpenSSL version (more specifically on 1.1).
```
OpenSSL "/usr/include/openssl/asn1_mac.h:10:2: error: #error This file is obsolete; please update your software."
```

I had the exactly same error message as it is described in https://github.com/rbenv/ruby-build/issues/1207.

> The openssl extension of Ruby version before 2.4 is not compatible with OpenSSL 1.1.x.

Quoted from the [Wiki](https://github.com/rbenv/ruby-build/wiki#openssl-usrincludeopensslasn1_mach102-error-error-this-file-is-obsolete-please-update-your-software).

So, I installed [OpenSSL_1_0_2o](https://github.com/openssl/openssl/releases/tag/OpenSSL_1_0_2o) (OpenSSL 1.0.x is recommended) and specified the OpenSSL location manually by:
```sh
export RUBY_CONFIGURE_OPTS=--with-openssl-dir=/usr/local/ssl
```

Executing the following command:
```
rbenv install 2.3.6
```

Will result in a fail:
```
Installing ruby-2.3.6...

BUILD FAILED (Ubuntu 16.04 using ruby-build 20180601-6-ge73041e)

Inspect or clean up the working tree at /tmp/ruby-build.20180617211459.12406
Results logged to /tmp/ruby-build.20180617211459.12406.log

Last 10 log lines:
installing default bigdecimal libraries
make[2]: Leaving directory '/tmp/ruby-build.20180617211459.12406/ruby-2.3.6/ext/dbm'
make[2]: Leaving directory '/tmp/ruby-build.20180617211459.12406/ruby-2.3.6/ext/-test-/string'
linking shared-object bigdecimal.so
make[2]: Leaving directory '/tmp/ruby-build.20180617211459.12406/ruby-2.3.6/ext/bigdecimal'
linking shared-object date_core.so
make[2]: Leaving directory '/tmp/ruby-build.20180617211459.12406/ruby-2.3.6/ext/date'
make[1]: Leaving directory '/tmp/ruby-build.20180617211459.12406/ruby-2.3.6'
uncommon.mk:203: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2
```

The log file:
[`/tmp/ruby-build.20180617211459.12406.log`](https://github.com/rbenv/ruby-build/files/2109291/ruby-build.20180617211459.12406.log)

The issue may be related to the https://github.com/rbenv/ruby-build/issues/1146 which was solved by specifying the OpenSSL directory via `--with-openssl-dir=/usr/local/ssl` in `CONFIGURE_OPTS` environment variable.

Installing any other ruby versions 2.4. and above such as 2.5.1 were successfully installed.

**Comment by p-mongo** [comment]
What does this yield?

<pre>
find /usr/local/ssl |grep libcrypto
</pre>

**Comment by europ** [comment]
@p-mongo the result of `find /usr/local/ssl | grep libcrypto` is:

```
/usr/local/ssl/lib/pkgconfig/libcrypto.pc
/usr/local/ssl/lib/libcrypto.a
```

**Comment by p-mongo** [comment]
You built openssl without shared libraries. My reading of their readme suggests this isn't the default behavior. How was openssl built?

**Comment by europ** [comment]
I followed the instructions in `INSTALL` file - section `Quick Start`.

```
  $ ./config
  $ make
  $ make test
  $ make install
```

Every step was successful.
