### ISSUE TITLE
need progressbar

### ISSUE THREAD

**Issue by cooldesigns** [rbenv/ruby-build#1225]
TTY have awesome libraries about console apps.
https://piotrmurach.github.io/tty/
Also you can look these.
https://github.com/fazibear/colorize
https://github.com/janlelis/paint
https://github.com/paul/progress_bar
https://github.com/jfelchner/ruby-progressbar

**Comment by mislav** [comment]
Thank you for suggesting!

We might be showing download progress in the future #536 but not any other kind of progress bar.
