### ISSUE TITLE
Building ruby-2.5.1 on macOS Mojave fails to (re)build essential extensions

### ISSUE THREAD

**Issue by todd-a-jacobs** [rbenv/ruby-build#1236]
Installing MRI Ruby 2.5.1 on macOS Mojave using `rbenv install`  seems to break because various gem extensions aren't being built. This seems to be especially true if there is an existing ~/.gem directory that was built before upgrading macOS.

In order to work around the problem, the following worked for me:

```
gem install ffi ffi-yajl libyajl2
gem pristine --all
yes | gem update
```

There may be a more elegant solution, but that's what got me up and running with rbenv under Mojave.

**Comment by mislav** [comment]
Thanks for sharing your workaround!

Closing since there haven't been similar reports in the meantime
