### ISSUE TITLE
Please make a new release with MRI 2.5.3 included

### ISSUE THREAD

**Issue by arpitchauhan** [rbenv/ruby-build#1243]

**Comment by jvillarejo** [comment]
The released was made. 
https://github.com/rbenv/ruby-build/releases/tag/v20181018

You can check the commits. 

The problem is that the description of the release is wrong. It says:

* Add 2.3.8, 2.4.5, 2.5.2

When it should say

Add 2.3.8, 2.4.5, 2.5.3

**Comment by soberstadt** [comment]
Agreed, I am running v20181018
and do not see 2.5.3 that is in master but not released:
![image](https://user-images.githubusercontent.com/1080613/47231578-e2e2cb00-d392-11e8-801c-b3aa76c28c2d.png)

**Comment by jvillarejo** [comment]
Yes, sorry my mistake. You are right. 
I downloaded the released version and the file ```share/ruby-build/2.5.3``` wasn't packaged.

**Comment by kshitij44** [comment]
> _No description provided._

Keep up the good work. Your are doing great.
