### ISSUE TITLE
2.4.2 install fails on macos Mojave with Homebrew binutils

### ISSUE THREAD

**Issue by duckpuppy** [rbenv/ruby-build#1250]
Build log here: https://gist.github.com/duckpuppy/aec6e9ca64ef1594c3e43b37531b806a

I'm getting a weird linker error when trying to build 2.4.2 on Mojave.  I installed 2.4.5 and 2.5.3 with no issues, but I get this error every time with 2.4.2, which unfortunately I need for a project.

**Comment by duckpuppy** [comment]
I tested with putting `/usr/bin` ahead of `/usr/local/bin` so the built-in `ar` was used over the homebrew one from `binutils` and the build worked.  Later rubies seem to work with the brew installed `ar`, but not 2.4.2...

**Comment by imeteora** [comment]
met this issue too, have not idea about it. why does libruby-static.a is  an ar achive?

**Comment by mislav** [comment]
@duckpuppy Thank you for reporting.

Homebrew's binutils are not supposed to be linked into `/usr/local`:

```
==> Caveats
binutils is keg-only, which means it was not symlinked into /usr/local,
because because Apple provides the same tools and binutils is poorly supported on macOS.
```

If you link it, then unexpected build errors can occur at your own risk.
