### ISSUE TITLE
Issue installing rbenv - win10 -bash on ubuntu

### ISSUE THREAD

**Issue by cortuga** [rbenv/ruby-build#1273]
Can anyone help me with this issue? 

I've tried installing a couple times with the same error:

Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 200 not upgraded.
1 not fully installed or removed.
Need to get 0 B/15.3 MB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
dpkg: error processing package emacs24-el (--configure):
 package is in a very bad inconsistent state; you should
 reinstall it before attempting configuration
Errors were encountered while processing:
 emacs24-el
E: Sub-process /usr/bin/dpkg returned an error code (1)

Thanks in advance!

**Comment by cortuga** [comment]
I feel so dumb. I see the solution now. lol.

**Comment by hsbt** [comment]
It's not rbenv or ruby-build issues. It's an issue of your environment of Ubuntu on Windows.

We have no solution for this.
