### ISSUE TITLE
conflicts Homebrew's OpenSSL and local LibreSSL

### ISSUE THREAD

**Issue by lufia** [rbenv/ruby-build#1277]
On my mac, Homebrew is installed at **/opt/homebrew** because **/usr/local** is used for other programs. And also, LibreSSL is installed at **/usr/local**.

In case of above, `gem` of Ruby that built with `rbenv` crashes:

```console
$ rbenv install
ruby-build: use openssl from homebrew
Downloading ruby-2.6.0.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.0.tar.bz2
Installing ruby-2.6.0...
ruby-build: use readline from homebrew
Installed ruby-2.6.0 to /Users/lufia/pkg/rbenv/versions/2.6.0

$ gem install bundle
dyld: lazy symbol binding failed: Symbol not found: _SSL_CTX_set_min_proto_version
  Referenced from: /Users/lufia/pkg/rbenv/versions/2.6.0/lib/ruby/2.6.0/x86_64-darwin18/openssl.bundle
  Expected in: flat namespace

dyld: Symbol not found: _SSL_CTX_set_min_proto_version
  Referenced from: /Users/lufia/pkg/rbenv/versions/2.6.0/lib/ruby/2.6.0/x86_64-darwin18/openssl.bundle
  Expected in: flat namespace
```

`SSL_CTX_set_min_proto_version` is declared in LibreSSL's /usr/local/include/openssl/ssl.h, but Homebrew's OpenSSL don't have.

I tried to build ruby without `ruby-build`:

```console
$ cd ruby-2.6.0
$ CFLAGS='-I/opt/homebrew/opt/openssl/include' make
```

Then, `gem` don't crash.

How to do give priority to **/opt/homebrew/opt/openssl/include** ?

**Comment by mislav** [comment]
You can try something like

```
RUBY_CONFIGURE_OPTS="--with-openssl-dir=`brew --prefix openssl`" rbenv install 2.6.0
```

However, the `ruby-build: use openssl from homebrew` line of output in what you reported above suggests that ruby-build tried to use that openssl dir automatically. I'm not sure what exactly is the problem here.

**Comment by hsbt** [comment]
> How to do give priority to **/opt/homebrew/opt/openssl/include** ?

Use or google `DYLD_LIBRARY_PATH`.
