### ISSUE TITLE
ruby-build ignores my mirror env

### ISSUE THREAD

**Issue by KsRyY** [rbenv/ruby-build#1290]
I have set the `RUBY_BUILD_MIRROR_URL` to the China ruby URL and set `RUBY_BUILD_SKIP_MIRROR` to `no`, but ruby-build still downloads source from the official repo.

I'm using ruby-build from asdf-vm

**Comment by mislav** [comment]
RUBY_BUILD_SKIP_MIRROR needs to be blank if you intend to use the mirror, not "no"!
