### ISSUE TITLE
Error installing any ruby version on MacOS 10.14.4 (Xcode 10.2)

### ISSUE THREAD

**Issue by federico-garcia** [rbenv/ruby-build#1295]
I have tried installing different versions of ruby without success.

This is the installation log:
```/var/folders/j6/_slhkj_s1xgdkgl4_x83ngx40000gn/T/ruby-build.20190331203847.1476 ~
/var/folders/j6/_slhkj_s1xgdkgl4_x83ngx40000gn/T/ruby-build.20190331203847.1476/ruby-2.5.5 /var/folders/j6/_slhkj_s1xgdkgl4_x83ngx40000gn/T/ruby-build.20190331203847.1476 ~
checking for ruby... /usr/bin/ruby
tool/config.guess already exists
tool/config.sub already exists
checking build system type... x86_64-apple-darwin18.5.0
checking host system type... x86_64-apple-darwin18.5.0
checking target system type... x86_64-apple-darwin18.5.0
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /usr/local/bin/ggrep
checking for egrep... /usr/local/bin/ggrep -E
checking whether clang needs -traditional... no
checking for ld... ld
checking whether the linker is GNU ld... no
checking whether clang -E accepts -o... yes
checking for real target cpu... x86_64
checking for ranlib... (cached) :
checking for ar... (cached) libtool -static
checking for libtool -static flags... (cached) -no_warning_for_no_symbols -o
checking for as... as
checking for objdump... objdump
checking for objcopy... no
checking for gobjcopy... no
checking for nm... nm
checking whether ln -s works... yes
checking whether make sets $(MAKE)... make: *** No targets specified and no makefile found.  Stop.
```

I have tried several workarounds found googling the error, still no success.

Thanks.

**Comment by federico-garcia** [comment]
I upgrade ruby-build to `https://github.com/rbenv/ruby-build/archive/v20190401.tar.gz` but I still get the same error.

**Comment by federico-garcia** [comment]
I ran `rbenv-doctor` and everything is OK.

`curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
Checking for `rbenv' in PATH: /usr/local/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: /usr/local/bin/rbenv-install (ruby-build 20190401)
Counting installed Ruby versions: none
  There aren't any Ruby versions installed under `/Users/federico/.rbenv/versions'.
  You can install Ruby versions like so: rbenv install 2.2.4
Checking RubyGems settings: OK
Auditing installed plugins: OK`

**Comment by mislav** [comment]
Have you tried `xcode-select --install`?

**Comment by stephanvane** [comment]
What version of Xcode do you have installed? In my case Xcode refused to update, and was stuck at version 9, causing the exact same problems. This worked for me:

1. Remove/uninstall Xcode
2. Download and install Xcode **10** from the app-store
3. **Start Xcode**
4. Press yes to install additional components
5. try again to install ruby 

I hope this helps someone!

**Comment by harokevin** [comment]
@stephanvane I did not want to uninstall my 9.4 xcode install for the newest version because of an ongoing react-native project but it did work. Thank you for your comment.

**Comment by mislav** [comment]
@federico-garcia Is this still a problem?

**Comment by hsbt** [comment]
There is no feedback over 1 year. I will close this.
