### ISSUE TITLE
2.7.0-dev fails to build on Mac OS X 10.14.4

### ISSUE THREAD

**Issue by snowe2010** [rbenv/ruby-build#1301]
`rbenv install 2.7.0-dev` results in `make: *** No targets specified and no makefile found.  Stop.` error. I have reviewed the entire troubleshooting guide and have made sure I've installed all the required modules. I have other versions of ruby installed perfectly fine. 

I found [this bug](https://bugs.ruby-lang.org/issues/15232) from years ago that seems to be the issue. Maybe it has popped up again in a recent release?

Error log:

<details>
<summary>Details</summary>
<pre>
rbenv install 2.7.0-dev                                                                                                                           
ruby-build: use openssl from homebrew
Cloning https://github.com/ruby/ruby.git...
Installing ruby-trunk...
ruby-build: use readline from homebrew

BUILD FAILED (OS X 10.14.4 using ruby-build 20190401)

Inspect or clean up the working tree at /var/folders/__/744w2qvj2l18z3dbywtqqdyc0000gp/T/ruby-build.20190417192919.36174
Results logged to /var/folders/__/744w2qvj2l18z3dbywtqqdyc0000gp/T/ruby-build.20190417192919.36174.log

Last 10 log lines:
/var/folders/__/744w2qvj2l18z3dbywtqqdyc0000gp/T/ruby-build.20190417192919.36174 ~/Documents/code/backend/promon-pluggle
Cloning into 'ruby-trunk'...
Checking out files: 100% (9094/9094), done.
/var/folders/__/744w2qvj2l18z3dbywtqqdyc0000gp/T/ruby-build.20190417192919.36174/ruby-trunk /var/folders/__/744w2qvj2l18z3dbywtqqdyc0000gp/T/ruby-build.20190417192919.36174 ~/Documents/code/backend/promon-pluggle
checking for ruby... /Users/tyler.thrailkill/.rbenv/shims/ruby
configure: error: cannot run /bin/sh tool/config.sub
make: *** No targets specified and no makefile found.  Stop.
</pre>
</details>

**Comment by mislav** [comment]
Thank you for reporting, but `-dev` versions are at your own risk (they are moving targets, after all) and we can't provide support for compiling them. In the meantime, `2.7.0-preview2` came out, so you can use that! It compiles well on my macOS
