### ISSUE TITLE
rbenv install 2.3.8 FAILED

### ISSUE THREAD

**Issue by jnpumarada** [rbenv/ruby-build#1303]
I'm in the middle of reinstalling my Ruby version 2.3.8. I didn't have any problems with my first installation, but I had some issues along the way (installation of gem and bundler, etc.) and based on my research the recommended solution was to uninstall. So I did, and now I'm reinstalling. However, I'm having problems.

This is the command that I typed:

> rbenv install 2.3.8

And this is the result that I'm getting:

> Downloading ruby-2.3.8.tar.bz2...
> -> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.8.tar.bz2
> Installing ruby-2.3.8...
> 
> BUILD FAILED (Ubuntu 18.04 using ruby-build 20190423)
> 
> Inspect or clean up the working tree at /tmp/ruby-build.20190505184003.14321
> Results logged to /tmp/ruby-build.20190505184003.14321.log
> 
> Last 10 log lines:
>   CCLD     libffi.la
> ar: 'u' modifier ignored since 'D' is the default (see 'U')
> make[5]: Leaving directory '/tmp/ruby-build.20190505184003.14321/ruby-2.3.8/ext/fiddle/libffi-3.2.1'
> make[4]: Leaving directory '/tmp/ruby-build.20190505184003.14321/ruby-2.3.8/ext/fiddle/libffi-3.2.1'
> make[3]: Leaving directory '/tmp/ruby-build.20190505184003.14321/ruby-2.3.8/ext/fiddle/libffi-3.2.1'
> linking shared-object fiddle.so
> make[2]: Leaving directory '/tmp/ruby-build.20190505184003.14321/ruby-2.3.8/ext/fiddle'
> make[1]: Leaving directory '/tmp/ruby-build.20190505184003.14321/ruby-2.3.8'
> uncommon.mk:203: recipe for target 'build-ext' failed
> make: *** [build-ext] Error 2

I've tried commands vagrant and ssh, as well as apt-get update. All have been successful, but when I finally proceed to install Ruby, the error above prompts.

Any help?

**Comment by mislav** [comment]
It looks like you're having problems with [ruby-build](https://github.com/rbenv/ruby-build), which is the plugin that provides the `rbenv install` command.

1. First, [ensure that ruby-build is updated](https://github.com/rbenv/ruby-build/wiki#updating-ruby-build) to the latest version.
2. If your problem persists, [check existing issues in the ruby-build repo](https://github.com/rbenv/ruby-build/issues) and open a new one if necessary. When opening a new issue, please attach the full build log.
