### ISSUE TITLE
Ruby 2.4.6 missing?

### ISSUE THREAD

**Issue by 0xdevalias** [rbenv/ruby-build#1304]
Looking at https://github.com/postmodern/ruby-versions/blob/master/ruby/stable.txt#L2 2.4.6 is included, but when I run `ruby-install` it's not listed:
```
⇒  ruby-install
Stable ruby versions:
  ruby:
    2.2.10
    2.3.8
    2.4.5
..snip..
```

Is there some way I can force my version to pull the latest list?

```
⇒  ruby-build --version
ruby-build 20190423
```

Alternatively, maybe the version on `brew` is outdated?

```
⇒  brew info ruby-build
ruby-build: stable 20190423, HEAD
```

Which seems to match the latest release: https://github.com/rbenv/ruby-build/releases/tag/v20190423

Which seems to have a definition for 2.4.6: https://github.com/rbenv/ruby-build/commit/cfc4cf0c827b108fd43634ae9237ff759e852744

It just doesn't seem to show in the list of stable ruby versions.

**Comment by hsbt** [comment]
Can you file it to https://github.com/postmodern/ruby-install ? This repository is `ruby-build`.

**Comment by 0xdevalias** [comment]
My bad.. started there, but must have got my tabs messed up ;p
