### ISSUE TITLE
Install ruby 2.3.0 fails in ubuntu 19.04

### ISSUE THREAD

**Issue by maxidr** [rbenv/ruby-build#1308]
Hello, I have an issue when try to install ruby 2.3.0 

libreadline-dev, libcurl4-openssl-dev, software-properties-common and libssl-dev is instaled (libssl1.0-dev is not present in Ubuntu 19.04)

> The Ruby openssl extension was not compiled.
> ERROR: Ruby install aborted due to missing extensions
> Try running `apt-get install -y libssl-dev` to fetch missing dependencies.

 [complete log](https://gist.github.com/maxidr/cd4c12857d3b4190c6cab21877fc144a)

**Comment by hsbt** [comment]
There is no solution to install ruby 2.3.x with openssl 1.1.x. Please use Ruby 2.4+ or LTS version of Ubuntu.

**Comment by ayqazi** [comment]
Is it not possible to install openssl 1.0 in a separate location and pass flags to ruby-build to use that instead of the system-installed openssl?
