### ISSUE TITLE
rbenv install bash script fails on bash 4.4.19

### ISSUE THREAD

**Issue by passmore** [rbenv/ruby-build#1315]
Problem raised in #323 seems to be happening again: `rbenv install --list` gives
rbenv-install: line 73: parse_options: command not found

I'm using ruby-build v20190615 with GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)

I ran rbenv-doctor and it confirms:

> Checking `rbenv install' support: ~/.rbenv/plugins/ruby-build/bin/rbenv-install/usr/bin/env: ‘bash\r’: No such file or directory
~/.rbenv/plugins/ruby-build/bin/rbenv-install: line 73: parse_options: command not found

**Comment by passmore** [comment]
I ran rbenv-doctor and it confirms:
`Checking `rbenv install' support: /home/passmore/.rbenv/plugins/ruby-build/bin/rbenv-install/usr/bin/env: ‘bash\r’: No such file or directory
/home/passmore/.rbenv/plugins/ruby-build/bin/rbenv-install: line 73: parse_options: command not found`

**Comment by mislav** [comment]
`` ‘bash\r’: No such file or directory ``: maybe the problem isn't the version of bash, but the fact the files that you've checked out seem to have CR-LF line endings (`\r\n`), whereas they should only ever have LF? Please check your git settings.

**Comment by passmore** [comment]
Thanks very much Mislav, that was the problem. Git was configured with auto crlf, when I deleted this and reinstalled ruby-build it all worked as before.
