### ISSUE TITLE
ruby-build 2.3.0 fails on debian/jessie beaglebone 

### ISSUE THREAD

**Issue by jonhp** [rbenv/ruby-build#1319]
[ruby-build.20190702201315.12123.log](https://github.com/rbenv/ruby-build/files/3354722/ruby-build.20190702201315.12123.log)
i was not able to capture the terminal window.
rbenv version is 0.4.0
the input command was rbenv install 2.3.0
the last few lines of the log file are:
`Generating RI format into /tmp/ruby-build.20190702201315.12123/ruby-2.3.0/.ext/rdoc...
Killed
uncommon.mk:441: recipe for target 'rdoc' failed
make: *** [rdoc] Error 137`

**Comment by znz** [comment]
I think insufficient memory causes `Killed`.
`RUBY_CONFIGURE_OPT=--disable-install-doc` may resolve the issue.

**Comment by mislav** [comment]
@jonhp Thank you for reporting. I think @znz's diagnosis is correct and workaround will likely solve this for you.
