### ISSUE TITLE
Can't install Ruby 2.6.3 on macOS 10.14.5

### ISSUE THREAD

**Issue by sewong98** [rbenv/ruby-build#1320]
This is what happens when I try to install ruby 2.6.3. Not sure what's going on here.

➜  / rbenv install 2.6.3
ruby-build: use openssl from homebrew
Downloading ruby-2.6.3.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.3.tar.bz2
error: failed to download ruby-2.6.3.tar.bz2

BUILD FAILED (OS X 10.14.5 using ruby-build 20190423)

Inspect or clean up the working tree at /var/folders/_5/vp4j4k5s6pngq64ws34q08700000gn/T/ruby-build.20190715004453.27545
Results logged to /var/folders/_5/vp4j4k5s6pngq64ws34q08700000gn/T/ruby-build.20190715004453.27545.log

Last 10 log lines:
/var/folders/_5/vp4j4k5s6pngq64ws34q08700000gn/T/ruby-build.20190715004453.27545 /
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60

**Comment by iamricks** [comment]
Same issue here

**Comment by naoufalelh** [comment]
I just come across this problem this morning here is what I did: `brew update && brew upgrade ruby-build`
then run `rbenv install 2.6.3` again.

**Comment by mislav** [comment]
Thanks for reporting! I'm going to assume that “error: failed to download ruby-2.6.3.tar.bz2” has been a temporal network error and that it has resolved itself since then.

**Comment by tom-brown** [comment]
I'm still having this problem, brew update &&  brew upgrade no help

**Comment by iamricks** [comment]
@tom-brown What OS are you on?

**Comment by tom-brown** [comment]
> @tom-brown What OS are you on?

10.14.6, and actually I was able to install 2.6.3.  I couldn't install 2.6.5. updating question now.
