### ISSUE TITLE
Unable to install Ruby 2.5.1 on macOS 10.14 Mojave

### ISSUE THREAD

**Issue by ActionScripted** [rbenv/ruby-build#1327]
When running the following:

```bash
rbenv install 2.5.1
```

The install fails with the following output:

```bash
ruby-build: use openssl from homebrew
Downloading ruby-2.5.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.1.tar.bz2
Installing ruby-2.5.1...
ruby-build: use readline from homebrew

BUILD FAILED (OS X 10.14 using ruby-build 20180822)

Inspect or clean up the working tree at /var/folders/5g/f1t038j95cnf6xcvb783rl5hh80m9n/T/ruby-build.20180925130957.80594
Results logged to /var/folders/5g/f1t038j95cnf6xcvb783rl5hh80m9n/T/ruby-build.20180925130957.80594.log

Last 10 log lines:
Ignoring openssl-2.1.1 because its extensions are not built. Try: gem pristine openssl --version 2.1.1
ERROR: Ruby install aborted due to missing extensions
Configure options used:
  --prefix=/Users/mthompson/.local/share/rbenv/versions/2.5.1
  --with-openssl-dir=/usr/local/opt/openssl
  --with-readline-dir=/usr/local/opt/readline
  CC=clang
  CFLAGS= -O3 -Wno-error=shorten-64-to-32
  LDFLAGS=-L/Users/mthompson/.local/share/rbenv/versions/2.5.1/lib
  CPPFLAGS=-I/Users/mthompson/.local/share/rbenv/versions/2.5.1/include
```

Full log: https://gist.github.com/ActionScripted/526c7a85797fb0d05bb54000bc922d00

**Comment by david-montante** [comment]
Just do `sudo rvm install 2.5.1`

**Comment by vadviktor** [comment]
I had `openssl` and `openssl@1.1` installed by Homebrew. Only `openssl@1.1` had dependent packages so I removed `openssl` and tried to install 2.6.4 with success.

**Comment by ioagel** [comment]
Just use `openssl@1.1` and add the following settings in` .bashrc` or `.zshrc`:

`export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"`
`export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"`
`export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"`
`export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"`

You can have `openssl 1.0.2t` side by side with `openssl@1.1` but you need to add the above exports in your shell conf files.
