### ISSUE TITLE
Unable to install Ruby 2.6.3 on macOS 10.14.5 Mojave

### ISSUE THREAD

**Issue by DoctorofTheEARTH** [rbenv/ruby-build#1332]
help me....
This is the first time to install Ruby.
when I run "rbenv install 2.6.3," this happens.
I cannot figure the solution out.
what steps do I have to fix it??

ruby-build: use openssl from homebrew
Downloading ruby-2.6.3.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.3.tar.bz2
Installing ruby-2.6.3...

BUILD FAILED (OS X 10.14.5 using ruby-build 20190423)

Inspect or clean up the working tree at /var/folders/ss/t826qgw50bg9_k1vdfq1q2940000gn/T/ruby-build.20190802010118.21626
Results logged to /var/folders/ss/t826qgw50bg9_k1vdfq1q2940000gn/T/ruby-build.20190802010118.21626.log

Last 10 log lines:
tool/config.guess already exists
tool/config.sub already exists
checking build system type... x86_64-apple-darwin18.6.0
checking host system type... x86_64-apple-darwin18.6.0
checking target system type... x86_64-apple-darwin18.6.0
checking whether the C compiler works... no
configure: error: in `/var/folders/ss/t826qgw50bg9_k1vdfq1q2940000gn/T/ruby-build.20190802010118.21626/ruby-2.6.3':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.

**Comment by mislav** [comment]
I'm sorry you have had trouble. I don't know what causes this, but see other threads: https://github.com/rbenv/ruby-build/issues/1364 https://github.com/rbenv/ruby-build/issues/1203 https://github.com/rbenv/ruby-build/issues/1193 https://github.com/rbenv/ruby-build/issues/779 https://github.com/rbenv/ruby-build/issues/640 https://github.com/rbenv/ruby-build/issues/353 https://github.com/rbenv/ruby-build/issues/319
