### ISSUE TITLE
Ruby 2.6.3 build failed for ConEmu/MINGW64 on Windows 10

### ISSUE THREAD

**Issue by ryanhinton** [rbenv/ruby-build#1337]
I am receiving the following error using ConEmu/MINGW64 on Windows 10.  I have installed MinGW to original tackle the first error of no gcc installed.  After that was taken care of, I now receive this error.  I cannot find anything to help with this problem, so creating this issue is my last resort to hopefully finding or receiving a solution.  Please let me know if there is anything else I can do to help supply you with the information that you may need.  Thank you!

```Ryan@Ryan-Y70 MINGW64 ~
$ rbenv install 2.6.3
Downloading ruby-2.6.3.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.3.tar.bz2
Installing ruby-2.6.3...

BUILD FAILED (MINGW64_NT-10.0-18362 3.0.7-338.x86_64 using ruby-build 20190615-7-g0e9094b)

Inspect or clean up the working tree at /tmp/ruby-build.20190816160241.8684
Results logged to /tmp/ruby-build.20190816160241.8684.log

Last 10 log lines:
c:\mingw\include\time.h:463:5: note: previous declaration of 'clock_getres' was here
 int clock_getres (clockid_t, struct timespec *);
     ^~~~~~~~~~~~
cc1.exe: warning: unrecognized command line option '-Wno-self-assign'
cc1.exe: warning: unrecognized command line option '-Wno-parentheses-equality'
cc1.exe: warning: unrecognized command line option '-Wno-constant-logical-operand'
make: *** [miniinit.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [dmydln.o] Error 1
make: *** [main.o] Error 1```

**Comment by mislav** [comment]
@ryanhinton Hi, sorry for the late reply. You didn't provide the relevant part of the full log in `/tmp/ruby-build.20190816160241.8684.log`, it seems. Your output only shows the last 10 lines, but they are only (non-fatal) warnings and not indicative of the underlying error.

If you have solved this in the meantime, please feel free to close. Thank you!

**Comment by jasonkarns** [comment]
Is this still an issue? If so, it looks related to #1307 ?

**Comment by hsbt** [comment]
ruby-build doesn't support mingw/msys environment. I recommend to use WSL2 on Windows.
