### ISSUE TITLE
Is it possible to let ruby-build use another set of definition file?

### ISSUE THREAD

**Issue by KsRyY** [rbenv/ruby-build#1342]
I am a developer in China and my connection to `cache.ruby-lang.org` is very slow. I always need to modify the definition file before install to make ruby-build download from the Chinese mirror.

Is it possible to make ruby-build use another set of definition file?

**Comment by jasonkarns** [comment]
Please see the readme docs for package mirrors: https://github.com/rbenv/ruby-build#package-mirrors

You can configure a custom mirror url or to skip mirrors entirely without modifying the build definition. See the env vars: `RUBY_BUILD_MIRROR_URL` and `RUBY_BUILD_SKIP_MIRROR` which are both documented under https://github.com/rbenv/ruby-build#custom-build-configuration

Also documented with the environment variables, is `RUBY_BUILD_DEFINITIONS` which lets you add additional paths to search for definition files.
