### ISSUE TITLE
macOS Catalina Version 10.15 Beta - Bug

### ISSUE THREAD

**Issue by MelihOzyurt** [rbenv/ruby-build#1343]
macOS Catalina, Version 10.15 Beta,

Message:
    Error code 126
Error: Command failed: scss-lint 'src/sass/index.scss' 'src/sass/components/introducing/_c-introducing-home.scss' --format=JSON
/bin/sh: /usr/local/bin/scss-lint: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory

Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false

[16:43:08] 'default' errored after 1.29 s
error Command failed with exit code 1.

**Comment by hsbt** [comment]
What's the bug of ruby-build? It seems to issue of shebang of `scss-lint`.

**Comment by MelihOzyurt** [comment]
By following the steps below I got rid of the (Gem :: FilePermissionError) error.

1- micro ~/.zshrc
2- eval "$(rbenv init -)" (last row)
3- rbevn global 2.3.0
4- gem install compass
5- gem install scss_lint
