### ISSUE TITLE
Cannot install ruby on macOS 10.14.4

### ISSUE THREAD

**Issue by stevetoro** [rbenv/ruby-build#1344]
**Edit:** To clarify, this is happening with all versions of Ruby that I try to install with rbenv.

I'm trying to install ruby 2.6.4 with rbenv 1.1.2. Machine is macOS Mojave. 

The command `rbenv install 2.6.4` just hangs after reaching `ruby-build: using readline from homebrew`.

From other threads, I've tried running `RUBY_CONFIGURE_OPTS=--with-readline-dir="$(brew --prefix readline)" rbenv install 2.6.4 ` as well as disabling (uninstalling) my antivirus software. Uninstalling and reinstalling brew, rbenv, ruby-build, readline, etc. Same result.

Here's the log:

```
/var/folders/9n/xdg2y2z93qj4_v2qb670y4qc0000gn/T/ruby-build.20190903184112.84286 ~/.rbenv
/var/folders/9n/xdg2y2z93qj4_v2qb670y4qc0000gn/T/ruby-build.20190903184112.84286/ruby-2.6.4 /var/folders/9n/xdg2y2z93qj4_v2qb670y4qc0000gn/T/ruby-build.20190903184112.84286 ~/.rbenv
checking for ruby... /Users//.rbenv/shims/ruby
tool/config.guess already exists
tool/config.sub already exists
checking build system type... x86_64-apple-darwin18.5.0
checking host system type... x86_64-apple-darwin18.5.0
checking target system type... x86_64-apple-darwin18.5.0
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether clang needs -traditional... no
checking for ld... ld
checking whether the linker is GNU ld... no
checking whether clang -E accepts -o... yes
checking for clang... /usr/bin/clang
checking for real target cpu... x86_64
checking for ranlib... (cached) :
checking for ar... (cached) libtool -static
checking for libtool -static flags... (cached) -no_warning_for_no_symbols -o
checking for as... as
checking for objdump... objdump
checking for objcopy... no
checking for gobjcopy... no
checking for nm... nm
checking whether ln -s works... yes
checking whether make sets $(MAKE)... make: *** No targets specified and no makefile found.  Stop.
```

**Comment by StephRicardo** [comment]
I'm also experiencing this issue

**Comment by armcknight** [comment]
Hit the same issue, and when I run `rbenv install --list` there is no `2.6.4`–or `2.6.3` for that matter–the latest in the `2.6.x` series is `2.6.2`.

**Comment by gfguthrie** [comment]
@armcknight you probably need to update `ruby-build`. Latest is `20191111`.

**Comment by joaquinnunez** [comment]
I have almost the same issue, mac os 10.15.4, ruby-build 20200401, my build hangs here
```checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking if make is GNU make... yes
.ext/include/x86_64-darwin19/ruby/config.h updated
configure: ruby library version = 2.5.0
configure: creating ./config.status
config.status: creating GNUmakefile
config.status: creating Makefile
```
for different ruby versions

**Comment by pelted** [comment]
I've been trying to get this installed for the last few hours on a new iMac with 10.15.6. Fresh install of homebrew and keeps hanging in the same spot `config.status: creating Makefile`. 

I've had readline give me issues in the past on but all the tricks I used to use haven't worked.

**Comment by kwuuu** [comment]
> I've been trying to get this installed for the last few hours on a new iMac with 10.15.6. Fresh install of homebrew and keeps hanging in the same spot `config.status: creating Makefile`.
> 
> I've had readline give me issues in the past on but all the tricks I used to use haven't worked.

Hello I ran into the same exact issue. This is what fixed it for me:

Catalina XCode command line tools no longer as SVN, and at that specific part of the installation, it relies on SVN being installed on your computer, so it gets stuck there if your computer is missing it.

so basically, running this:
`brew install evn`

and then trying again, resolved everything for me

**Comment by pelted** [comment]
@kwuuu THANK YOU! 
The little things we take for granted sometimes, like SVN just being there.

**Comment by ShanaSkydancer** [comment]
@kwuuu This fixed it for me!
Thank you so much!

*gives you a virtual coffee and high five*

**Comment by stevetoro** [comment]
Just as an update, this continues to happen on macOS 10.15.7 with rbenv 1.1.2 and ruby-build 20201210.

`rbenv install -v 2.7.2` shows the command hanging at `checking whether make sets $(MAKE)... make: *** No targets specified and no makefile found.  Stop.`

I've tried uninstalling homebrew, rbenv, make, etc. rvm is completely removed.
