### ISSUE TITLE
Feature request - Ruby-1.8.7 (1.9.3) to build on FreeBSD-12

### ISSUE THREAD

**Issue by byrnejb** [rbenv/ruby-build#1346]
I have a requirement to run a RoR-3 application on a FreeBSD-12.0 host.   It requires Ruby-1.8.7. Naturally, this is so old that the build environment onf FreeBSD is incompatible and Ruby-Build fails. Nonetheless, if it is possible to do I would like a standalone ability to build 1.8.7 on FreeBSD provided.

```
rbenv install 1.8.7-p375
Checking out http://svn.ruby-lang.org/repos/ruby/branches/ruby_1_8_7...
Installing ruby-1.8.7-p375...

WARNING: ruby-1.8.7-p375 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.


BUILD FAILED (FreeBSD 12.0-RELEASE-p10 using ruby-build 20190828-2-gd2a7eef)

Inspect or clean up the working tree at /tmp/ruby-build.20190918125806.43044
Results logged to /tmp/ruby-build.20190918125806.43044.log

Last 10 log lines:
Checked out revision 44351.
/tmp/ruby-build.20190918125806.43044/ruby-1.8.7-p375 /tmp/ruby-build.20190918125806.43044 ~
configure: WARNING: unrecognized options: --with-readline-dir
checking build system type... x86_64-unknown-freebsd12.0
checking host system type... x86_64-unknown-freebsd12.0
checking target system type... x86_64-unknown-freebsd12.0
checking whether the C compiler works... no
configure: error: in `/tmp/ruby-build.20190918125806.43044/ruby-1.8.7-p375':
configure: error: C compiler cannot create executables
See `config.log' for more details

[config.log](https://github.com/rbenv/ruby-build/files/3627575/config.log)
[ruby-build.20190918125806.43044.log](https://github.com/rbenv/ruby-build/files/3627578/ruby-build.20190918125806.43044.log)
```

As requested:  @duncan-bayne

**Comment by hsbt** [comment]
I have no plan to support the EOL version of Ruby with the modern OS. We welcome to your patch.

**Comment by duncan-bayne** [comment]
@byrnejb Out of curiosity, what happens if you d/l the 1.8.7 source and compile it w/ `./configure && make`?  That error suggests a compiler toolchain problem on your system.

**Comment by byrnejb** [comment]
On Wed, September 18, 2019 20:34, Duncan Bayne wrote:
> @byrnejb Out of curiosity, what happens if you d/l the 1.8.7 source
> and compile it w/ `./configure && make`?  That error suggests a
> compiler toolchain problem on your system.
>

I will look into that.  I have no doubt that the build tools on
FreeBSD-12 differ significantly from what was current when 1.8.7 was
shipped with Linux distros.  However, this is a secondary issue to the
problem I have.  For now I have recommissioned an old server to host
CentOS-6.10 which has 1.8.7.374.  When time permits I will carry out
the test you suggest and let you know the results.

Thank you for your offer to help.  It is greatly appreciated.

Regards,

James B. Byrne                mailto:ByrneJB@Harte-Lyne.ca
