### ISSUE TITLE
Install downloading empty tar gzip file - failed tar du pv 

### ISSUE THREAD

**Issue by Phill** [rbenv/ruby-build#1378]
Not sure if this is a problem on my end or not. I'm on Manjaro Linux.

I just installed rbenv and ruby-build. I wanted to install Ruby 2.6.4 (same thing happens on other version) so I do a "rbenv install 2.6.4".

```> rbenv install 2.6.4
Downloading ruby-2.6.4.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.4.tar.bz2

BUILD FAILED (ManjaroLinux 18.1.2 using ruby-build 20191111-2-g092b8da)

Inspect or clean up the working tree at /tmp/ruby-build.20191115111553.16725.5QapAG
Results logged to /tmp/ruby-build.20191115111553.16725.log

Last 10 log lines:
/tmp/ruby-build.20191115111553.16725.5QapAG /tmp/ruby-build.20191115110646.14688.sZGY4c
tar: xjf: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
du: cannot access 'xjf': No such file or directory
pv: option requires an argument -- 's'
Try `pv --help' for more information.
Extracted directory not found
```

So I check out the extraction directory.

```> ls
total 4.0K
-rw-r--r-- 1 phill phill 20 Nov 15 11:06 ruby-2.6.4.tar.bz2

> file ruby-2.6.4.tar.bz2
ruby-2.6.4.tar.bz2: gzip compressed data, from Unix, original size modulo 2^32 0
> mv ruby-2.6.4.tar.bz2 ruby-2.6.4.tar.gz
> gunzip ruby-2.6.4.tar.gz
> ls
total 0
-rw-r--r-- 1 phill phill 0 Nov 15 11:06 ruby-2.6.4.tar
```

It's downloading a blank tar.gz file and naming it the ruby bz file.

I can download the file manually just fine using the same URL above.

**Comment by mislav** [comment]
Can `tar` on your machine extract an archive like this:

```
tar xjf /path/to/tarball.tar.bz2
```

If not, can you try with a hyphen preceding the flags

```
tar -xjf /path/to/tarball.tar.bz2
```

Which tar version do you have?

**Comment by Phill** [comment]
Tar works just fine. The problem is that it's downloading an empty tar.gz file with the name tar.bz2. Unless I'm missing something here. And it's even more strange that I can use curl or wget to download the same exact file and it's fine.

**Comment by Phill** [comment]
Update on issue. I tried to use rvm and it does the same exact thing. So must be a bug in my system somewhere.

What I've found is that I can download the file with curl, extract the archive, configure and make the ruby just fine. Just doesn't work with rbenv or rvm.

On the extract process the file turns into an empty tar.gz with the file name tar.bz2.

Anyway, probably not a problem here, but I will update here when I figure it out in case someone else ever runs into this issue.

**Comment by Phill** [comment]
I created a new user on my system and rbenv + ruby-build works just fine.

**Comment by Phill** [comment]
I finally got it working by doing "sudo bash -" to get a clean login shell and "rbenv install 2.6.5" worked fine. So looks like it's something in my environment. Just running "bash" didn't clean my env. Now it's a process of figuring out what is breaking it. I have a lot of env vars loaded up. (if it's even an env var)

**Comment by Phill** [comment]
OMG. For some reason I had a shell script named tar in my ~/bin dir. I don't remember why it's there or what it does but it was messing up the tar process. Gesh.

**Comment by mislav** [comment]
Glad you figured it out! 😅
