### ISSUE TITLE
Ruby 2.7.0 install fails

### ISSUE THREAD

**Issue by stevewi** [rbenv/ruby-build#1394]
Please see the attached files:

   rbenv.txt - a copy/paste of what appeared in my terminal window
   rbenv.log - the log file referenced in rbenv.txt

Please advise.  Thank you.

[rbenv.txt](https://github.com/rbenv/rbenv/files/4003090/rbenv.txt)
[rbenv.log](https://github.com/rbenv/rbenv/files/4003091/rbenv.log)

**Comment by stevewi** [comment]
This appears to be fixed for all the cases I reported:

2.7.0-preview3
2.7.0-rc1
2.7.0-rc2
2.7.0

Although, I don't understand why each of them needs their own private copy of openssl@1.1.  They each use 'readline' (and now, apparently, 'libyaml') from homebrew.  Why not just use the openssl@1.1 from homebrew as well?

**Comment by mislav** [comment]
@stevewi https://github.com/Homebrew/homebrew-core/pull/47402#issuecomment-560973277 https://github.com/rbenv/ruby-build/releases/tag/v20191111

**Comment by stevewi** [comment]
I don't...  I only did it for the workaround on the build failure I reported.  I was just asking why...  Now I know.  Thanks.
