### ISSUE TITLE
Document the requirements/dependencies for ubuntu

### ISSUE THREAD

**Issue by asdofindia** [rbenv/ruby-build#1399]
On a fresh install of ubuntu 18.04 I had to install these dependencies to get rbenv install 2.7.0 to work:

* zlib1g-dev
* libssl-dev

Perhaps it is useful to document

**Comment by eregon** [comment]
It is already documented in the README:
https://github.com/rbenv/ruby-build#basic-usage
which links to https://github.com/rbenv/ruby-build/wiki#suggested-build-environment
