### ISSUE TITLE
Can't install multiple ruby versions in parallel due to rehashing conflict

### ISSUE THREAD

**Issue by ccunniff** [rbenv/ruby-build#1411]
Currently I am installing many ruby versions in parallel in order to speed up build time for a project. For example by running `rbenv install 2.6.3`, `rbenv install 2.6.4`, `rbenv install 2.6.5` etc. as asynchronous processes. 

Occasionally the build process will fail due to this issue https://github.com/rbenv/rbenv/issues/759#issuecomment-124748535 because sometimes the installs will finish and call rehash around the same time and will end failing due to the race condition.

Would it make sense to add a command line option to disable rehashing on install https://github.com/rbenv/ruby-build/blob/92fa223e34d3a4a7daffad12ce655648e63d5aa7/bin/rbenv-install#L229 so that i can instead run it after all the parallel ruby version installs complete?

**Comment by mislav** [comment]
Hi, we could certainly consider an option to disable rehashing if it's giving you trouble!

However, since you seem to have a very specific approach to installing multiple versions, perhaps your scripting can benefit from dropping down to a level lower than `rbenv install`? Example:

```sh
RBENV_ROOT="$(rbenv root)"
# optional:
export RUBY_BUILD_CACHE_PATH="$RBENV_ROOT/cache"
# install multiple versions in parallel:
for ver in 2.6.3 2.6.4 2.6.5; do
  ruby-build "$ver" "$RBENV_ROOT/versions/$ver" >/dev/null &
done
wait
# ensure rehash:
rbenv rehash
```

This approach would skip any rbenv plugins, so be mindful of that.

**Comment by ccunniff** [comment]
Hey @mislav, thank you for getting back to me. I hadn't thought of just doing a lower level approach like this but this should work for our use case.

Thank you!
-Chris
