### ISSUE TITLE
add PREFIX to list of configuration variables 

### ISSUE THREAD

**Issue by kevinburkemeter** [rbenv/ruby-build#1413]
install.sh uses the PREFIX environment variable to determine where to install, however this variable is missing from the list of options in the README.

**Comment by mislav** [comment]
Nice catch, but the list of options in the README are only those that affect the runtime of `ruby-build`. The install script is separate from that, and its support for PREFIX is demonstrated clearly in the installation part of the README. So I think this is fine on the documentation front like it is right now. Thank you!

**Comment by kevinburkemeter** [comment]
okay, just a heads up that I saw it used elsewhere in the README, but concluded that it was for Ruby itself, instead of ruby-build /wasn't actually doing anything since it wasn't in the list of configuration variables, and if I made that mistake it's possible others did as well.
