### ISSUE TITLE
Unable to install 2.6.0 on macOS

### ISSUE THREAD

**Issue by KazumaTakata** [rbenv/ruby-build#1417]
environment
OSX Sierra

command
```
rbenv install 2.6.0   
```
I got following error messsage.
```
Downloading openssl-1.1.1d.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/1e3a91bc1f9dfce01af26026f856e064eab4c8ee0a8f457b5ae30b40b8b711f2
Installing openssl-1.1.1d...
Installed openssl-1.1.1d to /Users/kazumatakata/.rbenv/versions/2.6.0

Downloading ruby-2.6.0.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.0.tar.bz2
Installing ruby-2.6.0...
ruby-build: using readline from homebrew

BUILD FAILED (OS X 10.13.6 using ruby-build 20200224)

Inspect or clean up the working tree at /var/folders/lh/07b346l92mv9xgg_93ybkf9w0000gn/T/ruby-build.20200316164132.96320.hNFqnw
Results logged to /var/folders/lh/07b346l92mv9xgg_93ybkf9w0000gn/T/ruby-build.20200316164132.96320.log

Last 10 log lines:
2020/03/16 16:46:15 listen udp 127.0.0.1:4242: bind: address already in use
make: *** [dmyext.o] Error 1
make: *** [miniprelude.o] Error 1
2020/03/16 16:46:15 listen udp 127.0.0.1:4242: bind: address already in use
make: *** [probes.h] Error 1
2020/03/16 16:46:15 listen udp 127.0.0.1:4242: bind: address already in use
make: *** [bignum.o] Error 1
Client: Sending 'foobar'
2020/03/16 16:46:45 NO_ERROR: No recent network activity
make: *** [dmydln.o] Error 1
```

**Comment by mislav** [comment]
Hi @KazumaTakata thank you for the report.

Could you attach the contents of the whole log file (referenced by the "Results logged to" line) [as a gist](https://gist.github.com/) and link to it here please?

**Comment by KazumaTakata** [comment]
Thank you for  response.
Here is a link to gist(https://gist.github.com/KazumaTakata/c8f1ec82d91c7faed49cf29ca323ce17).

**Comment by mislav** [comment]
It looks like you're building with clang found in
```
InstalledDir: /usr/local/opt/llvm/bin
```

That one exhibits strange behavior. Any chance that you can use the one distributed with macOS?

```
$ xcode-select --install
$ which -a clang
/usr/bin/clang
```

This would probably involve taking `/usr/local/opt/llvm/bin` out of your PATH.

**Comment by KazumaTakata** [comment]
As you say, output is 
```
$which -a clang
/usr/local/opt/llvm/bin/clang 
/usr/local/opt/llvm/bin/clang                                                                                                      
/usr/bin/clang
```

**Comment by KazumaTakata** [comment]
I remove /usr/local/opt/llvm/bin/clang from path

but i got same error message.

```
BUILD FAILED (OS X 10.13.6 using ruby-build 20200224)

Inspect or clean up the working tree at /var/folders/lh/07b346l92mv9xgg_93ybkf9w0000gn/T/ruby-build.20200317001911.59237.6Ft3n9
Results logged to /var/folders/lh/07b346l92mv9xgg_93ybkf9w0000gn/T/ruby-build.20200317001911.59237.log

Last 10 log lines:
make: *** [ast.o] Error 1
make: *** [dmydln.o] Error 1
2020/03/17 00:22:54 listen udp 127.0.0.1:4242: bind: address already in use
make: *** [bignum.o] Error 1
. ./vm_opts.h
2020/03/17 00:22:54 listen udp 127.0.0.1:4242: bind: address already in use
make: *** [miniprelude.o] Error 1
Client: Sending 'foobar'
2020/03/17 00:23:24 NO_ERROR: No recent network activity
```

**Comment by mislav** [comment]
Sorry, I have no idea what exactly is trying to access the port 4242 and what is already running there.

You can check processes bound to a specific port like this:
```
lsof -i :4242
```

You can then use its PID to kill the process. After that you may try compilation again to see if anything is different.

**Comment by KazumaTakata** [comment]
There is no running process on port 4242.
I could not find out.

**Comment by KazumaTakata** [comment]
Here is new gist(https://gist.github.com/KazumaTakata/719764b5465c193ecd261ea1c960f3f6)

**Comment by mislav** [comment]
Thank you for sharing. It looks like changing clang version didn't affect this at all. Therefore, it mighe be a problem with something else in your build chain, perhaps `make`?

```
$ which -a make
/usr/bin/make
$ make --version
GNU Make 3.81
...
This program built for i386-apple-darwin11.3.0
```

The key part of your error message seems to be this:

```
2020/03/17 13:35:21 listen udp 127.0.0.1:4242: bind: address already in use
make: *** [miniprelude.o] Error 1
make: *** Waiting for unfinished jobs....
Client: Sending 'foobar'
Server: Got 'foobar'
Client: Got 'foobar'
```

When I search the internet for error messages such as `Client: sending foobar`, there was a few hits of people getting an identical message in other projects, but with no solutions: https://github.com/lucas-clemente/quic-go/issues/2271 https://github.com/b-mueller/laser-ethereum/issues/3

Since this isn't something we can fix within ruby-build, I'm closing this ticket. If you manage to debug your build stack and find what was going on, please update the thread!

**Comment by KazumaTakata** [comment]
thank you for your effort.
