### ISSUE TITLE
BUILD FAILED (OS X 10.14.6 using ruby-build 20200224)

### ISSUE THREAD

**Issue by Vorkosigan76** [rbenv/ruby-build#1423]
Got this error, don't know how to resolve this issue. Please advice any workaround?
Im on MacOS Mojave 10.14.6

> rbenv install 2.7.0
> Downloading openssl-1.1.1d.tar.gz...
> -> https://dqw8nmjcqpjn7.cloudfront.net/1e3a91bc1f9dfce01af26026f856e064eab4c8ee0a8f457b5ae30b40b8b711f2
> Installing openssl-1.1.1d...
> 
> BUILD FAILED (OS X 10.14.6 using ruby-build 20200224)
> 
> Inspect or clean up the working tree at /var/folders/sr/pyz9yrtd42sdpvmhjfm1hw7r0000gn/T/ruby-build.20200329125953.61905.Jicvxm
> Results logged to /var/folders/sr/pyz9yrtd42sdpvmhjfm1hw7r0000gn/T/ruby-build.20200329125953.61905.log
> 
> Last 10 log lines:
>       _fd_write in bss_fd.o
>       _fd_puts in bss_fd.o
>       _sock_write in bss_sock.o
>       _sock_puts in bss_sock.o
>      (maybe you meant: _UI_method_get_writer, _RAND_write_file , _PEM_write_bio_PKCS7_stream , _PEM_write_X509_AUX , _PEM_write_PrivateKey , _PEM_write_bio_PrivateKey_traditional , _PEM_write_bio_PrivateKey , _PEM_write_PKCS8_PRIV_KEY_INFO , _PEM_write_bio_PKCS8_PRIV_KEY_INFO , _PEM_write_PKCS8PrivateKey , _PEM_write_bio_PKCS8PrivateKey , _PEM_write_bio , _PEM_X509_INFO_write_bio , _PEM_write_bio_PUBKEY , _PEM_write_DHparams , _PEM_write_EC_PUBKEY , _PEM_write_bio_EC_PUBKEY , _PEM_write_bio_ECPKParameters , _PEM_write_DSA_PUBKEY , _PEM_write_bio_RSA_PUBKEY , _PEM_write_RSAPublicKey , _PEM_write_PKCS7 , _PEM_write_bio_PKCS7 , _PEM_write_X509_CRL , _PEM_write_bio_X509_REQ_NEW , _PEM_write_X509_REQ , _PEM_write_bio_X509 , _PEM_write_PKCS8 , _PEM_write_DHxparams , _PEM_write_DSAparams , _PEM_write_ECPKParameters , _PEM_write_bio_RSAPrivateKey , _UI_method_set_writer , _PEM_write_bio_X509_AUX , _PEM_write_ECPrivateKey , _SMIME_write_CMS , _PEM_write_DSAPrivateKey , _PEM_write_X509 , _PEM_write , _PEM_write_bio_DSAPrivateKey , _PEM_write_bio_X509_CRL , _PEM_write_bio_NETSCAPE_CERT_SEQUENCE , _SMIME_write_PKCS7 , _PEM_ASN1_write , _PEM_ASN1_write_bio , _PEM_write_bio_CMS , _CRYPTO_THREAD_write_lock , _PEM_write_bio_DHxparams , _PEM_write_bio_DSAparams , _PEM_write_RSA_PUBKEY , _TXT_DB_write , _PEM_write_PUBKEY , _BIO_meth_set_write_ex , _BIO_meth_set_write , _BIO_meth_get_write , _PEM_write_bio_DSA_PUBKEY , _BIO_write_ex , _PEM_write_bio_X509_REQ , _PEM_write_bio_Parameters , _PEM_write_bio_ECPrivateKey , _PEM_write_bio_PKCS8 , _PEM_write_X509_REQ_NEW , _PEM_write_bio_DHparams , _BIO_ctrl_get_write_guarantee , _BIO_meth_get_write_ex , _PEM_write_bio_PKCS8PrivateKey_nid , _PEM_write_bio_ASN1_stream , _PEM_write_bio_CMS_stream , _BIO_write , _PEM_write_CMS , _PEM_write_RSAPrivateKey , _PEM_write_NETSCAPE_CERT_SEQUENCE , _PEM_write_PKCS8PrivateKey_nid , _SMIME_write_ASN1 , _PEM_write_bio_RSAPublicKey )
> ld: symbol(s) not found for architecture x86_64
> clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
> make[1]: *** [Makefile:756: libcrypto.dylib] Error 1
> make[1]: Leaving directory '/private/var/folders/sr/pyz9yrtd42sdpvmhjfm1hw7r0000gn/T/ruby-build.20200329125953.61905.Jicvxm/openssl-1.1.1d'
> make: *** [Makefile:174: all] Error 2
>

**Comment by mislav** [comment]
Hi, try using openssl from Homebrew!
```
brew install openssl
RUBY_CONFIGURE_OPTS="--with-openssl-dir=`brew --prefix openssl@1.1`" rbenv install 2.7.0
```

**Comment by Vorkosigan76** [comment]
Not working... :(
(I also tried to reinstall openssl)

>  brew install openssl
> Warning: openssl@1.1 1.1.1d is already installed and up-to-date
> To reinstall 1.1.1d, run `brew reinstall openssl@1.1`
>  RUBY_CONFIGURE_OPTS="--with-openssl-dir=`brew --prefix openssl@1.1`" rbenv install 2.7.0
> Downloading ruby-2.7.0.tar.bz2...
> -> https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.0.tar.bz2
> Installing ruby-2.7.0...
> ruby-build: using readline from homebrew
> 
> BUILD FAILED (OS X 10.14.6 using ruby-build 20200224)
> 
> Inspect or clean up the working tree at /var/folders/sr/pyz9yrtd42sdpvmhjfm1hw7r0000gn/T/ruby-build.20200329130940.68004.r2zFpZ
> Results logged to /var/folders/sr/pyz9yrtd42sdpvmhjfm1hw7r0000gn/T/ruby-build.20200329130940.68004.log
> 
> Last 10 log lines:
> tool/config.guess already exists
> tool/config.sub already exists
> checking build system type... x86_64-apple-darwin18.7.0
> checking host system type... x86_64-apple-darwin18.7.0
> checking target system type... x86_64-apple-darwin18.7.0
> checking whether the C compiler works... no
> configure: error: in `/var/folders/sr/pyz9yrtd42sdpvmhjfm1hw7r0000gn/T/ruby-build.20200329130940.68004.r2zFpZ/ruby-2.7.0':
> configure: error: C compiler cannot create executables
> See `config.log' for more details
> make: *** No targets specified and no makefile found.  Stop.

**Comment by Vorkosigan76** [comment]
The issue was an incompatibility with the parameters setup by anaconda in .bash_profile

**Comment by mislav** [comment]
Thank you for sharing the solution! 

Cross-referencing: https://github.com/rbenv/ruby-build/issues/1364
