### ISSUE TITLE
New build for 2.6.6

### ISSUE THREAD

**Issue by tibbon** [rbenv/ruby-build#1427]
I'm not sure how to initiate/upload a build for here, but so that Homebrew could be updated, can someone put together a build that supports the newest releases? Looks like the other changes to ruby-build to support them have been merged in https://github.com/rbenv/ruby-build/pull/1424

https://github.com/Homebrew/homebrew-core/blob/master/Formula/ruby-build.rb

https://github.com/rbenv/ruby-build/releases

**Comment by hsbt** [comment]
Done

* https://github.com/rbenv/ruby-build/pull/1428
* https://github.com/rbenv/ruby-build/releases/tag/v20200401
