### ISSUE TITLE
NoMethodError: undefined method `path' for nil:NilClass

### ISSUE THREAD

**Issue by fguillen** [rbenv/ruby-build#1434]
Trying to update rbenv list of ruby versions and get this error:

```
$ brew install rbenv
==> Installing dependencies for rbenv: ruby-build
==> Installing rbenv dependency: ruby-build
Error: An exception occurred within a child process:
  NoMethodError: undefined method `path' for nil:NilClass
Did you mean?  paths
```

- MacOs Catalina 10.15.3 (19D76)
- Xcode 10.2.1 Build version 10E1001

**Comment by jasonkarns** [comment]
This is an issue with the home brew formula for rbenv, not ruby-build. Perhaps check out the homebrew/homebrew-core repo for open issues or homebrew’s discourse forum.

**Comment by fguillen** [comment]
Hi @jasonkarns maybe my reproduction of the issue was confused, this is may more clear:

```
$ brew install ruby-build
Updating Homebrew...
Error: An exception occurred within a child process:
  NoMethodError: undefined method `path' for nil:NilClass
Did you mean?  paths
```

**Comment by fguillen** [comment]
I am trying older versions of the formula but still same error:

```
$ brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/48f2c038a13b9b22ce15ea1e507158b61825864e/Formula/ruby-build.rb
Updating Homebrew...
Warning: Unsupported installation from a commit URL!
Consider using `brew extract ruby-build ...` instead!"
This will extract your desired ruby-build version to a stable tap instead of
installing from a commit URL that cannnot receive updates or fixes!

######################################################################## 100.0%
Warning: ruby-build 20200401 is available and more recent than version 20200224.
Error: An exception occurred within a child process:
  NoMethodError: undefined method `path' for nil:NilClass
Did you mean?  paths
```

**Comment by jasonkarns** [comment]
Since the error is within Ruby, is there a chance that your brew itself is out of date?

**Comment by fguillen** [comment]
After running `brew doctor` I saw brew was complaining my Xcode version was outdated.

I have updated to

- Xcode 11.4 Build version 11E146

Now the error has disappeared

Thanks for being attentive @jasonkarns ;)

**Comment by queilawithaQ** [comment]
I changed ownership & re-ran my 'brew vendor-gems'


 `git config --global user.name "Your Name"`
    `git config --global user.email you@example.com`

After doing this, you may fix the identity used for this commit with:

`    git commit --amend --reset-author
`
