### ISSUE TITLE
Ruby 2.7.x irb arrow keys do not work with history

### ISSUE THREAD

**Issue by rmehner** [rbenv/ruby-build#1446]
👋 

I'm running into this weird issue and am not really sure if this is the right place to report, but here we go:

When I'm using Ruby 2.7.0 or Ruby 2.7.1 on macOS 10.15.5, irb does not work with using the arrow keys for navigating the history.

E.g. if I do the following:

1. `irb` in Terminal
2. Enter `puts "foo"` and hit Return
3. Hit arrow key up -> Nothing happens

Funnily enough, CTRL^R brings up reverse search for history, as expected.

If I switch to Ruby 2.6.x (any version), Ruby 2.8.0-dev or even Ruby 2.3.1 irb works as expected. Both 2.7.0 and 2.7.1 do **not** work.

I've tried installing the versions a new and even reinstalled readline from Homebrew. The build output even mentions it is using Homebrew's readline.

Readline version: 8.0.4

I've set up a Ubuntu 20.04 VM with rbenv to test if the problem happens there as well and it doesn't, so it seems to be something with my Mac setup.

Maybe you, kind reader, heard about this before and have an idea, because I'm really at loss here :) Thanks in advance!

**Comment by hsbt** [comment]
Can you file it to https://github.com/ruby/irb or https://bugs.ruby-lang.org/?

**Comment by hmans** [comment]
For anyone coming here from Google, OP created a follow-up issue at https://github.com/ruby/irb/issues/107, which also contains the workaround.
