### ISSUE TITLE
1.9.3 fails to use libyaml or zlib, unable to install bundler

### ISSUE THREAD

**Issue by jemminger** [rbenv/ruby-build#1485]
```bash

brew --prefix zlib
brew --prefix openssl@1.1
brew --prefix libyaml

/usr/local/Cellar/zlib/1.2.11
/usr/local/opt/openssl@1.1
/usr/local/opt/libyaml

➜  fpr git:(master) ✗                                                                                       
rbenv uninstall -f 1.9.3-p551
RUBY_CONFIGURE_OPTS="--with-zlib-dir=$(brew --prefix zlib) --with-openssl-dir=$(brew --prefix openssl@1.1) --with-libyaml-dir=$(brew --prefix libyaml)" rbenv install 1.9.3-p551

Downloading ruby-1.9.3-p551.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-p551.tar.bz2
Installing ruby-1.9.3-p551...

WARNING: ruby-1.9.3-p551 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.

ruby-build: using readline from homebrew
Installed ruby-1.9.3-p551 to /Users/jemminger/.rbenv/versions/1.9.3-p551

➜  fpr git:(master) ✗ gem install bundler -v'~>1.17.0'
/Users/jemminger/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/yaml.rb:84:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
ERROR:  Loading command: install (LoadError)
    cannot load such file -- zlib
ERROR:  While executing gem ... (NameError)
    uninitialized constant Gem::Commands::InstallCommand
```

**Comment by csgui** [comment]
Exactly same issue here.

**Comment by Jason733i** [comment]
Also experiencing this issue on a very old project..

**Comment by arnold805** [comment]
I'm having the same issue as user above me.

**Comment by brettkaplan** [comment]
I am also having this issue

**Comment by justintanner** [comment]
Same issue as well.

**Comment by marcandre** [comment]
Are you using OpenSSL 1.1 or 1.0? See https://github.com/rbenv/ruby-build/wiki#openssl-version-compatibility

**Comment by csgui** [comment]
Just tried with OpenSSL 1.0...

`$ RUBY_CONFIGURE_OPTS="--with-zlib-dir=$(brew --prefix zlib) --with-libyaml-dir=$(brew --prefix libyaml) --with-openssl-dir=$(brew --prefix openssl@1.0)" rbenv install 1.9.3-p551`

Same described issue.

**Comment by marcandre** [comment]
FWIW, I reinstalled everything ~3 weeks ago, and `rbenv install 1.9.3-p551` (no other config flag) worked without an issue (OS X Mojave)

**Comment by csgui** [comment]
MacOS Catalina here.

**Comment by xvrdmng** [comment]
I'm receiving the same error, I tried even compiling manually and the behavior is the same 

RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.0)" ruby-build 1.9.3-p551 ~/.rubies/ruby-1.9.3
ruby-build: using libyaml from homebrew
Downloading ruby-1.9.3-p551.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-p551.tar.bz2
Installing ruby-1.9.3-p551...

WARNING: ruby-1.9.3-p551 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.

ruby-build: using readline from homebrew
Installed ruby-1.9.3-p551 to /Users/xavi/.rubies/ruby-1.9.3


Then:

/Users/xavi/.rubies/ruby-1.9.3/lib/ruby/1.9.1/yaml.rb:84:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
ERROR:  Loading command: install (LoadError)
    cannot load such file -- zlib
ERROR:  While executing gem ... (NameError)
    uninitialized constant Gem::Commands::InstallCommand

**Comment by edlebert** [comment]
The fix is to set CFLAGS, which was changed in xcode 13

```
export CFLAGS="-Wno-error=implicit-function-declaration"
```

https://github.com/rbenv/ruby-build/issues/1489

**Comment by hsbt** [comment]
Try with https://github.com/rbenv/ruby-build/issues/1485#issuecomment-814180122 . I could install Ruby 1.9.3 with macOS Big Sur and Xcode 12.

**Comment by designium** [comment]
export CFLAGS="-Wno-error=implicit-function-declaration"

That worked for me with Big Sur, rbenv.

**Comment by billti** [comment]
I wrestled with this for an afternoon. Turns out I had Gems redirected to under my HOME dir. Removing that from my .bashrc and relaunching fixed the issue for me.
