### ISSUE TITLE
Ruby 2.7.1 fails to compile on Apple M1

### ISSUE THREAD

**Issue by lewisrobbins** [rbenv/ruby-build#1493]
`$ uname -a
Darwin Lewiss-MacBook-Pro.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE_ARM64_T8101 arm64
`

I'm using `60c933968584ac9ae7caac6dbed614740f899ec3` for `rbenv` and `f85906ea93c0d6557a5b2d3f52bfa958a69e4189` for `ruby-build`, when I run `rbenv install 2.7.1`, the build fails on OpenSSL

```
rbenv install 2.7.2  
Downloading openssl-1.1.1h.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/5c9ca8774bd7b03e5784f26ae9e9e6d749c9da2438545077e6b3d755a06595d9
Installing openssl-1.1.1h...

BUILD FAILED (macOS 11.0.1 using ruby-build 20201118)

Inspect or clean up the working tree at /var/folders/f_/cppq7d8n3jv5xm9c3t_f2w1w0000gp/T/ruby-build.20201127203014.10745.RaLH9A
Results logged to /var/folders/f_/cppq7d8n3jv5xm9c3t_f2w1w0000gp/T/ruby-build.20201127203014.10745.log

Last 10 log lines:
  "_write$UNIX2003", referenced from:
      _conn_write in bss_conn.o
      _conn_puts in bss_conn.o
      _dgram_write in bss_dgram.o
      _fd_write in bss_fd.o
      _sock_write in bss_sock.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libcrypto.dylib] Error 1
make: *** [all] Error 2
```

Is this related to the earlier Apple DTK issue #1456?

**Comment by eimermusic** [comment]
This topic on Ruby China got me going with Ruby 2.7.1 and 2.6.5
https://ruby-china.org/topics/40639
(Safari's new translation feature really came in handy for me)

It references the OpenSSL issue and is pretty concrete about how to get past it.

**Comment by hsbt** [comment]
You can install Ruby 2.7.2 with https://github.com/rbenv/ruby-build/issues/1456#issuecomment-670051168 by ARM arch.

**Comment by hsbt** [comment]
Fixed at https://github.com/rbenv/ruby-build/releases/tag/v20201210
