### ISSUE TITLE
Failed to install Ruby on Mac M1

### ISSUE THREAD

**Issue by florentmorin** [rbenv/ruby-build#1496]
Hi,

My installation of Ruby 2.7.2 failed on Mac M1.

This is the detail.

**Configuration**

Hardware: Mac M1
Homebrew: x86_64 version (`alias brew='arch -x86_64 brew'`)

**rbenv installation**

```bash
brew install rbenv
rbenv init
```

`.zshrc` file:

```bash
alias brew='arch -x86_64 brew'
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
eval "$(rbenv init -)"
```

**Ruby 2.7.2 installation**

```bash
rbenv install 2.7.2
```

**Current result**

It fails.

Log is joined here.
[ruby-build.20201204132953.28692.log](https://github.com/rbenv/rbenv/files/5642804/ruby-build.20201204132953.28692.log)

**Comment by hsbt** [comment]
see https://github.com/rbenv/ruby-build/issues/1456#issuecomment-670051168

**Comment by hsbt** [comment]
Fixed at https://github.com/rbenv/ruby-build/releases/tag/v20201210

**Comment by krschacht** [comment]
> ```shell
> export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
> ```

It took me a little while to fully make sense of this tip. It worked for me but here was how I implementd:

```
xcode-select --install
arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
alias ibrew="arch -x86_64 brew"
ibrew update

mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
sudo mv homebrew /opt/homebrew
export PATH="/opt/homebrew/bin:$PATH"
brew update

# Just in case you have lingering ones:

ibrew uninstall rbenv ruby-build
brew uninstall rbenv ruby-build

ibrew install ruby-build
ibrew install rbenv
brew install openssl@1.1
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"

rbenv install 2.7.2
```

**Comment by lumaxis** [comment]
Glad you got it working and sorry I wasn't more specific 😄 I didn't remember the exact steps I did to get there, just somehow got it working 🙏🏼
