### ISSUE TITLE
JRuby 9.2.14.0 was released

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [rbenv/ruby-build#1503]
Please add `jruby-9.2.14.0` to the list of available versions for installation.

https://www.jruby.org/2020/12/08/jruby-9-2-14-0.html

**Comment by ThomasKoppensteiner** [comment]
@hsbt when will this change be released? Is there a schedule for releases?

**Comment by hsbt** [comment]
Done. https://github.com/rbenv/ruby-build/releases/tag/v20201221
