### ISSUE TITLE
Option to omit Rdoc

### ISSUE THREAD

**Issue by jelder** [rbenv/ruby-build#156]
It seems like rbenv/ruby-build is becoming the de facto method of getting Ruby >= 1.9.3. For production servers, it would be nice if we could skip the unnecessary step of building Rdoc. Can this be an option please?

**Comment by swrobel** [comment]
Was this option ever added?

**Comment by mislav** [comment]
No, there isn't an option yet. Yes, the environment variable is still the way to go.

**Comment by hsbt** [comment]
We can select to omit documentation generating with `RUBY_CONFIGURE_OPT`. I think it's better than the built-in option of ruby-build.
