### ISSUE TITLE
You don't have write permissions into the /Library/Ruby/Gems/1.8 directory.

### ISSUE THREAD

**Issue by regedarek** [rbenv/ruby-build#168]
After installing via `rbenv install`

**Comment by hchaozhe** [comment]
Hi @mislav , I have a similar issue. 

> $ gem install bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

I have added 
>eval "$(rbenv init -)"  

to \.bash_profile, and if I run

> $ echo $PATH | tr ':' $'\n'

I got

>/Users/username/.rbenv/shims
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin

So you can see I have rbenv/shims at the highest. But when I run

> which -a ruby

I got

>/usr/bin/ruby
and with 

>which -a gem

I got 

>/usr/bin/gem

I don't know why they are still running. I have also tried 

> rbenv local
rbenv global

which is suggested by other people. But the error remains. Do you have any idea on solving this?

Thank you in advance!

**Comment by patrykkalinowski** [comment]
So, a quick solution which worked for me (OSX), might be helpful for others.
I installed ruby with `$ rbenv install 2.5.3`
`$ rbenv local` returned `system`
Next, I run `rbenv local 2.5.3`

Gem install worked after that
