### ISSUE TITLE
Can't get Ruby-2.7.0 installed on Cygwin64 Terminal

### ISSUE THREAD

**Issue by Dethik** [rbenv/ruby-build#1693]
I get the install ran, it finishes the RVM, runs through the Ruby config, and compile. Then errors out while running rvm_make -j8

![image](https://user-images.githubusercontent.com/8033617/102964410-67b05e80-44a0-11eb-9cbe-d94acd768976.png)

![image](https://user-images.githubusercontent.com/8033617/102964449-8adb0e00-44a0-11eb-9043-ac0b12bc5a29.png)

Please Help?

**Comment by hsbt** [comment]
It's not ruby-build issue.
