### ISSUE TITLE
Caching downloaded files (in the event of failure)

### ISSUE THREAD

**Issue by paul-hammant** [rbenv/ruby-build#1698]
Relating to #1697, if I run ruby-build commands back to back, there's a repeat of a previously successful step to download installers from cloudfront.

Sure, this only really affects people who'd have a problem with an installation, but it may be worth doing anyway?

**Comment by hsbt** [comment]
You can store them by rbenv cache mechanism that is `mkdir $RBENV_ROOT/cache`
