### ISSUE TITLE
artichoke-dev is shipping Apple Silicon binaries

### ISSUE THREAD

**Issue by lopopolo** [rbenv/ruby-build#1701]
Hi folks! 💎 Artichoke Ruby nightlies (available in `ruby-build` as `artichoke-dev`) are now building aarch64-apple-darwin (aka Apple Silicon) artifacts: https://github.com/artichoke/nightly/pull/17.

Example release: https://github.com/artichoke/nightly/releases/tag/test-2021-01-02-apple-silicon-2
Artifact name: `artichoke-nightly-aarch64-apple-darwin.tar.gz`

I'm not sure how to add this artifact to `ruby-build`. cc @deepj since you added `artichoke-dev` to `ruby-build`.

Another thing I'm unsure of is whether distributing these binaries through `ruby-build` will work as is or if I need to setup code signing of Mac artifacts first: https://github.com/artichoke/nightly/issues/18.

**Comment by lopopolo** [comment]
Today's scheduled nightly will kick off in a few minutes. I'll link back here once a scheduled build completes.

**Comment by lopopolo** [comment]
Today's scheduled nightly build succeeded: https://github.com/artichoke/nightly/releases/tag/nightly-2021-01-03.

The Apple Silicon artifact is: https://github.com/artichoke/nightly/releases/download/nightly-2021-01-03/artichoke-nightly-aarch64-apple-darwin.tar.gz. This artifact has the same contents as the existing x86_64 Mac and Linux artifacts.

**Comment by deepj** [comment]
@lopopolo Here my proposal https://gist.github.com/deepj/3c1f85893ef16e618690b6959ef7fa5c

If @hsbt is OK with that I can make a PR.

ARM
```
$ uname -m
arm64
$ ruby-build artichoke-dev ~/.rubies/artichoke-dev
Downloading artichoke-nightly-aarch64-apple-darwin.tar.gz...
-> https://github.com/artichoke/nightly/releases/latest/download/artichoke-nightly-aarch64-apple-darwin.tar.gz
Installing artichoke-nightly...
Installed artichoke-nightly to ~/.rubies/artichoke-dev

$ ~/.rubies/artichoke-dev/bin/ruby --version
artichoke 0.1.0-pre.0
$ ~/.rubies/artichoke-dev/bin/ruby -e "puts RUBY_PLATFORM"
aarch64-apple-darwin
```

Under x86_64

```
$ uname -m
x86_64
$ ruby-build artichoke-dev ~/.rubies/artichoke-dev
Downloading artichoke-nightly-x86_64-apple-darwin.tar.gz...
-> https://github.com/artichoke/nightly/releases/latest/download/artichoke-nightly-x86_64-apple-darwin.tar.gz
Installing artichoke-nightly...
Installed artichoke-nightly to ~/.rubies/artichoke-dev

$ ~/.rubies/artichoke-dev/bin/ruby --version
artichoke 0.1.0-pre.0
$ ~/.rubies/artichoke-dev/bin/ruby -e "puts RUBY_PLATFORM"
x86_64-apple-darwin
```

**Comment by deepj** [comment]
@lopopolo there is a new release of `ruby-build` containing the option to install a native version Artichoke Ruby on Apple Silicon's Macs
