### ISSUE TITLE
Ruby 2.6.5 installation fails on MacOS 11.1 M1 - Interrupted system call

### ISSUE THREAD

**Issue by gggaa820** [rbenv/ruby-build#1713]
Although I tried to install ruby 2.6.5, I could not install and catch following errors: 

compiling ossl_x509name.c
compiling ossl_x509req.c
compiling ossl_x509revoked.c
compiling ossl_x509store.c
installing default openssl libraries
linking shared-object openssl.bundle
linking shared-object ripper.bundle
./revision.h unchanged
linking ruby
*** Following extensions are not compiled:
syslog:
        Could not be configured. It will not be installed.
        /private/var/folders/zh/v3hksw51419_8_xk980c24cw0000gn/T/ruby-build.20210120213517.13386.vgRndC/ruby-2.6.5/lib/mkmf.rb:556: Interrupted system call - 
        Check ext/syslog/mkmf.log for more details.
gdbm:
        Could not be configured. It will not be installed.
        /private/var/folders/zh/v3hksw51419_8_xk980c24cw0000gn/T/ruby-build.20210120213517.13386.vgRndC/ruby-2.6.5/lib/mkmf.rb:556: Interrupted system call - 
        Check ext/gdbm/mkmf.log for more details.
pty:
        Could not be configured. It will not be installed.
        /private/var/folders/zh/v3hksw51419_8_xk980c24cw0000gn/T/ruby-build.20210120213517.13386.vgRndC/ruby-2.6.5/lib/mkmf.rb:556: Interrupted system call - 
        Check ext/pty/mkmf.log for more details.
digest/md5:
        Could not be configured. It will not be installed.
        /private/var/folders/zh/v3hksw51419_8_xk980c24cw0000gn/T/ruby-build.20210120213517.13386.vgRndC/ruby-2.6.5/lib/mkmf.rb:556: Interrupted system call - 

I checked that security software did not work (ref.  #1710).
Do you have any idea to install ruby 2.6.5 correctly ?

**Comment by hsbt** [comment]
Ruby 2.6 does not support Apple M1 chip officially.

**Comment by em77** [comment]
[Try this solution](https://github.com/rbenv/ruby-build/issues/1691#issuecomment-753636901)
