### ISSUE TITLE
Getting error after Mac OS Big Sur update

### ISSUE THREAD

**Issue by subratrout** [rbenv/ruby-build#1716]
After I updated my system from Catalina to Big Sur, I am trying to install rbenv with no luck.
When I am trying following:
``` rbenv install 3.0.0 ```
I am getting following error:
```
Downloading ruby-3.0.0.tar.gz...
-> https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.0.tar.gz
error: failed to download ruby-3.0.0.tar.gz
BUILD FAILED (macOS 11.1 using ruby-build 20210119)
```
Upon executing following command:

```
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | zsh
```
I am getting following error:
```
curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```

**Comment by hsbt** [comment]
I never reproduce that.

**Comment by subratrout** [comment]
I guess it was issue with the Mac OS Big Sur update. I was able to fix it. Thank you @hsbt
