### ISSUE TITLE
uninitialized constant SOCKSSocket

### ISSUE THREAD

**Issue by vkalach** [rbenv/ruby-build#1717]
I'm trying to install ruby using configure options for socks proxy: --enable-socks

the same guys do in [rvm](https://github.com/rvm/rvm/issues/4702)

but I still receive `uninitialized constant SOCKSSocket` error

**Steps to reproduce:**

`RUBY_CONFIGURE_OPTS="--enable-socks" rbenv install 2.5.3`

`ruby -e 'require "socket"; puts SOCKSSocket'`

> uninitialized constant SOCKSSocket (NameError)

----------------------------------------------------------------
`RUBY_CONFIGURE_OPTS="--enable-socks=true" rbenv install 2.5.3`

`ruby -e 'require "socket"; puts SOCKSSocket'`

> uninitialized constant SOCKSSocket (NameError)

I use macOS Big Sur 11.1

**expected:**
`ruby -e 'require "socket"; puts SOCKSSocket'`

> SOCKSSocket

**Comment by hsbt** [comment]
I could reproduce it. But it doesn't seem ruby-build issue, So it's Ruby issue. Can you file this to https://bugs.ruby-lang.org/?

Thanks.

**Comment by gammons** [comment]
SOCKSSocket requires `dante` to be installed, or else it won't find `rconnect`.  I found [this page](https://www.typeerror.org/docs/ruby~2.7/sockssocket) that gave me a hint.  I installed `dante`, recompiled with those flags, and `SOCKSSocket` was available.
