### ISSUE TITLE
Should jruby installations delete the `prefix` directory?

### ISSUE THREAD

**Issue by IanWhitney** [rbenv/ruby-build#1718]
Hi,

We are seeing some odd behavior with jRuby installs and are not sure if it is correct.

The `clean_build_path` method is running `rm -rf "$PREFIX_PATH`. This leads to a couple of problems.

On on hosts we install ruby-build with the `PREFIX_PATH` varible set to `/swadm`, so that ruby-build ends up in `/swadm/bin`. We then run `ruby-build jruby-9.2.14.0 /swadm`.

This leads to 2 problems

1. The `clean_build_path` method deletes the install of ruby-build
2. The installation of jruby then fails because running `rm -rf /swadm` fails, due to permissions.

Overall I'm not sure what this the goal of this `clean_build_path` method is. Or if it's going about it in the right way.

This may all be user error. But it seems weird to have a method that tries to wipe the entire prefix dir.

**Comment by supertry55** [comment]
@1718

**Comment by eregon** [comment]
You mean `clean_prefix_path` I guess.
I guess we could instead of `rm -rf "$PREFIX_PATH"` we could remove every file and directory under it but not the directory itself.
PR welcome.

Normally one would install a Ruby in its own directory, e.g. `~/.rbenv/versions/jruby-9.2.14.0`

**Comment by eregon** [comment]
Related to https://github.com/rbenv/ruby-build/issues/1821.
This is no longer the behavior, so closing this issue, but please follow https://github.com/rbenv/ruby-build/issues/1821 for potential future changes in this area.
