### ISSUE TITLE
Unable to install  rbenv install 2.6.3 on Apple M1 chip macbook

### ISSUE THREAD

**Issue by ChawlaBhavuk** [rbenv/ruby-build#1726]
Try to run this rbenv install 2.6.3 

After this getting this error 

ownloading openssl-1.1.1i.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/e8be6a35fe41d10603c3cc635e93289ed00bf34b79671a3a4de64fcee00d5242
Installing openssl-1.1.1i...
Installed openssl-1.1.1i to /Users/bhavukchawla/.rbenv/versions/2.6.3

Downloading ruby-2.6.3.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.3.tar.bz2
Installing ruby-2.6.3...
ruby-build: using readline from homebrew

BUILD FAILED (macOS 11.2.1 using ruby-build 20210119)

Inspect or clean up the working tree at /var/folders/p7/t246sd7n0n79kssvx81_zglc0000gn/T/ruby-build.20210219205038.69846.WLMBLS
Results logged to /var/folders/p7/t246sd7n0n79kssvx81_zglc0000gn/T/ruby-build.20210219205038.69846.log

Last 10 log lines:
../.././ext/psych/yaml/api.c:1321:32: warning: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
    return document->nodes.top - document->nodes.start;
    ~~~~~~ ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
compiling ../.././ext/psych/yaml/parser.c
linking shared-object -test-/string.bundle
5 warnings generated.
linking shared-object zlib.bundle
1 warning generated.
linking shared-object psych.bundle
make: *** [build-ext] Error 2

**Comment by hsbt** [comment]
Ruby 2.6 is not support Apple M1 chip officially.
