### ISSUE TITLE
rbenv 3.0.0 fails to install  on Mac OS X 10.15.7 with zsh

### ISSUE THREAD

**Issue by williambsb** [rbenv/ruby-build#1729]
Hi There, 
I have read a lot of other rbenv issues but nothing helped to turn around my issue.

I am using Catalina 10.15.7 with zsh and got a c compiler error 
```
rbenv install 3.0.0                                             1 ✘  3m 57s   13:55:34  
Downloading ruby-3.0.0.tar.gz...
-> https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.0.tar.gz
Installing ruby-3.0.0...
ruby-build: using readline from homebrew

BUILD FAILED (Mac OS X 10.15.7 using ruby-build 20210119)

Inspect or clean up the working tree at /var/folders/df/6rhjgghx3hb9pq0w4vj1lcl40000gn/T/ruby-build.20210223135756.42176.r4OefL
Results logged to /var/folders/df/6rhjgghx3hb9pq0w4vj1lcl40000gn/T/ruby-build.20210223135756.42176.log

Last 10 log lines:
checking for llvm-objcopy... no
checking for llvm-objdump... no
checking for llvm-ranlib... no
checking for llvm-strip... no
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/var/folders/df/6rhjgghx3hb9pq0w4vj1lcl40000gn/T/ruby-build.20210223135756.42176.r4OefL/ruby-3.0.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.
```
I have installed llvm with no errors.

I am suspecting of a Kind of conflict but not sure ... my Install sequence in this environment was :

NODE 14
Python
and now ... trying Ruby on Rails ...

Any ideia ?
Best Regards

**Comment by hsbt** [comment]
Maybe you need to install command line tools via `xcode-select --install`.

**Comment by williambsb** [comment]
> Maybe you need to install command line tools via `xcode-select --install`.

I have checked this ...
Now I remove my openssl that has been installed by Python and I will try again 
Thanks a lot

**Comment by demir** [comment]
I have the same problem too. @williambsb Did you solve the problem?

**Comment by williambsb** [comment]
> I have the same problem too. @williambsb Did you solve the problem?

Hi demir ... sorry my delay ... in my case I downgrade node from v15 to v14.16.0 and then worked .
Good Luck

**Comment by williambsb** [comment]
Downgrade Node to Stable Release v14.16.0 has fixed the issue
