### ISSUE TITLE
Error: "rm: illegal option -- a" installing ruby 2.2.2 on MacOS v11.2.3 Apple M1 Silicon

### ISSUE THREAD

**Issue by bradical** [rbenv/ruby-build#1742]
Steps:
- Installed `openssl@1.0` via this formula: https://github.com/rbenv/homebrew-tap/pull/2#issuecomment-811418484 as I couldn't get it build otherwise
- `export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.0)"`
- `CFLAGS="-Wno-error=implicit-function-declaration" rbenv install 2.2.2` as per https://github.com/rbenv/ruby-build/issues/1700#issue-777313922

It seems to fail at the very end with a strange error about an illegal option for `rm`:

```
config.status: creating -darwin20-fake.rb
rm: illegal option -- a
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
config.status: error: could not create -darwin20-fake.rb
make: *** [-darwin20-fake.rb] Error 64
```

I thought this might be related to https://github.com/rbenv/ruby-build/issues/1700 or https://github.com/rbenv/ruby-build/issues/1691 but it seems a bit different than both so I filed separately.

[ruby-build.20210331213055.45512.log](https://github.com/rbenv/ruby-build/files/6240387/ruby-build.20210331213055.45512.log)

**Comment by bradical** [comment]
Can confirm this happening when building ruby from source using:

```
./configure --prefix /Users/bradley/Downloads/temp
make
make install
```

which tells me this is not a ruby-build problem per se. Still, I have no other leads on this so if anyone has any ideas, that would be much appreciated. Feels like a problem with the `arch` somewhere in this `make` or `make install` that is resulting in an invalid command to `rm` perhaps due ot the name of the file `-darwin20-fake.rb`. The leading `-` maybe?

**Comment by hsbt** [comment]
At first, Ruby 2.2 is not supported M1 macOS and it's EOL today. I (also includes Ruby core team) have no plan to support it.

**Comment by bradical** [comment]
I understand and I'd like to upgrade as soon as I can but I need to get this running first. Is there anything obvious in that make file in the final linking step that I could tweak to get this to work?

**Comment by kule** [comment]
For anyone else interested this is how I got 2.2.10 to install on m1 mac:

Firstly to get openssl1.0 installed you need a patched version that accounts for the arch (thanks @felixbuenemann):

https://gist.github.com/felixbuenemann/5f4dcb30ebb3b86e1302e2ec305bac89#gistcomment-3567911

Try to install ruby 2.2.10 as per normal in rbenv:

`CFLAGS="-Wno-error=implicit-function-declaration" RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.0)" rbenv install 2.2.10`

After a while it'll fail as noted by @bradical with:

```
config.status: creating -darwin20-fake.rb
rm: illegal option -- a
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
config.status: error: could not create -darwin20-fake.rb
make: *** [-darwin20-fake.rb] Error 64
```

fyi @brandical I also wondered if the -darwin20-fake.rb was an error as usually it'd be something like x86_64-darwin20-fake.rb but I noticed this is just -darwin20-fake.rb with ruby 2.4 and works fine.

Anyways, take a note the debug log directory and go to ruby directory in that path e.g.

`$> cd /private/var/folders/yc/_clcptvx4nq0vw_h6frtk0j00000gn/T/ruby-build.20210509110656.28571.vlttTy/ruby-2.2.10`

I traced the error in `config.status` to this line 1097 (fyi $ac_file is -darwin20-fake.rb):

`  *) rm -f "$ac_file" && mv "$ac_tmp/out" "$ac_file";;`

It's obviously running the command as if darwin20-fake.rb are params to the rm command and failing (e.g. it looks like it's trying to run `rm -rfdarwin20-fake.rb` and bailing when it gets to the a in darwin as it's not a valid argument for rm).

There's most probably a better way to do this but for now it worked to just remove the rm -f part of the command:

`  *) mv "$ac_tmp/out" "$ac_file";;`

$> make && make install

voila working 2.2.10 ruby on m1 macs with rbenv.

**Comment by bradical** [comment]
Thanks for posting this @kule! Looking forward to trying this out and will report back here.

**Comment by dataf3l** [comment]
@kule thanks, your instructions worked.


I tried this:

rvm install

which yielded this:
```
thread.c:4835:20: error: implicit declaration of function 'rb_frame_last_func' is invalid in C99
```
so I tried this to solve THAT:

export optflags="-Wno-error=implicit-function-declaration"
rvm install ruby-2.0.0-p648

but I still got this issue:


```
Error running '__rvm_make install',
please read /Users/b/.rvm/log/1661667543_ruby-2.0.0-p648/install.log
There has been an error while running make install. Halting the installation.
```

So after reading a bit I tried this command:

echo $PATH|sed 's/:/\r/g'

which in MY computer printed this:

```
/Users/b/.rvm/gems/ruby-2.7.3/bin
/Users/b/.rvm/gems/ruby-2.7.3@global/bin
/Users/b/.rvm/rubies/ruby-2.7.3/bin
/Users/b/.rvm/bin
/opt/homebrew/opt/openssl@3/bin
/Users/b/.nvm/versions/node/v14.16.1/bin
/Users/b/.rbenv/shims
/opt/homebrew/opt/libpq/bin
/Users/b/work/_software/google-cloud-sdk/bin
/opt/homebrew/bin
/opt/homebrew/sbin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/usr/local/go/bin
/Library/Apple/usr/bin
/Users/b/.cargo/bin
```

So I decided to CLEAN UP the list of dependencies.




the process works if people need to install 2.0.0p648 I had the same error:

export PATH=/Users/b/.rvm/bin:/Users/b/.rbenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin


rvm install ruby-2.0.0-p648


```
There has been an error while running make install. Halting the installation.
b@m1 ~ % cat /Users/b/.rvm/log/1661668260_ruby-2.0.0-p648/install.log
+__rvm_make:0> make install
config.status: creating -darwin20.3.0-fake.rb
rm: illegal option -- a
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
config.status: error: could not create -darwin20.3.0-fake.rb
make: *** [-darwin20.3.0-fake.rb] Error 64
+__rvm_make:0> return 2
```

**Comment by lopespm** [comment]
> For anyone else interested this is how I got 2.2.10 to install on m1 mac:
> 
> Firstly to get openssl1.0 installed you need a patched version that accounts for the arch (thanks @felixbuenemann):
> 
> https://gist.github.com/felixbuenemann/5f4dcb30ebb3b86e1302e2ec305bac89#gistcomment-3567911
> 
> Try to install ruby 2.2.10 as per normal in rbenv:
> 
> `CFLAGS="-Wno-error=implicit-function-declaration" RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.0)" rbenv install 2.2.10`
> 
> After a while it'll fail as noted by @bradical with:
> 
> ```
> config.status: creating -darwin20-fake.rb
> rm: illegal option -- a
> usage: rm [-f | -i] [-dPRrvW] file ...
>        unlink file
> config.status: error: could not create -darwin20-fake.rb
> make: *** [-darwin20-fake.rb] Error 64
> ```
> 
> fyi @brandical I also wondered if the -darwin20-fake.rb was an error as usually it'd be something like x86_64-darwin20-fake.rb but I noticed this is just -darwin20-fake.rb with ruby 2.4 and works fine.
> 
> Anyways, take a note the debug log directory and go to ruby directory in that path e.g.
> 
> `$> cd /private/var/folders/yc/_clcptvx4nq0vw_h6frtk0j00000gn/T/ruby-build.20210509110656.28571.vlttTy/ruby-2.2.10`
> 
> I traced the error in `config.status` to this line 1097 (fyi $ac_file is -darwin20-fake.rb):
> 
> ` *) rm -f "$ac_file" && mv "$ac_tmp/out" "$ac_file";;`
> 
> It's obviously running the command as if -darwin20-fake.rb are args to the rm command rather than a filename and failing (e.g. simplified it's trying to run `rm -rfdarwin20-fake.rb` and bailing when it gets to the a in darwin as it's not a valid argument for rm).
> 
> There's most probably a better way to do this but for now it worked to just remove the rm -f part of the command:
> 
> ` *) mv "$ac_tmp/out" "$ac_file";;`
> 
> $> make && make install
> 
> voila working 2.2.10 ruby on m1 macs with rbenv.

This solution worked for me, when installing ruby-2.0.0-p648, via ruby-install - in my apple silicon machine, when attempting to install via ruby-install the file causing the issue was `config.status`, which was located at `/Users/<unixname>/src/ruby-2.0.0-p648/config.status`. Making the change that @kule suggested, worked for me

The steps were:
1. Run `CFLAGS="-Wno-error=implicit-function-declaration" RUBY_CONFIGURE_OPTS="--disable-install-doc --disable-shared --with-openssl-dir=$(brew --prefix openssl@1.1)" ruby-install ruby-2.0.0-p648`
2. `cd /Users/<unixname>/src/ruby-2.0.0-p648/`
3. Edit `config.status`, and change `*) rm -f "$ac_file" && mv "$ac_tmp/out" "$ac_file";;` into `*)  mv "$ac_tmp/out" "$ac_file";;`
4. Run `make && make install` on that folder
5. ruby-2.0.0-p648 is now available!
