### ISSUE TITLE
where is ruby 3 in list

### ISSUE THREAD

**Issue by perezjasonr** [rbenv/ruby-build#1749]
I installed using ubuntu apt package manager.

both ruby-build --definitions and rbenv install -l

provide something that looks like this:

...
...
...
2.3.1
2.3.2
2.3.3
2.3.4
2.4.0-dev
2.4.0-preview1
2.4.0-preview2
2.4.0-preview3
2.4.0-rc1
2.4.0
2.4.1
2.5.0-dev

everything else below that is jruby, rbx, where is normal ruby 3? I think on my mac a while back the ruby version went up to 2.7 so how come almost a year later now the highest is 2.5.x, is the ubuntu package just behind?

**Comment by hsbt** [comment]
I don't know the maintenance status of ruby-build on Ubuntu package. I could install Ruby 3.0 or later with the current master branch.

**Comment by brendon** [comment]
It looks like `ruby-build` the (apt package) hasn't been updated in a while. Here's what I did to use a newer version as a plugin for `rbenv`:

```
$ sudo apt install rbenv
$ sudo apt remove ruby-build
$ mkdir -p "$(rbenv root)"/plugins
$ git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
```
