### ISSUE TITLE
Cannot build NS-3 Netanim on Mac M1 (SDK error)

### ISSUE THREAD

**Issue by nahidp** [rbenv/ruby-build#1750]
Hello,
I installed NS-3.31 on Mac M1 (macOS Big Sur) and its built successfully. However, I cannot install netanim and I receive SDK version error. I tried to downgrade SDK but it didnt help. I also tried to add "CONFIG+=sdk_no_version_check" to NetAnim.pro file, but didnt help either. qt5 has also been installed as prerequisite to netanim.

Is there any solution to this problem?

root@Nahids-MacBook-Air netanim % qmake NetAnim.pro
Project WARNING: Qt has only been tested with version 10.15 of the platform SDK, you're using .
Project WARNING: This is an unsupported configuration. You may experience build issues, and by using
Project WARNING: the 11.1 SDK you are opting in to new features that Qt has not been prepared for.
Project WARNING: Please downgrade the SDK you use to build your app to version 10.15, or configure
Project WARNING: with CONFIG+=sdk_no_version_check when running qmake to silence this warning.

**Comment by hsbt** [comment]
I'm not sure what is `NS-3.31`. It seems to not related `ruby-build`

**Comment by nahidp** [comment]
Sorry it seems I have asked my question in a wrong page!
