### ISSUE TITLE
Instructions for updating list of rubies on Ubuntu

### ISSUE THREAD

**Issue by victorbstan** [rbenv/ruby-build#1756]
It seems like most of the instructions and Wiki are oriented towards Mac OSX with little info on using Ubuntu beyond some basics. I have a server running Ubuntu 16.4 LTS, I installed ruby-build with `apt` the latest ruby version is `2.3.0-dev`. This seems quite out of date, I would like to find out how to update the list of ruby versions so that I can get the most recent options. Is there some documentation for this that I may have overlooked?

**Comment by hsbt** [comment]
There is no document for it. Because the distribution package like apt or dnf is out of scope for the our maintenance policy and responsibility. 

But I'm happy to add the instructions or features for upgrading definitions to our wiki or README.md.
