### ISSUE TITLE
openssl documentation takes a long while to copy

### ISSUE THREAD

**Issue by parkr** [rbenv/ruby-build#1766]
I ran `rbenv install 2.6.7 --verbose` today and ended up with a _massive_ (and slowly outputting) list of openssl documentation. Is there a way to disable this?

```text
...
/Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_CTX_get_num_tickets.html -> /Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_CTX_set_num_tickets.html
/Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_CTX_set_options.html
/Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_set_options.html -> /Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_CTX_set_options.html
/Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_CTX_clear_options.html -> /Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_CTX_set_options.html
/Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_clear_options.html -> /Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_CTX_set_options.html
/Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_CTX_get_options.html -> /Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_CTX_set_options.html
/Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_get_options.html -> /Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_CTX_set_options.html
/Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_get_secure_renegotiation_support.html -> /Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_CTX_set_options.html
/Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_CTX_set_psk_client_callback.html
/Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_psk_client_cb_func.html -> /Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_CTX_set_psk_client_callback.html
/Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_psk_use_session_cb_func.html -> /Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_CTX_set_psk_client_callback.html
/Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_set_psk_client_callback.html -> /Users/parkr/.rbenv/versions/2.6.7/openssl/share/doc/openssl/html/man3/SSL_CTX_set_psk_client_callback.html
...
```

**Comment by parkr** [comment]
It's my understanding that I could also do `RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl)"` to use a pre-built openssl, but that's not really what I'm after. Upgrading the openssl in Homebrew would require re-compiling this ruby when I use that strategy, so really disabling docs for the ruby-build-built openssl would be best.

**Comment by hsbt** [comment]
Does anyone know a configuration option to disable to install document on openssl?

We should add it at first.

**Comment by parkr** [comment]
I believe it's in the Makefile:

https://github.com/ChatSecure/OpenSSL/blob/738d2c05096e175d5c48d08f6600be2f52e8f5d5/Makefile#L542-L544

Running `make install` installs the documentation as well as the software. The correct target would be `make install_sw` I believe.

It seems like `ruby-build` doesn't have the ability to customize the Make target:

https://github.com/rbenv/ruby-build/blob/19ed806d27df9aadd22ed7a9573e64bc894d9655/bin/ruby-build#L606

**Comment by mislav** [comment]
Thanks for looking into that, @parkr! Doesn't ruby-build have a separate routine for building openssl on macOS? Maybe we can specifically change that part to invoke `make install_sw` instead of `make install`. Other software should not be affected.

**Comment by parkr** [comment]
@mislav Skipping this documentation on Mac makes sense, but why not other platforms too? I guess as an engineer I use search engines and online documentation. If I need offline documentation (e.g. for a ✈️ trip) then apps like Dash offer that. Maybe I'm not :neckbeard: enough to want documentation alongside my installation for every Ruby installation I have. 😂 

I'm very new to this codebase, but I'll give a shot to understanding how this could work. The 3.0.1 definition defines:

```bash
install_package "openssl-1.1.1k" "https://www.openssl.org/source/openssl-1.1.1k.tar.gz#892a0875b9872acd04a9fde79b1f943075d5ea162415de3047c327df33fbaee5" mac_openssl --if has_broken_mac_openssl
```

This calls `install_package` which calls `install_package_using "tarball" 1 "$@"` which calls `make_package` which calls `build_package`.

On a Mac this eventually calls `build_package_mac_openssl`, which sets `package_option openssl make -j 1` then calls `build_package_standard "$@"`. This calls `build_package_standard_build` (effectively `make`) then `build_package_standard_install` (effectively `make install`). I'm not sure how we could change the `make install` target in `build_package_standard_install` without some changes:

```bash
build_package_standard_install() {
  local package_name="$1"
  local package_var_name="$(capitalize "${package_name%%-*}")"

  local PACKAGE_MAKE_INSTALL_OPTS="${package_var_name}_MAKE_INSTALL_OPTS"
  local PACKAGE_MAKE_INSTALL_OPTS_ARRAY="${package_var_name}_MAKE_INSTALL_OPTS_ARRAY[@]"

  { "$MAKE" install "${!PACKAGE_MAKE_INSTALL_OPTS_ARRAY}" $MAKE_INSTALL_OPTS ${!PACKAGE_MAKE_INSTALL_OPTS}
  } >&4 2>&1
}
```

`install` is hardcoded there so we'd want a way to either (1) not call this function and call something else, or (2) to allow `build_package_standard_install` to have some sort of customized target through the (admittedly still confusing to me) variable system in this file.

**Comment by mislav** [comment]
> Skipping this documentation on Mac makes sense, but why not other platforms too?

We never build openssl on other platforms. Just on macOS because its openssl is broken.

> This calls `build_package_standard_build` (effectively `make`) then `build_package_standard_install` (effectively `make install`). I'm not sure how we could change the `make install` target in `build_package_standard_install` without some changes

You are right, it's going to be tricky. We could introduce another variable, e.g. `MAKE_INSTALL_TARGET`, and make sure its default value is `install` but allow overriding it per invocation of `build_package_standard_install`.

**Comment by eregon** [comment]
I fixed this in https://github.com/rbenv/ruby-build/pull/1967

**Comment by parkr** [comment]
Thank you very much @eregon!!
