### ISSUE TITLE
not able to install ruby 2.2.3 on big sur on new Mac pro M1

### ISSUE THREAD

**Issue by BaidyaAnup** [rbenv/ruby-build#1767]
Tried every solution available, still no luck.pls help if any one has done

**Comment by hsbt** [comment]
Unfortunately, Ruby 2.2.x doesn't support with M1 macOS.

**Comment by disbelief** [comment]
Hi @hsbt I'm wondering if the same is true for ruby 1.9.x on M1 macOS? Is every version below 2.2.x unsupported?
