### ISSUE TITLE
Same error, different log on MacOs BigSur 11.4

### ISSUE THREAD

**Issue by krsinghshubham** [rbenv/ruby-build#1769]
I have the same error but with different log for installing ruby 2.3.3
Tried all the suggested solutions and even with RVM, for now RVM has been removed.
I am using the command which is in solution of this page to avoid other errors.
Error is posted as gist line, log file is 300k lines plus.
https://gist.github.com/krsinghshubham/2329d788f11d4db6f418e83629eae6b8.

Note: Xcode is updated.

**Comment by eregon** [comment]
> WARNING: ruby-2.3.3 is past its end of life and is now unsupported.
> It no longer receives bug fixes or critical security updates.

Probably latest Xcode/macOS + 2.3.3 does not work.
2.3.3 is too old, use something newer.
Anyway, not an issue of `ruby-build`.
