### ISSUE TITLE
travis-ci.org no longer builds and Ruby archives are no longer mirrored

### ISSUE THREAD

**Issue by eregon** [rbenv/ruby-build#1778]
See https://travis-ci.org/github/rbenv/ruby-build/builds, which says:

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

With https://github.com/rbenv/ruby-build/pull/1712, the only thing .travis.yml would do is to upload to the S3 mirror.
So recent Rubies are not mirrored anymore.

There are two options:
* Use travis-ci.com instead of travis-ci.org
* Move the secrets to upload to S3 to GitHub Actions, and let GitHub Actions handle the upload, cc @mislav.

**Comment by hsbt** [comment]
The current mirror is not needed because cache.ruby-lang.org is already delivered by fastly. So. every CRuby packages is delivered by CDN.

But I'm not sure backend of JRuby and TruffleRuby. If they are already delivered by CDN or similar solution. We don't need to mirror with Travis.

**Comment by eregon** [comment]
TruffleRuby releases are hosted on GitHub: https://github.com/oracle/truffleruby/releases
That has a CDN too, but historically we saw some issues when TravisCI was hitting that URL too many times in a short period: https://github.com/rvm/rvm/issues/4992. I have not seen it being problematic when ruby/setup-ruby is used, maybe because downloading in GitHub Actions implicitly has a higher limit or passes some extra credentials.

JRuby releases are hosted on S3: https://github.com/rbenv/ruby-build/blob/master/share/ruby-build/jruby-9.2.19.0
I'm not sure if that has a CDN and whether it's fine to accept many requests, cc @headius 

Probably not a big or urgent issue in practice, but I feel part of ruby-build's design is improved reliability by using that mirror.

There is some logic here, that looks like if no special mirror is set, it will check the default mirror url, unless it's cache.ruby-lang.org (CRuby).
https://github.com/rbenv/ruby-build/blob/f8e17bb435370581470b05537a065cdc9a69d3b1/bin/ruby-build#L365-L366
If the mirror does not have it it seems to just fallback:
https://github.com/rbenv/ruby-build/blob/f8e17bb435370581470b05537a065cdc9a69d3b1/bin/ruby-build#L387-L389

**Comment by mislav** [comment]
Thanks @eregon for the breakdown of the problem! I'm back from vacation now and will check whether I can move mirroring functionality to GitHub Actions so we can decommission Travis.

**Comment by eregon** [comment]
@mislav It seems there was an error when mirroring a new release, see https://github.com/rbenv/ruby-build/runs/3116765218

**Comment by mislav** [comment]
@eregon Thanks for letting me know. Fixed in dc047ade1ea5aa3bc997f1f12108ef4d7e3baf9a

**Comment by eregon** [comment]
Thanks!
