### ISSUE TITLE
Unable to install Ruby 3.0.x on macOS 11.4

### ISSUE THREAD

**Issue by nick-f** [rbenv/ruby-build#1779]
I've looked through the existing issues and have tried all the recommended steps in similar issues (like #1771 #1725) and have tried uninstalling and reinstalling the Command Line Tools, set different build flags, but still no luck.

All dependencies are up to date, using Homebrew. OpenSSL: 1.1.1k, ruby-build: 20210707. Running macOS 11.4 (20F71) on an Intel-based Mac.

In this run, I've set the dirs for openssl and other dependencies based on some troubleshooting from other issues, but the output is the same if that is not set and OpenSSL is downloaded as part of `rbenv install`.

```
❯ echo $RUBY_CONFIGURE_OPTS
--with-openssl-dir=/usr/local/opt/openssl@1.1 --with-readline-dir=/usr/local/opt/readline --with-libyaml-dir=/usr/local/opt/libyaml --with-zlib-dir=/usr/local/opt/zlib

❯ rbenv install 3.0.1
Downloading ruby-3.0.1.tar.gz...
-> https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.1.tar.gz
Installing ruby-3.0.1...

BUILD FAILED (macOS 11.4 using ruby-build 20210707)

Inspect or clean up the working tree at /var/folders/d_/6t0hnrmj7bj9nj7n04cqkj7c0000gp/T/ruby-build.20210709092347.76484.B7b4Tu
Results logged to /var/folders/d_/6t0hnrmj7bj9nj7n04cqkj7c0000gp/T/ruby-build.20210709092347.76484.log

Last 10 log lines:
installing default openssl libraries
linking shared-object openssl.bundle
./revision.h unchanged
make[1]: Nothing to be done for `note'.
Generating RDoc documentation
dyld: could not load inserted library '/var/folders/d_/6t0hnrmj7bj9nj7n04cqkj7c0000gp/T/ruby-build.20210709092347.76484.B7b4Tu/ruby-3.0.1/mjit_build_dir.dylib' because no suitable image found.  Did find:
        /var/folders/d_/6t0hnrmj7bj9nj7n04cqkj7c0000gp/T/ruby-build.20210709092347.76484.B7b4Tu/ruby-3.0.1/mjit_build_dir.dylib: code signing blocked mmap() of '/var/folders/d_/6t0hnrmj7bj9nj7n04cqkj7c0000gp/T/ruby-build.20210709092347.76484.B7b4Tu/ruby-3.0.1/mjit_build_dir.dylib'
        /var/folders/d_/6t0hnrmj7bj9nj7n04cqkj7c0000gp/T/ruby-build.20210709092347.76484.B7b4Tu/ruby-3.0.1/mjit_build_dir.dylib: stat() failed with errno=1

make: *** [rdoc] Abort trap: 6
```

Interestingly installing 3.1.0-dev succeeds:
```
❯ rbenv install 3.1.0-dev
Cloning https://github.com/ruby/ruby.git...
Installing ruby-master...
Installed ruby-master to /Users/nickf/.rbenv/versions/3.1.0-dev
```

As does 2.7.4:
```
❯ rbenv install 2.7.4
Downloading ruby-2.7.4.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.4.tar.bz2
Installing ruby-2.7.4...
Installed ruby-2.7.4 to /Users/nickf/.rbenv/versions/2.7.4
```

Any pointers on what to try next or what I might have missed?

**Comment by hsbt** [comment]
I could install 3.0 with macOS 11.x. I'm not sure why it's failed.

**Comment by nick-f** [comment]
Thank you for confirming, @hsbt.

I've done some more digging and compared output with others. It seems that the failure is caused by antivirus/endpoint protection software blocking the process.

Closing this out as it's not a ruby-build issue specifically.

**Comment by komidore64** [comment]
@nick-f would it be possible for you to elaborate more on this? possibly what might need to be allowed?

**Comment by mtrussell** [comment]
@nick-f I'm also getting this same issue. Could you explain how you fixed it?

**Comment by nick-f** [comment]
@komidore64 @mtrussell I think the paths that were being blocked were explicitly added to the allowlist for the antivirus. It was only happening on a work computer, so I contacted the company IT team and they contacted the AV vendor in order to find out more info about why this was happening. I wasn't involved in the fix directly so I don't have much more info than that unfortunately.

**Comment by komidore64** [comment]
Hey, that's alright! I appreciate you following up. 😄

**Comment by minhtienvu** [comment]
I have the same error when I try to install Ruby 3.0.x on my Macbook M1. I updated the version to 11.4
