### ISSUE TITLE
bump-homebrew-formula-action@v1.4 fails with HttpError: Bad credentials

### ISSUE THREAD

**Issue by eregon** [rbenv/ruby-build#1785]
See https://github.com/rbenv/ruby-build/runs/3163289927?check_suite_focus=true
cc @mislav 

Maybe the `COMMITTER_TOKEN` used was invalidated since GitHub recently changed the format of those and sent emails to renew them?

**Comment by mislav** [comment]
I've actually regenerated that token! I have no idea why it failed after that.

I've regenerated it again and updated the repository secret. Please reopen if it fails again 🤞
