### ISSUE TITLE
Support aarch64

### ISSUE THREAD

**Issue by joschl** [rbenv/ruby-build#1786]
https://github.com/rbenv/ruby-build/blob/cf9a6fcdade04c6dbe04c476482b42f04f30b2a1/share/ruby-build/truffleruby%2Bgraalvm-21.2.0#L3

truffleruby+graalvm-21.2.0 supports aarch64, but ruby-build will try to fetch the amd64 binary if uname -s matches "Linux".

**Comment by eregon** [comment]
True, Linux aarch64 is supported now for TruffleRuby, I'll update the update script.

**Comment by eregon** [comment]
@joschl Could you try https://github.com/rbenv/ruby-build/pull/1788 ?
