### ISSUE TITLE
Not able to install Ruby 2.3.4 on MacOS 11.5.1

### ISSUE THREAD

**Issue by namratasaun** [rbenv/ruby-build#1790]
I have tried almost all the methods and nothing worked, hence opening this issue.
![image](https://user-images.githubusercontent.com/35791871/128292634-848994a6-dfdc-4c4b-aa12-9f051a0ba337.png)

Can anyone please help.

**Comment by hsbt** [comment]
I could install 2.3.8 with macOS 11.5.1

```
$ rbenv install 2.3.8
Installing openssl-1.0.2u...
Installed openssl-1.0.2u to /Users/hsbt/.local/share/rbenv/versions/2.3.8

Installing ruby-2.3.8...

WARNING: ruby-2.3.8 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.

ruby-build: using readline from homebrew
lsInstalled ruby-2.3.8 to /Users/hsbt/.local/share/rbenv/versions/2.3.8
```

**Comment by brrusselburg** [comment]
Same issue with 2.6.7.

**Comment by AnatolZaitsev** [comment]
Seems like I handled this issue, just run terminal using Rosetta like in [this suggestion](https://github.com/Homebrew/discussions/discussions/149#discussioncomment-138276)

**Comment by hsbt** [comment]
I could install it with macOS 12.0.1 (Monterey).

**Comment by hsbt** [comment]
If it is caused by M1 arch, it's duplicate of https://github.com/rbenv/ruby-build/issues/1691
