### ISSUE TITLE
JRuby 9.3.0.0 Released

### ISSUE THREAD

**Issue by kaylareopelle** [rbenv/ruby-build#1796]
Hello! 

[JRuby 9.3.0.0 was released on September 22](https://www.jruby.org/2021/09/22/jruby-9-3-0-0.html). When do you anticipate ruby-build will support this version?

Thanks for this invaluable tool!

**Comment by eregon** [comment]
Basically it needs a PR to add the new version.
It's made a bit more complicated as the URL changed (https://github.com/ruby/setup-ruby/issues/220#issuecomment-926513032), but I'll try to find a workaround for it.

**Comment by kaylareopelle** [comment]
Thanks @eregon! 🎉
