### ISSUE TITLE
Hi I am facing Ruby  installation issue  ruby-2.3.1 in Linux ubuntu 20.04 LTS version 

### ISSUE THREAD

**Issue by rsurendraidexcel** [rbenv/ruby-build#1815]
Hi I have ubuntu 20.04 LTS version , i try install ruby 2.3.1 version , which my old application are using , while install ruby by using  rbenv  i am getting issue , event thought  in rvm also same issue

![Screenshot from 2021-10-30 21-06-25](https://user-images.githubusercontent.com/7713535/139540155-60e24666-a413-4f67-b131-0037b72e2ddb.png)

Log installation build fails log file
[ruby-buil.34xxx.log](https://github.com/rbenv/rbenv/files/7447024/ruby-buil.34xxx.log)

any body ruby people  have idia about this kind of issue . can you help me .

**Comment by vanwithme** [comment]
![image](https://user-images.githubusercontent.com/20986045/139642982-0480e185-95aa-4df3-a40b-c9b1fb136baf.png)

I got the same problem installing ruby 2.3.1 on ubuntu 20.04

Log installation build fails log file
[ruby-buil.34xxx.log](https://github.com/rbenv/ruby-build/files/7451700/ruby-buil.34xxx.log)

**Comment by hsbt** [comment]
Unfortunately, we can't fix it because Ruby 2.3.x is already EOL status. Maybe, You need to use the old version of ubuntu.
