### ISSUE TITLE
Cannot install jruby 1.6.7.2 or 1.7preview1 - Ubuntu

### ISSUE THREAD

**Issue by MortalCatalyst** [rbenv/ruby-build#188]
Is there a workaround to ruby-build to install jruby on ubuntu 12.04? I receive this error when trying to install.

sayth@sayth-TravelMate-5740G:~$ rbenv install jruby-1.6.7.2
Downloading http://jruby.org.s3.amazonaws.com/downloads/1.6.7.2/jruby-bin-1.6.7.2.tar.gz...
Installing jruby-1.6.7.2...

BUILD FAILED

Inspect or clean up the working tree at /tmp/ruby-build.20120720224807.9240
Results logged to /tmp/ruby-build.20120720224807.9240.log

Last 10 log lines:
make[2]: g++: Command not found
make[2]: **\* [build/unix/Linux/argparser.o] Error 127
make[2]: Leaving directory `/home/sayth/.rbenv/versions/jruby-1.6.7.2/lib/ruby/gems/1.8/gems/jruby-launcher-1.0.14-java'
make[1]: *** [.build-conf] Error 2
make[1]: Leaving directory`/home/sayth/.rbenv/versions/jruby-1.6.7.2/lib/ruby/gems/1.8/gems/jruby-launcher-1.0.14-java'
make: **\* [.build-impl] Error 2

Gem files will remain installed in /home/sayth/.rbenv/versions/jruby-1.6.7.2/lib/ruby/gems/1.8/gems/jruby-launcher-1.0.14-java for inspection.
Results logged to /home/sayth/.rbenv/versions/jruby-1.6.7.2/lib/ruby/gems/1.8/gems/jruby-launcher-1.0.14-java/./gem_make.out

**Comment by ryanermita** [comment]
im having this kind of problem, how did you solved this? Thanks :) :+1:

**Comment by ryanermita** [comment]
i solved it after installing g++.
`sudo apt-get install g++`

Thanks :)
