### ISSUE TITLE
Issue installing  mongodb-community@5.0

### ISSUE THREAD

**Issue by termasuke21** [rbenv/ruby-build#1917]
Hello,

I'm tryimg to install mongodb-community throgh brew, however, I'm getting the following error:

Error: undefined method `name' for nil:NilClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:275:in `block in initialize'
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:274:in `map'
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:274:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:561:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:561:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:420:in `factory'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:633:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:629:in `map'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:629:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:308:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:141:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'

**Comment by hsbt** [comment]
It's not `ruby-build` issue. You should ask it to https://github.com/Homebrew/homebrew-core/ or https://stackoverflow.com/
