### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by stanley90** [rbenv/ruby-build#1962]
### Steps to reproduce the behavior

Cannot install from git and from [`asdf-ruby`](https://github.com/asdf-vm/asdf-ruby)
It seems to have broken recently (1-2 weeks?) by upgrading something (unfortunately don't know what).

### Expected vs. actual behavior

Expected: install works

Actual: failure

### Logs

```
Warning: unknown option ‘-p’
Error in getOctD(x, offset, len) : invalid octal digit
```

Environment:

```
$ uname -a
Darwin fuji 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64
```

**Comment by mislav** [comment]
> ```
> Error in getOctD(x, offset, len) : invalid octal digit
> ```

Hi, since this project (ruby-build) is written in bash and does not have any function called `getOctD` in its codebase, my strong suggestion is that this error is coming from somewhere else and not from either ruby-build or from the Ruby compilation process.
