### ISSUE TITLE
New version please?

### ISSUE THREAD

**Issue by newellista** [rbenv/ruby-build#1988]
Can we get a new version that incorporates the changes for jruby-9.3.6.0?

Pull request adding that version is [here](https://github.com/rbenv/ruby-build/commit/fd36eb0d4eb3a1eb1307fca0f27ab68013a4a188)

Thanks!

**Comment by hsbt** [comment]
done https://github.com/rbenv/ruby-build/releases/tag/v20220630

**Comment by simonneutert** [comment]
Please do the same for 9.3.7.0 
☺️ Thank you very much 🙏

**Comment by eregon** [comment]
Done. It should be easy to use ruby-build master/head though, why do you need a release?

**Comment by simonneutert** [comment]
I thought asdf depends on it. 
Sorry, if I'm wrong, @eregon

**Comment by eregon** [comment]
For asdf, one can use `ASDF_RUBY_BUILD_VERSION=master`: https://github.com/asdf-vm/asdf-ruby#use
