### ISSUE TITLE
build failed on ruby-1.9.2-p290 in cygwin

### ISSUE THREAD

**Issue by hustcalm** [rbenv/ruby-build#199]
Error: dot: can't open /tmp/ruby-build.20120814175241.484/ruby-1.9.2-p290/doc/capi/html/d6/d73/class_8c__incl.dot^M
   7356 Error: dot: can't open /tmp/ruby-build.20120814175241.484/ruby-1.9.2-p290/doc/capi/html/d8/d41/array_8c__incl.dot^M
   7357 Error: dot: can't open /tmp/ruby-build.20120814175241.484/ruby-1.9.2-p290/doc/capi/html/d6/d59/bignum_8c__incl.dot^M
   7358 Problems running dot: exit code=2, command='dot', arguments='"/tmp/ruby-build.20120814175241.484/ruby-1.9.2-p290/doc/capi/html/d6/d59/bignum_8c__incl.dot" -Tpng -o
   7359 Problems running dot: exit code=2, command='dot', arguments='"/tmp/ruby-build.20120814175241.484/ruby-1.9.2-p290/doc/capi/html/d6/d73/class_8c__incl.dot" -Tpng -o "
   7360 Problems running dot: exit code=2, command='dot', arguments='"/tmp/ruby-build.20120814175241.484/ruby-1.9.2-p290/doc/capi/html/d8/d41/array_8c__incl.dot" -Tpng -o "

error: problems opening map file /tmp/ruby-build.20120814175241.484/ruby-1.9.2-p290/doc/capi/html/da/d43/enum_8c__incl.map for inclusion in the docs!
   9911 If you installed Graphviz/dot after a previous failing run,
   9912 try deleting the output directory and rerun doxygen.

Maybe it's concerned with Doxygen.

PS:
it is ok to install ruby-1.9.3-p0 with rbenv.

**Comment by mijoharas** [comment]
Just want to verify, I guess you're still not supporting cygwin? Can you add that to the docs, just trying to add a version manager to my windows work computer.

**Comment by mislav** [comment]
It says so in the first line of the README:

> ruby-build is an rbenv plugin that provides an rbenv install command to compile and install different versions of Ruby on UNIX-like systems.

Windows is not a UNIX-like system.

**Comment by mijoharas** [comment]
Windows isn't but [cygwin kinda is](https://en.wikipedia.org/wiki/Cygwin):

> Cygwin (/ˈsɪɡwɪn/ sig-win[2]) is a Unix-like environment and command-line interface for Microsoft Windows

I understand why you don't support it as it can bring it's own set of headaches (on top of the ones you get using windows natively), I just thought the docs were less clear than they could be.

Thanks for your response (and clarification that it's still unsupported).

**Comment by mislav** [comment]
Cygwin attempts to bring a UNIX-like environment to Windows but evidently fails. If it had succeeded, using rbenv and ruby-build would have been possible under cygwin.
