### ISSUE TITLE
Connection timeout from ubuntu server

### ISSUE THREAD

**Issue by psnider30** [rbenv/ruby-build#2020]
Ubuntu Version: 16.04
I'm trying to install ruby 2.6.6 with rbenv
However, ruby 2.6.6 is not currently in my `rbenv install --list'
Initial ruby-build setup per:  [https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rbenv-on-ubuntu-16-04](url)
Terminal commands showing timeout error when trying to pull down from ruby-build github:
<img width="635" alt="Screen Shot 2022-08-05 at 7 42 51 PM" src="https://user-images.githubusercontent.com/13356541/183230447-2ddf867a-a2ff-4a71-87b1-f8773ec3f9d1.png">

**Comment by eregon** [comment]
It's a problem of your network connection, or of GitHub potentially.
The failing command is `git pull`, so nothing ruby-build can do about that.
