### ISSUE TITLE
Can't install ruby on macOS Ventura

### ISSUE THREAD

**Issue by leobrival** [rbenv/ruby-build#2046]
Hello, I have a particular problem, I am unable to install ruby-build on macOS Ventura

<img width="1791" alt="Capture d’écran 2022-09-14 à 12 37 52" src="https://user-images.githubusercontent.com/29938311/190213892-ff91b4c8-bd13-4875-b1c3-b1bd6cd6da15.png">

**Comment by hsbt** [comment]
You need to install Xcode Command Line Tools and related toolchains. And you should investigate like them by yourself because Ventura is still beta status.

I'm working in progress to build Ruby with macOS Ventura. But It's not complete yet.

**Comment by orbanbalage** [comment]
I did many things, so I'm not 100% this final thing is the only one needed, but after I installed the latest Command Line Tools and in case you're missing any packages you can issue this first:

`brew reinstall automake bison gdbm libffi libyaml openssl@1.1 openssl@3 readline chruby ruby-install`

and then 
`export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"` 

was the missing piece [your PATH may vary]

`>>> Successfully installed ruby 3.1.2 into /Users/orbanbalage/.rubies/ruby-3.1.2`
