### ISSUE TITLE
truffleruby+graalvm-dev fails it install, url not found

### ISSUE THREAD

**Issue by matthewford** [rbenv/ruby-build#2092]
asdf install ruby truffleruby+graalvm-dev --verbose                                                                                     truffle-ruby ✭ ✱
To follow progress, use 'tail -f /var/folders/g0/rksdkbdn56j7xg5fd3fpv05w0000gn/T/ruby-build.20221120222346.38981.log' or pass --verbose
ruby-build: using openssl from homebrew
Downloading graalvm-ce-java11-darwin-amd64-dev.tar.gz...
-> https://github.com/graalvm/graalvm-ce-dev-builds/releases/latest/download/graalvm-ce-java11-darwin-amd64-dev.tar.gz
error: failed to download truffleruby+graalvm-dev.tar.gz

BUILD FAILED (macOS 12.6 using ruby-build 20221116)

**Comment by eregon** [comment]
Thanks for the report, the supported java version is now 17, I'll update the URL in ruby-build.
