### ISSUE TITLE
Ruby 3.2.1 cannot be installed

### ISSUE THREAD

**Issue by ledermann** [rbenv/ruby-build#2149]
Trying to install Ruby 3.2.1 fails.

### Steps to reproduce the behavior

```
$ rbenv install 3.2.1
ruby-build: definition not found: 3.2.1
```

### Expected vs. actual behavior

`rbenv install 3.2.1` should install Ruby 3.2.1, but the definition cannot be found.

Side note: Homebrew informs me that ruby-build `20230208` is installed and up-to-date, but on the release page there is a [v20230208.1](https://github.com/rbenv/ruby-build/releases/tag/v20230208.1). Maybe **this** is the issue and there is something wrong with the `.1` release.

### Logs

```
$ rbenv install 3.2.1
ruby-build: definition not found: 3.2.1

See all available versions with `rbenv install --list'.

If the version you need is missing, try upgrading ruby-build:

  brew update && brew upgrade ruby-build

$ brew update && brew upgrade ruby-build
Already up-to-date.
Warning: ruby-build 20230208 already installed
```

### Machine

MacOS 13.2
Homebrew 3.6.21
rbenv 1.2.0
ruby-build 20230208

**Comment by hsbt** [comment]
Because https://github.com/Homebrew/homebrew-core/pull/122671 is not merged yet.

**Comment by chenrui333** [comment]
ruby-build PR is merged now.

**Comment by ledermann** [comment]
Thanks a lot, it works fine now 👍
