### ISSUE TITLE
ASDF_RUBY_VERSION is always taking priority

### ISSUE THREAD

**Issue by yordis** [rbenv/ruby-build#2169]
### Steps to reproduce the behavior
1. Create a project under `~/Developer/github.com/rbenv/myproject`
2. Run `cd ~/Developer/github.com/rbenv/myproject`
3. Run `asdf local ruby 2.7.6`
4. Run `cat ~/Developer/github.com/rbenv/myproject/.tool-versions` and it should have `ruby 2.7.6`
5. Run `asdf global ruby system`
6. Run `cat ~/.tool-vervions` and it should have `ruby system`
7. Run `asdf current`

### Expected vs. actual behavior

**Expected:** `ruby 2.6.5 ~/Developer/github.com/rbenv/myproject/.tool-versions`
**Actual:** `ruby 2.6.5 ASDF_RUBY_VERSION environment variable`

**Comment by mislav** [comment]
Hi, sorry, this is a question for the asdf project (something I'm not familiar with).

**Comment by yordis** [comment]
@mislav OMG!!!!! I was like, where my issue for `asdf-ruby` went ... 🤦🏻

Well, it turns out that I opened the issue in a completely different project 😭 I am so sorry!!!!!!

**Comment by mislav** [comment]
But if asdf is anything like rbenv, then it absolutely makes sense that an environment variable "ASDF_RUBY_VERSION" wins over `.tool-versions`. rbenv works the same way with RBENV_VERSION.
