### ISSUE TITLE
jirb for jruby-9.4.2.0 not working on Apple M1 (arm64-darwin)

### ISSUE THREAD

**Issue by steve-solomon** [rbenv/ruby-build#2179]
Hello.

I'm not sure that this is the right project to create this issue for.

After installing jruby-9.4.2.0 using ruby-build on a new MacOS with the M1 arch (arm-64), the jirb interactive shell is not working. I assume it's precompiled for x86-64 instead.

Here is the stack trace after starting jirb (full path ~/.rbenv/versions/jruby-9.4.2.0/bin/jirb):

[username]@Q62D3Q9H29 ~ % ~/.rbenv/versions/jruby-9.4.2.0/bin/jirb
Ignoring jruby-launcher-1.1.19-java because its extensions are not built. Try: gem pristine jruby-launcher --version 1.1.19
▽NameError: undefined local variable or method `path' for #<IO:(closed)>
                       ttymode at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/io/console/ffi/native_console.rb:22
                 ttymode_yield at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/io/console/ffi/native_console.rb:31
                           raw at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/io/console/ffi/native_console.rb:56
                    cursor_pos at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/reline/ansi.rb:248
  may_req_ambiguous_char_width at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/reline.rb:478
                inner_readline at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/reline.rb:291
                 readmultiline at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/reline.rb:254
                 readmultiline at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/forwardable.rb:238
                 readmultiline at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/forwardable.rb:238
                          gets at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/irb/input-method.rb:421
                    eval_input at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/irb.rb:491
                 signal_status at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/irb.rb:722
                    eval_input at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/irb.rb:490
                           lex at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/irb/ruby-lex.rb:273
      each_top_level_statement at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/irb/ruby-lex.rb:242
                          loop at org/jruby/RubyKernel.java:1586
      each_top_level_statement at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/irb/ruby-lex.rb:239
                         catch at org/jruby/RubyKernel.java:1292
      each_top_level_statement at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/irb/ruby-lex.rb:238
                    eval_input at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/irb.rb:509
                           run at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/irb.rb:443
                         catch at org/jruby/RubyKernel.java:1292
                           run at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/irb.rb:442
                         start at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/lib/ruby/stdlib/irb.rb:375
                        <main> at /Users/k30838/.rbenv/versions/jruby-9.4.2.0/bin/jirb:13

FYI 1: jruby seems to be working fine, e.g:
[username]@Q62D3Q9H29 ~ % jruby --version                                                                        
jruby 9.4.2.0 (3.1.0) 2023-03-08 90d2913fda OpenJDK 64-Bit Server VM 11.0.18+10-LTS on 11.0.18+10-LTS +jit [arm64-darwin]

FYI 2: This same issue applies when starting jirb using jruby installed from homebrew.

**Comment by hsbt** [comment]
Can you file this to https://github.com/jruby/jruby? It seems not `ruby-build` issue.
