### ISSUE TITLE
Unknown escape sequence '\ ' when building OpenSSL

### ISSUE THREAD

**Issue by vanyauhalin** [rbenv/ruby-build#2201]
### Steps to reproduce the behavior

```sh
$ env
RBENV_ROOT=/Users/vanyauhalin/Library/Application\ Support/rbenv
$ brew install rbenv ruby-build
$ rbenv install 3.2.2
```

### Expected vs. actual behavior

I follow [XDG Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and in the macOS home directory for any programs it's `/Users/{{username}}/Library/Application Support`. The problem is that when I try to install OpenSSL, I get an error from Clang that says:

```log
crypto/ct/ct_log.c:173:15: warning: unknown escape sequence '\ ' [-Wunknown-escape-sequence]
      fpath = CTLOG_FILE;
              ^~~~~~~~~~
include/internal/cryptlib.h:71:35: note: expanded from macro 'CTLOG_FILE'
#  define CTLOG_FILE              OPENSSLDIR "/ct_log_list.cnf"
                                  ^~~~~~~~~~
<command line>:17:59: note: expanded from macro 'OPENSSLDIR'
#define OPENSSLDIR "/Users/vanyauhalin/Library/Application\ Support/rbenv/versions/3.2.2/openssl/ssl"
                                                          ^~
```

I don't understand Clang, but a [quick look on the internet](https://stackoverflow.com/questions/42022735/warning-unknown-escape-sequence#answer-42022766) says to escape a string with spaces with a double slash.

```
"\\Hello\\Test"
```

### Logs

https://gist.github.com/vanyauhalin/903d356672b948066d8e4e9c0b6e36e8

**Comment by mislav** [comment]
Thanks for reporting. This is a bug with openssl build process. https://github.com/openssl/openssl/issues/4668#issuecomment-1581045763

There might not be a way to install openssl into your `Application Support` path, so you're going to have to manually install it elsewhere and link Ruby to it. I suggest using Homebrew:

```
brew install openssl@1.1
RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)" rbenv install 3.2.2
```
