### ISSUE TITLE
Automatic Homebrew formula update broken

### ISSUE THREAD

**Issue by eregon** [rbenv/ruby-build#2208]
See https://github.com/mislav/bump-homebrew-formula-action/issues/52

The first failed build is https://github.com/rbenv/ruby-build/actions/runs/5205365492/jobs/9390735532 (FYI @hsbt)
All builds: https://github.com/rbenv/ruby-build/actions/workflows/release.yml

Until it's fixed, we should manually create a PRs to https://github.com/Homebrew/homebrew-core when releasing, similar to this PR: https://github.com/Homebrew/homebrew-core/pull/130837

**Comment by hsbt** [comment]
oh, Thanks. I didn't notice it.

**Comment by mislav** [comment]
Might have been a GitHub API glitch. Let's keep an eye out around the next release.

**Comment by mislav** [comment]
I added the `workflow` scope to the PAT that is used for opening the Homebrew PR. That should fix the issue! https://github.com/mislav/bump-homebrew-formula-action/issues/52#issuecomment-1600697372
