### ISSUE TITLE
macos-latest (macos-12) trufferuby-head (23.1.0-dev-b64cd1d4): native extentsion compiling with both OpenSSL 3.1 and 1.1 include directories.

### ISSUE THREAD

**Issue by junaruga** [rbenv/ruby-build#2220]
We see an issue on the macos-latest trufferuby-head case on the GitHub Actions on ruby/openssl. The issue ticket is <https://github.com/ruby/openssl/issues/650>. I don't know where the issue comes from. But my guess is that the trufferuby-head was built with both OpenSSL 3.1 and 1.1 include directories unintentionally. 

---

### Steps to reproduce the behavior

1. Fork the repository: <https://github.com/ruby/openssl>.
2. Push an dummy empty commit to your repository.
3. Check the macos-latest truffleruby-head case on the GitHub Actions on the repository.

### Expected vs. actual behavior

Expected: The case succeeds. There is no compiler warning.

Actual: The case fails. There is a compiler warning.

```
/Users/runner/.rubies/truffleruby-head/lib/sulong/native/bin/graalvm-native-clang -I. -I/Users/runner/.rubies/truffleruby-head/lib/cext/include -I/Users/runner/.rubies/truffleruby-head/lib/cext/include/ruby/backward -I/Users/runner/.rubies/truffleruby-head/lib/cext/include -I../../../../ext/openssl -I/usr/local/Cellar/openssl@3/3.1.1_1/include -DRUBY_EXTCONF_H=\"extconf.h\"  -D_DARWIN_C_SOURCE -DTRUFFLERUBY_ABI_VERSION=3.1.3.9 -I/usr/local/opt/openssl@1.1/include -fPIC   -Werror=implicit-function-declaration -Wno-int-conversion -Wno-int-to-pointer-cast -Wno-incompatible-pointer-types -Wno-format-invalid-specifier -Wno-format-extra-args -ferror-limit=500  -Werror  -o ossl.o -c ../../../../ext/openssl/ossl.c 
In file included from ../../../../ext/openssl/ossl.c:10:
In file included from ../../../../ext/openssl/ossl.h:175:
../../../../ext/openssl/openssl_missing.h:195:11: error: 'TS_VERIFY_CTS_set_certs' macro redefined [-Werror,-Wmacro-redefined]
#  define TS_VERIFY_CTS_set_certs(ctx, crts) ((ctx)->certs=(crts))
          ^
/usr/local/Cellar/openssl@3/3.1.1_1/include/openssl/ts.h:426:11: note: previous definition is here
#  define TS_VERIFY_CTS_set_certs(ctx, cert) TS_VERIFY_CTX_set_certs(ctx,cert)
          ^
```

I suppose that the problem is both OpenSSL 1.1 include directory `-I/usr/local/opt/openssl@1.1/include` and OpenSSL 3.1 directory `-I/usr/local/Cellar/openssl@3/3.1.1_1/include` are specified in the command line. I assume the truffleruby-head was built with both the include directories.

### Logs

https://github.com/ruby/openssl/actions/runs/5580792815/job/15113450849#step:8:91

**Comment by junaruga** [comment]
I suspect that the following codes may cause this issue.

https://github.com/rbenv/ruby-build/blob/35e5d2a29df62213e930e9617894e0a8eed9da70/share/ruby-build/truffleruby-dev#L10

https://github.com/rbenv/ruby-build/blob/35e5d2a29df62213e930e9617894e0a8eed9da70/bin/ruby-build#L1154

**Comment by junaruga** [comment]
Here is an temporary workaround for this issue in Ruby OpenSSL binding repository.

https://github.com/ruby/openssl/pull/652

```
diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
index 36609e2..4e5def4 100644
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -51,6 +51,12 @@ jobs:
         run:  echo "RUBY_OPENSSL_EXTCFLAGS=-Werror" >> $GITHUB_ENV
         if: ${{ !matrix.skip-warnings }}
 
+      # A temporary workaround to pass the CI case.
+      # https://github.com/ruby/openssl/issues/650
+      - name: remove openssl 3 include directory.
+        run:  rm -rfv "$(brew --prefix openssl@3)/include"
+        if: matrix.os == 'macos-latest' && matrix.ruby == 'truffleruby-head'
+
       # Enable provider search path for OpenSSL 3.0 in MSYS2.
       # Remove when Ruby 3.2 build is updated
       - name: enable windows provider search path
```

**Comment by eregon** [comment]
IIRC `use_homebrew_openssl` has no effect on TruffleRuby, TruffleRuby has its own logic to find the system libssl:
https://github.com/oracle/truffleruby/blob/16db2e64472e5f4d88176ae122815b6b291c0947/lib/truffle/truffle/openssl-prefix.rb
So let's continue in https://github.com/ruby/openssl/issues/650
