### ISSUE TITLE
Old Ruby, mismatched OpenSSL

### ISSUE THREAD

**Issue by pointlessone** [rbenv/ruby-build#2300]
### Steps to reproduce the behavior

`rbenv install 2.6.10`

### Details

The build fails with mismatched OpenSSL error.

- I have both openssl@1.1 and openssl@3 installed in homebrew
- I run macOS Sonoma 14.2
- I have ruby-build installed through homebrew, version 20231107

ruby-build seem to correctly detect openssl@1.1:

```
-> ./configure "--prefix=$HOME/.rbenv/versions/2.6.10" --enable-shared --with-readline-dir=/usr/local/opt/readline --with-libyaml-dir=/usr/local/opt/libyaml --with-gmp-dir=/usr/local/opt/gmp --with-openssl-dir=/usr/local/opt/openssl@1.1
```

But this somehow gets lost during compilation phase:

```
compiling ossl.c
ossl.c:311:14: error: 'ERR_get_error_line_data' is deprecated [-Werror,-Wdeprecated-declarations]
        while ((e = ERR_get_error_line_data(&file, &line, &data, &flags))) {
                    ^
/usr/local/Cellar/openssl@3/3.1.4/include/openssl/err.h:424:1: note: 'ERR_get_error_line_data' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0
^
/usr/local/Cellar/openssl@3/3.1.4/include/openssl/macros.h:193:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/local/Cellar/openssl@3/3.1.4/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
1 error generated.
```

### Logs

[Full log](https://gist.github.com/pointlessone/77756e5058ce8a183506c57c366f10a5)

**Comment by mislav** [comment]
Thank you for reporting. It looks like ruby-build does its job correctly, but Ruby 2.6 ignores the `--with-openssl-dir` passed to it. If you temporarily `brew unlink openssl@3`, does the problem go away?

Was this a problem for you before the latest release of ruby-build?

**Comment by mislav** [comment]
Some more information here: https://github.com/rbenv/ruby-build/discussions/2125#discussioncomment-7516993

Closing as there is more evidence that is a problem of the Ruby 2.6 build system, which makes the `brew unlink openssl@3` workaround more likely to have effect.

**Comment by pointlessone** [comment]
Unlinking newer openssl does fix the issue. Thank you.

**Comment by php4fan** [comment]
I'm hitting this issue on Debian.
What's the workaround?

The one you mention uses "brew" which if I'm not mistaken is a Mac thing...
