### ISSUE TITLE
Using CRuby snapshot archives instead of building from git

### ISSUE THREAD

**Issue by eregon** [rbenv/ruby-build#2306]
https://www.ruby-lang.org/en/downloads/ has:
* https://cache.ruby-lang.org/pub/ruby/snapshot/snapshot-ruby_3_1.tar.gz
* https://cache.ruby-lang.org/pub/ruby/snapshot/snapshot-ruby_3_2.tar.gz
* https://cache.ruby-lang.org/pub/ruby/snapshot/snapshot-master.tar.gz
* etc

These have the advantages that autoconf, bison, etc have already run.
So they don't need extra packages and they can use the same logic as building releases.

BTW currently https://github.com/rbenv/ruby-build/wiki#suggested-build-environment is missing autoconf for Fedora & RHEL.
So it would also simplify that page if we don't have to include dependencies only relevant for building from git.

**Comment by mislav** [comment]
> These have the advantages that autoconf, bison, etc have already run.
> So they don't need extra packages and they can use the same logic as building releases.

I'm up for this if @hsbt agrees!

Would builds on top of these snapshots still require `make update-gems`, `make extract-gems`? https://github.com/rbenv/ruby-build/blob/270ecd0bcbe9b40e3aa9199d842552db455cadb3/bin/ruby-build#L708-L713

**Comment by eregon** [comment]
No it would not :)

**Comment by hsbt** [comment]
stable(3.2) and old stable(3.1) are okay to replace snapshot packages. But master(3.3.0-dev) is sometimes old with daily package. Because I used it at many times while daytime.

**Comment by eregon** [comment]
I see, that's unfortunate. Maybe the master snapshot could be automatically updated after every commit and then it would be reasonably fast?

master is kind of special, in fact I think we should add a  `ruby-dev` definition for that instead/in addition to 3.3.0-dev.

**Comment by mislav** [comment]
> But master(3.3.0-dev) is sometimes old with daily package.

If the snapshots are behind the actual git commits to any of the development branches, then switching ruby-build definitions to snapshots would be a downgrade, in my opinion.

> So it would also simplify that page if we don't have to include dependencies only relevant for building from git.

@eregon The aim for the wiki page was to provide a suggested build environment for _stable_ releases of Ruby only. As for development releases, we assume that a person willing to build a `*-dev` version would also put in the research necessary to gather the necessary prerequisites, such as autoconf.

**Comment by mislav** [comment]
If I am reading this correctly, then the master snapshot is several days behind the master branch in git:

```
$ tar xzf snapshot-master.tar.gz -O -- \*/revision.h | grep REVISION                                                                                
#define RUBY_REVISION "bbfd735b88"
#define RUBY_FULL_REVISION "bbfd735b887de71de48c7f862e6e3842bcc03241"

$ git -C ~/.rbenv/cache/https_github.com_ruby_ruby.git describe --all bbfd735b887de71de48c7f862e6e3842bcc03241 --match master
heads/master-876-gbbfd735b88
```

**Comment by eregon** [comment]
Right, unless snapshots are pretty close to latest commit I agree it's not a viable option, so let's close this at least until that's the case.

> @eregon The aim for the wiki page was to provide a suggested build environment for _stable_ releases of Ruby only. As for development releases, we assume that a person willing to build a `*-dev` version would also put in the research necessary to gather the necessary prerequisites, such as autoconf.

The nice thing about `jruby-dev` and `truffleruby-dev` is they have the exact same deps as release builds.
So the different dependencies for `-dev` seems to only affect CRuby.

Also since some of https://github.com/rbenv/ruby-build/wiki#suggested-build-environment contain autoconf I think originally they contained deps for CRuby dev too.

@mislav How about adding autoconf for Fedora and RHEL in the wiki? I'll do that.
Plus that would remove the need for the `dnf install perl-FindBin perl-File-Compare` section as that's dependencies of autoconf.

**Comment by mislav** [comment]
> How about adding autoconf for Fedora and RHEL in the wiki? I'll do that.

I'm not opposed; thanks for doing that!
