### ISSUE TITLE
ruby-build: definition not found: 3.3.0.rc1

### ISSUE THREAD

**Issue by dorianmariefr** [rbenv/ruby-build#2344]
### Steps to reproduce the behavior

```
asdf install ruby 3.3.0.rc1
```

### Expected vs. actual behavior

Expected: installs ruby 3.3.0.rc1

Actual: 

```
Downloading ruby-build...
ruby-build: definition not found: 3.3.0.rc1
```

I downloaded Campfire and it uses 3.3.0.rc1, would be nice to have that version.

Thanks

**Comment by monfresh** [comment]
A couple of comments:

1. You misspelled the version number. It should be `3.3.0-rc1`
2. 3.3.0 was officially released 9 days ago. There's no reason to use the release candidate. I would recommend updating Campfire to 3.3.0.

**Comment by mislav** [comment]
You can also always list all available definitions to find out about the correct spelling of versions:
```
$ bin/ruby-build --definitions | grep rc
1.9.1-rc1
1.9.1-rc2
1.9.2-rc1
1.9.2-rc2
1.9.3-rc1
2.0.0-rc1
2.0.0-rc2
2.1.0-rc1
2.2.0-rc1
2.4.0-rc1
2.5.0-rc1
2.6.0-rc1
2.6.0-rc2
2.7.0-rc1
2.7.0-rc2
3.0.0-rc1
3.2.0-rc1
3.3.0-rc1
...
```

**Comment by dorianmarie** [comment]
Oh okay, I took the spelling out of their .ruby-version file

Apparently something is broken in 3.3.0 but not in 3.3.0-rc1 (docker build)

Anyway thanks both for your answers
