### ISSUE TITLE
Wiki open to edits

### ISSUE THREAD

**Issue by amancevice** [rbenv/ruby-build#2352]
### Steps to reproduce the behavior

Kind of a meta-issue and not sure if it's a bug or not but I thought I'd let you know I was able to edit the Wiki for this project in GitHub without being a member of this organization.

The edit was in good faith but it doesn't seem like something I should be able to do?

I don't know enough about GitHub wikis to determine if it can be locked down or what.

### Expected vs. actual behavior

I didn't expect to be able to edit the Wiki!

### Logs

N/A

**Comment by mislav** [comment]
> The edit was in good faith but it doesn't seem like something I should be able to do?
> 
> I don't know enough about GitHub wikis to determine if it can be locked down or what.

This is expected. GitHub repository wikis are editable by any GitHub user by default, but there is an option to lock it down per-repo if a repository is seeing mostly unhelpful edits (e.g. spam or vandalism). The community has been doing a really good job making contributions to our wiki so far.

**Comment by amancevice** [comment]
Thanks, @mislav — happy building
