### ISSUE TITLE
RUBY_BUILD_MIRROR_URL ignored

### ISSUE THREAD

**Issue by glyh** [rbenv/ruby-build#2360]
### Steps to reproduce the behavior

```bash
RUBY_BUILD_SKIP_MIRROR= RUBY_BUILD_MIRROR_URL=https://cache.ruby-china.com asdf install ruby
```

### Expected vs. actual behavior

Expected using mirrors, but didn't

### Logs

```
==> Downloading ruby-3.3.0.tar.gz...
-> aria2c --allow-overwrite=true --no-conf=true --console-log-level=warn --stderr -o ruby-3.3.0.tar.gz https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.0.tar.gz
[#63f0bd 0B/0B CN:1 DL:0B]            
```

**Comment by glyh** [comment]
Also opened as https://github.com/asdf-vm/asdf-ruby/issues/272

**Comment by glyh** [comment]
![image](https://github.com/rbenv/ruby-build/assets/12870742/254ac242-b3a6-477c-bbc9-44752ec098fb)

**Comment by mislav** [comment]
Thanks for checking. Finally, can you verify that `shasum` process exits with a "success" status?

```
shasum -a 256 -b <<<"test" && echo SUCCESS
```

Other than that, I have no idea why your RUBY_BUILD_MIRROR_URL setting was ignored.

**Comment by glyh** [comment]
![image](https://github.com/rbenv/ruby-build/assets/12870742/cc460078-8a43-4428-ab66-83e52104d7dc)

**Comment by mislav** [comment]
Thanks for checking. No, your default shell being fish should not negatively affect ruby-build functionality.

I think I found out what is the problem: your mirror setting isn't ignored, but the resource wasn't found on the mirror URL:
```
$ curl -f https://cache.ruby-china.com/96518814d9832bece92a85415a819d4893b307db5921ae1f0f751a9a89a56b7d
curl: (22) The requested URL returned error: 404
```
In that case, ruby-build downloads the file from the original location at `https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.0.tar.gz`. What was likely confusing for you is that the attempt to hit the mirror isn't reflected in any ruby-build output.

[See here for more information about ruby-build mirrors](https://github.com/rbenv/ruby-build#package-mirrors).

**Comment by glyh** [comment]
That seems to be the case, thanks!
