### ISSUE TITLE
Can't upgrade above 20211019 via brew on macos

### ISSUE THREAD

**Issue by Nakilon** [rbenv/ruby-build#2363]
### Steps to reproduce the behavior

Trying to upgrade ruby-build to install newer Ruby via rbenv.

### Expected vs. actual behavior

Homebrew says my (2021) version is "up-to-date".

### Logs

```none
$ brew upgrade ruby-build
Warning: ruby-build 20211019 already installed
```
```none
$ rbenv install -L | grep ^3.
3.0.0-dev
3.0.0-preview1
3.0.0-preview2
3.0.0-rc1
3.0.0
3.0.1
3.0.2
3.1.0-dev
```

```none
$ brew uninstall ruby-build
Error: Refusing to uninstall /usr/local/Cellar/ruby-build/20211019
because it is required by rbenv, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies ruby-build
```

**Comment by Nakilon** [comment]
Uninstalling with `--ignore-dependencies` then still installs 20211019 -- is it because my macbook isn't ARM?

**Comment by monfresh** [comment]
My guess is that your Homebrew itself is very out of date. Have you tried `brew update` and `brew doctor`?

**Comment by Nakilon** [comment]
Yeah, it appeared I needed `brew update-reset` (https://1v0.dev/posts/14-fix-macos-homebrew-hang/) and then `brew install libressl` (because for some reason it failed to download autoconf from github or smth).
