### ISSUE TITLE
trying to install ruby 2.7.0

### ISSUE THREAD

**Issue by MagarKJ** [rbenv/ruby-build#2417]
rvm install 2.7.0

### Expected vs. actual behavior

tukisoft@Tukis-MacBook-Air ~ % rvm cleanup all
rvm install 2.7.0

Cleaning up rvm archives
Cleaning up rvm repos
Cleaning up rvm src
Cleaning up rvm log
Cleaning up rvm tmp
Cleaning up rvm gemsets
Cleaning up rvm links
Cleanup done.
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/14.5/arm64/ruby-2.7.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates bundle '/opt/homebrew/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/tukisoft/.rvm/rubies/ruby-2.7.0, this may take a while depending on your cpu(s)...
ruby-2.7.0 - #downloading ruby-2.7.0, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.0M  100 14.0M    0     0  5302k      0  0:00:02  0:00:02 --:--:-- 5302k
ruby-2.7.0 - #extracting ruby-2.7.0 to /Users/tukisoft/.rvm/src/ruby-2.7.0 - please wait
ruby-2.7.0 - #configuring - please wait
ruby-2.7.0 - #post-configuration - please wait
ruby-2.7.0 - #compiling - please wait
Error running '__rvm_make -j8',
please read /Users/tukisoft/.rvm/log/1719247174_ruby-2.7.0/make.log

There has been an error while running make. Halting the installation.

**Comment by hsbt** [comment]
Please file it to https://github.com/rvm/rvm. This repository is for `ruby-build`, not `rvm`.
