### ISSUE TITLE
Instructions out of date for RHEL 8/9

### ISSUE THREAD

**Issue by mcandre** [rbenv/ruby-build#2437]
When I try to install Ruby on RHEL (8/9), then yum and dnf note that there is no package called `libyaml-devel`, and that the version of GCC cited no longer exists.

Let's remove the `-6` version suffix entirely from the GCC package, for maintainability with future OS versions that will grow this number over time.

In recent versions of RHEL, the `libyaml-devel` package is hidden by default. RHEL users will need to explicitly enable some package groups:

```
# RHEL 8 based distros:
dnf config-manager --set-enabled powertools

# RHEL 9 based distros:
dnf config-manager --set-enabled crb

dnf install libyaml-devel
```

Per https://github.com/rvm/rvm/issues/5288#issuecomment-1387705721

For comparison, RVM uses Ruby's built-in libyaml implementation:

https://github.com/rvm/rvm/issues/2998#issuecomment-330061538

Ruby is one of the more complicated programming languages to install. Would be nice to have a tarball of pre-compiled binaries, independent of package management install media, in order to provide a dead simple way to get Ruby in contexts like ephemeral CI/CD environments and Docker FROM scratch images.

**Comment by mcandre** [comment]
What's more, the instructions differ between the old CentOS variant vs RHEL.

CentOS used a repository called powertools, a debranded copy of codeready builder for rhel. In other words...

* CentOS: `sudo dnf config-manager --set-enabled powertools`
* RHEL: `sudo subscription-manager repos --enable codeready-builder-for-rhel-<your RHEL major version here>-x86_64-rpms`

**Comment by mislav** [comment]
Hi, thanks for bringing this to my attention. I've updated CentOS/RHEL instructions to read:

```sh
yum install -y autoconf gcc patch bzip2 openssl-devel libffi-devel readline-devel zlib-devel gdbm-devel ncurses-devel tar
```

The wiki where these instructions are is community-editable, so feel free to make tweaks to the instructions too. I'm personally not familiar with most operating systems that we maintain installation instructions for, so I'm dependent on people like you to keep the instructions valid and up-to-date for the systems you have experience with.

**Comment by aep-sunlife** [comment]
No, the README is still out of date. It still omits the `libyaml-devel` requirement.

**Comment by mislav** [comment]
@aep-sunlife It was my understanding that `libyaml-devel` is no longer available from default RHEL repositories, thus we don't recommend installing it anymore in our one-liner. If you are experienced with RHEL and have concrete suggestions on how to improve the installation instructions for the average RHEL user, please elaborate here or thoughtfully [edit the wiki](https://github.com/rbenv/ruby-build/wiki). Thank you!

**Comment by mcandre** [comment]
Without libyaml-devel the Ruby compilation fails on RHEL8.

**Comment by mislav** [comment]
@mcandre Aha, so this line which is otherwise needed for RHEL 9 is already enabled by default in RHEL 8? `dnf config-manager --set-enabled crb`

**Comment by mislav** [comment]
BTW, which packages is this needed for, exactly? `dnf config-manager --set-enabled powertools`
