### ISSUE TITLE
"bad array subscript" error

### ISSUE THREAD

**Issue by sanjioh** [rbenv/ruby-build#2455]
### Steps to reproduce the behavior
`rbenv install 2.7.8`
### Expected vs. actual behavior
I get the error `/usr/local/bin/ruby-build: line 1158: versions: bad array subscript`, right after issuing the command, which I suppose should not happen.
The error is not blocking (build completes successfully).
### Logs
```shell
$ ruby-build --version
ruby-build 20241017
```

This happens on an Intel Mac with macOS 14.7, ruby-build installed from Homebrew.

**Comment by mislav** [comment]
Thank you for reporting.

If you paste the following code into a bash shell, what does it output? (You could paste it into zsh too; it will likely work.)

```sh
  brew list 2>/dev/null | grep '^openssl@' | while read -r formula; do
    prefix="$(brew --prefix "$formula" 2>/dev/null || true)"
    [ -n "$prefix" ] || continue
    version="$("$prefix"/bin/openssl version 2>/dev/null | sed -n 's/OpenSSL \([0-9][0-9.]*\).*/\1/p')"
    [ -z "$version" ] || printf '%s %s %s\n' "$formula" "$version" "$prefix"
  done
```

**Comment by sanjioh** [comment]
Hi, thanks for replying.

The output is:

`openssl@3 3.3.2 /usr/local/opt/openssl@3`

**Comment by mislav** [comment]
Thanks for checking. That looks okay, so I actually don't know what triggers the "bad array subscript" error. However, I do think that it's trying to access an array at index `-1` somehow, so I could add a guard around that, even if I don't understand how that index happened to be.

**Comment by mislav** [comment]
Another "bad array subscript" error spotted in the wild: https://github.com/rbenv/ruby-build/discussions/2387#discussioncomment-11142578
