### ISSUE TITLE
No Way To Install Latest Patch or Version of Specific Ruby

### ISSUE THREAD

**Issue by ksylvest** [rbenv/ruby-build#261]
It would be useful to have a way of installing the latest patch level and version of a given Ruby. For example:

```
rbenv install ruby # rbenv install 1.9.3-p362
rbenv install jruby # rbenv install jruby-1.7.1
rbenv install rbx # rbenv install rbx-1.2.4

rbenv install 1.9.3 # rbenv install 1.9.3-p362
rbenv install 1.9.2 # rbenv install 1.9.3-p320
rbenv install 1.8.7 # rbenv install 1.8.7-p371
```

This might be easiest by using symbolic links within the `ruby-build` folder. If this feature sounds useful I'd be happy to work on it.

**Comment by fulldecent** [comment]
If you don't know that then it is difficult. 

If it is not acceptable to have fuzzy matching to install/use the latest version, then a useful behavior can be that a fuzzy match will result in a message

"The latest available version of ruby 2 is ruby 2.1.99 you can install this with

Rbenv install 2.1.99"
