### ISSUE TITLE
1.9.3-p385 BUILD FAILED

### ISSUE THREAD

**Issue by fernandoaleman** [rbenv/ruby-build#281]
After updating rbenv and ruby-build via `git pull`, I got the following error when installing ruby 1.9.3-p385.

master ✔ $ rbenv install 1.9.3-p385 
Downloading yaml-0.1.4.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/36c852831d02cf90508c29852361d01b
Installing yaml-0.1.4...
Installed yaml-0.1.4 to /Users/faleman/.rbenv/versions/1.9.3-p385

Downloading ruby-1.9.3-p385.tar.gz...
-> http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-p385.tar.gz
Installing ruby-1.9.3-p385...

BUILD FAILED

Inspect or clean up the working tree at /var/folders/9s/shz_gbr939v125d4ckt02tyh0000gn/T/ruby-build.20130210102505.73135
Results logged to /var/folders/9s/shz_gbr939v125d4ckt02tyh0000gn/T/ruby-build.20130210102505.73135.log

Last 10 log lines:
compiling regenc.c
compiling regerror.c
compiling regexec.c
compiling regparse.c
regparse.c:582:15: error: implicit conversion loses integer precision: 'st_index_t' (aka 'unsigned long') to 'int' [-Werror,-Wshorten-64-to-32]
    return t->num_entries;
    ~~~~~~ ~~~^~~~~~~~~~~
1 error generated.
make: **\* [regparse.o] Error 1
make: **\* Waiting for unfinished jobs....

**Comment by thefonso** [comment]
> Install with `CCFLAGS='-Wno-error=shorten-64-to-32'`

How exactly is this done please?

**Comment by davidrupp** [comment]
I was able to get the compile phase to work this morning (MacBook Pro 16", MacOS 10.15.3) with the following:

`CFLAGS='-Wno-error=shorten-64-to-32' rbenv install 1.9.3-p385`

This sets the `CFLAGS` environment variable temporarily, for just the duration of the `rbenv install` command. You can do the same thing in general for other environment variables and other bash commands / scripts.

You can also separate setting the environment variable and running the command like so:

```
export CFLAGS='-Wno-error=shorten-64-to-32'
rbenv install 1.9.3-p385
```

Unfortunately, my build failed during linking, around openssl.bundle, so you may have some more digging to do.
