### ISSUE TITLE
configure: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by jrgifford** [rbenv/ruby-build#319]
I see this with any version of the C ruby family. 

https://gist.github.com/jrgifford/5057327

However, when I revert ruby-build to 84820db1c0793239ad20a36a10ac3e74c1a73a0d, it works.

OS: Ubuntu 12.10, 32 bit.

**Comment by Nakilon** [comment]
Despite this issue is two years long I had to do [this](https://github.com/sstephenson/rbenv/issues/778#issuecomment-138057691) patch manually a month ago.
```
$ ruby-build --version
ruby-build 20150818
```
