### ISSUE TITLE
PACKAGE_CFLAGS lead to fiber errors

### ISSUE THREAD

**Issue by krakatoa** [rbenv/ruby-build#330]
I did the following hot-fix: https://github.com/krakatoa/ruby-build/commit/015f3e20bf5bd41e52f1b4af229811693d55f9b0 in order to avoid an error related to the stack size of fibers utilized with the Celluloid library. Perhaps this bug is associated with this one: https://github.com/sstephenson/ruby-build/issues/325. I tracked down this issue and the origin is on the 06d7994bcf0a32673e4e73027ee953063f034d5e commit, but I'm not sure what is the best way to fix it. Here is the tracelog of the bug: https://gist.github.com/krakatoa/62bc7bd84a0c7fb515ce

Please tell me if you need some other log.

**Comment by mislav** [comment]
Closing as outdated
