### ISSUE TITLE
Build ruby with shared library

### ISSUE THREAD

**Issue by mloughran** [rbenv/ruby-build#35]
I'm not sure whether there is a good reason for this, but ruby-build does not build a ruby shared library.

This caused an issue for me when trying to build the zookeeper gem (ruby `1.9.2-p290`), which fails to compile.

I solved the issue by recompiling ruby with

```
./configure --prefix=$HOME/.rbenv/versions/1.9.2-p290 --enable-shared
```

RVM appears to do this by default - can ruby-build do the same?

Thanks!

**Comment by gavit** [comment]
For those with the same issue:
CONFIGURE_OPTS=--enable-shared  rbenv install 2.2.3

**Comment by mislav** [comment]
What exactly requires the shared library and would there be any downsides to enabling it for all builds?

**Comment by jeremy** [comment]
Ruby doesn't build as a shared lib by default. Most things link fine against the static lib. Generally, those who need a shared lib know. We could expose a toplevel option to make it easier/more discoverable, though.

Rice does explicitly state "Also Rice requires a Ruby built with –enable-shared and will not install properly against a Ruby with only static libraries." but it doesn't give any guidance on how to do that with rbenv, rvm, etc.

A little more background: https://www.ruby-forum.com/topic/4422189

Also, can be more specific than blanket CONFIGURE_OPTS:
```bash
RUBY_CONFIGURE_OPTS=--enable_shared rbenv install 2.2.3
```

**Comment by mislav** [comment]
Is there a short code snippet one could use in `ruby -e "..."` to test if the current Ruby has shared lib support?

**Comment by gavit** [comment]
Shared libraries are libraries that are loaded by programs when they start. When a shared library is installed properly, all programs that start afterwards automatically use the new shared library. So basically if you have a program that needs a shared library (in this case ruby libruby.so.2.2.0 or similar) the program will fail (to start hopefully) if it doesn't exist. if  you want to know if you have the shared library you can do a simple search for the file libruby.so*, but as jeremy indicated, you don't need it, and those that do will know.

**Comment by rickypai** [comment]
seems like you can test it with `RbConfig::CONFIG["ENABLE_SHARED"] == "no"`

https://github.com/jasonroelofs/rice/blob/master/extconf.rb#L21

**Comment by cmol** [comment]
Or `ruby -e "require 'rbconfig'; puts RbConfig::CONFIG['ENABLE_SHARED']"` for the lazy.

I just came across the same issue with the cwiid gem, that didn't compile until ruby was installed with `--enable-shared`. My "system" ruby comes with `--enable-shared` as well so I cannot see why this shouldn't be default for ruby-build.

**Comment by Ruin0x11** [comment]
I wasted several hours trying to install qtbindings before realizing `--enable-shared` wasn't set by default. I also don't see any reason not to set it by default.

**Comment by nathanaeljones** [comment]
Can this please be re-opened? Lack of shared by default breaks *so* many applications and gems.

**Comment by mislav** [comment]
@nathanaeljones This issue was open all along.

If someone wants to contribute a workaround that does `--enable-shared` by default for MRI, that would be welcome. I didn't realize this affected so many people, and so far we are not aware of a potential downside of doing that by default.

**Comment by rubypanther** [comment]
Is the most desirable way to add this by adding an enable_shared package target?
For example right now ruby-2.3.0 has this line in the definition file:
`install_package "ruby-2.3.0" "https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.0.tar.bz2#ec7579eaba2e4c402a089dbc86c98e5f1f62507880fd800b9b34ca30166bfa5e" ldflags_dirs standard verify_openssl
`
and I've got a fork that adds a build_package_enable_shared function in the ruby-build script, and then the package options just change to ldflags_dirs enable_shared standard verify_openssl
That way it can be controlled from the definitions file. Good, bad, comments?

**Comment by yashi** [comment]
Why not just pass `--enable-shared` when building Ruby?  Even if we change the current MRI, we don't get backported to older ones.  I'm not sure what's holding the change to ruby-build.  This little bug seems have wasted enough time for so many people already.  Can we fix this now?

**Comment by eregon** [comment]
Something to consider is that `--enable-shared` might affect performance.

**Comment by megatux** [comment]
Is this option still valid? I remember it was working, but trying it now throws me a `configure: error: unrecognized option: `--enable_shared'`  error  :
```
$ RUBY_CONFIGURE_OPTS=--enable_shared asdf install ruby 2.5.7
Downloading ruby-build...
Clonando en 'ruby-build-source'...
remote: Enumerating objects: 81, done.
remote: Counting objects: 100% (81/81), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 9872 (delta 40), reused 48 (delta 18), pack-reused 9791
Recibiendo objetos: 100% (9872/9872), 2.10 MiB | 248.00 KiB/s, listo.
Resolviendo deltas: 100% (6405/6405), listo.
Nota: actualizando el árbol de trabajo 'v20191004'.

Te encuentras en estado 'detached HEAD'. Puedes revisar por aquí, hacer
cambios experimentales y confirmarlos, y puedes descartar cualquier
commit que hayas hecho en este estado sin impactar a tu rama realizando
otro checkout.

Si quieres crear una nueva rama para mantener los commits que has creado,
puedes hacerlo (ahora o después) usando -b con el comando checkout. Ejemplo:

  git checkout -b <nombre-de-nueva-rama>

HEAD está ahora en da8e0b4 Bump version to v20191004
Downloading ruby-2.5.7.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.7.tar.bz2
Installing ruby-2.5.7...

BUILD FAILED (elementary 5.0 using ruby-build 20191004)

Inspect or clean up the working tree at /tmp/ruby-build.20191004095220.15967
Results logged to /tmp/ruby-build.20191004095220.15967.log

Last 10 log lines:
/tmp/ruby-build.20191004095220.15967 ~/code/other/r10k
/tmp/ruby-build.20191004095220.15967/ruby-2.5.7 /tmp/ruby-build.20191004095220.15967 ~/code/other/r10k
configure: error: unrecognized option: `--enable_shared'
Try `./configure --help' for more information
```

**Comment by eregon** [comment]
@megatux It's `--enable-shared`, not `--enable_shared`

**Comment by megatux** [comment]
:man_facepalming: thx @eregon (I copied from a comment above).

**Comment by ankane** [comment]
Hey, would love to try and move this forward. I think getting Rice and the rbenv defaults to play nicely would be a big/foundational step forward for the Ruby ML ecosystem (more context here: https://github.com/jasonroelofs/rice/issues/112).

@eregon it sounds like performance may be a concern. I'm happy to help test this. What's the best way to do that?

To all: are there any other concerns with making `--enable-shared` the default?

**Comment by mislav** [comment]
@ankane Thank you for offering to help! This would be a good starting point: https://github.com/rbenv/ruby-build/pull/1368

**Comment by ankane** [comment]
Awesome, thanks @mislav (for this and all you do for JS and Rails)! That PR does the trick on my machine.

**Comment by shehackedyou** [comment]
Happy to see this, wanted to experiment with connecting directly with the Ruby c libraries with Go purego and finally build sensible access to ruby that doesn't involve embedding a binary.
