### ISSUE TITLE
The Ruby openssl extension was not compiled. Missing the OpenSSL lib?

### ISSUE THREAD

**Issue by nathany** [rbenv/ruby-build#377]
`rbenv install 2.0.0-p247` fails on Mac OS X 10.8.4 with the error:

```
The Ruby openssl extension was not compiled. Missing the OpenSSL lib?
```

I had no problem installing **1.9.3-p448**.

Using ruby-build 20130628 via Homebrew.

**Comment by florianb** [comment]
@mislav I'd like to suggest a check based upon `ldconfig -p | grep libssl` as it is mentioned on this [serverfault post](http://serverfault.com/questions/54736/how-to-check-if-a-library-is-installed).

If appreciated i'd like trying to create a pull-request for that issue.

**Comment by mislav** [comment]
@florianb That's a start, except it doesn't work on OS X.

Pull requests welcome of course.

**Comment by defaye** [comment]
`sudo apt-get install libssl-dev` works on ubuntu 15.04 :+1:

**Comment by mingliangfeng** [comment]
Some basic libs are required, recommend this:
```
sudo apt-get install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev
```

**Comment by andreynering** [comment]
I had problems trying to install Ruby 2.2.2 on Fedora 22, but the following worked for me:

```
dnf install openssl-devel
rbenv install 2.2.2
rbenv global 2.2.2
```

**Comment by charneykaye** [comment]
Ubuntu 14:
    sudo apt-get install libssl-dev

**Comment by emckenna** [comment]
patch worked for me when installing 2.2.2 and 2.2.3 on Arch using openssl 1.0.2.g-3

**Comment by hugobast** [comment]
I'm sorry to say this but on macOS 10.12 with latest ruby-build this is still an issue. I brew installed openssl and I still have a hell of a time in making it play nice with `rbenv install`.

It's really unfortunate but this: 

```
CONFIGURE_OPTS="--with-openssl-dir=`brew --prefix openssl`"
```

... worked ...

**Comment by Superpencil** [comment]
macOS 10.13 High Sierra Beta 2
```CONFIGURE_OPTS="--with-openssl-dir=`brew --prefix openssl`" rbenv install 2.3.4```
Thank you @hugobast

**Comment by menjxo** [comment]
@hugobast 

Will try your solution as well, I encountered same error during installation as well.

**Comment by dubcl** [comment]
Hi, for Debian Stretch install

apt-get install libssl1.0-dev

not libssl-dev

**Comment by dubcl** [comment]
Hi, for Debian Stretch and ruby 2.2.3 install:

apt-get install libssl1.0-dev

not libssl-dev, then apply this:

https://github.com/rbenv/ruby-build/issues/834#issuecomment-160627207

**Comment by andersonmills** [comment]
For macports, this worked for me...

```RUBY_CONFIGURE_OPTS="--with-openssl-dir=/opt/local/" rbenv install 2.4.1```

**Comment by bg-scro** [comment]
`git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build` worked for me!

Followed that with `rbenv install 2.4.0` and everything is hunky-dory.

**Comment by zackkenyon** [comment]
when I installed rbenv through brew, I got this message
```
This formula is keg-only, which means it was not symlinked into /usr/local,
because Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
```

have you tried adding these flags to rbenv install?

**Comment by gregorvand** [comment]
using `RUBY_CONFIGURE_OPTS=--with-openssl-dir=/usr/local/Cellar/openssl/[latest version] rbenv install [version]` worked for me finally..

**Comment by wmpeng** [comment]
> using `RUBY_CONFIGURE_OPTS=--with-openssl-dir=/usr/local/Cellar/openssl/[latest version] rbenv install [version]` worked for me finally..

Works for me. macOS 10.14.6

**Comment by TorvaldsDB** [comment]
> using `RUBY_CONFIGURE_OPTS=--with-openssl-dir=/usr/local/Cellar/openssl/[latest version] rbenv install [version]` worked for me finally..

First, thank you so much. I failed at the  beginning because I copied the commands above guys' . You help me out of the trouble.

Here the exactly what we should do: 

```ruby
ls /usr/local/Cellar/openssl/
```

**Comment by garydamm** [comment]
I was having this issue with OSX 10.15.3. The version of openssl that homebrew installed was  1.1 and I was trying to install ruby 2.3.8, which did not work. 

I eventually got it to work using openssl version 1.0.2.

```RUBY_CONFIGURE_OPTS=--with-openssl-dir=/usr/local/Cellar/openssl/1.0.2 rbenv install 2.3.8```

**Comment by MilanVilov** [comment]
I had this issue and official rbenv documentation as well as installation of a new version of ruby (2.7.1) solved it.
https://github.com/rbenv/ruby-build/wiki#updating-ruby-build
