### ISSUE TITLE
rbenv: bundle: command not found

### ISSUE THREAD

**Issue by mhenrixon** [rbenv/ruby-build#419]
I am still experiencing this problem and I already tried the rbenv-rbx plugin but that doesn't do squat for me. 

> The `bundle' command exists in these Ruby versions:
>    2.0.0-p195
>    2.0.0-p247

I don't think this is a rubinius issue but rather a rbenv or ruby-build issue. What is your take on it?

On Mac OS X Mavericks with XCode 5 and latest rbenv/ruby-build through homebrew.

**Comment by StevenIseki** [comment]
This may be a bit naive as I am pretty new to ruby, but for me I just needed to run `gem install rails` to fix this error message after installing `ruby 2.4.0`
