### ISSUE TITLE
Error installing REE 1.8.7-2009.10 — ossl.c:119:1: error: unknown type name ‘STACK’

### ISSUE THREAD

**Issue by rwrrll** [rbenv/ruby-build#445]
Hi!

I'm trying to use this bad-ass tool to install REE 1.8.7-2009.10 (don't ask!) on our Ubuntu 13.04 Jenkins CI server. I appreciate that this Ruby version is mega-old, but I'm seriously stuck with trying to get it to compile and wondered if anyone had any clues?

I've cleared a couple of hurdles so far, but stumbled on the third. Here's where I've managed to get up to:

``` bash
jenkins@jenkins:~$ export CONFIGURE_OPTS="--no-tcmalloc -c --with-readline=/usr/share/readline"
jenkins@jenkins:~$ rbenv install ree-1.8.7-2009.10
Downloading ruby-enterprise-1.8.7-2009.10.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/3727eef7b6b1b2f31db7d091328d966e
Installing ruby-enterprise-1.8.7-2009.10...

BUILD FAILED

Inspect or clean up the working tree at /tmp/ruby-build.20131104122418.19336
Results logged to /tmp/ruby-build.20131104122418.19336.log

Last 10 log lines:
ossl_x509crl.c: In function ‘ossl_x509crl_get_revoked’:
ossl_x509crl.c:265:11: warning: pointer type mismatch in conditional expression [enabled by default]
ossl_x509crl.c:273:24: warning: pointer type mismatch in conditional expression [enabled by default]
/usr/bin/gcc -I. -I../.. -I../../. -I../.././ext/openssl -DRUBY_EXTCONF_H=\"extconf.h\" -I/var/lib/jenkins/.rbenv/versions/ree-1.8.7-2009.10/include   -I/var/lib/jenkins/.rbenv/versions/ree-1.8.7-2009.10/include  -fPIC -g -Os -fno-strict-aliasing    -c ossl.c
ossl.c:118:1: error: unknown type name ‘STACK’
ossl.c:119:1: error: unknown type name ‘STACK’
make[1]: *** [ossl.o] Error 1
make[1]: Leaving directory `/tmp/ruby-build.20131104122418.19336/ruby-enterprise-1.8.7-2009.10/source/ext/openssl'
make: *** [all] Error 1
```

I have `libssl-dev` installed, and `/usr/include/openssl/stack.h` is present, but I just can't figure out how to get it recognised (if that's even the right answer!)

I can compile other rubies OK (e.g., 2.0.0-p247 is running like a dream). I found some solutions for RVM, but nothing for rbenv / ruby-build. Any ideas how I might get past this problem?

Thanks in advance,
Richard

**Comment by ganar** [comment]
@mislav your contribution is a godsend!

I want it to add that this also works with RVM in a simpler way and without errors. In my case it was 

`rvm install ruby-1.8.7-p249 --patch https://github.com/wayneeseguin/rvm/raw/187ab4c/patches/ree/1.8.6/openssl-1.0.patch --patch https://github.com/wayneeseguin/rvm/raw/187ab4cc/patches/ree/1.8.7/no_sslv2.diff`

your second patch gave me the following result during installation

`Patch no_sslv2 was already applied.`

**Comment by specialforest** [comment]
I combined both patches into a single one to be used with rbenv - https://gist.github.com/specialforest/d74b772eda5058a0f680f52d6e75bc4e/raw/004b9a457a92640d62b67a4828c6a7dd3c616d50/ruby-1.8.7.patch

cat ruby-1.8.7.patch | rbenv -p install 1.8.7

Successfully built Ruby 1.8.7 on Ubuntu 16.04.
