### ISSUE TITLE
OS X compile hangs indefinitely when using MacPorts' gcc

### ISSUE THREAD

**Issue by mislav** [rbenv/ruby-build#472]
Reported by @jackrg in https://github.com/sstephenson/rbenv/issues/498#issuecomment-29675233

> I think I figured this out.  The fundamental problem was that I had MacPorts installed (along with HomeBrew), and MacPorts’ GCC compiler was in front of HomeBrew’s.  Once I removed MacPorts, the problem went away and Ruby built okay.

It might be a good idea to try to detect MacPorts' compiler ourselves and abort the build until the user removes MacPorts or at least removes the compiler from PATH.

**Comment by hsbt** [comment]
I couldn't reproduce GCC of MacPorts on El Capitan.

```
$ RUBY_CONFIGURE_OPTS="--with-openssl-dir=/opt/local" CC=/opt/local/bin/gcc-mp-5 rbenv install 2.3.4
Downloading ruby-2.3.4.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.4.tar.bz2
Installing ruby-2.3.4...
Installed ruby-2.3.4 to /Users/hsbt/.anyenv/envs/rbenv/versions/2.3.4
```
