### ISSUE TITLE
Fail to install jruby-1.6.8

### ISSUE THREAD

**Issue by fuse** [rbenv/ruby-build#513]
I'm using rbenv 0.4.0, trying to install jruby-1.6.8 on Mavericks.

I've got almost the same issue as described here: #324 
Also, I've been able to install jruby-1.7.9 without any problem.

```
x jruby-1.6.8/tool/nailgun/configure
/var/folders/dy/6jbqq91x65b5lsp2n4xblsdr0000gn/T/ruby-build.20140222085625.74067/jruby-1.6.8 /var/folders/dy/6jbqq91x65b5lsp2n4xblsdr0000gn/T/ruby-build.20140222085625.74067 ~/tmp
JRuby limited openssl loaded. http://jruby.org/openssl
gem install jruby-openssl for full support.
LoadError: OpenSSL::SSL requires the jruby-openssl gem
                          (root) at /usr/local/opt/rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/shared/jruby/openssl/autoloads/ssl.rb:8
                        use_ssl= at /usr/local/opt/rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/shared/jruby/openssl/autoloads/ssl.rb:124
```

**Comment by calamitas** [comment]
Also getting a comparable error on Yosemite with the latest ruby-build from Homebrew (version 20150319zf).

    >> rbenv install jruby-1.6.8
    Downloading jruby-bin-1.6.8.tar.gz...
    -> http://dqw8nmjcqpjn7.cloudfront.net/e3b05f9cf0ba9b02e6cba75d5b62e2abf8ac7a4483c3713dc4eb83e3b8b162d4
    Installing jruby-1.6.8...
    
    BUILD FAILED (OS X 10.10.2 using ruby-build 20150319zf)
    
    Inspect or clean up the working tree at /var/folders/tw/9rgplx_55x1bdksz8gqby7km0000gn/T/ruby-build.20150325093018.37248
    Results logged to /var/folders/tw/9rgplx_55x1bdksz8gqby7km0000gn/T/ruby-build.20150325093018.37248.log

Contents of the log file:

    /var/folders/tw/9rgplx_55x1bdksz8gqby7km0000gn/T/ruby-build.20150325093018.37248 <sensitive folder name>
    HTTP/1.1 200 OK
    Content-Type: binary/octet-stream
    Content-Length: 15705394
    Connection: keep-alive
    Date: Wed, 25 Mar 2015 08:06:25 GMT
    Last-Modified: Fri, 23 May 2014 08:39:55 GMT
    ETag: "a76ac5845640e4a1ebdfa74421efc935"
    Accept-Ranges: bytes
    Server: AmazonS3
    Age: 1433
    X-Cache: Hit from cloudfront
    Via: 1.1 694067e538aff1de3d804656c0b75883.cloudfront.net (CloudFront)
    X-Amz-Cf-Id: nH272xEHZh8w6NZAOfkiogwBK_dXIm-N_I7Xa3Dn_HbXRfnrpV-5Kg==
    
    /var/folders/tw/9rgplx_55x1bdksz8gqby7km0000gn/T/ruby-build.20150325093018.37248/jruby-1.6.8 /var/folders/tw/9rgplx_55x1bdksz8gqby7km0000gn/T/ruby-build.20150325093018.37248 <sensitive folder name>
    JRuby limited openssl loaded. http://jruby.org/openssl
    gem install jruby-openssl for full support.
    LoadError: OpenSSL::SSL requires the jruby-openssl gem
                              (root) at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/shared/jruby/openssl/autoloads/ssl.rb:8
                            use_ssl= at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/shared/jruby/openssl/autoloads/ssl.rb:124
      configure_connection_for_https at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/remote_fetcher.rb:352
                      connection_for at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/remote_fetcher.rb:328
                             request at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/remote_fetcher.rb:418
                          fetch_http at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/remote_fetcher.rb:210
                                send at org/jruby/RubyKernel.java:2117
                          fetch_path at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/remote_fetcher.rb:243
                          load_specs at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/spec_fetcher.rb:265
                          load_specs at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/maven_gemify.rb:72
                                list at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/spec_fetcher.rb:237
                                each at org/jruby/RubyArray.java:1620
                                list at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/spec_fetcher.rb:233
                                list at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/maven_gemify.rb:63
           find_matching_with_errors at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/spec_fetcher.rb:156
           find_matching_with_errors at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/maven_gemify.rb:54
                   fetch_with_errors at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/spec_fetcher.rb:89
              find_gems_with_sources at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/dependency_installer.rb:110
       find_spec_by_name_and_version at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/dependency_installer.rb:228
                             install at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/dependency_installer.rb:259
                             execute at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/commands/install_command.rb:121
                                each at org/jruby/RubyArray.java:1620
                             execute at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/commands/install_command.rb:115
                              invoke at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/command.rb:278
                        process_args at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/command_manager.rb:147
                                 run at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/command_manager.rb:117
                                 run at /Users/peter/.rbenv/versions/jruby-1.6.8/lib/ruby/site_ruby/1.8/rubygems/gem_runner.rb:65
                              (root) at gem:21

It looks like it tries to install a gem and that fails. Given that this fails, it is likely that installing the jruby-openssl gem will also fail.

Could this have something to do with rubygems.org moving to https? Maybe the installation installs a Rubygems version that uses https and JRuby can't handle https out of the box?

Note that the install actually fails, so nothing gets installed in the end.

I've got JRuby 1.6.8 running inside a Docker container using a Dockerfile based on https://github.com/cpuguy83/docker-jruby/blob/68e55e5eaf8f8159ade4a305df0fd65f633493ae/1.7/jre/Dockerfile. The installed version can be fixed up afterwards to work including an install of the openssl gem. However, it is excruciatingly slow (Rails requests that normally take fractions of a second take minutes), so I want to run it on my Mac but in that case I'd rather install it cleanly with ruby-build.

**Comment by calamitas** [comment]
Just for reference, what I ended up doing was edit my .gemrc so all sources use http instead of https, then install jruby 1.6.8 through ruby-build, then install the jruby-openssl gem for the just installed jruby version, then undo my edit of my .gemrc.

**Comment by mislav** [comment]
> what I ended up doing was edit my .gemrc so all sources use http instead of https

Thanks for the tip solving that chicken-egg problem. This smells like an oversight in JRuby's build system. Hopefully the 1.7.x and 9000 release series don't suffer from the same problem.

I'm going to eventually close this as a problem with JRuby 1.8 and not a problem with ruby-build, unless someone has an idea for a workaround we can easily implement in ruby-build.

**Comment by calamitas** [comment]
FYI, rubygems now automatically redirects to HTTPS, so my trick above no longer works.

**Comment by hsbt** [comment]
This issue related JRuby 1.6.x and osx 10.9.x. This environments are EOL status. We can't triage and investigate it.
