### ISSUE TITLE
Please list ruby core optional dependencies in the documentation

### ISSUE THREAD

**Issue by a1exsh** [rbenv/ruby-build#557]
Installed ruby-1.9.3 using rbenv+ruby-build on a clean system today.

Problems:
1. The `gem` command is broken due to missing `zlib` (e.g. `gem update --system`)
2. The `irb` prompt is less functional than used to be due to lack of readline support.

Fixed by installing dev packages for zlib and libreadline, then re-installing the ruby version (had to do that two times actually: first for zlib, then discovered that `irb` problem--not nice.)

It would be really nice if you mention these as caveats in the documentation (by the way, I believe libssl is another optional dependency of ruby core, but I can't find the definitive list ATM, guess checking ./configure options in ruby source tree would be it.)

**Comment by mislav** [comment]
Closing as outdated
