### ISSUE TITLE
OSX - Can't install ruby 2.1.2 through rbenv even after brew update

### ISSUE THREAD

**Issue by davidjconnolly** [rbenv/ruby-build#569]
I wasn't able to get 2.1.2 to show up on rbenv install -l for some reason.  I'm running OSX 10.9.2 with homebrew.

I followed the following steps:
1. brew update
2. brew upgrade rbenv ruby-build
3. ran rbenv install -l but 2.1.2 wasn't an option
4. went to ~/.rbenv/plugins/ruby-build/ and did a git pull and everything worked fine

I suspect I've messed up the linkage with homebrew somehow but I'm not sure what to do to fix it.  Any suggestions?

**Comment by symmetriccurve** [comment]
This helped me https://stackoverflow.com/questions/26183787/upgrading-to-ruby-2-1-3-on-mac-osx-10-9-5
