### ISSUE TITLE
parse a ruby mirror for new ruby versions and dynamicaly find new releases (optionally as fallback)

### ISSUE THREAD

**Issue by kiranos** [rbenv/ruby-build#578]
There are ruby mirrors: http://www.mirrorservice.org/sites/ftp.ruby-lang.org/pub/ruby/ why not parse these when you search for a ruby version and if it finds one it donwloads and compiles. I feel this is a much better approach then having to update ruby-build to get new versions.

(nvm - node version managed does this with nodes http://nodejs.org/dist/ )

**Comment by jasonkarns** [comment]
I realize this is an old issue, but I thought I'd share the way that [node-build](https://github.com/OiNutter/node-build) solves this issue.

We have a scraper that generates build definitions using dist listings that nodejs.org and iojs.org publish on their website. We've extracted this scraper into a plugin of its own: https://github.com/jasonkarns/node-build-update-defs

This plugin is used from node-build by the maintainers when adding new definitions to node-build itself. However, the plugin allows end users to scrape new versions themselves, without waiting for a node-build release. The plugin writes the definitions that it scrapes into its own `share/node-build` directory, which as a nodenv plugin itself, is included in the lookup path by node-build.

**Comment by mislav** [comment]
I'm interested in exploring this direction, especially for Rubinius at first which has releases daily and we can't keep up with definitions.

**Comment by jasonkarns** [comment]
I'd be willing to fork node-build-update-defs plugin for ruby, if someone wants to contribute the rubinius scraper.

**Comment by jasonkarns** [comment]
@mislav forked [node-build-update-defs](https://github.com/jasonkarns/node-build-update-defs) to [ruby-build-update-defs](https://github.com/jasonkarns/ruby-build-update-defs)

I've removed the nodejs/iojs scrapers, so the plugin won't work until there are some scrapers added. Opened an issue to create a rubinius scraper for whomever wants to tackle it. https://github.com/jasonkarns/ruby-build-update-defs/issues/1

**Comment by mislav** [comment]
Solid ideas in this thread, but I'm closing this in favor of a much more feasible and straightforward approach described in https://github.com/rbenv/ruby-build/issues/1194. No guarantees that we will take that one either, but it's worth considering.
