### ISSUE TITLE
Installing Ruby 2.0.0-p353 in Ubuntu 14.04

### ISSUE THREAD

**Issue by duaneadam** [rbenv/ruby-build#587]
I am using rbenv & here's the command I use to install ruby 2.0.0-p353:
rbenv install 2.0.0-p353

I can install ruby-p481 but not p353. The project I am working is using p353. 

I installed everything based on this guide:
https://gorails.com/setup/ubuntu/14.04

Error message:
Inspect or clean up the working tree at /tmp/ruby-build.20140619095720.18187
Results logged to /tmp/ruby-build.20140619095720.18187.log

Last 10 log lines:
compiling ossl_pkey.c
compiling ossl_engine.c
compiling ossl_hmac.c
compiling ossl_x509.c
compiling ossl_x509attr.c
installing default openssl libraries
linking shared-object openssl.so
make[2]: Leaving directory `/tmp/ruby-build.20140619095720.18187/ruby-2.0.0-p353/ext/openssl'
make[1]: Leaving directory`/tmp/ruby-build.20140619095720.18187/ruby-2.0.0-p353'
make: **\* [build-ext] Error 2

**Comment by gabriella4c** [comment]
This will possibly save hours for anyone wanting to get Ruby 2.0.0-p353 installed without upgrading the patch version, tested on Ubuntu 14.04.

Of course you should check the code first before running external scripts in your PC.

```
curl -fsSL https://gist.githubusercontent.com/gabriella4c/a5c6783e5ced651551e74c3cb6dbb50a/raw/ca12f1c9091f216ea49806279fc3a8353a14efd7/ruby-2.0.0-p353-readline.patch | rbenv install --patch 2.0.0-p353
```
