### ISSUE TITLE
Fails to install 1.9.2 on Yosemite

### ISSUE THREAD

**Issue by chrise86** [rbenv/ruby-build#648]
Running `rbenv install 1.9.2-p330`:

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
couldn't understand kern.osversion `14.0.0'
Downloading ruby-1.9.2-p330.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/23ef45fdaecc5d6c7b4e9e2d51b23817fc6aa8225a20f123f7fa98760e8b5ca9
Installing ruby-1.9.2-p330...

BUILD FAILED (OS X 10.10 using ruby-build 20140926)

Inspect or clean up the working tree at /var/folders/f5/10yx8t4j7vx3rx7lff6jfpxr0000gn/T/ruby-build.20141007124752.9733
Results logged to /var/folders/f5/10yx8t4j7vx3rx7lff6jfpxr0000gn/T/ruby-build.20141007124752.9733.log

Last 10 log lines:
couldn't understand kern.osversion `14.0.0'
ld: warning: directory not found for option '-L/Users/chrisedwards/.rbenv/versions/1.9.2-p330/lib'
./miniruby -I./lib -I.ext/common -I./- -r./ext/purelib.rb  ./tool/generic_erb.rb -c -o encdb.h ./template/encdb.h.tmpl ./enc enc
miniruby(17709,0x7fff7c00a300) malloc: *** error for object 0x100801808: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
miniruby(17708,0x7fff7c00a300) malloc: *** error for object 0x100801808: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
make: *** [.rbconfig.time] Abort trap: 6
make: *** Waiting for unfinished jobs....
make: *** [encdb.h] Abort trap: 6
```

**Comment by MarcoDeBortoli** [comment]
Hey everyone, what's the current status of this? Anyone succeeded eventually or we should just give up? 

[This](https://gist.github.com/MarcoDeBortoli/b680f5853bda4d1a1fc1) is the error I'm currently getting with any 1.9.2 regardless the patch level. Also 1.9.2 is the only one that seem affected, previous versions down to 1.8.6 compiles just fine.

The same error is spat out with a previously compiled 1.9.2-p330 that I installed and still have on my system from before Yosemite.

I hope it helps.

**Comment by chrisRidgers** [comment]
I'm still having issues with this currently.  Does anyone have a working solution?

**Comment by mislav** [comment]
Sometimes a working solution gets reported but it doesn't work consistently. A much better course of action for you would be to upgrade your project to latest 1.9.3. Are you unable to do that?

**Comment by chrisRidgers** [comment]
As it turns out I am, but the documentation on Veewee is currently (I'm about to submit a pull request) unclear about supported versions of ruby.  As it currently stands, only 1.9.2-p320 is currently mentioned.

**Comment by MarcoDeBortoli** [comment]
@chrisRidgers the problem is not with Veewee documentation or anything it's a deeper problem related to OSX Yosemite and ruby itself. People who don't have Yosemite are still able to compile this without any issue.

**Comment by chrisRidgers** [comment]
Fair point, I only mentioned the Veewee documentation because it's through that project that I've ended up here looking for a solution.

As it turns out, Veewee's current supported version is 2.2.0.  Had the documentation said as much I wouldn't have had issues :p

**Comment by MarcoDeBortoli** [comment]
I know you meant well, I just wanted to clarify to be thorough

**Comment by fro** [comment]
I've just spent a lot of time to figure how to handle this without luck.
I'm trying to install ruby 1.9.2-p0 on Yosemite. I've tried `brew tap homebrew/dupes ; brew install apple-gcc42`

Here's the config.log: 
https://gist.github.com/fro/cb761a1f41275cbccb2a

Does someone has succeeded in installing 1.9.2-p0 on Yosemite?

**Comment by MarcoDeBortoli** [comment]
@fro as I mentioned already the answer is simple, you can't.

**Comment by fro** [comment]
@MarcoDeBortoli Then, I'll switch to `1.9.3`, thanks.

**Comment by MarcoDeBortoli** [comment]
@fro yeah, that's the only solution unfortunately, it's problem with Yosemite itself that cannot be resolved or even if it can it's not worth the effort

**Comment by martinwells** [comment]
This worked for me:

    brew install gcc48
    CC=/usr/local/Cellar/gcc48/4.8.4/bin/gcc-4.8 rvm install 1.9.3

**Comment by MarcoDeBortoli** [comment]
@martinwells that's ruby 1.9.3, the problem is with ruby 1.9.2
