### ISSUE TITLE
Build of Ruby 2.1.3 is stuck on Debian

### ISSUE THREAD

**Issue by andreypanin** [rbenv/ruby-build#650]
I'm having troubles with installation of Ruby 2.1.3.

I execute 'rbenv install -v 2.1.3' and some time later I see the same message printed out infinitely:

```
...
make: Warning: File `common.mk' has modification time 1.3e+06 s in the future
make: Warning: File `common.mk' has modification time 1.3e+06 s in the future
make: Warning: File `common.mk' has modification time 1.3e+06 s in the future
make: Warning: File `common.mk' has modification time 1.3e+06 s in the future
make: Warning: File `common.mk' has modification time 1.3e+06 s in the future
^C
BUILD FAILED (Debian 7.6 using ruby-build 20140926)

Inspect or clean up the working tree at /tmp/ruby-build.20140827094234.11278
Results logged to /tmp/ruby-build.20140827094234.11278.log
```

uname says:
`Linux debian 3.2.0-4-686-pae #1 SMP Debian 3.2.60-1+deb7u3 i686 GNU/Linux`

What could be the issue here?

**Comment by AnushaBalivada** [comment]
Hello,

I wanted to provide an update to this.

I am using Ubuntu 14.04 LTS (64-bit) via VMPlayer. I tried using <pre><code>rbenv install 2.1.3</code></pre> but it was just stuck.

Followed the suggestion in [this](https://github.com/sstephenson/ruby-build/issues/642) thread, tried  <pre><code>CC=clang rbenv install 2.1.3</code></pre>.
The error provided was that C Compiler was not working. Detailed logs were stored in <pre><code>config.log</code></pre> in the following path <pre><code>/tmp/ruby-build.<date-time>.xxxxx/ruby-2.1.3/</code></pre>

Log proved to be useful. <pre><code>clang</code></pre> was missing. Installed it.

However, rbenv install 2.1.3 still did not work. CC=clang rbenv install 2.1.3 worked.

I hope this helps.

Thank you.

**Comment by Mehonoshin** [comment]
I've solved problem like @cykhoo. Just to setup correct time in system

**Comment by hsbt** [comment]
I couldn't reproduce Debian 7.11 and Ruby 2.1.10.

```
$ rbenv install 2.1.10
Downloading ruby-2.1.10.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.10.tar.bz2
Installing ruby-2.1.10...

WARNING: ruby-2.1.10 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.

Installed ruby-2.1.10 to /home/hsbt/.rbenv/versions/2.1.10

```
