### ISSUE TITLE
Need to prevent MRI from using gcc-4.2 on Yosemite

### ISSUE THREAD

**Issue by mislav** [rbenv/ruby-build#651]
Newer MRI installs are broken on Yosemite for people who have Homebrew `apple-gcc42` installed. Previously MRIs would find `gcc-4.2` in PATH and use it over `/usr/bin/gcc`/clang and it would be fine either way, but that doesn't work in Yosemite for some reason.

The workaround is easy: set `CC=/usr/bin/gcc` or `CC=clang` for the build and Ruby will use clang instead of detecting `gcc-4.2` in PATH.

We can't expect each person to figure this out by themselves. I propose that on Yosemite we default to CC=clang for MRI >= 1.9.3-p0 if an explicit `CC` wasn't set.

Original issue: https://github.com/sstephenson/rbenv/issues/610

/cc @hsbt @jeremy

**Comment by sahilbathla** [comment]
+1
