### ISSUE TITLE
Building Ruby on Yosemite with multiple filesystems fails

### ISSUE THREAD

**Issue by smace** [rbenv/ruby-build#673]
I'm not able to build ruby 2.1.5 on OS X 10.10.1, installed rbenv and ruby-build via homebrew. I have a slightly different error message (from others issues found) :

Installing ruby-2.1.5...

```
BUILD FAILED (OS X 10.10.1 using ruby-build 20141113)

Inspect or clean up the working tree at /var/folders/5p/gr83jg696c3267_bjg5tcpnr0000gn/T/ruby-build.20141119200519.529
Results logged to /var/folders/5p/gr83jg696c3267_bjg5tcpnr0000gn/T/ruby-build.20141119200519.529.log

Last 10 log lines:

/var/folders/5p/gr83jg696c3267_bjg5tcpnr0000gn/T/ruby-build.20141119200519.529/ruby-2.1.5 /var/folders/5p/gr83jg696c3267_bjg5tcpnr0000gn/T/ruby-build.20141119200519.529 ~
checking build system type... x86_64-apple-darwin14.0.0
checking host system type... x86_64-apple-darwin14.0.0
checking target system type... x86_64-apple-darwin14.0.0
checking whether the C compiler works... no
configure: error: in `/var/folders/5p/gr83jg696c3267_bjg5tcpnr0000gn/T/ruby-build.20141119200519.529/ruby-2.1.5':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.
```

I have already tried many different command like:  `CC=clang rbenv install 2.1.5`

**Comment by hkmurari** [comment]
->http://dqw8nmjcqpjn7.cloudfront.net/4305cc6ceb094df55210d83548dcbeb5117d74eea25196a9b14fa268d354b100
i got this error during installation of ruby 2.1.5 on ubuntu 14.04..please help

**Comment by RubyCreative** [comment]
Hi i am having a similar problem, especially creating the right development environment i need for the tutorial projects that i am working on "learning". Any help guys would be much appreciated. Thanks

Daniels-iMac:~ rubycreative$ rbenv install 2.0.0-p353
Downloading yaml-0.1.6.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/7da6971b4bd08a986dd2a61353bc422362bd0edcc67d7ebaac68c95f74182749
Installing yaml-0.1.6...

BUILD FAILED (OS X 10.10.1 using ruby-build 20150226-3-g0901e41)

Inspect or clean up the working tree at /var/folders/dk/d5tcfyvd2fg92k6p4p_1hj1m0000gp/T/ruby-build.20150301142712.40263
Results logged to /var/folders/dk/d5tcfyvd2fg92k6p4p_1hj1m0000gp/T/ruby-build.20150301142712.40263.log

Last 10 log lines:
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/var/folders/dk/d5tcfyvd2fg92k6p4p_1hj1m0000gp/T/ruby-build.20150301142712.40263/yaml-0.1.6':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.
Daniels-iMac:~ rubycreative$

**Comment by mislav** [comment]
Does everyone in this thread have multiple disks mounted on the filesystem and one of them is mounted as the home directory?

**Comment by sman591** [comment]
I believe I have the same issue here - two filesystems, one of them is mounted as my home directory. What's the solution?

**Comment by sman591** [comment]
This seem to have fixed itself when I ran `export RBENV_ROOT=/usr/local/var/rbenv`... but why? I've always used `~/.rbenv`

**Comment by mislav** [comment]
Compiling Ruby on one filesystem and installing it to another doesn't seem to work. In your case, Ruby gets compiled in `/tmp` but installed under `~/.rbenv/versions` which is in your home directory and thus on a separate filesystem.

To work around your problem, you could try something like:

```
TMPDIR="${HOME}/tmp" rbenv install ...
```

**Comment by sman591** [comment]
@mislav Makes sense, though resulted in a separate error:

> checking whether the C compiler works... no
configure: error: in '/Volumes/Macintosh HD/Users/stuart/tmp/ruby-build.20151112160133.88984/ruby-2.2.3':
> configure: error: C compiler cannot create executables
> See 'config.log' for more details

**Comment by mislav** [comment]
@sman591 That's really weird. I have no idea what's going on there.

**Comment by hsbt** [comment]
macOS 10.10 is EOL now.
