### ISSUE TITLE
rbenv install --list does not include all versions from ruby-build --definitions

### ISSUE THREAD

**Issue by waynehiner** [rbenv/ruby-build#676]
I am trying to install Ruby 2.1.5 on Mac OS X 10.10.1.  I installed rbenv and ruby-build via Homebrew and I have upgraded both to the latest versions (0.4.0 for rbenv, 20141113 for ruby-build).
The output for rbenv install --list for regular Ruby stops at 2.1.0-preview1.
The output for ruby-build --definitions goes all the way to 2.2.10.
It looks like rbenv install <version.no> should just call ruby-build <version.no> <install-path>, so there should not be a conflict.
Is there something to do to update rbenv install to be sure that all definitions of ruby-build are available?
Many thanks.

**Comment by wilferrel** [comment]
@mislav I don't have a plugins folder in .rbenv directory. Any advise?

**Comment by mislav** [comment]
@wilferrel Do you have the same problem: `rbenv install --list` not being equal to `ruby-build --definitions`? Can you post the result of the following:

1. ``ls `rbenv root`/plugins``
2. `which -a ruby-build rbenv-install`

Thank you

**Comment by mattgraham** [comment]
My alternative to removing the directory all together was to add an alias to my dot files: 

```
alias rbenv-update='cd ~/.rbenv/plugins/ruby-build/ && git pull'
```

however, not to promise this will include the bleeding edge builds.

**Comment by vadimeremeev** [comment]
Removing ~/.rbenv/plugins/ruby-build help me too. Thanks.

**Comment by Sheval** [comment]
Thank you. It works for me too.

**Comment by miriammuros** [comment]
Removing ~/.rbenv/plugins/ruby-build help me too. Thank so much!

**Comment by samueleaton** [comment]
When I originally install rbenv with homebrew, homebrew said: 
`To use Homebrew's directories rather than ~/.rbenv add to your profile:`
`export RBENV_ROOT=/usr/local/var/rbenv`

I removed that line from my profile and then removed any signs of rbenv in the `/usr/local/var` directory. 

Now when I do `echo $(rbenv root)` you should get  `/Users/<username>/.rbenv` instead of `/usr/local/var/rbenv`.

Now everything works fine.

**Comment by timomod** [comment]
Think I have the problem described above. How do I remove ~/.rbenv/plugins/ruby-build ?

**Comment by Bahanix** [comment]
*Sorry for the late post*

Homebrew is only available on OSX. Another solution is to updage your ruby-build plugin.

```sh
cd ~/.rbenv/plugins/ruby-build/
git pull origin master
cd -
rbenv install -l
```

It should work on any patform.

**Comment by anaumov** [comment]
If you install ruby-build not as a plugin, you can do so
```
brew update
brew upgrade ruby-build
```

**Comment by qmclaugh** [comment]
> If you install ruby-build not as a plugin, you can do so
> 
> ```
> brew update
> brew upgrade ruby-build
> ```

Yes, under a homebrew install of ruby-build the ~/.rbenv/plugins directory doesn't exist.  This solves the issue for that case.  Thank you!

**Comment by Dkilpatrick31** [comment]
> _Sorry for the late post_
> 
> Homebrew is only available on OSX. Another solution is to updage your ruby-build plugin.
> 
> ```shell
> cd ~/.rbenv/plugins/ruby-build/
> git pull origin master
> cd -
> rbenv install -l
> ```
> 
> It should work on any patform.

Thank you! this worked perfectly.

**Comment by rgp** [comment]
Not anymore, I do not have that directory (nor the plugins dir)

**Comment by danielmyasnikov** [comment]
For devops engineers and these ones who can't find ruby-build, here is the readme file:

https://github.com/rbenv/ruby-build#installation

Worked for me :)

**Comment by dvodvo** [comment]
@Dkilpatrick31   context: OS X mavericks with homebrew.  Homebrew is understandably complaining about me not succumbing to OS churn [gulp] tyranny.  Going to that directory and pulling assumes the directory was set as a git repository.
@danielmyasnikov 's suggestion works immediate wonders.  I can now toy  (and keep focus) with 2.7.2 and 3.0.0 on a stable OS.
