### ISSUE TITLE
rbenv install 2.2.0 failed

### ISSUE THREAD

**Issue by qiang123** [rbenv/ruby-build#691]
ubuntu 14.04 64bit
Where the error happened:

linking shared-object fiddle.so
/usr/bin/ld: ./libffi-3.2.1/.libs/libffi.a(raw_api.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
./libffi-3.2.1/.libs/libffi.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [../../.ext/x86_64-linux/fiddle.so] Error 1
make[2]: Leaving directory`/tmp/ruby-build.20141226145342.42365/ruby-2.2.0/ext/fiddle'
make[1]: **\* [ext/fiddle/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
linking shared-object bigdecimal.so
make[2]: Leaving directory `/tmp/ruby-build.20141226145342.42365/ruby-2.2.0/ext/openssl'
make[2]: Leaving directory`/tmp/ruby-build.20141226145342.42365/ruby-2.2.0/ext/bigdecimal'
linking shared-object nkf.so
make[2]: Leaving directory `/tmp/ruby-build.20141226145342.42365/ruby-2.2.0/ext/nkf'
linking shared-object psych.so
make[2]: Leaving directory`/tmp/ruby-build.20141226145342.42365/ruby-2.2.0/ext/psych'
linking shared-object date_core.so
make[2]: Leaving directory `/tmp/ruby-build.20141226145342.42365/ruby-2.2.0/ext/date'
linking shared-object ripper.so
make[2]: Leaving directory`/tmp/ruby-build.20141226145342.42365/ruby-2.2.0/ext/ripper'
make[1]: Leaving directory `/tmp/ruby-build.20141226145342.42365/ruby-2.2.0'
make: **\* [build-ext] Error 2

**Comment by craft37** [comment]
Have same issue on Ubuntu 15.04 Alpha

$ RUBY_CONFIGURE_OPTS=--enable-shared rbenv install 2.2.0 Downloading ruby-2.2.0.tar.gz... -> http://dqw8nmjcqpjn7.cloudfront.net/7671e394abfb5d262fbcd3b27a71bf78737c7e9347fa21c39e58b0bb9c4840fc Installing ruby-2.2.0...

BUILD FAILED (Ubuntu 15.04 using ruby-build 20150116-6-g7f1d8df)

Inspect or clean up the working tree at /tmp/ruby-build.20150122215659.9399 Results logged to /tmp/ruby-build.20150122215659.9399.log

Last 10 log lines: from /tmp/ruby-build.20150122215659.9399/ruby-2.2.0/lib/rubygems.rb:556:in install' from ./tool/rbinstall.rb:717:inblock (2 levels) in ' from ./tool/rbinstall.rb:716:in each' from ./tool/rbinstall.rb:716:inblock in ' from ./tool/rbinstall.rb:749:in call' from ./tool/rbinstall.rb:749:inblock in ' from ./tool/rbinstall.rb:746:in each' from ./tool/rbinstall.rb:746:in' uncommon.mk:244: recipe for target 'do-install-all' failed make: *** [do-install-all] Error 1

**Comment by naskoblg** [comment]
Same issue with 2.2.1 on FreeBSD 9.3-STABLE
I was able to fix it with:
1. Using clang
2. make.conf
CC=clang
CXX=clang++
CPP=clang-cpp
CFLAG=-fPIC
3. RUBY_CONFIGURE_OPTS=--enable-shared
