### ISSUE TITLE
ruby 2.2.0 fails to build on Ubuntu

### ISSUE THREAD

**Issue by ivar** [rbenv/ruby-build#695]
I haven't been able to compile Ruby 2.2.0 using ruby-build as a plugin to rbenv.
This is using ruby-build from master, commit 45b75ed on Ubuntu 14.04.1 LTS
The error appears to be: `relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC ./libffi-3.2.1/.libs/libffi.a: error adding symbols: Bad value`

Here is the log file: https://gist.github.com/ivar/b595ca0dd03314c96b7a

(edit: I'm running ubuntu 14.04.1 in a virtual machine and originally posted this issue as having occured in my host machine as opposed to VM)

```
> gcc --version
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
```

**Comment by lucascaton** [comment]
It might help: http://stackoverflow.com/questions/27915581/error-with-rbenv-install-2-2-0
