### ISSUE TITLE
curl commands get -q passed to them ignoring proxy settings

### ISSUE THREAD

**Issue by stewartmatheson** [rbenv/ruby-build#704]
Hi I noticed that curl gets called with -q. This means that my proxy settings in .curlrc get ignored. Does this mean that curl can't connect using a proxy when called by ruby-build? I can understand why you would want to ignore any other settings however would it be possible to respect proxy settings? What about reading HTTP_PROXY from the env?

**Comment by mislav** [comment]
There has already been a report of this: https://github.com/sstephenson/rbenv/issues/652

It could be a good idea to respect proxy settings from curlrc, but ignore other settings. Setting `http_proxy` or `HTTP_PROXY` should work, however. Did you try it?

**Comment by stewartmatheson** [comment]
Yes curl does respect these values. Unlike windows you have to run 'source' to populate environment variables outside of a script. That caught me out. So -q is not an issue for proxy users as you can just set HTTP_PROXY and http_proxy before running any ruby-build commands. I would be surprised if wget did not work in the same way. That said I don't think this is really an issue. Is there another reason to respect .curlrc?

**Comment by jasonkarns** [comment]
As of f998f10597931551bf12d0e9872a3dce58aed1c5, one can also set additional options to be passed to curl via `CURL_OPTS`. Since proxies in particular can be set via `HTTP_PROXY` and other curl options set in general via `CURL_OPTS`, can we consider this closed?

**Comment by mislav** [comment]
Yes, I'm going to close this due to there being sufficient options to configure curl and wget via environment variables.

I'm not 100% sure why this project initially chose to explicitly avoid reading curlrc and wgetrc files, but I'm guessing that we wanted to shield ourselves from people's weird configs that could negatively affect ruby-build downloads.
