### ISSUE TITLE
can't install JRuby 1.7.19

### ISSUE THREAD

**Issue by rosenfeld** [rbenv/ruby-build#718]
I get this message everytime I try to install it:

```
$ rbenv install jruby-1.7.19
Downloading jruby-bin-1.7.19.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/8e34f8a94bb6abedc0f6f9d0cc174b4fadc78a50fb44804c16f19bf8f2586d5d
Installing jruby-1.7.19...

BUILD FAILED (Debian 8.0 using ruby-build 20150130)

Inspect or clean up the working tree at /tmp/ruby-build.20150202104828.3290
Results logged to /tmp/ruby-build.20150202104828.3290.log

Last 10 log lines:
Accept-Ranges: bytes
Server: AmazonS3
Age: 1850
X-Cache: Hit from cloudfront
Via: 1.1 80cbee2e9466cbd1efb2c4fd759a28ea.cloudfront.net (CloudFront)
X-Amz-Cf-Id: ljZMINKVvpshhAI_vOIbScpzA_gSOe-uj-dWkvE_U5p_q1BsZoSOrA==

/tmp/ruby-build.20150202104828.3290/jruby-1.7.19 /tmp/ruby-build.20150202104828.3290 ~/.rbenv/plugins/ruby-build
ERROR:  While executing gem ... (ArgumentError)
    marshal data too short
```

Any ideas on what could be causing this?

**Comment by rosenfeld** [comment]
I believe this is caused by this JRuby issue when using mode 2.0, as I have `compat.version=2.0` in my ~/.jrubyrc:

https://github.com/jruby/jruby/issues/2457

Commenting it allowed me to install JRuby correctly.

Unless you think ruby-build should force the compat version to 1.9 in order to install this JRuby version you can close this issue. Or maybe you could simply detect the version mode somehow during the install and warn the user that 2.0 is not supported for installing JRuby yet...

**Comment by mislav** [comment]
Nasty issue. Thanks for letting us know. Not sure if it's worth the trouble trying to work around this issue. Maybe just wait for the next JRuby release?

**Comment by mislav** [comment]
@rosenfeld What environment variable or build flag could we set to override compat mode from your `jrubyrc`?

**Comment by rosenfeld** [comment]
Hi @mislav, I'm not really sure what would be the best way to deal with this. I've just made this test with jrubyrc setting the default compat version to 2.0.0:

```
$ ruby -e "puts RUBY_VERSION"
2.0.0
$ JRUBY_OPTS="--1.9" ruby -e "puts RUBY_VERSION"
1.9.3
```

The JRUBY_OPTS has preferences over `.jrubyrc`. Does that help?

**Comment by mislav** [comment]
Should we then set `JRUBY_OPTS="--1.9"` unconditionally when installing JRuby?

**Comment by rosenfeld** [comment]
I believe this is the best we can do to work around this problem until this is fixed in JRuby for a while already. @headius, do you have any other suggestions or work-arounds for this problem?

**Comment by hsbt** [comment]
JRuby 1.7.x is EOL now. see https://github.com/jruby/jruby/issues/4112
