### ISSUE TITLE
JRuby 1.7.19 fails to build on Ubuntu 14

### ISSUE THREAD

**Issue by suetanvil** [rbenv/ruby-build#734]
I am unable to install jruby-1.7.19 on Ubuntu 14 using rbenv.

After some digging, I tracked down the problem to a C++ compile-time error while installing the `jruby-launcher` gem.  When I commented out the call to `install_ruby_launcher` in `ruby-build`, jruby installed with no problems and ran perfectly.

I'll be submitting a pull request shortly that makes `jruby-launcher` optional.

**Comment by zhaohanweng** [comment]
Currently still cannot install jruby via `rbenv install jruby-1.7.19` on mac with jdk8. 

Output:
```
Last 10 log lines:
         ^
1 error generated.
make[2]: *** [build/unix/Darwin/argparser.o] Error 1
make[1]: *** [.build-conf] Error 2
make: *** [.build-impl] Error 2

make failed, uncaught signal 2

Gem files will remain installed in /usr/local/var/rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/jruby-launcher-1.1.1-java for inspection.
Results logged to /usr/local/var/rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/extensions/universal-java-1.8/1.9/jruby-launcher-1.1.1-java/gem_make.out
```

Still  have the jruby-launcher problem. will this fix be merged next release?

**Comment by zhaohanweng** [comment]
I tried just removing the `install-jruby-launcher` line in the ruby-build. it installed the jruby fine. but I cannot use `gem` after.

```
>> gem
>> /usr/local/var/rbenv/versions/jruby-1.7.19/bin/gem: line 4: syntax error near unexpected token `('
>> /usr/local/var/rbenv/versions/jruby-1.7.19/bin/gem: line 4: `load File.join(File.dirname(__FILE__), 'jgem')'
```

**Comment by cldwalker** [comment]
Also unable to install jruby-1.7.19 on osx 10.10 with jdk8 and getting the same errors as @zhaohanweng

**Comment by mislav** [comment]
Is JRuby 1.7 even compatible with JDK 8?

**Comment by zhaohanweng** [comment]
`rbenv install jruby-1.7.20` works.

**Comment by hsbt** [comment]
JRuby 1.7.x is EOL now. see https://github.com/jruby/jruby/issues/4112
