### ISSUE TITLE
Ruby 2.2.0 build fails on MacOS 10.10.2

### ISSUE THREAD

**Issue by chaak20** [rbenv/ruby-build#736]
I'm consistently getting a failure trying to install Ruby 2.2.0 on Yosemite 10.10.2. I tried the recipe in post:

https://bearmetal.eu/theden/install-ruby-2-dot-2-0-yosemite-openssl-error/

but can't get it work on my machine. I've installed openssl using brew and modified the PATH variable so that this version of openssl is found first.

```
$ openssl version -a
OpenSSL 1.0.2 22 Jan 2015
built on: reproducible build, date unspecified
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: clang -I. -I.. -I../include  -fPIC -fno-common -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch x86_64 -O3 -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/local/etc/openssl"

$ rbenv install 2.2.0
Downloading ruby-2.2.0.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/7671e394abfb5d262fbcd3b27a71bf78737c7e9347fa21c39e58b0bb9c4840fc
Installing ruby-2.2.0...

BUILD FAILED (OS X 10.10.2 using ruby-build 20150303)

Inspect or clean up the working tree at /var/folders/74/59dpfdlj6c90v3q84wn8lj8h0000gn/T/ruby-build.20150322163125.2886
Results logged to /var/folders/74/59dpfdlj6c90v3q84wn8lj8h0000gn/T/ruby-build.20150322163125.2886.log

Last 10 log lines:
ossl_ssl.c:19:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
1 warning and 9 errors generated.
make[2]: *** [ossl_ssl.o] Error 1
make[1]: *** [ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
linking shared-object psych.bundle
installing default psych libraries
```

I tried using rbenv to install because installing via rvm failed (with I'm pretty sure the same error).

**Comment by chaak20** [comment]
Here are the first couple of lines from the failure (identical to the rvm method):

ossl_ssl.c:125:5: error: use of undeclared identifier 'TLSv1_2_method'
    OSSL_SSL_METHOD_ENTRY(TLSv1_2),
    ^
ossl_ssl.c:119:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_metho
d }
                                                                    ^
<scratch space>:105:1: note: expanded from here
TLSv1_2_method
^
ossl_ssl.c:126:5: error: use of undeclared identifier 'TLSv1_2_server_method'
    OSSL_SSL_METHOD_ENTRY(TLSv1_2_server),
    ^
ossl_ssl.c:119:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_met

I've checked CPPFLAGS and they point to dirs with ossl.h and ssl.h that do define these macros so I'm not sure what else needs to be done to fix the build.

**Comment by justindowning** [comment]
Similar issue with install 2.2.1 on Ubuntu 12.04 related to openssl:
```
justin@ubuntu ~ $ rbenv install 2.2.1                                                                   
Downloading ruby-2.2.1.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/5a4de38068eca8919cb087d338c0c2e3d72c9382c804fb27ab746e6c7819ab28
Installing ruby-2.2.1...

BUILD FAILED (Ubuntu 12.04 using ruby-build 20150319zf)

Inspect or clean up the working tree at /tmp/ruby-build.20150323033157.18808
Results logged to /tmp/ruby-build.20150323033157.18808.log

Last 10 log lines:
compiling ossl_x509attr.c
compiling ossl_x509store.c
installing default openssl libraries
installing default psych libraries
linking shared-object openssl.so
make[2]: Leaving directory `/tmp/ruby-build.20150323033157.18808/ruby-2.2.1/ext/openssl'
linking shared-object psych.so
make[2]: Leaving directory `/tmp/ruby-build.20150323033157.18808/ruby-2.2.1/ext/psych'
make[1]: Leaving directory `/tmp/ruby-build.20150323033157.18808/ruby-2.2.1'
make: *** [build-ext] Error 2

justin@ubuntu ~ $ openssl version -a
OpenSSL 1.0.1 14 Mar 2012
built on: Thu Mar 19 15:18:39 UTC 2015
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: cc -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -DTERMIO -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wa,--noexecstack -Wall -DOPENSSL_NO_TLS1_2_CLIENT -DMD32_REG_T=int -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/usr/lib/ssl"
```

**Comment by chaak20** [comment]
I have also tried:
$ RUBY_CONFIGURE_OPTS=--with-openssl-dir=/usr/local/Cellar/openssl/1.0.2 rbenv install 2.2.0
to tell it explicitly where to find openssl headers and libraries.  It still fails the same exact way.

**Comment by AbhimanyuAryan** [comment]
In my case as well it failed

Installing ruby-2.2.1...

BUILD FAILED (OS X 10.10.2 using ruby-build 20150319zf)

Inspect or clean up the working tree at /var/folders/c8/tr13g20944g8jymgp72wz7pw0000gn/T/ruby-build.20150326002550.58440
Results logged to /var/folders/c8/tr13g20944g8jymgp72wz7pw0000gn/T/ruby-build.20150326002550.58440.log

Last 10 log lines:
                              psych 2.0.8
                              rake 10.4.2
                              rdoc 4.2.0
./tool/rbinstall.rb:714:in `rescue in block in <main>': uninitialized constant LoadErroe (NameError)
	from ./tool/rbinstall.rb:712:in `block in <main>'
	from ./tool/rbinstall.rb:757:in `call'
	from ./tool/rbinstall.rb:757:in `block in <main>'
	from ./tool/rbinstall.rb:754:in `each'
	from ./tool/rbinstall.rb:754:in `<main>'
make: *** [do-install-all] Error 1

**Comment by fer** [comment]
Mine didn't give any ruby error at the end but failed on 10.10.2 as well trying to build ruby-build 20150319zf:

```
BUILD FAILED (OS X 10.10.2 using ruby-build 20150319zf)

Inspect or clean up the working tree at /var/folders/w_/6bv2f3z17tv7g0hz7krwfjv00000gn/T/ruby-build.20150325210546.19326
Results logged to /var/folders/w_/6bv2f3z17tv7g0hz7krwfjv00000gn/T/ruby-build.20150325210546.19326.log

Last 10 log lines:
/var/folders/w_/6bv2f3z17tv7g0hz7krwfjv00000gn/T/ruby-build.20150325210546.19326/ruby-2.2.1 /var/folders/w_/6bv2f3z17tv7g0hz7krwfjv00000gn/T/ruby-build.20150325210546.19326 ~/.dotfiles
make: *** [install-ruby] Error 1
```

**Comment by chaak20** [comment]
@fer,  @justindowning, can you post the actual compilation error from your log file (the snippet you posted doesn't reveal enough information).  I'm very interested to know if it's the same compiler message as mine or different.

**Comment by fer** [comment]
@chaak20 I am afraid it didn't throw much more info rather that that.

**Comment by chaak20** [comment]
Look at file with tail:

$ tail -20 /var/folders/w_/6bv2f3z17tv7g0hz7krwfjv00000gn/T/ruby-build.20150325210546.19326.log

and paste the output.

**Comment by fer** [comment]
```
/var/folders/w_/6bv2f3z17tv7g0hz7krwfjv00000gn/T/ruby-build.20150325210546.19326 ~/.dotfiles
HTTP/1.1 200 OK
Content-Type: binary/octet-stream
Content-Length: 16512208
Connection: keep-alive
Date: Tue, 03 Mar 2015 07:53:04 GMT
Last-Modified: Tue, 03 Mar 2015 06:56:49 GMT
ETag: "b49fc67a834e4f77249eb73eecffb1c9"
Accept-Ranges: bytes
Server: AmazonS3
Age: 1324
X-Cache: Hit from cloudfront
Via: 1.1 2ce2adf0d84119b3d9d0aa38dd54656f.cloudfront.net (CloudFront)
X-Amz-Cf-Id: zCm-AL8pbVX5xHNx1qdGx4GOuvguilxcJiMojDfEq6k2rmoT2v4oug==

/var/folders/w_/6bv2f3z17tv7g0hz7krwfjv00000gn/T/ruby-build.20150325210546.19326/ruby-2.2.1 /var/folders/w_/6bv2f3z17tv7g0hz7krwfjv00000gn/T/ruby-build.20150325210546.19326 ~/.dotfiles
```

**Comment by mislav** [comment]
@AbhimanyuAryan Your failure is related to https://github.com/sstephenson/ruby-build/issues/728

@fer Your issue is very weird because there's practically no log output. Please open a separate issue where you post more information such as your `bash --version` and whether you have installed Xcode command-line tools (`xcode-select --install`). Thanks!

**Comment by mrsellars** [comment]
@chaak20 i guess you have some old openssl header-Files in the compiler load path. For example in /opt/local/include/openssl through macports. Maybe you can symlink this directory to the new openssl include directory which comes from brew. But create a backup from /opt/local/include/openssl beforehand. Don't know if you have other libs that needs these old header files.

**Comment by chaak20** [comment]
@mrsellars I've inspected the path that cc uses to search for headers (via -I /path settings) and the thing is the files being used do actually contain the definitions that the compiler chokes on.  It could be there's some other dependency that I'm just not aware of.  I'll take a look at some of the other environment variables that may be set.

**Comment by nextofsearch** [comment]
Did anyone figure it out? I can't install 2.2.4 on MAC 10.11.4.

`
ossl_ssl.c:137:5: error: use of undeclared identifier 'SSLv2_method'
    OSSL_SSL_METHOD_ENTRY(SSLv2),
    ^
ossl_ssl.c:119:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
<scratch space>:144:1: note: expanded from here
SSLv2_method
^
ossl_ssl.c:138:5: error: use of undeclared identifier 'SSLv2_server_method'
    OSSL_SSL_METHOD_ENTRY(SSLv2_server),
    ^
ossl_ssl.c:119:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
<scratch space>:144:1: note: expanded from here
SSLv2_server_method
^
ossl_ssl.c:139:5: error: use of undeclared identifier 'SSLv2_client_method'
    OSSL_SSL_METHOD_ENTRY(SSLv2_client),
    ^
ossl_ssl.c:119:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
<scratch space>:144:1: note: expanded from here
SSLv2_client_method
^
ossl_ssl.c:213:21: error: invalid application of 'sizeof' to an incomplete type 'const struct <anonymous struct at ossl_ssl.c:115:14> []'
    for (i = 0; i < numberof(ossl_ssl_method_tab); i++) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:19:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
ossl_ssl.c:2216:23: error: invalid application of 'sizeof' to an incomplete type 'const struct <anonymous struct at ossl_ssl.c:115:14> []'
    ary = rb_ary_new2(numberof(ossl_ssl_method_tab));
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:19:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
ossl_ssl.c:2217:21: error: invalid application of 'sizeof' to an incomplete type 'const struct <anonymous struct at ossl_ssl.c:115:14> []'
    for (i = 0; i < numberof(ossl_ssl_method_tab); i++) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:19:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
6 errors generated.
make[2]: *** [ossl_ssl.o] Error 1
make[1]: *** [ext/openssl/all] Error 2
make: *** [build-ext] Error 2
++ return 2
`

**Comment by ckoppelman** [comment]
I'm hitting this issue as well while installing Ruby 2.3 and 2.4 using rvm onto OSX 10.9.

Error text starts with some warnings.

```
compiling openssl_missing.c
compiling ossl.c
compiling ossl_asn1.c
ossl_asn1.c:124:26: warning: passing 'const ASN1_INTEGER *' (aka 'const struct asn1_string_st *') to parameter of type 'ASN1_INTEGER *' (aka 'struct asn1_string_st *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        bn = ASN1_INTEGER_to_BN(ai, NULL);
                                ^~
/usr/local/Cellar/openssl098/0.9.8zg/include/openssl/asn1.h:904:42: note: passing argument to parameter 'ai' here
BIGNUM *ASN1_INTEGER_to_BN(ASN1_INTEGER *ai, BIGNUM *bn);
                                         ^
ossl_asn1.c:276:15: warning: implicit declaration of function 'ASN1_UTCTIME_adj' is invalid in C99 [-Wimplicit-function-declaration]
    if (!(t = ASN1_UTCTIME_adj(NULL, sec, off_days, 0)))
              ^
ossl_asn1.c:276:13: warning: incompatible integer to pointer conversion assigning to 'ASN1_UTCTIME *' (aka 'struct asn1_string_st *') from 'int' [-Wint-conversion]
    if (!(t = ASN1_UTCTIME_adj(NULL, sec, off_days, 0)))
            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_asn1.c:296:15: warning: implicit declaration of function 'ASN1_GENERALIZEDTIME_adj' is invalid in C99 [-Wimplicit-function-declaration]
    if (!(t = ASN1_GENERALIZEDTIME_adj(NULL, sec, off_days, 0)))
              ^
ossl_asn1.c:296:13: warning: incompatible integer to pointer conversion assigning to 'ASN1_GENERALIZEDTIME *' (aka 'struct asn1_string_st *') from 'int' [-Wint-conversion]
    if (!(t = ASN1_GENERALIZEDTIME_adj(NULL, sec, off_days, 0)))
            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
5 warnings generated.
compiling ossl_bio.c
compiling ossl_bn.c
compiling ossl_cipher.c
ossl_cipher.c:150:9: warning: implicit declaration of function 'EVP_CIPHER_CTX_copy' is invalid in C99 [-Wimplicit-function-declaration]
    if (EVP_CIPHER_CTX_copy(ctx1, ctx2) != 1)
        ^
1 warning generated.
compiling ossl_config.c
compiling ossl_digest.c
compiling ossl_engine.c
compiling ossl_hmac.c
ossl_hmac.c:129:10: warning: implicit declaration of function 'HMAC_CTX_copy' is invalid in C99 [-Wimplicit-function-declaration]
    if (!HMAC_CTX_copy(ctx1, ctx2))
         ^
1 warning generated.
compiling ossl_ns_spki.c
compiling ossl_ocsp.c
compiling ossl_pkcs12.c
compiling ossl_pkcs5.c
ossl_pkcs5.c:38:9: warning: implicit declaration of function 'PKCS5_PBKDF2_HMAC' is invalid in C99 [-Wimplicit-function-declaration]
    if (PKCS5_PBKDF2_HMAC(RSTRING_PTR(pass), RSTRING_LENINT(pass),
        ^
1 warning generated.
compiling ossl_pkcs7.c
compiling ossl_pkey.c
ossl_pkey.c:79:13: warning: implicit declaration of function 'EVP_PKEY_base_id' is invalid in C99 [-Wimplicit-function-declaration]
    switch (EVP_PKEY_base_id(pkey)) {
            ^
ossl_pkey.c:170:11: warning: implicit declaration of function 'EVP_PKEY_get0' is invalid in C99 [-Wimplicit-function-declaration]
    ptr = EVP_PKEY_get0(pkey);
          ^
ossl_pkey.c:170:9: warning: incompatible integer to pointer conversion assigning to 'void *' from 'int' [-Wint-conversion]
    ptr = EVP_PKEY_get0(pkey);
        ^ ~~~~~~~~~~~~~~~~~~~
3 warnings generated.
compiling ossl_pkey_dh.c
ossl_pkey_dh.c:66:6: warning: implicit declaration of function 'EVP_PKEY_base_id' is invalid in C99 [-Wimplicit-function-declaration]
        if (EVP_PKEY_base_id(pkey) != EVP_PKEY_DH) {
            ^
1 warning generated.
compiling ossl_pkey_dsa.c
ossl_pkey_dsa.c:80:6: warning: implicit declaration of function 'EVP_PKEY_base_id' is invalid in C99 [-Wimplicit-function-declaration]
        if (EVP_PKEY_base_id(pkey) != EVP_PKEY_DSA) {
            ^
1 warning generated.
compiling ossl_pkey_ec.c
ossl_pkey_ec.c:107:6: warning: implicit declaration of function 'EVP_PKEY_base_id' is invalid in C99 [-Wimplicit-function-declaration]
        if (EVP_PKEY_base_id(pkey) != EVP_PKEY_EC) {
            ^
1 warning generated.
compiling ossl_pkey_rsa.c
ossl_pkey_rsa.c:82:6: warning: implicit declaration of function 'EVP_PKEY_base_id' is invalid in C99 [-Wimplicit-function-declaration]
        if (EVP_PKEY_base_id(pkey) != EVP_PKEY_RSA) {
            ^
1 warning generated.
compiling ossl_rand.c
compiling ossl_ssl.c
ossl_ssl.c:76:5: error: use of undeclared identifier 'TLSv1_1_method'
    OSSL_SSL_METHOD_ENTRY(TLSv1_1, TLS1_1_VERSION),
    ^
ossl_ssl.c:64:46: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
    { #name,          (SSL_METHOD *(*)(void))name##_method, version }, \
                                             ^
<scratch space>:181:1: note: expanded from here
TLSv1_1_method
```

**Comment by ckoppelman** [comment]
Wow! I just did an ls -l on openssl and found this:

    > ls -l `which openssl`
    lrwxr-xr-x  1 cskm  admin  40 Jan 25 16:37 /usr/local/bin/openssl -> ../Cellar/openssl098/0.9.8zg/bin/openssl

**Comment by ckoppelman** [comment]
Running `brew unlink openssl098` did it!  I need to track down who installed that ancient openssl.  Thank you for breaking without a modern openssl!

**Comment by hsbt** [comment]
macOS 10.10 is EOL now. Please try with latest version of Ruby 2.2 series on macOS 10.12 or 10.11.
