### ISSUE TITLE
Warn when installing EOLed versions

### ISSUE THREAD

**Issue by sstephenson** [rbenv/ruby-build#742]
Let’s print a warning to stderr when installing a Ruby version that’s been EOLed by its maintainers. 

We don’t want to get into the business of applying [unofficial backported security patches](https://github.com/sikachu/ruby/commit/868cccadb59b83dfe2b13baf5a1881ec0c388634), but it feels similarly irresponsible to let people install vulnerable versions without notifying them first.

**Comment by hsbt** [comment]
:+1: I agree to your suggestion.

**Comment by mislav** [comment]
Which Ruby versions have been EOLed?

* 1.8.x
* 1.9.2
* ?

**Comment by hsbt** [comment]
and 1.9.3

**Comment by jeremy** [comment]
:+1::+1::+1:

**Comment by eregon** [comment]
And 2.0.0 now.

**Comment by e2** [comment]
And technically 2.1 is also no longer supported. (Fixing just vulnerabilities doesn't count as "support").

I wrote a gem for these kinds of warnings: https://github.com/e2/ruby_dep/blob/master/lib/ruby_dep/warning.rb

Porting it to shell seems a bit too daunting for me.
