### ISSUE TITLE
`CONFIGURE_OPTS` not honored when building RBX

### ISSUE THREAD

**Issue by alexdowad** [rbenv/ruby-build#796]
The README states that "`CONFIGURE_OPTS` lets you pass additional options to `configure`", and "`RUBY_CONFIGURE_OPTS`... allow[s] you to specify options for building MRI".

However, when building RBX, only `RUBY_CONFIGURE_OPTS` is actually used, not `CONFIGURE_OPTS`. This seems wrong in 2 ways: first, according to the docs, `RUBY_CONFIGURE_OPTS` was supposed to be for MRI, not for RBX. And second, `CONFIGURE_OPTS` is not handled the way the docs say it should be.

Either the behavior is wrong, or the documentation is wrong, or both. I'm not sure what your intention was, or I would send a PR.

**Comment by mislav** [comment]
Thanks for reporting. Yes, the "MRI" bit is wrong. It should say that RUBY_CONFIGURE_OPTS is used to configure the Ruby install but installs for any of the dependencies like libyaml or openssl.

**Comment by alexdowad** [comment]
How about `CONFIGURE_OPTS`? Is it only passed to `configure` when building dependencies?

**Comment by mislav** [comment]
No, it's passed to all `./configure` operations, including Ruby

**Comment by hsbt** [comment]
We gave-up to support rbx build now.
