### ISSUE TITLE
OpenSSL isn't available anymore to build against in OS X 10.11

### ISSUE THREAD

**Issue by lloeki** [rbenv/ruby-build#797]
That old buggy version is finally going away, therefore this is how I built rubinius:

```
brew tap homebrew/versions
brew install llvm35 openssl
RUBY_CONFIGURE_OPTS="--with-lib-dir=$(brew --prefix openssl)/lib --with-include-dir=$(brew --prefix openssl)/include" rbenv install rbx-2.5.8
```

`rbenv install 2.2.2` builds and uses its own openssl, I suppose `rbenv install rbx` should do the same.

**Comment by mislav** [comment]
Oh wow, thanks for the news!

**Comment by gaboesquivel** [comment]
Thanks @lloeki

**Comment by hsbt** [comment]
llvm35 is outdated status on homebrew in 2017. I will close this issue.

We should decide to handle old rubinius versions: ref #862
