### ISSUE TITLE
Incorporate SSL patch from Wiki

### ISSUE THREAD

**Issue by mvz** [rbenv/ruby-build#825]
Rubies up to 1.9.3 fail to build on Debian 7.5 and up. Is it possible for the patch workaround from the wiki to be incorporated in the build recipe?

**Comment by mislav** [comment]
It's possible, but we never embedded patches in Ruby recipes before and we would like to avoid doing so if possible. I don't feel that it's worth patching 1.9.3 because it's a very old verison. Isn't the workaround outlined in the wiki enough?

**Comment by mvz** [comment]
I only found the workaround after two failed build attempts, so it would definitely be *faster* if it was incorporated. Perhaps some kind of check for the installed version of openssl would be useful.

I would love to not have to build 1.9.3, but I'm working on a project that currently needs such an old version. Also, work is still being done to keep it buildable on OSX.

Building *with* the patch currently also fails, so a bigger patch is probably needed now. I'll try to get it to build first to see what's needed.

**Comment by mislav** [comment]
Please let us know if you manage to build on Debian.

**Comment by mvz** [comment]
I've managed to get it to build with a combination of the 'OpenSSL bindings on Debian' patch and a modified version of the 'OpenSSL “SSLv3_method undeclared” error' patch.

See this gist: https://gist.github.com/mvz/5d13b6a79406a721fb87#file-ruby-build-1-9-debian-patch

Following up on the original discussion, even recent CRubies fail to build on Debian Sid and need the SSLv3_method undeclared patch. It would be great if that could be automated somehow.

**Comment by mislav** [comment]
Thanks for sharing. How did you modify the `SSLv3_method undeclared` patch?

**Comment by mvz** [comment]
I had to change some of the context lines in `ext/openssl/extconf.rb` since that file is different in 1.9.3.

**Comment by danny8376** [comment]
Openssl isn't built with sslv2 support by default starting from 1.0.1g.
However, the macro that checks sslv2 isn't added until ruby 2.3.0-dev.
Those "old versions" will definitely fail to build without patching when distros upgrading their openssl.
(Hope that won't happened before ruby 2.2 is phasing out :smile: )

**Comment by mislav** [comment]
Closing as stale
