### ISSUE TITLE
Undefined symbols for architecture x86_64 (OS X 10.10)

### ISSUE THREAD

**Issue by demhaq** [rbenv/ruby-build#828]
```
rbenv install 2.2.3
Downloading openssl-1.0.1p.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/bd5ee6803165c0fb60bbecbacacf244f1f90d2aa0d71353af610c29121e9b2f1
Installing openssl-1.0.1p...

BUILD FAILED (OS X 10.10.1 using ruby-build 20151028-10-gf174d58)

Inspect or clean up the working tree at /var/folders/5m/_jv81jbx1tj3ngl3t99r0yxr0000gn/T/ruby-build.20151114100739.68344
Results logged to /var/folders/5m/_jv81jbx1tj3ngl3t99r0yxr0000gn/T/ruby-build.20151114100739.68344.log

Last 10 log lines:
Undefined symbols for architecture x86_64:
  "___divti3", referenced from:
      ___muloti4 in libclang_rt.osx.a(muloti4.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [link_a.darwin] Error 1
make[3]: *** [do_darwin-shared] Error 2
make[2]: *** [libcrypto.1.0.0.dylib] Error 2
make[1]: *** [shared] Error 2
make: *** [build_crypto] Error 1
```

**Comment by demhaq** [comment]
anybody encountered this type of issue when installing the latest ruby version

**Comment by mislav** [comment]
That's strange. Have you tried `xcode-select --install`?

**Comment by demhaq** [comment]
Yes i id my version number is 2339 for xcode-select, I did do it again using Home brew this is what i did step by step 1. brew install rbenv 2. exported my environment variable which is export RBENV _ROOT = /usr/local/var/rbenv to my bash_profile , and added this to initial rbenv  if which rbenv > /dev/null; then eval "$(rbenv init -)";fi  3. when to my path cd/usr/local/var/rbenv and make a directory called plugins into it i cloned ruby-build git clone https://github.com/sstephenson/ruby-build.git. 4. when i type rbenv install --list i get all the possible version to be installed i can see the the version i want which is 2.2.3 
5 rbenv install 2.2.3, this is the error i am getting on my command line 
Downloading ruby-2.2.3.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/df795f2f99860745a416092a4004b016ccf77e8b82dec956b120f18bdc71edce
Installing ruby-2.2.3...

BUILD FAILED (OS X 10.10.1 using ruby-build 20151028-10-gf174d58)

Inspect or clean up the working tree at /var/folders/5m/_jv81jbx1tj3ngl3t99r0yxr0000gn/T/ruby-build.20151115095948.5066
Results logged to /var/folders/5m/_jv81jbx1tj3ngl3t99r0yxr0000gn/T/ruby-build.20151115095948.5066.log

Last 10 log lines:
config.guess already exists
config.sub already exists
checking build system type... x86_64-apple-darwin14.0.0
checking host system type... x86_64-apple-darwin14.0.0
checking target system type... x86_64-apple-darwin14.0.0
checking whether the C compiler works... no
configure: error: in `/var/folders/5m/_jv81jbx1tj3ngl3t99r0yxr0000gn/T/ruby-build.20151115095948.5066/ruby-2.2.3':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.

**Comment by mislav** [comment]
Could you paste the full build log (see "Results logged to ..." line) [as a gist](https://gist.github.com/)?

**Comment by demhaq** [comment]
<script src="https://gist.github.com/demhaq/5c357da2b7203c86da41.js"></script>

**Comment by demhaq** [comment]
<script src="https://gist.github.com/demhaq/5c357da2b7203c86da41.js"></script>

**Comment by demhaq** [comment]
gist:5c357da2b7203c86da41

**Comment by demhaq** [comment]
Downloading ruby-2.2.3.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/df795f2f99860745a416092a4004b016ccf77e8b82dec956b120f18bdc71edce
Installing ruby-2.2.3...

BUILD FAILED (OS X 10.10.1 using ruby-build 20151028-10-gf174d58)

Inspect or clean up the working tree at /var/folders/5m/_jv81jbx1tj3ngl3t99r0yxr0000gn/T/ruby-build.20151115095948.5066
Results logged to /var/folders/5m/_jv81jbx1tj3ngl3t99r0yxr0000gn/T/ruby-build.20151115095948.5066.log

Last 10 log lines:
config.guess already exists
config.sub already exists
checking build system type... x86_64-apple-darwin14.0.0
checking host system type... x86_64-apple-darwin14.0.0
checking target system type... x86_64-apple-darwin14.0.0
checking whether the C compiler works... no
configure: error: in `/var/folders/5m/_jv81jbx1tj3ngl3t99r0yxr0000gn/T/ruby-build.20151115095948.5066/ruby-2.2.3':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.

**Comment by mislav** [comment]
What I meant was:

1. `pbcopy </var/folders/5m/_jv81jbx1tj3ngl3t99r0yxr0000gn/T/ruby-build.20151115095948.5066.log`
2. Go to https://gist.github.com/
3. Paste log into text area
4. Press "Create secret gist"
5. Copy the browser URL
6. Paste the URL here.

**Comment by afelle1** [comment]
https://gist.github.com/afelle1/bc5da9b8465f107493c3

**Comment by mislav** [comment]
@afelle1 I haven't seen this openssl compile error before, but what you can try is to install openssl with Homebrew (`brew install openssl`) and then try `rbenv install ...` again. Let us know if that works!

**Comment by afelle1** [comment]
@mislav the bew install openssl installed a newer version and bypassed the previous error @demhaq and I were having, however there is a new error instead:

https://gist.github.com/afelle1/73ac2304d5e28ca19e22

**Comment by mislav** [comment]
@afelle1 Ouch. Does `xcode-select --install` help

**Comment by afelle1** [comment]
@mislav So I think I figured out my issue.  Whenever I upgraded to Yosemite, there was some issue with Xcode as not being validated or something, so I deleted Xcode and uninstalled the command line tools (http://stackoverflow.com/questions/27438457/xcode-6-1-how-to-uninstall-command-line-tools) and then reinstalled them ala *xcode-select --install* and was able to get past the openssl issue @demhaq and I were hitting.  After that, ruby 2.2.3 installed completely fine, so thanks again for your help!  Think demhaq needs to uninstall and reinstall xcode and/or xcode command line tools.

**Comment by afelle1** [comment]
```
andrew.feller@andrew-feller-m ~ $ rbenv install 2.2.3
Downloading openssl-1.0.1p.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/bd5ee6803165c0fb60bbecbacacf244f1f90d2aa0d71353af610c29121e9b2f1
Installing openssl-1.0.1p...
Installed openssl-1.0.1p to /Users/andrew.feller/.rbenv/versions/2.2.3

Downloading ruby-2.2.3.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/df795f2f99860745a416092a4004b016ccf77e8b82dec956b120f18bdc71edce
Installing ruby-2.2.3...
Installed ruby-2.2.3 to /Users/andrew.feller/.rbenv/versions/2.2.3

andrew.feller@andrew-feller-m ~ $ ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
andrew.feller@andrew-feller-m ~ $ rbenv local 2.2.3
andrew.feller@andrew-feller-m ~ $ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
```

**Comment by mislav** [comment]
Thanks for sharing, @afelle1. @demhaq do you still have the original issue?

**Comment by hsbt** [comment]
macOS 10.10 is EOL now.

**Comment by DominicTobias** [comment]
To those who got into my strange situation: Had to install a parallel version of XCode (12.4) for some outdated build tools at work, which included adding `SYSTEM_VERSION_COMPAT=1`. This caused the ruby install process to think it was working with the previous version of MacOS, and so clang linking failed:

```
ld: warning: dylib (/usr/local/lib/libgmp.dylib) was built for newer macOS version (12.0) than being linked (11.1)
Undefined symbols for architecture x86_64:
  "__mh_execute_header", referenced from:
      _rb_dump_backtrace_with_lines in addr2line.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It worked from one or both of removing `SYSTEM_VERSION_COMPAT=1` (or setting to 0/false), and _possibly_ switching back to the latest XCode command line tools `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer` since I have 12.4 installed in parallel (`sudo xcode-select --switch /Applications/Xcode12.4.app/Contents/Developer`)
