### ISSUE TITLE
Ruby zlib extension was not compiled OS X 10.9.5

### ISSUE THREAD

**Issue by robochase6000** [rbenv/ruby-build#832]
trying to get ruby 2.2.3 running on this computer.  curiously, i was able to do this just fine on a different computer earlier today (probably running 10.8 or 10.9). also tried 2.2.2, same result.

I'm guessing there's just something trivial I need to do, but I'm a little dicey on this kind of stuff.

Here's the log when I run rbenv install 2.2.3

```
Downloading ruby-2.2.3.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/df795f2f99860745a416092a4004b016ccf77e8b82dec956b120f18bdc71edce
Installing ruby-2.2.3...

BUILD FAILED (OS X 10.9.5 using ruby-build 20151028)

Inspect or clean up the working tree at /var/folders/zp/snp4qhvj401d3jnp2ltql9c40000gn/T/ruby-build.20151118232539.75260
Results logged to /var/folders/zp/snp4qhvj401d3jnp2ltql9c40000gn/T/ruby-build.20151118232539.75260.log

Last 10 log lines:
installing capi-docs:         /Users/chasedelanguillette/.rbenv/versions/2.2.3/share/doc/ruby
The Ruby zlib extension was not compiled.
ERROR: Ruby install aborted due to missing extensions
Configure options used:
  --prefix=/Users/chasedelanguillette/.rbenv/versions/2.2.3
  --with-openssl-dir=/usr/local/opt/openssl
  --with-readline-dir=/usr/local/opt/readline
  CFLAGS= -O3 -Wno-error=shorten-64-to-32 
  LDFLAGS=-L/Users/chasedelanguillette/.rbenv/versions/2.2.3/lib 
  CPPFLAGS=-I/Users/chasedelanguillette/.rbenv/versions/2.2.3/include 
```

**Comment by robochase6000** [comment]
omg, totally listed this in the wrong github page.  too many tabs open trying to fix this. sorry!

**Comment by mislav** [comment]
You totally listed this in the right GitHub repo :wink: The ruby-build project is responsible for `rbenv install` command.

That's a very interesting error. Rubies were known to compile without problems using OS X system libzlib. For you, it failed for some reason. Have you installed a custom zlib somehow?

**Comment by robochase6000** [comment]
that's a great question.  i've done numerous things to the computer in question over the years so maybe.  how would i know where to look?

**Comment by mislav** [comment]
I'm not sure how to look :(

You could always try to install zlib with Homebrew and use `RUBY_CONFIGURE_OPTS=--with-zlib-dir="$(brew --prefix zlib)"`. Maybe that would work

**Comment by mislav** [comment]
Other things to try:

```sh
ls /usr/lib/libz*
# should produce:
# /usr/lib/libz.1.1.3.dylib
# /usr/lib/libz.1.2.5.dylib
# /usr/lib/libz.1.dylib
# /usr/lib/libz.dylib

# if all else fails, resort to Homebrew:
brew install zlib
LDFLAGS=-L/usr/local/opt/zlib/lib CPPFLAGS=-I/usr/local/opt/zlib/include rbenv install 2.2.4
```

**Comment by renatomoya** [comment]
I had the same issue and the following worked.

```
# if all else fails, resort to Homebrew:
brew install zlib
LDFLAGS=-L/usr/local/opt/zlib/lib CPPFLAGS=-I/usr/local/opt/zlib/include rbenv install 2.2.4
```

**Comment by mislav** [comment]
Thanks for sharing that it worked for you, @renatomoya. Could you also share your output of `ls -l /usr/lib/libz*`?

The reason I'm confused about this is that Ruby should compile well against system version of zlib on OS X. The Homebrew step shouldn't be necessary, but for some people it mysteriously is.

**Comment by robochase6000** [comment]
thanks for not giving up on this, i practically had :)

I tried punching in the things that were suggested here, but i still have the same zlib errors

Here's my output when i run `ls -l /usr/lib/libz*`
lrwxr-xr-x  1 root  wheel      16 Oct  5  2013 /usr/lib/libz.1.1.3.dylib -> libz.1.2.5.dylib
-rwxr-xr-x  1 root  wheel  169392 Oct  5  2013 /usr/lib/libz.1.2.5.dylib
lrwxr-xr-x  1 root  wheel      16 Oct  5  2013 /usr/lib/libz.1.dylib -> libz.1.2.5.dylib
lrwxr-xr-x  1 root  wheel      16 Oct  5  2013 /usr/lib/libz.dylib -> libz.1.2.5.dylib

quick question, when you said "You could always try to install zlib with Homebrew and use RUBY_CONFIGURE_OPTS=--with-zlib-dir="$(brew --prefix zlib)""...tell me more about that RUBY_CONFIGURE_OPTS part.  do i just punch that line into terminal and hit enter? or am I supposed to tack that on the `rbenv install 2.3.0` command?

**Comment by mislav** [comment]
You would literally do these commands in the terminal:

```
brew install zlib
RUBY_CONFIGURE_OPTS="--with-zlib-dir=$(brew --prefix zlib)" rbenv install 2.2.3
```

Everyone: When someone experiences a zlib failure on OS X without using Homebrew zlib next, could you please paste the full build log (stored in a file as indicated) [as a gist](https://gist.github.com) and paste the link here? Thanks.

**Comment by robochase6000** [comment]
oh ok.  i figured the RUBY_CONFIGURE_OPTS line and the rbenv line were separate and meant to be entered seperately. i pasted the entire line and it works! Thanks so much!

**Comment by renatomoya** [comment]
@mislav This the output:

```bash
lrwxr-xr-x  1 root  wheel      12 Jun 30  2015 /usr/lib/libz.1.1.3.dylib -> libz.1.dylib
lrwxr-xr-x  1 root  wheel      12 Jun 30  2015 /usr/lib/libz.1.2.5.dylib -> libz.1.dylib
-rwxr-xr-x  1 root  wheel  169312 Sep  9  2014 /usr/lib/libz.1.dylib
lrwxr-xr-x  1 root  wheel      12 Jun 30  2015 /usr/lib/libz.dylib -> libz.1.dylib
```

**Comment by mislav** [comment]
@renatomoya That looks alright; thanks for sharing. It's really weird that Ruby has trouble linking to zlib for only specific people.

Next time this happens to anyone, please share the full build log as a gist so that I can inspect any zlib-related output. Thanks!

**Comment by ledbettj** [comment]
Hi,

I just ran into this trying to install `2.3.0` on OS X El Capitan.  [Here's the full log](https://gist.github.com/ledbettj/c79659dfd4f4a6297867) without zlib installed via Homebrew.

**Comment by ledbettj** [comment]
Shot in the dark:  I have also had issues getting OpenSSL installed on El Capitan that were related to SIP, zlib, and dynamic module loading -- https://langui.sh/2015/11/27/sip-and-dlopen/ explains that in more detail.

**Comment by mislav** [comment]
@ledbettj Thanks for sharing! Does the error go away if you remove `/usr/local/lib/libz.a`? What installed it in the first place?

**Comment by ledbettj** [comment]
@mislav Yup, I just tried that (unsure what dropped it there -- it wasn't homebrew) and yes, the install completed fine with no errors.  Unsure if this is related to the original issue here though.  Thanks for the help!

**Comment by mislav** [comment]
@ledbettj Thanks for checking! It's quite possible that other people reporting this issue might have had something in their `/usr/local/lib/libz*` too; probably an artifact of unrelated installs in the past.

**Comment by PjEdwards** [comment]
@mislav Just wanted to confirm the working theory. I'm running OSX 10.10.5 and while attempting to `rbenv install ruby-2.0.0-p481` I ran into this same issue. I checked and did have `libz` stuff in both `/usr/local/lib` and in `/usr/lib`. Removing the `/usr/local/lib` stuff was the only change I made and this allowed the install to succeed. I got this MacBook through the company and there was a version of Ruby pre-installed by root as well as a whole slew of other software. I have no way of tracing where the `/usr/local/lib` stuff came from.

**Comment by audiolion** [comment]
Had the same issue on OSX 10.10.5, found stuff with `ls /usr/local/lib/libz*` and removed it, retried the install of `rbenv install 2.2.4` and everything worked

**Comment by jduckworth** [comment]
The same worked for me as well installing 2.3.1. In case it's helpful, [here is the full log of the original failure](https://gist.github.com/jduckworth/08b226eab59f95c42941fe4628e1481d)

**Comment by techbrownbags** [comment]
i was having the same issue. I have files in /usr/local/lib/libz* and /usr/lib/libz*. I moved the files from /usr/local/lib/ and  it worked. Thanks

/usr/local/lib/libz*
-rw-r--r--  1 root  wheel  99184 Apr 12  2016 /usr/local/lib/libz.1.2.5.dylib
-rw-r--r--  1 root  wheel  95312 Oct 19 20:51 /usr/local/lib/libz.1.2.6.dylib
-rw-r--r--  1 root  wheel  95312 Oct 19 20:51 /usr/local/lib/libz.1.dylib
-rw-r--r--  1 root  wheel  95312 Oct 19 20:51 /usr/local/lib/libz.dylib

/usr/lib/libz*
lrwxr-xr-x  1 root  wheel      16 Feb 18  2014 /usr/lib/libz.1.1.3.dylib -> libz.1.2.5.dylib
-rwxr-xr-x  1 root  wheel  169392 Feb 18  2014 /usr/lib/libz.1.2.5.dylib
lrwxr-xr-x  1 root  wheel      16 Feb 18  2014 /usr/lib/libz.1.dylib -> libz.1.2.5.dylib
lrwxr-xr-x  1 root  wheel      16 Feb 18  2014 /usr/lib/libz.dylib -> libz.1.2.5.dylib

**Comment by hsbt** [comment]
macOS 10.9 is EOL status by Apple. We can't investigate this continuously in 2017.

**Comment by audiolion** [comment]
I had the issue on 10.10.5, just sayin

**Comment by tsbehlman** [comment]
Had the same issue in 10.12.3.  Removing the libz* files under usr/local/lib/ fixed it for me.

**Comment by jarsen** [comment]
Had this problem in 10.12.6

I removed the libz* files under `usr/local/lib/` and am now able to carry on with my life.
