### ISSUE TITLE
Can't Install 2.3.0-preview1 on Ubuntu 14.04

### ISSUE THREAD

**Issue by todd** [rbenv/ruby-build#833]
Having issues installing 2.3.0-preview1 on Trusty. Looks like it can't find erb for whatever reason. Any ideas? No issues installing it on my OS X 10.11.x host machine.

```
vagrant@development:/vagrant$ rbenv install 2.3.0-preview1
Downloading ruby-2.3.0-preview1.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/dc8f9d48392a2bb226df5f4b4fd2074d81af155cdf3f3799139a6e31e012aefe
Installing ruby-2.3.0-preview1...

BUILD FAILED (Ubuntu 14.04 using ruby-build 20151028-11-gbd22205)

Inspect or clean up the working tree at /tmp/ruby-build.20151122223304.3251
Results logged to /tmp/ruby-build.20151122223304.3251.log

Last 10 log lines:

  Total:      0 (0 undocumented)
    0.00% documented

  Elapsed: 0.0s

generating x86_64-linux-fake.rb
./tool/generic_erb.rb:2:in `require': cannot load such file -- erb (LoadError)
        from ./tool/generic_erb.rb:2:in `<main>'
make: *** [x86_64-linux-fake.rb] Error 1
```

Release info:
```
vagrant@development:/vagrant$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```

**Comment by mislav** [comment]
Thanks for reporting. /cc @hsbt re: a possible Ruby 2.3 build bug.

@todd Can you paste the full build log from the referenced file [as a gist](https://gist.github.com)?

**Comment by hsbt** [comment]
@todd @mislav I got same error with other user sometimes. I think this is defect of official ruby package. I will investigate this week.

**Comment by todd** [comment]
@mislav @hsbt Thanks for looking into this. Here's the build log: https://gist.github.com/todd/02657c126de9bd0fbafd

**Comment by hsbt** [comment]
Hmm, I can't reproduce this situation with ubuntu 14.04 and vagrant. 

@todd 

Can you provide me output of `apt list --installed`?

**Comment by todd** [comment]
@hsbt Updated my Gist with the output of `apt list --installed` - https://gist.github.com/todd/02657c126de9bd0fbafd#file-apt-list

**Comment by olivierlacan** [comment]
I managed to reproduce this on a clean install of OS X 10.11.1: 

```
generating x86_64-darwin15-fake.rb
./tool/generic_erb.rb:2:in `require': cannot load such file -- erb (LoadError)
	from ./tool/generic_erb.rb:2:in `<main>'
clang: error: unable to execute command: Broken pipe: 13
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg:
```

Build log here: https://gist.github.com/olivierlacan/2d719579f1f36430399d

**Comment by todd** [comment]
@hsbt preview2 builds are failing as well. New Gist with the build log is here: https://gist.github.com/todd/e7ce9f282a934ca3f8a5

I saw the bug you mentioned on #848, I'll also subscribe to that.

**Comment by hsbt** [comment]
Thanks tracking. Can you paste your `config.status` and `Makefile`

**Comment by todd** [comment]
@hsbt Added `config.status` and the `Makefile` to the new Gist.

**Comment by hsbt** [comment]
@todd Thanks for your quick action. we investigate this.

**Comment by todd** [comment]
Let me know if I can provide any more help.

**Comment by hsbt** [comment]
We found cause of this issue. You should not use `system` ruby with 2.3.0 build.

You need to invoke `rbenv install 2.2.3` and `rbenv global 2.2.3`. Aftter that, You can install Ruby 2.3.0preview2.

It's defect of rbenv functions. @eagletmt already submit patch for this issue.

**Comment by todd** [comment]
Confirmed that rbenv/rbenv#836 fixes this issue. Closing.
