### ISSUE TITLE
Build failed for ruby 2.2.x on Ubuntu 14.04 - make: command not found

### ISSUE THREAD

**Issue by alexrois** [rbenv/ruby-build#838]
I try to install ruby 2.2.3 using rbenv and ruby-build on Ubuntu 14.04 LTS. But there is BUILD FAILED for any ruby 2.2.x (I tried to install 2.2.3, 2.2.2, 2.2.1). Every time I have this output: "... make: command not found". Examples:

ruby 2.2.3
![r223](https://cloud.githubusercontent.com/assets/16092409/11519522/a29b3fbe-98a3-11e5-9bdc-e4ee0d71d8be.jpg)

ruby 2.2.2
![r222](https://cloud.githubusercontent.com/assets/16092409/11519554/e5fb9ae2-98a3-11e5-8f24-3c051b79e96e.jpg)

ruby 2.2.1
![r221](https://cloud.githubusercontent.com/assets/16092409/11519531/bab5846a-98a3-11e5-8073-1628c2c1eb98.jpg)

**Comment by mislav** [comment]
See https://github.com/rbenv/ruby-build/wiki#suggested-build-environment and try again after installing packages such as `build-essential` that provides `make`.

**Comment by alexrois** [comment]
I have installed all suggested packages for Ubuntu (from ruby-build wiki). After that ruby 2.2.3 installed correct.

Thanks for help!

**Comment by mislav** [comment]
Thanks for updating!
