### ISSUE TITLE
Find correct LLVM version on Debian/Ubuntu

### ISSUE THREAD

**Issue by mvz** [rbenv/ruby-build#853]
There is special code to find LLVM versions on MacOSX, but not for Ubuntu/Debian. It would be nice if this was available so there's no need to add `RUBY_CONFIGURE_OPTS="--llvm-config=/usr/bin/llvm-config-3.5"`.

I can try my hand at a pull request.

**Comment by mislav** [comment]
What is this in reference to? How does it relate to #765? Thanks

**Comment by mvz** [comment]
Sorry, my description was lacking in context:

I'm trying to build Rubinius on Debian, and it needs LLVM 3.5. Debian comes with that version, but its default version is 3.6, and that is what llvm-config will report. I therefore need to set the environment variable `RUBY_CONFIGURE_OPTS` to `--llvm-config=/usr/bin/llvm-config-3.5` before calling `ruby-build`.

#765 relates to setting this automatically for Homebrew, but does nothing on Debian.

**Comment by mislav** [comment]
What are the steps that someone can take to obtain LLVM 3.5 on Debian right now? Can we encapsulate that somehow, or at least output an error message with some practical instructions?

**Comment by mvz** [comment]
`sudo apt-get install llvm-3.5-dev` should do it. Because of the `sudo` emitting an error message is probably best.

**Comment by huangjj27** [comment]
WSL Ubuntu 18.04.1, initial installed llvm(llvm-6) removed and llvm-7 installed. complaining:

```
# We use one thread so the emscripten stdouts doesn't collide
cargo test --all --exclude wasmer-runtime-c-api --exclude wasmer-emscripten --exclude wasmer-spectests --exclude wasmer-singlepass-backend --
   Compiling wasmer-llvm-backend v0.4.0 (/home/huangjj27/wasmer/lib/llvm-backend)
   Compiling zstd-safe v1.4.9+zstd.1.4.0
   Compiling wabt-sys v0.5.4
   Compiling lz4 v1.23.1 (https://github.com/zboxfs/lz4-rs.git#47041445)
error: failed to run custom build command for `wasmer-llvm-backend v0.4.0 (/home/huangjj27/wasmer/lib/llvm-backend)`
process didn't exit successfully: `/home/huangjj27/wasmer/target/debug/build/wasmer-llvm-backend-0ea6d4fd90f89670/build-script-build` (exit code: 101)
--- stdout
Didn't find usable system-wide LLVM.
No suitable version of LLVM was found system-wide or pointed
                  to by LLVM_SYS_70_PREFIX.

                  Consider using `llvmenv` to compile an appropriate copy of LLVM, and
                  refer to the llvm-sys documentation for more information.

                  llvm-sys: https://crates.io/crates/llvm-sys
                  llvmenv: https://crates.io/crates/llvmenv

--- stderr
thread 'main' panicked at 'Could not find a compatible version of LLVM', lib/llvm-backend/build.rs:83:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
Makefile:47: recipe for target 'test' failed
make: *** [test] Error 101
```

**Comment by milongkmt** [comment]
Us

**Comment by eregon** [comment]
Closing this, llvm 3.5 is outdated and likely this is no longer a problem.
