### ISSUE TITLE
Add metadata for rubinius 3.0

### ISSUE THREAD

**Issue by keltia** [rbenv/ruby-build#865]
I'm aware of issue #862 but in the meantime, hoping it will get resolved w/o removing rubinius support, here is the file for rbx-3.0.0 — a simple copy from 2.11.0 w/ SHA and filenames edited.  It builds and installs fine.

Thanks.
[rbx-3.0.0.txt](https://github.com/rbenv/ruby-build/files/76786/rbx-3.0.0.txt)

**Comment by mislav** [comment]
Could you perhaps submit this as a pull request? Thanks

**Comment by keltia** [comment]
Done, see https://github.com/rbenv/ruby-build/pull/866.
