### ISSUE TITLE
Unable to install any ruby version (MRI) later than the one currently installed

### ISSUE THREAD

**Issue by MatthewMDavis** [rbenv/ruby-build#868]
See, e.g.:

 > $ rbenv install 2.2.3

 > ruby-build: definition not found: 2.2.3

 > The following versions contain `2.2.3' in the name:
 >   rbx-2.2.3

 > See all available versions with `rbenv install --list'.

 > If the version you need is missing, try upgrading ruby-build:

 >   brew update && brew upgrade ruby-build

running "brew upgrade ruby-build" tells me "Error: ruby-build 20151230 already installed", and running "ruby-build --definitions", I DO see a listing for 2.2.3. So whatever is causing this, it isn't ruby-build being out of date.

**Comment by mislav** [comment]
You might have duplicate installations of ruby-build: one might be installed as a plugin. If you [run `rbenv-doctor` script as outlined here](https://github.com/rbenv/rbenv-installer#rbenv-doctor), it might tell you the same thing. If you find a plugin, you can delete it (``rm -rf `rbenv root`/plugins/ruby-build``) and keep using just the Homebrew version.

**Comment by MatthewMDavis** [comment]
That's got it. Thanks.

I wonder how I did that.

**Comment by mislav** [comment]
Many people do that, but I'm not sure how. Probably they install rbenv from Homebrew and ruby-build as plugin, but they are unaware that Homebrew also installed ruby-build package as a dependency of "rbenv". Hence the duplicate installs, and the detection I've made for it in the doctor script.

Thanks for updating!
