### ISSUE TITLE
Wrong build options for ruby 2.3

### ISSUE THREAD

**Issue by JanStevens** [rbenv/ruby-build#869]
It seems there is a build problem for ruby 2.3

https://github.com/mperham/sidekiq/issues/2749
https://bugs.ruby-lang.org/issues/11930

Using `ruby-install` I don't seem to have crashes when starting sidekiq

**Comment by hsbt** [comment]
It's not build problem. It's ruby core internal issue such as thread or GC marking.

We(ruby-core) are investigating now. see https://bugs.ruby-lang.org/issues/11930#note-4
