### ISSUE TITLE
Can't install on CentOS 7

### ISSUE THREAD

**Issue by jandudulski** [rbenv/ruby-build#870]
```bash
$ rbenv install -k 2.3.0
/home/user/.rbenv/plugins/ruby-build/bin/ruby-build: line 207: pushd: ruby-2.3.0: No such file or directory

BUILD FAILED (CentOS Linux 7 using ruby-build 20151230)
```

**Comment by mislav** [comment]
That's bizarre. Is there really no other output? Is the error the same every time?

**Comment by jimnanney** [comment]
BUILD FAILED
tar: Child returned status 2
tar: Error is not recoverable: exiting now
(Red Hat Enterprise Linux Server 7.2 using ruby-build 20151230)
 
Inspect or clean up the working tree at /opt/james.nanney/tmp/ruby-build.20160107094924.4078
Results logged to /opt/james.nanney/tmp/ruby-build.20160107094924.4078.log
 
Last 10 log lines:
/opt/james.nanney/tmp/ruby-build.20160107094924.4078 ~
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

Looks like bzip2 is missing from my rhel 7 install, maybe same on centos?

**Comment by jimnanney** [comment]
sudo yum install -y bzip2 worked for me.

**Comment by mislav** [comment]
Ouch, thanks for reporting. This is probably caused by #852 /cc @deepj 

I had no idea that some platforms don't support bz2 decompression out of the box through tar. I'm not sure what to do about this. We could definitely try to improve the error message so at least you get a hint that you should install bz2. Or, we could try falling back transparently to gz tarballs? However, I'm not sure if every `*.bz2` download within ruby-build has a corresponding `.tar.gz` download.

**Comment by jimnanney** [comment]
Forked and added a warning to the log when bzip2 is not in path, how do I run the test suite?

**Comment by deepj** [comment]
@mislav This suprises me. If I'm not wrong RVM uses bz2 tarballs as well.

**Comment by mislav** [comment]
> how do I run the test suite?

Yeah, sorry that this is not more clear. I add `bats` to my PATH:

```sh
ln -s /path/to/bats ~/bin/bats
```

Then simply `bats test` in the ruby-build project.

**Comment by jimnanney** [comment]
Thanks! I'm not sure how to write a test for it, but sending a pull request to echo a warning to the log.

**Comment by jandudulski** [comment]
> Looks like bzip2 is missing from my rhel 7 install, maybe same on centos?

Yes, installing bzip2 helped, thanks.

**Comment by hsbt** [comment]
We should revert https://github.com/rbenv/ruby-build/pull/852 . I think.

It's provide more user frustration at distribution specific environment rather than reducing transfer rate cost.

**Comment by deepj** [comment]
@hsbt RVM uses definetely bz2 tarballs (see https://github.com/rvm/rvm/blob/01f3cb6e777b958dccfa3eb747aa6574bda9cc04/config/sha512).

**Comment by hsbt** [comment]
@deepj It's no reason why we should use bzip2.

**Comment by deepj** [comment]
@hsbt Rubinius or Topaz offers only bz2 tarballs. So what with them?

**Comment by hsbt** [comment]
> Rubinius or Topaz offers only bz2 tarballs.

It better to replace gzip.

In my opiniton, ruby-build dependencies should be small in major OS distribution. If we added some dependency to ruby-build, All of users need to add its dependency in all over the world. It's big transfer rather than transfer reducing by bzip2.

**Comment by deepj** [comment]
For example I don't have to add anything because my OS contains it in a default configuration. I guess users without bzip2 is a minority. But I speak myself.

**Comment by deepj** [comment]
And one thing. RVM has larger user space than ruby-build and they have problems with that...

**Comment by hsbt** [comment]
> users without bzip2 are a minority

It's most important point on this issue. We need to decide to omit or help these users.

@mislav How do you think this?

**Comment by deepj** [comment]
@hsbt please, don't forget on RVM. That's significant and valid point in this making decision. Anyway, an installation of bzip2 is for most possible users of ruby-build without bzip2 much more easier than an installation of ruby-build itself. Mostly they do something like _packer-manager_ install bzip2. The installation of ruby-build in compare of that is nontrivial...

**Comment by mislav** [comment]
I've merged the change that adds a warning that you're missing bzip2 and [added the hint to instructions for CentOS/Fedora](https://github.com/rbenv/ruby-build/wiki#suggested-build-environment) on our wiki.

Let's see if it becomes a problem. I know the bz2 switch might have inconvenienced some of our users, but due to other bz2 usage within ruby-build I'd like to think of bz2 as a build dependency for ruby-build. Let's see if this becomes a larger problem.

**Comment by hsbt** [comment]
ok, I understand.
