### ISSUE TITLE
Sha 512 support

### ISSUE THREAD

**Issue by jasonkarns** [rbenv/ruby-build#878]
While working on the [rubinius scraper](https://github.com/jasonkarns/ruby-build-update-defs/pull/2) I realized that ruby-build doesn't yet have support for sha512.

While sha512 support isn't *solely* for rubinius support (which is still in question, maybe? #863), lack of sha512 is a blocker for the rubinius scraper, since rubinius only publishes sha512 checksums for their builds. (I'd prefer the scraper not generate its own checksums, but pull them from the host site.)

I'm happy to work on a PR, but opened this issue in case someone else has some cycles to spare.

**Comment by mislav** [comment]
See referenced PR for why we won't be needing sha512 support just yet.

**Comment by jasonkarns** [comment]
I have opened #951 as the first step in fully automating the addition of build definitions. (The second step is to have the definitions pushed as PRs themselves when new ones are scraped. I already have this scripted for node-build and plan to port it soon.)

However, the scraper isn't quite as useful as it could be, because rubinius still only publishes sha-512 checksums. As such, the scraper can't generate rubinius definitions with checksums, thus the fully automated process would so far only apply to cruby.

Reasons for declining sha-512 support:

1. <strike>only rubinius needs it, and rubinius may go away</strike>

    #862 is 5 months old with most recent discussion being 3 months stale. It seems rubinius may stay?
1. <strike>the checksums are hosted at the same place as the packages themselves</strike>

    The rubinius host is implicitly trusted if the rubinius build definitions manually derive the checksum from the packages hosted there. Therefore any checksum published on the same host has the same level as trust as the package itself. While the published checksums can't guard against the host being compromised, nor does the current process. However, the current process can't guard against *accidental* corruption, whereas using the published checksums will. Thus, using the published checksums is an improvement over the current process.
1. the mirroring script assumes sha256


So the only remaining blocker to using sha-512 checksums in the build definitions is the lack of support in the mirroring script. To that end, I intend to port the checksum-handling code from the ruby-build bin over to the mirror script. Would this be well received? Indeed, I think that having a more versatile mirror script would be beneficial regardless of whether ruby-build yet supports sha512.
