### ISSUE TITLE
Cannot install 2.3.0 on Debian 8.2

### ISSUE THREAD

**Issue by dflourusso** [rbenv/ruby-build#889]
```
$ rbenv install 2.3.0

Downloading ruby-2.3.0.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.0.tar.bz2
Installing ruby-2.3.0...

BUILD FAILED (Debian 8.2 using ruby-build 20160111-12-g6bdc16c)

Inspect or clean up the working tree at /tmp/ruby-build.20160119084622.30193
Results logged to /tmp/ruby-build.20160119084622.30193.log

Last 10 log lines:
compiling ./enc/trans/big5.c
gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
enc.mk:793: recipe for target 'enc/trans/big5.o' failed
make[1]: *** [enc/trans/big5.o] Error 4
make[1]: Leaving directory '/tmp/ruby-build.20160119084622.30193/ruby-2.3.0'
uncommon.mk:643: recipe for target 'trans' failed
make: *** [trans] Error 2
```

**Comment by mislav** [comment]
Thanks for reporting. Is the error the same every time?

You could also share the full build log (saved into a file as indicated by output) as a link to a Gist.

/cc @hsbt

**Comment by dflourusso** [comment]
Thanks, follows the error: **[GIST](https://gist.github.com/dflourusso/07bfac1e6d4df2da1e27)**

**Comment by mislav** [comment]
Thanks for that log! It will be helpful to the Ruby core team to determine what's going on.

You can try installing `2.3.0-dev`, which will download and compile the edge version from the `2.3.x` series in development. Maybe the build problem has already been fixed?

**Comment by Lukom** [comment]
I had the same error. On other machine rvm installed ruby-2.3 successfully, so I ran it like this `rvm --debug install 2.3` to see what ruby dependencies it installed for ruby. Then I installed these dependencies on machine with rbenv like this:

`sudo apt-get install bash curl patch bzip2 ca-certificates gawk g++ gcc make libc6-dev patch openssl ca-certificates libreadline6 libreadline6-dev curl zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 autoconf libgmp-dev libgdbm-dev libncurses5-dev automake libtool bison pkg-config libffi-dev`

    ...
    The following extra packages will be installed:
      libgmpxx4ldbl
    The following NEW packages will be installed:
      libgdbm-dev libgmp-dev libgmpxx4ldbl

Now I have a little different error:
    
    linking transcoder transdb.so
    compiling ./enc/trans/big5.c
    virtual memory exhausted: Cannot allocate memory
    make[1]: *** [enc/trans/big5.o] Error 1

**Comment by Lukom** [comment]
I have followed this [swap-file tutorial](https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04) and created 2G swap (I have 490mb ram on server). After this ruby 2.3.0 installed successfully (while installation it used ~250mb swap).
