### ISSUE TITLE
Release Policy?

### ISSUE THREAD

**Issue by kenips** [rbenv/ruby-build#895]
Hey guys,

I'm wondering if there's a release policy currently in place? If not I'd like to propose adding one. ruby-build is amazing and now an indispensable tool for many of us. However, if it isn't always updated when new ruby revisions are out (for example, currently with jruby-9.0.5.0), it becomes frustrating unless you stay on `master`. It's not a workflow for everyone.

I'd love to have your buy-in into a more clear release policy, such as:
- committing to releasing a minor/patch version whenever a new ruby revision is added.
- allowing maintainers to release minor/patch as they merge new ruby revisions.
- deciding on whom to merge/release actual improvements to rbenv (keeping to owners only, etc) if there's a concern with `master` stability for always releasing.

This should make rbenv a better tool for everyone especial those on non-MRI ruby.

Thanks!

**Comment by mislav** [comment]
We try to release ruby-build soon after there's been a significant change or few new versions added. Certainly immediately after new MRI get added. I admit we aren't as responsive for new JRuby and Rubinius releases.

We also have only 1 line of releases— no major/minor/patch releases. We always try to keep ruby-build backwards compatible.

I don't know what a more sophisticated release policy would be. I was thinking that the project could benefit from being able to look up definitions here in GitHub master branch if they are not found locally. That would enable people to install a version of Ruby immediately after it's been merged, even after a release.

**Comment by kenips** [comment]
Hey @mislav yeah going `master` is one way to go as mentioned. Unfortunately I think a large install base of `rbenv` are `brew` users. Even the [instructions](https://github.com/rbenv/ruby-build/blob/a93741819081afe4ee228728f9c2e91a973c1f75/bin/rbenv-install#L215) tell people to run brew upgrade. Complicating the issue is that [`brew` doesn't handle upgrade for installation with `--HEAD`](https://github.com/Homebrew/homebrew/issues/48027), so we're left with pure git pull approach or reinstallation with `--HEAD` flag, which isn't nice (and difficult for me to teach junior devs).

I think the consideration of this release policy is that:
 * large portion of `rbenv` / `ruby-build`'s user base is using `brew`
 * `brew` doesn't work well with `--HEAD` upgrades
 * we need faster access to new revisions of JRuby and Rubinius

The concern right now is the 1 line of release - so that master might not be releasable at all times? These ruby revisions are definitely backwards compatible so they should always be releasable. Perhaps we need development to run on a separate branch or the current release to run on a release branch? I definitely don't want to complicate the development process for you guys, so I'll leave that to you.

Also I don't think most of us are expecting *immediate* access to new revisions. We will actively send pull requests and here and on `brew` to help this happen, as long as a release policy is in place to support it :).

**Comment by kenips** [comment]
Actually, alternatively we could actively push `master` installation for `brew` users. We can update installation instructions to:

```
brew install ruby-install --HEAD
```

and update definition update instructions to:

```
brew reinstall ruby-install --HEAD
```

That is a good workaround but a less elegant solution imo, and a bit frustrating perhaps.

**Comment by mislav** [comment]
I've just released latest JRuby addition: https://github.com/rbenv/ruby-build/releases/tag/v20160130

**Comment by parkr** [comment]
Hi @mislav! Would you please consider a release for the OpenSSL merge of #912? :smile:

**Comment by mislav** [comment]
We lately did releases pretty often. If you're not satisfied with that, please use master. Thanks!
