### ISSUE TITLE
build fails when inaccessible directory exists in $PREFIX_DIR

### ISSUE THREAD

**Issue by DebbieGillespie** [rbenv/ruby-build#902]
I encountered the following error when attempting to install ruby on our RHEL 6 server using a prefix directory:

```
find: `/swadm/lost+found': Permission denied

BUILD FAILED (Red Hat Enterprise LInux Server release 6.7 (Santiago) using ruby-build 20160130)
```

The /swadm/lost+found directory is owned by root and we are installing ruby using a different user, which is why the find command run by the `fix_directory_permissions` method is generating the error.  I will be submitting a pull request that addresses this error shortly.

**Comment by mislav** [comment]
3a10951711e213de2ee1c4e6996590f3a6c62044
