### ISSUE TITLE
Install error ruby 2.3.0 on Ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by Lukom** [rbenv/ruby-build#905]
$ rbenv install 2.3.0
    
    Downloading ruby-2.3.0.tar.bz2...
    -> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.0.tar.bz2
    Installing ruby-2.3.0...
    
    BUILD FAILED (Ubuntu 14.04 using ruby-build 20160130-6-g9e57fb0)
    
    Inspect or clean up the working tree at /tmp/ruby-build.20160214110648.19668
    Results logged to /tmp/ruby-build.20160214110648.19668.log
    
    Last 10 log lines:
    compiling node.c
    compiling numeric.c
    compiling object.c
    compiling pack.c
    compiling parse.c
    gcc: internal compiler error: Killed (program cc1)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
    make: *** [parse.o] Error 4

Detailed [Log](https://gist.github.com/Lukom/8e17cf792850b61fcb83)

**Comment by hsbt** [comment]
Thank you for your report. Note: It's similar with https://github.com/rbenv/ruby-build/issues/889 . I will investigate this.

**Comment by Lukom** [comment]
I have installed some ruby dependencies:

    sudo apt-get install build-essential openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev autoconf libc6-dev automake libtool bison subversion pkg-config libxslt1-dev libncurses5-dev

    ...
    The following NEW packages will be installed:
      autoconf automake autotools-dev bison libapr1 libaprutil1 libbison-dev
      libltdl-dev libltdl7 libncurses5-dev libserf-1-1 libsvn1 libtool m4
      subversion
    The following packages will be upgraded:
      openssl

And now I have the same error as in #889:

    ...
    compiling ./enc/trans/big5.c
    gcc: internal compiler error: Killed (program cc1)
    ...

**Comment by sachin026** [comment]
please help for following output

$ rbenv install 2.3.1
Downloading ruby-2.3.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
error: failed to download ruby-2.3.1.tar.bz2

BUILD FAILED (Ubuntu 14.04 using ruby-build 20160426-2-g82e275d)

Inspect or clean up the working tree at /tmp/ruby-build.20160430022438.758
Results logged to /tmp/ruby-build.20160430022438.758.log

Last 10 log lines:
/tmp/ruby-build.20160430022438.758 ~
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 110


what to do to download Ruby

and also i have installed ruby 1.9... some version without  rvm and rbenv

**Comment by chevinbrown** [comment]
+1, same issue for me

**Comment by Becarev** [comment]
Same here
