### ISSUE TITLE
2.3.0 install problem

### ISSUE THREAD

**Issue by grigoris86** [rbenv/ruby-build#907]
i try to install ruby 2.3.0 with rbenv and after typing the terminal `rbenv install 2.3.0 ` i wait for hours and stoped...

**Comment by grigoris86** [comment]
rbenv install 2.3.0-dev
Cloning https://github.com/ruby/ruby.git...
Installing ruby-2.3.0-dev...

BUILD FAILED (Ubuntu 14.04 using ruby-build 20160130-6-g9e57fb0)

Inspect or clean up the working tree at /tmp/ruby-build.20160219111509.20531
Results logged to /tmp/ruby-build.20160219111509.20531.log

Last 10 log lines:
/tmp/ruby-build.20160219111509.20531 ~
Cloning into 'ruby-2.3.0-dev'...
/tmp/ruby-build.20160219111509.20531/ruby-2.3.0-dev /tmp/ruby-build.20160219111509.20531 ~
/home/user/.rbenv/plugins/ruby-build/bin/ruby-build: γραμμή 550: autoconf: command not found

**Comment by grigoris86** [comment]
try to
sudo apt-get install autoconf bison build-essential libssl-dev libyaml-dev libreadline6 libreadline6-dev zlib1g zlib1g-dev

and work fine!

thanks @lgs for #594

**Comment by marat-chardymov** [comment]
thank you!

**Comment by lumitron** [comment]
Thank you!

**Comment by condef5** [comment]
Thank you man!!!!
