### ISSUE TITLE
Unable to install 2.3.0

### ISSUE THREAD

**Issue by matthewsalan** [rbenv/ruby-build#913]
After updating ```homebrew```, uninstalling and re-installing ```ruby-build```, ```rbenv``` doesn't list ```2.3.0``` as an option to install.  It only lists ```2.3.0-dev```, and when I install that and run ```rbenv local 2.3.0-dev``` it sets the local version of ruby to ```2.4.0```.  Error:

    ruby-build: definition not found: 2.3.0

    The following versions contain `2.3.0' in the name:
      2.3.0-dev
      rbx-2.3.0

    See all available versions with `rbenv install --list'.

    If the version you need is missing, try upgrading ruby-build:

Apologize if this has been addressed, but I've only seen issues where ```brew``` and ```ruby-build``` have been updated and it resolved the issue.  #861 

My machine: MacBook Pro 15 (2009), OSX Yosemite 10.10.5
rbenv 1.0.0
ruby-build 20160228
Zsh, iTerm

**Comment by mislav** [comment]
I think this is a problem of duplicate ruby-build installs. You might have an old version of ruby-build installed separately as rbenv plugin. Please [run rbenv-doctor script](https://github.com/rbenv/rbenv-installer#rbenv-doctor) to detect such issues.

**Comment by matthewsalan** [comment]
Thanks @mislav, the rbenv-doctor script helped.  Also deleting this ```~/.rbenv/plugins/ruby-build``` got rid of the stale versions.
