### ISSUE TITLE
Problems to update ruby version to 2.3.0 on linux / debian.

### ISSUE THREAD

**Issue by Nigmatulin** [rbenv/ruby-build#916]
Hello, I'm having the same problem. 
I already did `rbenv install 2.3.0` and it was successfully installed. So i ran `rbenv versions` and the result are:
`* system (set by /home/eduardo/.rbenv/versions/.ruby-version)`
`2.3.0`
So, I ran `rbenv local 2.3.0` and `rbenv global 2.3.0` and the result, after the command versions, are:
`system`
`* 2.3.0 (set by /home/eduardo/.rbenv/versions/.ruby-version)`
But, when I ran the command `ruby -v`, the result are:
`ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]`

I need some help.

**Comment by Nigmatulin** [comment]
I added the line:
`eval "$(rbenv init -)"`
after the:
`export PATH="$HOME/.rbenv/bin:$PATH"`
and it worked for me, `ruby -v`
`ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]`

**Comment by ito2307** [comment]
Nice Nigmatulin
