### ISSUE TITLE
unrecognized options: --with-readline-dir

### ISSUE THREAD

**Issue by shelbydz** [rbenv/ruby-build#919]
Trying to install 1.9.3-p448 on Arch Linux with the following command

```
RUBY_CONFIGURE_OPTS=--with-readline-dir="/usr/lib/libreadline.so" rbenv install 1.9.3-p448
```

it fails with 

```
uncommon.mk:178: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2
```

and in the log I see. 

```
configure: WARNING: unrecognized options: --with-readline-dir
...
Failed to configure readline. It will not be installed. 
...
readline nor libedit not found
```

I've installed the dependencies listed in the wiki and I have the `/usr/lib/libreadline.so` library. 
I also tried other versions of Ruby with similar problems. 

This is the version of Ruby we use for development at my work.

**Comment by mislav** [comment]
`--with-readline-dir` expects a directory, not a path to the file. You should try `--with-readline-dir=/usr`, or simply not supplying the option at all. The build process should pick up the default readline from system path.

**Comment by hsbt** [comment]
Ruby 1.9 didn't have `--with-readline-dir` option in configure script. Please try to use `--with-opt-dir=/usr/local`
