### ISSUE TITLE
ree-1.8.7-2011.03 fails to build on OSX

### ISSUE THREAD

**Issue by VinceG3** [rbenv/ruby-build#920]
vince@Vincents-MacBook-Pro:~/src/bionic$ ruby-build ree-1.8.7-2011.03 ree
    Downloading ruby-enterprise-1.8.7-2011.03.tar.gz...
    -> https://dqw8nmjcqpjn7.cloudfront.net/0c0ddbc43b3aef49686db27e761e55a23437f12e1f00b6fe55d94724637bff6b
    Installing ruby-enterprise-1.8.7-2011.03...

    BUILD FAILED (OS X 10.11.3 using ruby-build 20160228)

    Inspect or clean up the working tree at /var/folders/82/xsqy9bx97zq9nj_8s95lfr5w0000gn/T/ruby-build.20160314134139.67016
    Results logged to /var/folders/82/xsqy9bx97zq9nj_8s95lfr5w0000gn/T/ruby-build.20160314134139.67016.log

    Last 10 log lines:
    Some required software is not installed.
    But don't worry, this installer will tell you how to install them.
    Press Enter to continue, or Ctrl-C to abort.
    --------------------------------------------
    Installation instructions for required software

     * To install OpenSSL development headers:
       Please download it from http://www.openssl.org/

It appears the installer requires user input. I have openssl installed via Homebrew.

**Comment by hsbt** [comment]
REE is EOL status. We can't support this fails on latest OSX box.
