### ISSUE TITLE
Error during configure fails to be echoed (with RBENV_DEBUG)

### ISSUE THREAD

**Issue by jasonkarns** [rbenv/ruby-build#933]
The following command errors out, but isn't printing to STDOUT:

```
${!PACKAGE_CONFIGURE:-./configure} --prefix="${!PACKAGE_PREFIX_PATH:-$PREFIX_PATH}" \
      $CONFIGURE_OPTS ${!PACKAGE_CONFIGURE_OPTS} "${!PACKAGE_CONFIGURE_OPTS_ARRAY}" || return 1
```

(from https://github.com/rbenv/ruby-build/blob/master/bin/ruby-build#L540-L541)

I have `RBENV_DEBUG=true` so I would expect that the `./configure` command would be echoed out so I can see what all the variables resolve to at that point.

Last message printed prior to that is `Installing <version>...` The output from the .configure command is captured in the log, though.

**Comment by mislav** [comment]
Agreed that we should be writing more information in the log, even if no special environment variables are set. It wouldn't hurt, and it would help debugging.
