### ISSUE TITLE
Ruby 2.3.1 build issues on Solaris

### ISSUE THREAD

**Issue by mehayden** [rbenv/ruby-build#950]
System is Joyent SmartOS, Solaris 11, aka SunOS 5.11
    $ uname -a
    SunOS XXXXX.local 5.11 joyent_20160420T005724Z i86pc i386 i86pc Solaris

Ruby-build was executed using:

```
$ rbenv install 2.3.1
```
## Issue 1:

```
BUILD FAILED (SunOS 5.11 using ruby-build 20160426-12-gf03f7f8)

Inspect or clean up the working tree at /tmp/ruby-build.20160509183403.77306
Results logged to /tmp/ruby-build.20160509183403.77306.log

Last 10 log lines:
/tmp/ruby-build.20160509183403.77306/ruby-2.3.1/load.c:968: undefined reference to `__dtraceenabled_ruby___require__entry'
/tmp/ruby-build.20160509183403.77306/ruby-2.3.1/load.c:981: undefined reference to `__dtraceenabled_ruby___find__require__entry'
/tmp/ruby-build.20160509183403.77306/ruby-2.3.1/load.c:986: undefined reference to `__dtraceenabled_ruby___find__require__return'
/tmp/ruby-build.20160509183403.77306/ruby-2.3.1/load.c:1025: undefined reference to `__dtraceenabled_ruby___require__return'
/tmp/ruby-build.20160509183403.77306/ruby-2.3.1/load.c:968: undefined reference to `__dtrace_ruby___require__entry'
/tmp/ruby-build.20160509183403.77306/ruby-2.3.1/load.c:986: undefined reference to `__dtrace_ruby___find__require__return'
/tmp/ruby-build.20160509183403.77306/ruby-2.3.1/load.c:1025: undefined reference to `__dtrace_ruby___require__return'
/tmp/ruby-build.20160509183403.77306/ruby-2.3.1/load.c:981: undefined reference to `__dtrace_ruby___find__require__entry'
collect2: error: ld returned 1 exit status
make: *** [miniruby] Error 1
```

Configure detects that this system supports dtrace and so a number of external probe functions (defined in probes.h) are defined into many source files using the RUBY_DTRACE_CREATE_HOOK and RUBY_DTRACE_HOOK macros. The linker fails to find these defined anywhere. A workaround is described below, but I'd like to know where these functions were intended to be defined from in a system consistent with these Ruby-defined probes.

I got beyond this issue by invoking as follows:

```
$ CONFIGURE_OPTS="--disable-dtrace" rbenv install 2.3.1
```
## Issue 2:

```
BUILD FAILED (SunOS 5.11 using ruby-build 20160426-12-gf03f7f8)

Inspect or clean up the working tree at /tmp/ruby-build.20160509193626.5925
Results logged to /tmp/ruby-build.20160509193626.5925.log

Last 10 log lines:
The Ruby readline extension was not compiled.
The Ruby zlib extension was not compiled.
ERROR: Ruby install aborted due to missing extensions
Try running `yum install -y openssl-devel readline-devel zlib-devel` to fetch missing dependencies.
```

It turns out that these packages are present, but configure could not find related include files under "/opt/local" which is a fairly standard place to put installed packages on this system. It took quite a while to discover the existence of the --with-opt-dir option to configure, which I used to fix this issue as follows:

```
$ CONFIGURE_OPTS="--disable-dtrace --with-opt-dir=/opt/local" rbenv install 2.3.1
```
## Issue 3:

```
BUILD FAILED (SunOS 5.11 using ruby-build 20160426-12-gf03f7f8)

Inspect or clean up the working tree at /tmp/ruby-build.20160509233006.25497
Results logged to /tmp/ruby-build.20160509233006.25497.log

Last 10 log lines:
checking for typeof syntax and keyword spelling... __typeof__
checking for long long... yes
checking for off_t... yes
checking char bit... 8
checking size of int... 0
checking size of short... 0
checking size of long... 0
checking size of long long... configure: error: in `/tmp/ruby-build.20160509233006.25497/ruby-2.3.1':
configure: error: cannot compute sizeof (long long)
See `config.log' for more details
```

This turned out to also be related to the /opt/local directory, but this time the build failed to find libraries located under /opt/local/lib. The comment in the configure script describes the  --with-opt-dir as used to "add optional headers and libraries directories", so I was surprised that using it wasn't sufficient to find these libraries. This issue was eventually resolved using the following command configuring the runtime linker:

```
# crle -u -l /opt/local/lib
```

I am not sure that any of these problems are within the scope of ruby-build function or documentation, but at least mentioning them here might help someone building Ruby on this system in the future.

**Comment by mislav** [comment]
Thanks for sharing these awesome workarounds! @hsbt will definitely be interested in these findings.

If these issues are common for everyone on Solaris, we should probably share these workarounds on the wiki too.

**Comment by mislav** [comment]
Ruby 2.3 is now EOL.
