### ISSUE TITLE
New tag with JRuby 9.1.2.0

### ISSUE THREAD

**Issue by zzk** [rbenv/ruby-build#957]
Hello,
Cloud you guys release tag that will include jruby 9.1 and jruby 9.1.2?
Without proper tag there's no way to 'easy' install jruby with brew on osx (and not every user on osx is using HEAD version 😉 )
Much appreciate!

**Comment by mPanasiewicz** [comment]
PLZ release tag
+++++

**Comment by mislav** [comment]
Done! https://github.com/rbenv/ruby-build/releases/tag/v20160602
