### ISSUE TITLE
Fail to build after downloading with aria2 arbitrarily (El Capitan)

### ISSUE THREAD

**Issue by sticnarf** [rbenv/ruby-build#971]
I installed aria2 with HomeBrew before and I make it run in the RPC mode through a conf-file `aria2.conf` located in `$HOME/.aria2/`.
Firstly, when I executed `rbenv install 2.3.1`, it failed to download the ruby source code. And I found it was trying to launch aria2. But there was one aria2c program running occupying the port, so it failed.
Then, I killed the existing aria2c and ran `rbenv install 2.3.1` again. It successfully downloaded the package, but to the folder I set in `aria2.conf`. That's to say, the aria2 client launched by rbenv uses the conf file.
However, the process stopped at this point. There is nothing more printed to the screen.

Logs in verbose mode are as follows:

```
➜  ~ rbenv install 2.3.1 -v
/var/folders/lr/rdvb3rr970g79mhl7lj4csqm0000gn/T/ruby-build.20160623224324.27450 ~
Downloading ruby-2.3.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2

06/23 22:43:25 [WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.

06/23 22:43:25 [NOTICE] IPv4 RPC: listening on TCP port 6800

06/23 22:43:25 [NOTICE] IPv6 RPC: listening on TCP port 6800

06/23 22:43:26 [NOTICE] GID#af657e01c8026fcb - Download has already completed: /Users/username/Downloads/ruby-2.3.1.tar.bz2

06/23 22:43:26 [NOTICE] Download complete: /Users/username/Downloads/ruby-2.3.1.tar.bz2

# Stuck here, then pressed Ctrl+C

06/23 22:56:33 [NOTICE] Shutdown sequence commencing... Press Ctrl-C again for emergency shutdown.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
af657e|OK  |       0B/s|/Users/username/Downloads/ruby-2.3.1.tar.bz2

Status Legend:
(OK):download completed.
/Users/username/.rbenv/plugins/ruby-build/bin/ruby-build: line 209: pushd: ruby-2.3.1: No such file or directory

BUILD FAILED (OS X 10.11.5 using ruby-build 20160602-11-gc593baa)

/Users/username/.rbenv/plugins/ruby-build/bin/ruby-build: line 1270: kill: (27474) - No such process
```

And the rbenv config file:

```
enable-rpc=true
rpc-allow-origin-all=true
rpc-listen-all=true
max-concurrent-downloads=5
continue=true
max-connection-per-server=5
min-split-size=10M
split=10
max-overall-download-limit=0
max-download-limit=0
max-overall-upload-limit=0
max-upload-limit=0
dir=/Users/username/Downloads
file-allocation=prealloc
```

**Comment by mislav** [comment]
Thanks for reporting! /cc @yyuu

**Comment by yyuu** [comment]
I think this must be the same issue as yyuu/pyenv#625. I've already prepared fix for it as 6baed1ff66d3bffc6e9ac18d212344f986cfa9d4 as a part of rbenv/ruby-build#965.

However, it'll ignore all the configurations other than `dir=` as well. It might not be adequate from the point of view of downloading performance.... I'll try to prepare another workaround for it.

**Comment by yyuu** [comment]
It seems `aria2c` will block after downloading if `enable-rpc=true` is set. I have no idea for now how I can deal with the option 😢 

@sticnarf If you'd like to set some downloading options for `aria2c`, setting them in `RUBY_BUILD_ARIA2_OPTS` is the only option available for now....

https://github.com/rbenv/ruby-build/blob/c593baacd271f8807cb6ecd16b0bcb70491327a8/bin/ruby-build#L1240

**Comment by mislav** [comment]
Going to close this as stale. We haven't been getting further reports about this. Also, there is always RUBY_BUILD_ARIA2_OPTS.
