### ISSUE TITLE
Tag a release that includes Ruby 2.4 preview-1?

### ISSUE THREAD

**Issue by indirect** [rbenv/ruby-build#972]
The source includes a definition for Ruby 2.4 preview 1, but there hasn't been a release yet...

**Comment by sferik** [comment]
That’s correct. We normally don’t :shipit: new `ruby-build` versions for preview release.

To upgrade to Ruby 2.4.0-preview1 (assuming you’re using `ruby-build`, `rbenv`, and `hombrew` on a Mac):

```sh
brew reinstall ruby-build --HEAD
rbenv install 2.4.0-preview1
```
