### ISSUE TITLE
Use brew bump-formula-pr

### ISSUE THREAD

**Issue by MikeMcQuaid** [rbenv/ruby-build#980]
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-formula-pr.rb may give you a better experience than using your own version (as we'll notice quicker if it breaks).

**Comment by hsbt** [comment]
@MikeMcQuaid Thank you for your information. I tried to create new version with `bump-formula-pr`. It's very useful for me. I replace our original script to it.
