### ISSUE TITLE
new tag for ruby version

### ISSUE THREAD

**Issue by mPanasiewicz** [rbenv/ruby-build#981]
Hello,
Could you guys release tag that will include ruby 2.3.2?
Much appreciate!

**Comment by mislav** [comment]
I don't find any evidence that 2.3.2 was released?

**Comment by hsbt** [comment]
> 2.3.2 was released?

not yet.

**Comment by mPanasiewicz** [comment]
Lol, sorry guys. I don't know how I imagined that 2.3.2 was released ... Apologize me!
