### ISSUE TITLE
unable to install into /usr/local/rbenv/plugins

### ISSUE THREAD

**Issue by 4ndrej** [rbenv/ruby-build#986]
when installed into /usr/local/rbenv/plugins/ruby-build the rbenv is not detecting rbenv install command:
```
$ rbenv install -l
rbenv: no such command `install'

```
when installed into ~/.rbenv/plugins/ruby-build everything works nice

install script for failure install is:
```
git clone https://github.com/sstephenson/rbenv.git /usr/local/rbenv
chmod -R g+rwxXs /usr/local/rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
source ~/.bashrc
git clone https://github.com/sstephenson/ruby-build.git /usr/local/rbenv/plugins/ruby-build
```

**Comment by sekrett** [comment]
It should be `echo 'export PATH="/usr/local/rbenv/bin:$PATH"' >> ~/.bashrc` if you install globally. But for me it also does not work with correct path.

After I run `/usr/local/rbenv/plugins/ruby-build/install.sh` it works. I wonder why documentation does not tell to do this for plugin installation.

**Comment by mislav** [comment]
`/usr/local/rbenv` is a non-standard installation for rbenv, so in order for its `plugins/` directory to work, you need to set `RBENV_ROOT=/usr/local/rbenv` globally. See https://github.com/rbenv/rbenv/issues/917

After doing that, calling `/usr/local/rbenv/plugins/ruby-build/install.sh` is _not_ necessary.
