### ISSUE TITLE
New tag with JRuby 9.1.3.0

### ISSUE THREAD

**Issue by gwu1** [rbenv/ruby-build#987]
Hi everyone,

Is it possible to release a tag that will include jruby 9.1.3.0?

I think there are some homebrew users on OSX waiting for this proper tag.

Thanks for any help you can provide.

**Comment by gwu1** [comment]
@mislav thanks for any help you can provide.

**Comment by hsbt** [comment]
JRuby 9.1.3.0 has some regression. We need to add definition of JRuby 9.1.4.0

**Comment by hsbt** [comment]
Already done. https://github.com/rbenv/ruby-build/releases/tag/v20160913
